### PR TITLE
Mons started as a replicaset instead of directly as a pod

### LINKED ISSUE #579: Operator not replacing dead mons
After a day or so of running a cluster, I just noticed only 1 mon is running. Few hours ago I had a couple of unrelated pods die and get recreated(the ones using deployment/etc). My pods with already mounted volumes continue to work.

I am using `v0.3.1`.

tl;dr operator thinks 3 mons are running, and api server probably fails to connect to the mons probably because it is under quorum. 

Is there a way to "tell" the operator about the vanished mons?

```
$ kubectl get pods --all-namespaces -o wide | grep rook
default       rook-operator-2900126290-7k03v          1/1       Running             0          14m       10.2.75.5       10.130.55.21
rook          mds-4027210838-zghbs                    1/1       Running             0          1d        10.2.49.10      10.130.55.18
rook          mon1                                    1/1       Running             0          1d        10.2.49.4       10.130.55.18
rook          osd-0cdm1                               1/1       Running             0          1d        10.2.60.2       10.130.54.215
rook          osd-4k1sn                               1/1       Running             0          1d        10.2.82.5       10.130.55.8
rook          osd-bht2f                               1/1       Running             0          1d        10.2.49.5       10.130.55.18
rook          osd-m1bwd                               1/1       Running             0          1d        10.2.75.7       10.130.55.21
rook          osd-qc1h5                               1/1       Running             0          1d        10.2.37.2       10.130.54.184
rook          prometheus-rook-prometheus-0            2/2       Running             0          1d        10.2.49.7       10.130.55.18
rook          rook-api-1392339950-wj4lj               1/1       Running             0          15m       10.2.75.6       10.130.55.21
```

I tried killing the operator and api to see if it helps, it didnt. Here is the log from the operator.

```
$ kubectl logs rook-operator-2900126290-7k03v
2017-04-15 15:04:04.653781 I | rook-operator: starting operator in namespace default
2017-04-15 15:04:04.654156 I | operator: creating rookcluster TPR
2017-04-15 15:04:04.793384 I | operator: creating rookpool TPR
2017-04-15 15:04:04.877786 I | operator: finding existing clusters...
2017-04-15 15:04:04.890272 I | operator: found 1 clusters
2017-04-15 15:04:04.890318 I | operator: resuming cluster rook in namespace rook
2017-04-15 15:04:04.890346 I | operator: finding existing pools...
2017-04-15 15:04:04.895285 I | operator: found 1 pools. ensuring they exist.
2017-04-15 15:04:04.895437 I | op-cluster: retrieving rook api endpoint for namespace rook
2017-04-15 15:04:04.907598 I | op-mon: start running mons
2017-04-15 15:04:04.908348 I | op-cluster: rook api endpoint 10.3.0.146:8124 for namespace rook
2017-04-15 15:04:04.915025 I | cephmon: parsing mon endpoints: mon2=10.2.75.6:6790,mon0=10.2.75.5:6790,mon1=10.2.49.4:6790
2017-04-15 15:04:04.915258 I | op-mon: loaded: maxMonID=2, mons=map[mon2:0xc4201c9fc0 mon0:0xc420360000 mon1:0xc42000c120]
2017-04-15 15:04:04.964472 I | cephmon: connecting to ceph cluster rook with user admin
2017-04-15 15:04:19.908630 I | op-cluster: creating pool replicapool in namespace rook with replicas 2
2017-04-15 15:04:34.909323 W | operator: failed to check that pool replicapool exists in namespace rook. failed to create pool replicapool. Post http://10.3.0.146:8124/pool: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2017-04-15 15:04:34.909398 I | operator: start watching rookpool tpr: 165056
2017-04-15 15:04:34.909553 I | operator: start watching rookcluster tpr: 165056
2017-04-15 15:09:05.075646 c8c3240  0 monclient(hunting): authenticate timed out after 300
2017-04-15 15:09:05.075689 c8c3240  0 librados: client.admin authentication error (110) Connection timed out
2017-04-15 15:09:05.085617 W | op-mon: failed to check mon health map[mon2:0xc4201c9fc0 mon0:0xc420360000 mon1:0xc42000c120]. cannot connect to cluster. failed to connect to cluster rook: cephd: Connection timed out
2017-04-15 15:09:05.085651 I | op-api: starting the Rook api
2017-04-15 15:09:05.348657 I | op-api: api service already running
2017-04-15 15:09:05.361347 I | op-api: api deployment already exists
2017-04-15 15:09:05.361375 I | op-osd: start running osds
2017-04-15 15:09:05.377776 I | op-osd: osd daemon set already exists
2017-04-15 15:09:05.378156 I | cephmon: connecting to ceph cluster rook with user admin
2017-04-15 15:14:05.382732 7f8f853a3700  0 monclient(hunting): authenticate timed out after 300
2017-04-15 15:14:05.382780 7f8f853a3700  0 librados: client.admin authentication error (110) Connection timed out
2017-04-15 15:14:05.383969 E | operator: failed to create cluster in namespace rook. failed to create client access. failed to connect to cluster: failed to connect to cluster rook: cephd: Connection timed out
```

The operator thinks mon[0-2] are running, when in fact only mon1 is alive. The operator should have noticed this and created 2 replacement mons before continuing.

Here are the logs from rook-api

```
$ kubectl logs rook-api-1392339950-wj4lj -n rook --tail=20
2017-04-15 15:22:55.655996 I | api: 3426f802-39d4-4deb-b1a6-c9af9c7f961f	GET	/metrics	GetMetrics	(start)
2017-04-15 15:22:55.660482 I | api: 3426f802-39d4-4deb-b1a6-c9af9c7f961f	GET	/metrics	GetMetrics	200 OK	4.502423ms
2017-04-15 15:22:58.612026 7f6912163700  0 monclient(hunting): authenticate timed out after 300
2017-04-15 15:22:58.612082 7f6912163700  0 librados: client.admin authentication error (110) Connection timed out
2017-04-15 15:22:58.617680 E | api: failed to connect to cluster as admin: failed to connect to cluster rook: cephd: Connection timed out
2017-04-15 15:22:58.617751 I | api: 7e358f65-c220-468a-8fd1-bacc1ee92c16	POST	/pool	CreatePool	500 Internal Server Error	5m0.01019285s
2017-04-15 15:23:00.652965 I | api: 895bd099-a903-4530-8bbf-0e7a2f91cd45	GET	/metrics	GetMetrics	(start)
2017-04-15 15:23:00.655343 I | api: 895bd099-a903-4530-8bbf-0e7a2f91cd45	GET	/metrics	GetMetrics	200 OK	2.38202ms
2017-04-15 15:23:05.652227 I | api: 2d9f1043-72e0-4c1b-af18-d497318fc14e	GET	/metrics	GetMetrics	(start)
2017-04-15 15:23:05.656073 I | api: 2d9f1043-72e0-4c1b-af18-d497318fc14e	GET	/metrics	GetMetrics	200 OK	3.891765ms
2017-04-15 15:23:10.655544 I | api: cde774ad-07c5-46e8-8fee-d84d37c101ca	GET	/metrics	GetMetrics	(start)
2017-04-15 15:23:10.663114 I | api: cde774ad-07c5-46e8-8fee-d84d37c101ca	GET	/metrics	GetMetrics	200 OK	7.57575ms
2017-04-15 15:23:15.673726 I | api: a29f9d72-0ea5-462d-b1bb-3c845c942b2e	GET	/metrics	GetMetrics	(start)
2017-04-15 15:23:15.686239 I | api: a29f9d72-0ea5-462d-b1bb-3c845c942b2e	GET	/metrics	GetMetrics	200 OK	12.45735ms
2017-04-15 15:23:20.651477 I | api: a55fa7c2-0620-4c12-b5c0-23e811f6834f	GET	/metrics	GetMetrics	(start)
2017-04-15 15:23:20.663685 I | api: a55fa7c2-0620-4c12-b5c0-23e811f6834f	GET	/metrics	GetMetrics	200 OK	12.21069ms
2017-04-15 15:23:25.681739 I | api: f252034f-0b9e-40d7-aedd-2604005baedc	GET	/metrics	GetMetrics	(start)
2017-04-15 15:23:25.685323 I | api: f252034f-0b9e-40d7-aedd-2604005baedc	GET	/metrics	GetMetrics	200 OK	3.593654ms
2017-04-15 15:23:30.665981 I | api: 1a431ca4-08bb-433c-abf0-5539e76d9c48	GET	/metrics	GetMetrics	(start)
2017-04-15 15:23:30.668636 I | api: 1a431ca4-08bb-433c-abf0-5539e76d9c48	GET	/metrics	GetMetrics	200 OK	2.664765ms
```

Here is the logs from the 3 mons from around the time of the crash: https://gist.github.com/sajal/d1cbb8503267af6ac8214f13b3d5247c

### PR DESCRIPTION
**Pull request by travisn**
One replicaset is created for each mon, with a replica count of 1. The mons are assigned to a node, which is critical for recovery of the mon. When a new pod is started, the same metadata dir will be available on the same node as long as a hostDir was specified. If no hostDir was specified then quorum is required to restore that monitor. Bringing up a new mon to replace a bad pod is dependent on #586. Until that is fixed, if the replicaset replaces a mon pod, it will just be killed off by the operator's health check and a new mon will be created altogether.
Fixes #579

### CODE REVIEW

**Comment by travisn** [comment]
Also fixes #681

**Comment by kokhang** [comment]
Question: Instead of a replicaset per mon, why not a replicaset for all mons? That way you can scale the mons by simply scaling the replicaset, which is the natural way to do this. There is a probably good reason you didnt do it this way. I just want to know what that is :)

File: pkg/operator/mon/health.go [hunk 1]
```diff
@@ -0,0 +1,116 @@
+/*
+Copyright 2016 The Rook Authors. All rights reserved.
```
Comment (kokhang) [inline pkg/operator/mon/health.go]: Its 2017 :)

File: pkg/operator/mon/mon.go [hunk 2]
```diff
@@ -376,18 +301,30 @@ func (c *Cluster) waitForPodToStart(name string) (string, error) {
 
 	// Poll the status of the pods to see if they are ready
 	status := ""
-	for i := 0; i < c.context.MaxRetries; i++ {
+	retryFactor := 3
```
Comment (jbw976) [inline pkg/operator/mon/mon.go]: why does a `retryFactor` need to be used here?

File: pkg/operator/mon/mon.go [hunk 3]
```diff
@@ -376,18 +301,30 @@ func (c *Cluster) waitForPodToStart(name string) (string, error) {
...
+		if i%retryFactor == 0 {
+			logger.Infof("waiting for mon %s to start. status=%s", name, status)
+		}
+		<-time.After(time.Duration(c.context.RetryDelay/retryFactor) * time.Second)
 
-		pod, err := c.context.Clientset.CoreV1().Pods(c.Namespace).Get(name, metav1.GetOptions{})
+		options := metav1.ListOptions{LabelSelector: fmt.Sprintf("mon=%s", name)}
+		pods, err := c.context.Clientset.CoreV1().Pods(c.Namespace).List(options)
 		if err != nil {
-			return "", fmt.Errorf("failed to get mon pod %s. %+v", name, err)
```
Comment (jbw976) [inline pkg/operator/mon/mon.go]: why is the mon name not important for this error message anymore?

File: pkg/operator/mon/mon.go [hunk 4]
```diff
@@ -376,18 +301,30 @@ func (c *Cluster) waitForPodToStart(name string) (string, error) {
...
+			return "", fmt.Errorf("failed to get mon pod. %+v", err)
+		}
+		if len(pods.Items) == 0 {
+			logger.Infof("%s pod not yet created", name)
+			continue
+		}
+		if len(pods.Items) > 1 {
+			logger.Warningf("more than one mon pod found for %s", name)
```
Comment (jbw976) [inline pkg/operator/mon/mon.go]: if there's more than 1 mon pod, is there something we need to do to rectify that situation?

File: pkg/operator/mon/health.go [hunk 5]
```diff
@@ -0,0 +1,116 @@
...
+
+			if len(status.MonMap.Mons) > c.Size {
+				// no need to create a new mon since we have an extra
+				err = c.removeMon(conn, mon.Name)
+			} else {
+				// bring up a new mon to replace the unhealthy mon
+				err = c.failoverMon(conn, mon.Name)
+			}
+			if err != nil {
+				logger.Errorf("failed to failover mon %s. %+v", mon.Name, err)
```
Comment (kokhang) [inline pkg/operator/mon/health.go]: Dont you want to return this error?

File: pkg/operator/mon/mon.go [hunk 6]
```diff
@@ -464,16 +401,83 @@ func (c *Cluster) loadMonConfig() error {
...
+	for _, c := range node.Status.Conditions {
+		if c.Type == v1.NodeReady {
+			return true
+		}
+	}
+	logger.Infof("node %s is not ready. %+v", node.Name, node.Status.Conditions)
+	return false
+}
+
+func (c *Cluster) getNodesWithMons() (map[string]interface{}, error) {
```
Comment (jbw976) [inline pkg/operator/mon/mon.go]: are you using `map[string]interface{}` here as a Set?  could we use `util.Set` instead if that's the case?

**Comment by travisn** [comment]
Good question, certainly that would have been much simpler. There are multiple challenges, including:
- A mon has an identity. If I bring up a new pod to replace a dead pod, it must have the same identity. Each of the three mons have a unique identity so they can't be created with the same podspec.
- A mon needs to be tied to a machine with a hostPath (or local dir in the future), so if the pod dies and a new pod is started in its place, we can come back up with the same identity and data.

File: pkg/operator/mon/pod.go [hunk 7]
```diff
@@ -20,8 +20,8 @@ import (
```
Comment (kokhang) [inline pkg/operator/mon/pod.go]: The name of the file doesnt really match anymore, does it :p?

**Comment by mikefedyk** [comment]
There could be one replicaset for all mons if it uses a placement label on
the nodes with soft node affinity, and the operator can manage the node
label assignment.  Also the pods would have to use hard pod anti-affinity.

https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity

File: pkg/operator/mon/pod.go [hunk 8]
```diff
@@ -43,31 +43,52 @@ func AdminSecretEnvVar() v1.EnvVar {
...
+	return rs
+}
+
+func (c *Cluster) makeMonPod(config *MonConfig, nodeName string) *v1.Pod {
 	dataDirSource := v1.VolumeSource{EmptyDir: &v1.EmptyDirVolumeSource{}}
 	if c.dataDirHostPath != "" {
 		dataDirSource = v1.VolumeSource{HostPath: &v1.HostPathVolumeSource{Path: c.dataDirHostPath}}
 	}
 
+	container := c.monContainer(config, c.clusterInfo.FSID)
```
Comment (kokhang) [inline pkg/operator/mon/pod.go]: where is this variable used?

**Comment by mikefedyk** [comment]
Also, Statefulset provides a stable identity to each pod in the set.

https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/

**Comment by travisn** [comment]
@mikefedyk good points. 
- Each mon not only needs a stable identity, but it is a very specific identity that can be assigned by the operator. When the operator decides a mon is dead, it needs to explicitly kill the bad one and start a new one with the new identity.
- To get the persistent storage in a statefulset pod it requires a PVC. We don't have any storage available to the mons except local storage so it wouldn't be able to change nodes if the statefulset decides to schedule a pod to a different node. Or am I misunderstanding the statefulset persistence?

**Comment by mikefedyk** [comment]
I don't know if the Statefulset forces the use of PVCs or not.  Many times different objects are expected to be used together (Statefulset and PVC with network storage), but not implicitly required during operation.  Hostpath breaks many pod assumptions anyway, so why not PVCs too?

**Comment by travisn** [comment]
the monitors need persistent storage. With K8s 1.7 we will be able to use local storage, which will definitely be a step up from hostPath. However, we can't use a PVC since that requires a storage subsystem, but that presents a chicken-and-egg problem because we are setting up the storage platform.

Overall, my thought is that the operator needs full control of monitors, their health, and deciding when to failover. I'm not seeing that replicaset with count greater than one fits the scenario, or how statefulset solves it.

**Comment by mikefedyk** [comment]
That makes sense to me.  Especially while working with lower layers of the
stack and working with a storage system.

Statefulset can always be revisited later.  It is curious what part of
Statefulset functionality I would be missing for ceph mons and how patroni
for postgres works with it, and what the etcd operator does.

If there is a deficiency in Statefulset, would be nice if it was found and
fixed before that API goes stable.
