### PR TITLE
ceph: fail when metadataDevice not used by cephvol

### LINKED ISSUE #3092: ceph-volume should reject metadataDevice which has same storage class as data devices
(Followup to #2777)

OSDs are now bootstrapped with `ceph-volume`, with optional metadataDevice.   `ceph-volume` does all the magic putting db volume onto metadataDevice, if it is a faster device (eg ssd).  If one specify hdd for both metadataDevice, and device, `ceph-volume` will actually create two hdd OSDs, which is not what the user would expected.  In this case, the metadataDevice config should be rejected. it should warn the user, and proceed with bootstrapping the osd without metadataDevice.

### PR DESCRIPTION
**Pull request by mvollman**
Signed-off-by: Michael Vollman <michael.b.vollman@gmail.com>

**Description of your changes:**
Fail when metadataDevice is specified but ceph-volume batch does not
automatically use the metadataDevice as the block.db.

**Which issue is resolved by this Pull Request:**
Resolves #3092

**Checklist:**
- [x] Documentation has been updated, if necessary.
- [x] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](../CONTRIBUTING.md#comments)

### CODE REVIEW

File: pkg/daemon/ceph/osd/volume.go [hunk 1]
```diff
@@ -149,12 +153,28 @@ func (a *OsdAgent) initializeDevices(context *clusterd.Context, devices *DeviceO
...
+			"json",
 		}...)
 
-		if err := context.Executor.ExecuteCommand(false, "", baseCommand, reportArgs...); err != nil {
+		cvOut, err := context.Executor.ExecuteCommandWithOutput(false, "", baseCommand, reportArgs...)
+		if err != nil {
 			return fmt.Errorf("failed ceph-volume report. %+v", err) // fail return here as validation provided by ceph-volume
 		}
 
+		logger.Infof("ceph-volume report: %+v", cvOut)
```
Comment (BlaineEXE) [inline pkg/daemon/ceph/osd/volume.go]: I think this should be a `Debugf` rather than info.

File: pkg/daemon/ceph/osd/volume.go [hunk 2]
```diff
@@ -149,12 +153,28 @@ func (a *OsdAgent) initializeDevices(context *clusterd.Context, devices *DeviceO
...
+
+		var cvReport cephVolReport
+		if err = json.Unmarshal([]byte(cvOut), &cvReport); err != nil {
+			return fmt.Errorf("failed to unmarshal ceph-volume report json. %+v", err)
+		}
+
+		for _, osd := range cvReport.Osds {
+			if len(osd.BlockDB) == 0 {
+				return fmt.Errorf("ceph-volume not using %s as metadataDevice.", a.metadataDevice)
```
Comment (BlaineEXE) [inline pkg/daemon/ceph/osd/volume.go]: Error messages shouldn't end in a period.

I think this message needs to be more verbose for users to appropriately understand and correct the issue. Something like: "ceph-volume did not use the expected metadataDevice [%s]. ceph-volume report: %s". Ideally, we should also output why c-v didn't do it correctly, but I'm not sure if that information is reported.

**Comment by BlaineEXE** [comment]
Please add this to the pending release notes as well, and also note this in  `Documentation/ceph-cluster-crd.md`.

File: pkg/daemon/ceph/osd/volume.go (hunk 1 above)
Comment (mvollman) [reply pkg/daemon/ceph/osd/volume.go]: I personally like having the c-v report output logged prior to provisioning the OSDs so if your OSD configuration does not match your expectations you can check the log and see why.  Otherwise you would have to clean up the OSDs, enable DEBUG logging and then provision again to get the report.  I also left the report off of the error message since it was just printed here.  If you do still want this to be a debug message I am happy to change it and add the report to the error message.

**Comment by mvollman** [comment]
@BlaineEXE Yes the desired effect is to fail provisioning if c-v batch does not automatically identify the requested metadataDevice as either a DB or Journal depending on scenario.  c-v batch defaults to automatically determining placement of OSDs and metadataDevice based on device performance.

**Comment by mvollman** [comment]
Is there a way for me to trigger a recheck?

File: PendingReleaseNotes.md [hunk 3]
```diff
@@ -6,6 +6,8 @@
 - Creation of storage pools through the custom resource definitions (CRDs) now allows users to optionally specify `deviceClass` property to enable
 distribution of the data only across the specified device class. See [Ceph Block Pool CRD](Documentation/ceph-pool-crd.md#ceph-block-pool-crd) for
 an example usage
+- Provisioning with ceph-volume will fail if metadataDevice is specfied and the metadataDevice is not a higher performing device class than the OSD
```
Comment (BlaineEXE) [inline PendingReleaseNotes.md]: Same concern before regarding the specificities of the functionality built into Rook: "Provisioning will fail if the user specifies a metadataDevice but that device is not used as a metadata device by Ceph." (or something equivalent) should be sufficient here.

File: pkg/daemon/ceph/osd/volume.go (hunk 1 above)
Comment (BlaineEXE) [reply pkg/daemon/ceph/osd/volume.go]: I'm on the fence, so I will leave the choice up to you as a user. There is a balance to be made between overly verbose logs and output that is beneficial to a large number of users. I try to keep in mind that often, restarting the operator with debug logging on is sufficient to figure out an error after it has occurred. As well, overly verbose versus beneficial may change for clusters with dozens of nodes.

**Comment by BlaineEXE** [comment]
> Is there a way for me to trigger a recheck?

Do you mean re-running CI? If so, I usually do a `git commit --amend` without any changes and then push the changed hash to get CI to rerun.

File: pkg/daemon/ceph/osd/volume.go (hunk 1 above)
Comment (travisn) [reply pkg/daemon/ceph/osd/volume.go]: @mvollman The report is already printing in a human readable form and i thought it was working well. Why do we need to change it to json? It seems less readable to the human eye. If we need the json report in order to determine the error condition below, perhaps we should run the readable report first, then run the report again to get the json, but not print the json to the log

File: pkg/daemon/ceph/osd/volume.go [hunk 4]
```diff
@@ -149,12 +153,26 @@ func (a *OsdAgent) initializeDevices(context *clusterd.Context, devices *DeviceO
...
 
+		logger.Infof("ceph-volume report: %+v", cvOut)
+
+		var cvReport cephVolReport
+		if err = json.Unmarshal([]byte(cvOut), &cvReport); err != nil {
+			return fmt.Errorf("failed to unmarshal ceph-volume report json. %+v", err)
+		}
+
+		if path.Join("/dev", a.metadataDevice) != cvReport.Vg.Devices {
+			return fmt.Errorf("ceph-volume did not use the expected metadataDevice [%s]", a.metadataDevice)
```
Comment (travisn) [inline pkg/daemon/ceph/osd/volume.go]: This would be skipping OSD creation for all the devices in this batch. Could you add all the devices to the error message?

File: pkg/daemon/ceph/osd/volume.go (hunk 1 above)
Comment (mvollman) [reply pkg/daemon/ceph/osd/volume.go]: Agreed, the human readable report is nicer to look at.  I was just trying to avoid running ceph-volume 3 times, but I can certainly change it to print the human readable report instead.

File: pkg/daemon/ceph/osd/volume.go (hunk 4 above)
Comment (mvollman) [reply pkg/daemon/ceph/osd/volume.go]: All of the devices will be listed in the human readable c-v output directly above the error in the log.  I can add this, but it would require another variable tracking the devices since they are all just appended to batchArgs.  This could be added in https://github.com/rook/rook/pull/3213 where the osd devices are already available here as a list.

Comment (travisn) [reply pkg/daemon/ceph/osd/volume.go]: true, since it's already in the above output that sounds fine, thanks

File: pkg/daemon/ceph/osd/volume.go [hunk 5]
```diff
@@ -155,6 +157,27 @@ func (a *OsdAgent) initializeDevices(context *clusterd.Context, devices *DeviceO
...
+			"--format",
+			"json",
+		}...)
+
+		cvOut, err := context.Executor.ExecuteCommandWithOutput(false, "", baseCommand, reportArgs...)
+		if err != nil {
+			return fmt.Errorf("failed ceph-volume json report. %+v", err) // fail return here as validation provided by ceph-volume
+		}
+
+		logger.Debugf("ceph-volume report: %+v", cvOut)
```
Comment (travisn) [inline pkg/daemon/ceph/osd/volume.go]: Do we not get the report in human-readable form anymore? Above on line 131 it will only apply when the metadataDevice is not specified. It would still be useful to always have the output even if we have to call c-v twice.

Comment (mvollman) [reply pkg/daemon/ceph/osd/volume.go]: @travisn Yes the human readable report is still there from when it was added in #3149 it is just not changed show it does not show in the diff.  So when metadataDevice is specified we run c-v 3 times and when it is not we run c-v twice.  The json output provides a little more information than the human readable so printing it can be useful for debugging.

Comment (travisn) [reply pkg/daemon/ceph/osd/volume.go]: Ah, now I see it thanks for the clarification

File: Documentation/ceph-cluster-crd.md [hunk 6]
```diff
@@ -148,7 +148,7 @@ Below are the settings available, both at the cluster and individual node level,
 ### OSD Configuration Settings
 The following storage selection settings are specific to Ceph and do not apply to other backends. All variables are key-value pairs represented as strings.
 
-- `metadataDevice`: Name of a device to use for the metadata of OSDs on each node.  Performance can be improved by using a low latency device (such as SSD or NVMe) as the metadata device, while other spinning platter (HDD) devices on a node are used to store data.
+- `metadataDevice`: Name of a device to use for the metadata of OSDs on each node.  Performance can be improved by using a low latency device (such as SSD or NVMe) as the metadata device, while other spinning platter (HDD) devices on a node are used to store data.  Provisioning will fail if the user specifies a metadataDevice but that device is not used as a metadata device by Ceph. Notably, ceph-volume will not use a device of the same device class (HDD, SSD, NVMe) as OSD devices for metadata, resulting in this failure.
```
Comment (leseb) [inline Documentation/ceph-cluster-crd.md]:
```suggestion
- `metadataDevice`: Name of a device to use for the metadata of OSDs on each node.  Performance can be improved by using a low latency device (such as SSD or NVMe) as the metadata device, while other spinning platter (HDD) devices on a node are used to store data. Provisioning will fail if the user specifies a `metadataDevice` but that device is not used as a metadata device by Ceph. Notably, `ceph-volume` will not use a device of the same device class (HDD, SSD, NVMe) as OSD devices for metadata, resulting in this failure.
```

File: PendingReleaseNotes.md [hunk 7]
```diff
@@ -6,6 +6,7 @@
 - Creation of storage pools through the custom resource definitions (CRDs) now allows users to optionally specify `deviceClass` property to enable
 distribution of the data only across the specified device class. See [Ceph Block Pool CRD](Documentation/ceph-pool-crd.md#ceph-block-pool-crd) for
 an example usage
+- Provisioning will fail if the user specifies a metadataDevice but that device is not used as a metadata device by Ceph.
```
Comment (leseb) [inline PendingReleaseNotes.md]:
```suggestion
- Provisioning will fail if the user specifies a `metadataDevice` but that device is not used as a metadata device by Ceph.
```

**Comment by mvollman** [comment]
rebased to check CI status.  @leseb can you take another look?  I made the changes you requested.

**Comment by galexrt** [comment]
Restarted CI.

**Comment by mvollman** [comment]
Rebased again.  @leseb Can you resolve your review of this change? The requested changes were made.  @travisn It appears the CI issues were resolved at one point.  Is this ready to be merged?
