### PR TITLE
osd: add expand-bluefs init container for host-based cluster

### LINKED ISSUE #10930: Raw OSD increment not add as available space but as taken
* Bug Report

**Expected behavior:**
When i increment RAW virtual disk in proxmox of the OSD, the size incremented is not added as available but as taken.

**How to reproduce it (minimal and precise):**
Deploy rook-ceph with HELM on 6 proxmox VM. With the default configuration. Each kubernetes worker need to have 1 disk unused for rook can use it as OSD.
In my setup, disks are virtualized with VirtIO block.
So, when the cluster is deployed with the 3 OSD of workers, i stop the OSD with kubectl -n rook-ceph scale deployment rook-ceph-osd-<id> --replicas=0.
After this i increment the virtual disk from 100GB to 150GB (in proxmox).
When i start the OSD with  rook-ceph scale deployment rook-ceph-osd-<id> --replicas=1, the OSD start correclty but the new space incremented is considered as taken.
image

Log of OSD after restart:
[logs-from-osd-in-rook-ceph-osd-2-78c9b4cc96-klw9k.log](https://github.com/rook/rook/files/9524783/logs-from-osd-in-rook-ceph-osd-2-78c9b4cc96-klw9k.log)

**Environment**:
* OS (e.g. from /etc/os-release):
image

* Kernel (e.g. `uname -a`): Linux k8s-dev-11 5.10.0-15-amd64 '#' 1 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.10.0-alpha.0.95.gc7ab01b94 
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.10 (45fa1a083152e41a408d15505f594ec5f1b4fe17) pacific (stable)
* Kubernetes version (use `kubectl version`): 1.24.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Bare-metal multi-master
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): 
image

### PR DESCRIPTION
**Pull request by cupnes**
**Description of your changes:**
OSD is not resized in host-based clusters even though expanding
the backing block device. It's due to the lack of bluefs-bdev-expand
init container.

**Which issue is resolved by this Pull Request:**
Resolves #10930

**Checklist:**

- [X] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [X] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [X] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [X] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

File: pkg/operator/ceph/cluster/osd/spec.go [hunk 1]
```diff
@@ -1166,6 +1167,32 @@ func (c *Cluster) getExpandPVCInitContainer(osdProps osdProperties, osdID string
...
 
+func (c *Cluster) getExpandInitContainer(osdProps osdProperties, configDir, namespace, osdID string, osdInfo OSDInfo) v1.Container {
+	// Output example is in the comments at the beginning of `getExpandPVCInitContainer`().
+	osdDataPath := activateOSDMountPath + osdID
+
+	_, adminKeyringVolMount := cephkey.Volume().Admin(), cephkey.VolumeMount().Admin()
+	volMounts := []v1.VolumeMount{
+		{Name: activateOSDVolumeName, MountPath: osdDataPath},
+		{Name: "devices", MountPath: "/dev"},
+		{Name: k8sutil.ConfigOverrideName, ReadOnly: true, MountPath: tempEtcCephDir},
```
Comment (satoru-takeuchi) [inline pkg/operator/ceph/cluster/osd/spec.go:1178]: Are this volume and `adminKeyVolMount` and  neccessary in this container? I guess `bluefs-bdev-expand` works without these volumes. CMIIW.

File: pkg/operator/ceph/cluster/osd/spec.go [hunk 2]
```diff
@@ -1166,6 +1167,32 @@ func (c *Cluster) getExpandPVCInitContainer(osdProps osdProperties, osdID string
 	}
 }
 
+func (c *Cluster) getExpandInitContainer(osdProps osdProperties, configDir, namespace, osdID string, osdInfo OSDInfo) v1.Container {
+	// Output example is in the comments at the beginning of `getExpandPVCInitContainer`().
```
[the remark this answers is not in the document]
Comment (cupnes) [reply pkg/operator/ceph/cluster/osd/spec.go]: I fixed.

File: pkg/operator/ceph/cluster/osd/spec.go (hunk 1 above)
Comment (cupnes) [reply pkg/operator/ceph/cluster/osd/spec.go]: You are right. They are not neccessary. I fixed.

**Review by satoru-takeuchi — APPROVED** [review]
@cupnes LGTM, thank you for your contribution!
