### PR TITLE
pool: Allow negative step num in crush rule

### LINKED ISSUE #14685: Block pool deserialization is failing when a custom crush rule was created
rook-ceph v1.15.0 doesn't create CephBlockPool "rook-ceph/replicapool"

rook-ceph-operator error log is as follows

```
2024-09-04 07:40:02.608111 I | ceph-spec: parsing mon endpoints: c=192.168.0.158:6789,a=192.168.0.159:6789,b=192.168.0.160:6789
2024-09-04 07:40:02.836318 E | ceph-block-pool-controller: failed to reconcile CephBlockPool "rook-ceph/replicapool". invalid pool CR "replicapool" spec: failed to get crush map: failed to unmarshal crush map: json: cannot unmarshal number -1 into Go struct field stepSpec.rules.steps.num of type uint
```

```
# cat cephblockpool.yaml
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3

# kubectl create -f cephblockpool.yaml 
cephblockpool.ceph.rook.io/replicapool created

```

ceph didn't find replicapool pool

```
bash-5.1$ ceph osd pool ls 
.mgr


bash-5.1$ ceph status
  cluster:
    id:     15475c67-ab60-4fa2-aa80-92ed018fa93c
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,c,b (age 23h)
    mgr: a(active, since 20h), standbys: b
    osd: 21 osds: 21 up (since 4h), 21 in (since 4h)
 
  data:
    pools:   1 pools, 1 pgs
    objects: 2 objects, 449 KiB
    usage:   630 MiB used, 1.4 TiB / 1.4 TiB avail
    pgs:     1 active+clean

bash-5.1$ ceph -v
ceph version 18.2.4 (e7ad5345525c7aa95470c26863873b581076945d) reef (stable)

sh-5.1$ rook version
2024/09/04 08:06:09 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
rook: v1.15.0
go: go1.22.6

```

OS and k8s information

```
# cat /etc/os-release 
NAME="AlmaLinux"
VERSION="9.2 (Turquoise Kodkod)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="AlmaLinux 9.2 (Turquoise Kodkod)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-9"
ALMALINUX_MANTISBT_PROJECT_VERSION="9.2"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"


# uname -a
Linux test-alma9-kvm167 5.14.0-284.11.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Tue May 9 05:49:00 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

# kubectl version 
Client Version: v1.30.0
```

### PR DESCRIPTION
**Pull request by travisn**
The crush rules may have a negative step num. Rook had assumed negative values were not possible, but just had not been encountered previously in a custom crush rule.

**Issue resolved by this Pull Request:**
Resolves #14685 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by sp98 — APPROVED** [review]

**Review by subhamkrai — APPROVED** [review]

File: pkg/daemon/ceph/client/crush_rule_test.go [hunk 1]
```diff
@@ -56,7 +56,7 @@ func TestBuildCrushSteps(t *testing.T) {
 	assert.Equal(t, 4, len(steps))
 	assert.Equal(t, cephv1.DefaultCRUSHRoot, steps[0].ItemName)
 	assert.Equal(t, "datacenter", steps[1].Type)
-	assert.Equal(t, uint(2), steps[2].Number)
+	assert.Equal(t, 2, steps[2].Number)
```
Comment (parth-gr) [inline pkg/daemon/ceph/client/crush_rule_test.go:59]: can we a unit test for negative number `-2`

Comment (travisn) [reply pkg/daemon/ceph/client/crush_rule_test.go:59]: We actually don't have any code that works with the negative step numbers, we just want to allow it in case the user wants to create custom crush rules. So there is not really anything interesting for a unit test to cover.

Comment (parth-gr) [reply pkg/daemon/ceph/client/crush_rule_test.go:59]: I thought the check is equivalent to 
`ReplicasPerFailureDomain: 2,`
