### PR TITLE
pool: Skip crush rule update when not needed

### LINKED ISSUE #13643: crush rules being recreated, deviceClass has changed (but it hasn't?)
After upgrading to Rook `1.12.10` and Ceph Reef `v18.2.1` we notice repeated messages about crush rules being created and migrated from one failure domain to another, or to a new device class, but it seems to erroneous or at least misleading.  

Rook is creating two identical rules for a pool and only uses one of them, but also logs messages that incorrectly states a rule is no longer being used, and the reason given can be wrong (in the case of deviceClass changes).   Other than the concerning messages, it doesn't seem to have any ill effects on the cluster.

Here's some debug logs filtered for just one block pool.  The failure domain didn't change (host to host), and the rule never changed either, the pool always uses crush rule `ceph-ops1-block-pool-1_host_ssd`.  It seems to be deciding that the `deviceClass` has changed, although the logger isn't configured to print the device class changes.

```
2024-01-26 22:36:46.813204 I | cephclient: creating a new crush rule for changed deviceClass on crush rule "ceph-ops1-block-pool-1_host_ssd"
2024-01-26 22:36:46.813260 I | cephclient: updating pool "ceph-ops1-block-pool-1" failure domain from "host" to "host" with new crush rule "ceph-ops1-block-pool-1_host_ssd"
2024-01-26 22:36:46.813279 I | cephclient: crush rule "ceph-ops1-block-pool-1_host_ssd" will no longer be used by pool "ceph-ops1-block-pool-1"
```

I don't know why `deviceClass` is being detected as changing, since both the rules are `default~ssd`:

https://github.com/rook/rook/blob/release-1.12/pkg/daemon/ceph/client/pool.go#L508-L510

Maybe the deviceClass detection didn't work here? https://github.com/rook/rook/blob/release-1.12/pkg/daemon/ceph/client/pool.go#L544

The message printed here always implies `failureDomain` changed, even when it might be `deviceClass`:

https://github.com/rook/rook/blob/release-1.12/pkg/daemon/ceph/client/pool.go#L517-L518

In any case, I don't think our device class is changing.  This seems to be related to the changes in this commit:

https://github.com/rook/rook/commit/a417ce880cf0124fee15a1843854138091da641a

```
... logs -l app=rook-ceph-operator  | grep ceph-ops1-block-pool-1
2024-01-26 22:34:46.017379 D | ceph-block-pool-controller: successfully configured CephBlockPool "ceph-ops1/ceph-ops1-block-pool-1"
2024-01-26 22:34:59.454871 D | ceph-block-pool-controller: successfully configured CephBlockPool "ceph-ops1/ceph-ops1-block-pool-1"
2024-01-26 22:35:35.823690 D | ceph-block-pool-controller: successfully configured CephBlockPool "ceph-ops1/ceph-ops1-block-pool-1"
2024-01-26 22:35:47.215664 D | ceph-block-pool-controller: successfully configured CephBlockPool "ceph-ops1/ceph-ops1-block-pool-1"
2024-01-26 22:35:57.315926 D | ceph-block-pool-controller: successfully configured CephBlockPool "ceph-ops1/ceph-ops1-block-pool-1"
2024-01-26 22:36:08.535113 D | ceph-block-pool-controller: successfully configured CephBlockPool "ceph-ops1/ceph-ops1-block-pool-1"
2024-01-26 22:36:19.098757 D | ceph-block-pool-controller: successfully configured CephBlockPool "ceph-ops1/ceph-ops1-block-pool-1"
2024-01-26 22:36:30.538633 I | ceph-block-pool-controller: creating pool "ceph-ops1-block-pool-1" in namespace "ceph-ops1"
2024-01-26 22:36:30.538649 D | exec: Running command: ceph osd crush rule create-replicated ceph-ops1-block-pool-1 default host ssd --connect-timeout=15 --cluster=ceph-ops1 --conf=/var/lib/rook/ceph-ops1/ceph-ops1.config --name=client.admin --keyring=/var/lib/rook/ceph-ops1/client.admin.keyring --format json
2024-01-26 22:36:31.523955 D | exec: Running command: ceph osd pool get ceph-ops1-block-pool-1 all --connect-timeout=15 --cluster=ceph-ops1 --conf=/var/lib/rook/ceph-ops1/ceph-ops1.config --name=client.admin --keyring=/var/lib/rook/ceph-ops1/client.admin.keyring --format json
2024-01-26 22:36:33.621571 D | exec: Running command: ceph osd pool application get ceph-ops1-block-pool-1 --connect-timeout=15 --cluster=ceph-ops1 --conf=/var/lib/rook/ceph-ops1/ceph-ops1.config --name=client.admin --keyring=/var/lib/rook/ceph-ops1/client.admin.keyring --format json
2024-01-26 22:36:38.919564 I | cephclient: application "rbd" is already set on pool "ceph-ops1-block-pool-1"
2024-01-26 22:36:38.919603 I | cephclient: reconciling replicated pool ceph-ops1-block-pool-1 succeeded
2024-01-26 22:36:38.919618 D | cephclient: checking that pool "ceph-ops1-block-pool-1" has the failure domain "host" and deviceClass "ssd"
2024-01-26 22:36:38.919645 D | exec: Running command: ceph osd pool get ceph-ops1-block-pool-1 all --connect-timeout=15 --cluster=ceph-ops1 --conf=/var/lib/rook/ceph-ops1/ceph-ops1.config --name=client.admin --keyring=/var/lib/rook/ceph-ops1/client.admin.keyring --format json
2024-01-26 22:36:43.309214 D | exec: Running command: ceph osd crush rule dump ceph-ops1-block-pool-1_host_ssd --connect-timeout=15 --cluster=ceph-ops1 --conf=/var/lib/rook/ceph-ops1/ceph-ops1.config --name=client.admin --keyring=/var/lib/rook/ceph-ops1/client.admin.keyring --format json
2024-01-26 22:36:46.813204 I | cephclient: creating a new crush rule for changed deviceClass on crush rule "ceph-ops1-block-pool-1_host_ssd"
2024-01-26 22:36:46.813260 I | cephclient: updating pool "ceph-ops1-block-pool-1" failure domain from "host" to "host" with new crush rule "ceph-ops1-block-pool-1_host_ssd"
2024-01-26 22:36:46.813279 I | cephclient: crush rule "ceph-ops1-block-pool-1_host_ssd" will no longer be used by pool "ceph-ops1-block-pool-1"
2024-01-26 22:36:46.813318 D | exec: Running command: ceph osd crush rule create-replicated ceph-ops1-block-pool-1_host_ssd default host ssd --connect-timeout=15 --cluster=ceph-ops1 --conf=/var/lib/rook/ceph-ops1/ceph-ops1.config --name=client.admin --keyring=/var/lib/rook/ceph-ops1/client.admin.keyring --format json
2024-01-26 22:36:55.610704 D | exec: Running command: ceph osd pool set ceph-ops1-block-pool-1 crush_rule ceph-ops1-block-pool-1_host_ssd --connect-timeout=15 --cluster=ceph-ops1 --conf=/var/lib/rook/ceph-ops1/ceph-ops1.config --name=client.admin --keyring=/var/lib/rook/ceph-ops1/client.admin.keyring --format json
2024-01-26 22:37:02.920986 I | cephclient: Successfully updated pool "ceph-ops1-block-pool-1" failure domain to "host"
2024-01-26 22:37:02.920999 I | ceph-block-pool-controller: initializing pool "ceph-ops1-block-pool-1" for RBD use
2024-01-26 22:37:02.921008 D | exec: Running command: rbd pool init ceph-ops1-block-pool-1 --cluster=ceph-ops1 --conf=/var/lib/rook/ceph-ops1/ceph-ops1.config --name=client.admin --keyring=/var/lib/rook/ceph-ops1/client.admin.keyring
2024-01-26 22:37:03.926691 I | ceph-block-pool-controller: successfully initialized pool "ceph-ops1-block-pool-1" for RBD use
2024-01-26 22:37:16.118528 D | ceph-block-pool-controller: pool "ceph-ops1/ceph-ops1-block-pool-1" status updated to "Ready"
2024-01-26 22:37:16.118629 D | ceph-block-pool-controller: successfully configured CephBlockPool "ceph-ops1/ceph-ops1-block-pool-1"
```

Here's the pool, it seems to always use `ceph-ops1-block-pool-1_host_ssd` rule:

```
ceph osd pool get ceph-ops1-block-pool-1 all                   
size: 2
min_size: 1
pg_num: 1
pgp_num: 1
crush_rule: ceph-ops1-block-pool-1_host_ssd
hashpspool: true
nodelete: false
nopgchange: false
nosizechange: false
write_fadvise_dontneed: false
noscrub: false
nodeep-scrub: false
use_gmt_hitset: 1
fast_read: 0
pg_autoscale_mode: on
eio: false
bulk: false
```

Here's the two identical rules.  If I delete the unused `ceph-ops1-block-pool-1` rule, it gets recreated by rook:

```
ceph osd crush rule dump ceph-ops1-block-pool-1
{
    "rule_id": 11,
    "rule_name": "ceph-ops1-block-pool-1",
    "type": 1,
    "steps": [
        {
            "op": "take",
            "item": -2,
            "item_name": "default~ssd"
        },
        {
            "op": "chooseleaf_firstn",
            "num": 0,
            "type": "host"
        },
        {
            "op": "emit"
        }
    ]
}


ceph osd crush rule dump ceph-ops1-block-pool-1_host_ssd
{
    "rule_id": 12,
    "rule_name": "ceph-ops1-block-pool-1_host_ssd",
    "type": 1,
    "steps": [
        {
            "op": "take",
            "item": -2,
            "item_name": "default~ssd"
        },
        {
            "op": "chooseleaf_firstn",
            "num": 0,
            "type": "host"
        },
        {
            "op": "emit"
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by travisn**
The crush rule will be updated when the failure domain changes. This update can be skipped when the expected crush rule is already configured. Otherwise, the log has a confusing message that makes it appear that the crush rule was updated when in fact it was not.

These messages were seen in the operator log on every reconcile of the existing pools:
```
2024-02-14 23:40:27.118868 I | cephclient: updating pool "myfs-replicated" failure domain from "osd" to "osd" with new crush rule "myfs-replicated_osd"
2024-02-14 23:40:27.118870 I | cephclient: crush rule "myfs-replicated_osd" will no longer be used by pool "myfs-replicated"
2024-02-14 23:40:28.665915 I | cephclient: Successfully updated pool "myfs-replicated" failure domain to "osd"
```

**Issue resolved by this Pull Request:**
Resolves #13643 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by subhamkrai** [comment]
@travisn I had brief look at the pr seems like this is related to this issue https://github.com/rook/rook/issues/13643 maybe we need to fix this https://github.com/rook/rook/issues/13643#issuecomment-1921352780 ?

**Review by BlaineEXE — APPROVED** [review]
Looks good. I wonder if it's worth updating the unit test to ensure the side effects are as intended in this case.

**Comment by travisn** [comment]
> @travisn I had brief look at the pr seems like this is related to this issue #13643 maybe we need to fix this [#13643 (comment)](https://github.com/rook/rook/issues/13643#issuecomment-1921352780) ?

Reading through that issue, I believe this will fix it. Rook is indicating it needs to update the device class even though it's the same, so nothing will actually change.

**Comment by travisn** [comment]
> > @travisn I had brief look at the pr seems like this is related to this issue #13643 maybe we need to fix this [#13643 (comment)](https://github.com/rook/rook/issues/13643#issuecomment-1921352780) ?
> 
> Reading through that issue, I believe this will fix it. Rook is indicating it needs to update the device class even though it's the same, so nothing will actually change.

After reading through #13643 more closely, I re-ordered the printing of some logs to indicate when the crush rule is being updated, and to handle if the crush rule name is not changing. This will cover if the current deviceClass is detected as a version of `default`, and is desired to stay as default since the setting is blank in the pool CR. 

I had repro'd this by creating the filesystem-test.yaml example, which sets the `failureDomain: osd`. So anyone setting `failureDomain` and not setting `deviceClass` would have seen these log messages that indicate the same crush rule would be created repeatedly.

**Review by subhamkrai — COMMENTED** [review]
do we need to handle where deviceClass name has prefix added by ceph for example
we set `ssd` but in the command it will print `"default~ssd"`.

For example
```
ceph osd crush rule dump ceph-ops1-block-pool-1_host_ssd
{
    "rule_id": 12,
    "rule_name": "ceph-ops1-block-pool-1_host_ssd",
    "type": 1,
    "steps": [
        {
            "op": "take",
            "item": -2,
            "item_name": "default~ssd"
        },
        {
            "op": "chooseleaf_firstn",
            "num": 0,
            "type": "host"
        },
        {
            "op": "emit"
        }
    ]
}
```

Copied the example from the original issue. We can also discuss more offline.

File: pkg/daemon/ceph/client/pool.go [hunk 1]
```diff
@@ -510,18 +510,23 @@ func updatePoolCrushRule(context *clusterd.Context, clusterInfo *ClusterInfo, cl
...
-		logger.Infof("creating a new crush rule for changed deviceClass on crush rule %q", details.CrushRule)
-	}
-
 	// Use a crush rule name that is unique to the desired failure domain
 	crushRuleName := fmt.Sprintf("%s_%s", pool.Name, pool.FailureDomain)
 	if pool.DeviceClass != "" {
 		crushRuleName = fmt.Sprintf("%s_%s_%s", pool.Name, pool.FailureDomain, pool.DeviceClass)
 	}
+	if crushRuleName == details.CrushRule {
+		logger.Debugf("crush rule already set to %q for pool %q", crushRuleName, pool.Name)
```
Comment (BlaineEXE) [inline pkg/daemon/ceph/client/pool.go:519]: We could also log failure domain and device class here informationally. It's definitely not necessary but could clarify Rook's internal state if there is ever a time when it doesn't fully match Ceph's state or the user's desired state.

**Review by BlaineEXE — APPROVED** [review]

**Comment by travisn** [comment]
> do we need to handle where deviceClass name has prefix added by ceph for example we set `ssd` but in the command it will print `"default~ssd"`.
> 
> For example
> 
> ```
> ceph osd crush rule dump ceph-ops1-block-pool-1_host_ssd
> {
>     "rule_id": 12,
>     "rule_name": "ceph-ops1-block-pool-1_host_ssd",
>     "type": 1,
>     "steps": [
>         {
>             "op": "take",
>             "item": -2,
>             "item_name": "default~ssd"
>         },
>         {
>             "op": "chooseleaf_firstn",
>             "num": 0,
>             "type": "host"
>         },
>         {
>             "op": "emit"
>         }
>     ]
> }
> ```
> 
> Copied the example from the original issue. We can also discuss more offline.

I'm seeing that this case is already handled by these changes. We didn't need any special processing for the `default~hdd` because we skip if the crush rule of the expected name already exists.

If I create a pool named `hddpool` with `deviceClass: hdd` and `failureDomain: osd`, then restart the operator I see this log and no action is taken:
```
2024-02-16 19:23:59.169828 D | cephclient: crush rule already set to "hddpool_osd_hdd" for pool "hddpool"
```

**Review by subhamkrai — APPROVED** [review]
