### PR TITLE
osd: remount filestore device at startup if it has already been forma…

### LINKED ISSUE #736: OSD cannot start after a pod delete
Hello,

I'm trying to implement Rook in my K8S cluster, managed to use block devices through StorageClass but now i'm challenging Rook resiliency by shutting down OSD nodes.
At first when leaving dataDirHostPath: "" in the rook-cluster config, the osd configuration wasn't persistent so at every osd node reboot or osd pod delete/recreate, i lost the configuration of the previous osd.
Now i'm using dataDirHostPath: "/var/lib/rook-storage" and the config is saved properly into this directory.

The problem is when i delete an osd pod, on recreating, the osd throws error because he doesn't seem to be able to access the dataDirHostPath mounted in /var/lib/rook.

From my recreated OSD container, i have the mount point and all files as below : 

```
/ # ls -lalh /var/lib/rook/
total 4.0K
drwxr-xr-x 6 root root  87 Jun 14 10:33 .
drwxr-xr-x 1 root root  18 Jun 14 10:33 ..
drwxr--r-- 2 root root  45 Jun 14 10:33 bootstrap-osd
drwxr--r-- 2 root root  40 Jun 13 14:25 mon0
drwxr--r-- 2 root root  40 Jun 14 10:33 mon1
drwxr--r-- 4 root root 201 Jun 14 10:33 osd3
-rw-r--r-- 1 root root 277 Jun 13 14:25 partition-scheme
/ # ls -lalh /var/lib/rook/osd3/
total 1.1G
drwxr--r-- 4 root root  201 Jun 14 10:33 .
drwxr-xr-x 6 root root   87 Jun 14 10:33 ..
-rw-r--r-- 1 root root   37 Jun 14 10:33 ceph_fsid
drwxr-xr-x 4 root root   65 Jun 14 10:33 current
-rw-r--r-- 1 root root   37 Jun 14 10:33 fsid
-rw-r--r-- 1 root root 1.0G Jun 14 10:33 journal
-rw------- 1 root root   56 Jun 14 10:33 keyring
-rw-r--r-- 1 root root   21 Jun 14 10:33 magic
-rw-r--r-- 1 root root    6 Jun 14 10:33 ready
-rw-r--r-- 1 root root 2.0K Jun 14 10:33 rook.config
-rw-r--r-- 1 root root    4 Jun 14 10:33 store_version
-rw-r--r-- 1 root root   53 Jun 14 10:33 superblock
drwxr--r-- 2 root root   29 Jun 14 10:33 tmp
-rw-r--r-- 1 root root   10 Jun 14 10:33 type
-rw-r--r-- 1 root root    2 Jun 14 10:33 whoami
```

Still, OSD logs show that there is a problem when accessing these files :

```
2017-06-14 10:33:52.811009 I | mkfs-osd3: 2017-06-14 10:33:52.810967 e222240  0 filestore(/var/lib/rook/osd3) mount: enabling WRITEAHEAD journal mode: checkpoint is not enabled
2017-06-14 10:33:52.811069 I | mkfs-osd3: 2017-06-14 10:33:52.811040 e222240 -1 journal FileJournal::_open: disabling aio for non-block journal.  Use journal_force_aio to force use of aio anyway
2017-06-14 10:33:52.811990 I | mkfs-osd3: 2017-06-14 10:33:52.811920 e222240 -1 filestore(/var/lib/rook/osd3) could not find #-1:7b3f43c4:::osd_superblock:0# in index: (2) No such file or directory
2017-06-14 10:33:52.839009 I | mkfs-osd3: 2017-06-14 10:33:52.838934 e222240 -1 created object store /var/lib/rook/osd3 for osd.3 fsid ee7d8f35-73a9-4176-a43c-1cc166e1ccce
2017-06-14 10:33:52.839043 I | mkfs-osd3: 2017-06-14 10:33:52.838974 e222240 -1 auth: error reading file: /var/lib/rook/osd3/keyring: can't open /var/lib/rook/osd3/keyring: (2) No such file or directory
2017-06-14 10:33:52.839128 I | mkfs-osd3: 2017-06-14 10:33:52.839099 e222240 -1 created new key in keyring /var/lib/rook/osd3/keyring
2017-06-14 10:33:52.841620 I | mkfs-osd3: 2017-06-14 10:33:52.788249 e222240 -1 journal FileJournal::_open: disabling aio for non-block journal.  Use journal_force_aio to force use of aio anyway
2017-06-14 10:33:52.841634 I | mkfs-osd3: 2017-06-14 10:33:52.811040 e222240 -1 journal FileJournal::_open: disabling aio for non-block journal.  Use journal_force_aio to force use of aio anyway
2017-06-14 10:33:52.841645 I | mkfs-osd3: 2017-06-14 10:33:52.811920 e222240 -1 filestore(/var/lib/rook/osd3) could not find #-1:7b3f43c4:::osd_superblock:0# in index: (2) No such file or directory
2017-06-14 10:33:52.841649 I | mkfs-osd3: 2017-06-14 10:33:52.838934 e222240 -1 created object store /var/lib/rook/osd3 for osd.3 fsid ee7d8f35-73a9-4176-a43c-1cc166e1ccce
2017-06-14 10:33:52.841669 I | mkfs-osd3: 2017-06-14 10:33:52.838974 e222240 -1 auth: error reading file: /var/lib/rook/osd3/keyring: can't open /var/lib/rook/osd3/keyring: (2) No such file or directory
2017-06-14 10:33:52.841676 I | mkfs-osd3: 2017-06-14 10:33:52.839099 e222240 -1 created new key in keyring /var/lib/rook/osd3/keyring
2017-06-14 10:33:52.842906 E | cephosd: failed to config osd 3. failed to initialize OSD at /var/lib/rook/osd3: mon_command auth add failed: cephd: Invalid argument
2017-06-14 10:33:52.842918 I | cephosd: 0/1 osd devices succeeded on this
```
What can i do to get this persistent OSD config setting? I cannot troubleshoot it myself because i have no visibility on the ceph tools used by rookd during the osd init.

### PR DESCRIPTION
**Pull request by jbw976**
…tted/partitioned

Fixes #736

### CODE REVIEW

File: pkg/ceph/osd/device.go [hunk 1]
```diff
@@ -305,6 +288,71 @@ func partitionOSD(context *clusterd.Context, config *osdConfig) error {
 	return nil
 }
 
+func prepareFilestoreDevice(context *clusterd.Context, config *osdConfig, doFormat bool) error {
+	if !isFilestoreDevice(config) {
+		// nothing to do
+		return nil
```
Comment (kokhang) [inline pkg/ceph/osd/device.go]: shouldnt this raise an error if it gets here and it is not Filestore? Or are there valid cases where this could happen?

File: pkg/ceph/osd/agent.go [hunk 2]
```diff
@@ -565,6 +565,13 @@ func refreshDeviceInfo(name string, nameToUUID map[string]string, scheme *PerfSc
 func (a *OsdAgent) startOSD(context *clusterd.Context, config *osdConfig) error {
 	newOSD := false
 	config.rootPath = path.Join(config.configRoot, fmt.Sprintf("osd%d", config.id))
+
+	if isFilestoreDevice(config) {
+		if err := remountFilestoreDeviceIfNeeded(context, config); err != nil {
```
Comment (kokhang) [inline pkg/ceph/osd/agent.go]: Should this check be placed in the `else` block line L623, since this is not a new OSD?

File: pkg/ceph/osd/device.go (hunk 1 above)
Comment (jbw976) [inline pkg/ceph/osd/device.go]: no, there are no valid cases for this to be called when it's not a filestore device.  i'll update it to return an error.

File: pkg/ceph/osd/agent.go (hunk 2 above)
Comment (jbw976) [inline pkg/ceph/osd/agent.go]: we actually don't know if it's a new OSD or not until after we do the remounting (if it's needed).  we check if it's a new OSD or not by the existence of its `whoami` file, which doesn't show up until after the filestore device is remounted.

I'm moving the declaration of the `newOSD` variable until after this check to make it more clear that we don't know if it's new or not yet.
