### PR TITLE
rgw: avoid double encoding of certificate secret

### LINKED ISSUE #967: RGW Certificate double base64 encoded
If I run `rookctl create object --certificate=some.pem` it creates a secret with the pem file base64 encoded in kubernetes.
Problem is that somehow the pem file is double encoded which makes starting the rgw instance fail.

```
2017-09-07 18:23:29.217856 I | rgw: 2017-09-07 18:23:29.217791 7f81fe14be80  0 starting handler: civetweb
2017-09-07 18:23:29.261865 I | rgw: 2017-09-07 18:23:29.261623 7f81fe14be80  0 civetweb: 0x563ddd60a1a0: ssl_use_pem_file: cannot open certificate file /etc/rook/private/rgw-cert.pem: error:0906D06C:PEM routines:PEM_read_bio:no start line
```

### PR DESCRIPTION
**Pull request by travisn**
Fixes #967

### CODE REVIEW

File: pkg/api/k8s/cluster_handler.go [hunk 1]
```diff
@@ -54,8 +53,7 @@ func (s *clusterHandler) EnableObjectStore(config model.ObjectStore) error {
 		certName := fmt.Sprintf("rook-rgw-%s-cert", config.Name)
 		config.CertificateRef = certName
 
-		encodedCert := base64.StdEncoding.EncodeToString([]byte(config.Certificate))
```
Comment (jbw976) [inline pkg/api/k8s/cluster_handler.go]: is this because kubernetes does the encoding for us already automatically?

Comment (travisn) [reply pkg/api/k8s/cluster_handler.go]: right, the api handles it for us
