### PR TITLE
cassandra: fix wrong mount point

### LINKED ISSUE #2443: [cassandra] wrong mount point for PersistentVolume
* Bug Report

**Deviation from expected behavior:**
The cassandra operator should mount the persistent volume under `/var/lib/cassandra`. Instead, it mounts it under `/var/lib/cassandra/data`, which is the data directory. That means the commitlog gets written in the host disk, which results in a bottleneck.

**Expected behavior:**
PersistentVolume should be mounted under `/var/lib/cassandra`.

### PR DESCRIPTION
**Pull request by yanniszark**
**Description of your changes:**
Fixes wrong mount point for PersistentVolume used by Cassandra. Code changes are very minor.

**Which issue is resolved by this Pull Request:**
Resolves #2443

### CODE REVIEW

File: pkg/operator/cassandra/constants/constants.go [hunk 1]
```diff
@@ -68,8 +68,8 @@ const (
 	SharedDirName = "/mnt/shared"
 	PluginDirName = SharedDirName + "/" + "plugins"
 
-	DataDirCassandra = "/var/lib/cassandra/data"
-	DataDirScylla    = "/var/lib/scylla/data"
+	DataDirCassandra = "/var/lib/cassandra"
```
Comment (galexrt) [inline pkg/operator/cassandra/constants/constants.go]: Is this change backwards compatible?

Comment (yanniszark) [reply pkg/operator/cassandra/constants/constants.go]: It should be. 
Essentially, the commit log is written in ephemeral storage and is lost when the Pod dies. This is wrong and bottlenecks Cassandra's speed to the ephemeral disk's speed.
With these changes, the commit log is written on the PersistentVolume and persists across reboots.

Comment (galexrt) [reply pkg/operator/cassandra/constants/constants.go]: @yanniszark If currently for existing instances the contents of `/var/lib/cassandra/data` where "directly" written to the "root" of the PV:
```
ROOT OF PV
-old-file-1
-old-file-2
```
and you now change it the mount dir to `/var/lib/cassandra`, it would result in this:
```
ROOT OF PV
-old-file-1
-old-file-2
-data/
  -new-file-1
  -new-file-2
```

Meaning that the `old-file-*` are just "sitting" there not being used as new `new-file-*` are generated which are used for the DB(s), which could lead to data loss when Cassandra doesn't replicate fast enough till the next Pod(s) are going down so that the data is still available enough.

Please make sure this is backwards compatible.

Comment (yanniszark) [reply pkg/operator/cassandra/constants/constants.go]: You're right, it isn't backwards compatible because:

If we remount an disk with existing data on /var/lib/cassandra instead of /var/lib/cassandra/data, cassandra will not recognise the folder structure. So the way to ensure compatibility would be to copy all the data in the PV under a new data folder. 

Old PV filesystem:
- file1
- file2

New PV Filesystem: 
- data/file1
- data/file2

Let's see how we can move on with this.

File: Documentation/cassandra-operator-upgrade.md [hunk 2]
```diff
@@ -0,0 +1,74 @@
+---
+title: Cassandra Operator Upgrade
```
Comment (galexrt) [inline Documentation/cassandra-operator-upgrade.md]: As it is not "only" the operator, but the clusters too, naming the file and title just "Cassandra Upgrade".

File: Documentation/cassandra-operator-upgrade.md [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+weight: 51
+---
+
+# Cassandra Operator Upgrades
+
+This guide will walk you through the manual steps to upgrade the software in Cassandra Operator from one version to the next. The cassandra operator is made up of two parts:
```
Comment (galexrt) [inline Documentation/cassandra-operator-upgrade.md]: Same here.

File: Documentation/cassandra-operator-upgrade.md [hunk 4]
```diff
@@ -0,0 +1,74 @@
...
+With this upgrade guide, there are a few notes to consider:
+* **WARNING:** Upgrading a Rook cluster is not without risk. There may be unexpected issues or
+  obstacles that damage the integrity and health of your storage cluster, including data loss. Only
+  proceed with this guide if you are comfortable with that. It is recommended that you backup your data before proceeding.
+* **WARNING:** The current process to upgrade REQUIRES the cluster to be unavailable for the time of the upgrade.
+
+## Prerequisites
+
+* Before starting the procedure, ensure that your Cassandra Clusters are in a healthy state. You can check a Cassandra Cluster's health by using `kubectl describe $NAME -n $NAMESPACE` and ensuring that for each rack in the Status, `readyMembers` equals `members`.
+* If you are upgrading from v0.9.1 to a later version, the mount point of the PVC for each member has changed because it was wrong.
```
Comment (galexrt) [inline Documentation/cassandra-operator-upgrade.md]: "it was wrong" isn't really correct here from my perspsective.
It was correct and still is, but it was not optimal in point that all persistent and "temporary" (journal, write log or so) data on the volume.

File: Documentation/cassandra-operator-upgrade.md [hunk 5]
```diff
@@ -0,0 +1,74 @@
...
+```bash
+# Assumes cluster rook-cassandra in namespace rook-cassandra
+NAME=rook-cassandra
+NAMESPACE=rook-cassandra
+
+kubectl get $NAME -n $NAMESPACE -o yaml > $NAME.yaml
+kubectl delete $NAME -n $NAMESPACE
+```
+
+2. After that, we upgrade the version of the `Controller`. To achieve that, we patch the StatefulSet running the `Controller`:
```
Comment (galexrt) [inline Documentation/cassandra-operator-upgrade.md]: "Controller"? It is about the Rook Cassandra Operator, right? Just writing operator or the full would be less confusing (same for the first list point).

File: Documentation/cassandra-operator-upgrade.md [hunk 6]
```diff
@@ -0,0 +1,74 @@
...
+3. Recreate the manifests previously deleted:
+```bash
+kubectl apply -f $NAME.yaml
+```
+The controller will pick up the newly created Cassandra Clusters and recreate them with the correct version of the sidecar.
+
+
+## Before Upgrading from v0.9.1
+
+* Do the following before proceeding:
```
Comment (galexrt) [inline Documentation/cassandra-operator-upgrade.md]: Remove the list point here:
```
Do the following before proceeding:

* For each member of each cluster:
[...]
```

File: Documentation/cassandra-operator-upgrade.md [hunk 7]
```diff
@@ -0,0 +1,74 @@
...
+```
+
+3. Recreate the manifests previously deleted:
+```bash
+kubectl apply -f $NAME.yaml
+```
+The controller will pick up the newly created Cassandra Clusters and recreate them with the correct version of the sidecar.
+
+
+## Before Upgrading from v0.9.1
```
Comment (galexrt) [inline Documentation/cassandra-operator-upgrade.md]: It would be good to add a note at the top of the document that this section exists and must be walked through if one wants to upgrade to v0.9.1

I think the anchor for this section would be `#before-upgrading-from-v091`.

File: Documentation/cassandra-operator-upgrade.md (hunk 5 above)
Comment (yanniszark) [reply Documentation/cassandra-operator-upgrade.md]: This is a naming thing (always the worst :stuck_out_tongue: )
The pattern of using a controller and a CRD is called the Operator pattern. 
The software running, looping and watching the CRD is called a Controller. 
But since operator is heavily used in the rook docs, maybe it's better to call it that.
@jbw976 what do you think?

File: Documentation/cassandra-operator-upgrade.md (hunk 6 above)
Comment (yanniszark) [reply Documentation/cassandra-operator-upgrade.md]: Will do!

File: Documentation/cassandra-operator-upgrade.md (hunk 7 above)
Comment (yanniszark) [reply Documentation/cassandra-operator-upgrade.md]: Sounds good, will do!

File: Documentation/cassandra-operator-upgrade.md (hunk 5 above)
Comment (jbw976) [reply Documentation/cassandra-operator-upgrade.md]: in my experience (within the Rook community especially), the common understanding is that Operator is used to cover all of that, both the pattern and the controller itself.  I would use the terminology of "operator" in this document here to avoid confusion.

**Comment by yanniszark** [comment]
@galexrt I finally found some time to add the recommended changes.
This should pass review now!

**Comment by galexrt** [comment]
@yanniszark I think you need to fix the rebase as you have other commits in the PR. I'm looking at the PR now.

File: Documentation/cassandra-operator-upgrade.md [hunk 8]
```diff
@@ -0,0 +1,74 @@
...
+NAME=rook-cassandra
+NAMESPACE=rook-cassandra
+
+kubectl get $NAME -n $NAMESPACE -o yaml > $NAME.yaml
+kubectl delete $NAME -n $NAMESPACE
+```
+
+2. After that, we upgrade the version of the `Operator`. To achieve that, we patch the StatefulSet running the `Operator`:
+```bash
+# Assumes Operator is running in StatefulSet rook-cassandra-operator
```
Comment (galexrt) [inline Documentation/cassandra-operator-upgrade.md]: Just wondering, why is the Cassandra operator a StatefulSet and not a Deployment as the other operators?

Comment (yanniszark) [reply Documentation/cassandra-operator-upgrade.md]: Because the Deployment doesn't guarantee that at most one instance of the operator is running. 
With Deployment you may end up with 2 instances of the operator which will race with each other. 
We may use Deployment later when we implement some kind of leader election. 

Finally, the kubebuilder project generates a Statefulset for running an operator, which confirms this is the right choice to make.

File: Documentation/cassandra-operator-upgrade.md [hunk 9]
```diff
@@ -0,0 +1,74 @@
...
+## Procedure
+
+1. Because each version of the `Operator` is designed to work with the same version of the `Sidecar`, they must be upgraded together. In order to avoid mixing versions between the `Operator` and `Sidecar`, we first delete every Cassandra Cluster CRD in our Kubernetes cluster, after first backing up their manifests. This will not delete your data because the PVCs will be retained even if the Cassandra Cluster object is deleted. Example:
+```bash
+# Assumes cluster rook-cassandra in namespace rook-cassandra
+NAME=rook-cassandra
+NAMESPACE=rook-cassandra
+
+kubectl get $NAME -n $NAMESPACE -o yaml > $NAME.yaml
+kubectl delete $NAME -n $NAMESPACE
```
Comment (galexrt) [inline Documentation/cassandra-operator-upgrade.md]: Aren't the object names are missing (e.g., `kubectl delete pod $NAME -n $NAMESPACE`)?

File: Documentation/cassandra-operator-upgrade.md [hunk 10]
```diff
@@ -0,0 +1,74 @@
...
+
+# Change /var/lib/cassandra to /var/lib/scylla for a scylla cluster
+kubectl exec $POD -n $NAMESPACE -- /bin/bash 
+
+> mkdir /var/lib/cassandra/data/data
+> shopt -s extglob
+> mv !(/var/lib/cassandra/data) /var/lib/cassandra/data/data
+```
+
+After that continue with the upgrade procedure.
```
Comment (galexrt) [inline Documentation/cassandra-operator-upgrade.md]: `with the upgrade` -> `with the operator upgrade`

File: Documentation/cassandra-operator-upgrade.md (hunk 9 above)
Comment (yanniszark) [reply Documentation/cassandra-operator-upgrade.md]: You are correct!
It's missing the `clusters.cassandra.rook.io` object name.
Just added it !
