### PR TITLE
Stripping out debug log of rbd command output for ListImages

### LINKED ISSUE #942: rbd commands fail if extra logging is on
As @mrahbar found in https://gitter.im/rook/rook?at=599f301fa7b406262dc32732, extra logging turned on will cause `rbd` commands to fail.  This is because `rbd` does not support `--out-file` and both its logging and its output/result go to stdout.  We fail to parse the result that is mixed in with the logging.

It would be nice if upstream Ceph's `rbd` could support the `--out-file` argument.

### PR DESCRIPTION
**Pull request by mrahbar**
Fixes #942 

## Changes
- Added simple brackets regex for ListImages with the assumption that stdout contains the relevant information as a json-block
- added test for different log-level

## Playground code snippet
https://play.golang.org/p/fxA5beReir

### CODE REVIEW

File: pkg/ceph/client/image.go [hunk 1]
```diff
@@ -41,6 +42,9 @@ func ListImages(context *clusterd.Context, clusterName, poolName string) ([]Ceph
 		return nil, fmt.Errorf("failed to list images for pool %s: %+v", poolName, err)
 	}
 
+	res := regexp.MustCompile(`\[(.*)\]$`).FindStringSubmatch(string(buf))
+	buf = []byte(res[0])
```
Comment (jbw976) [inline pkg/ceph/client/image.go]: We should check to make sure there's 1 entry in the slice before indexing into it.  If the slice is empty, should that be an error condition or should we just return an empty slice from this function?

File: pkg/ceph/client/image_test.go [hunk 2]
```diff
@@ -91,3 +91,103 @@ func TestCreateImage(t *testing.T) {
 	assert.True(t, createCalled)
 	createCalled = false
 }
+
+func TestListImageLogLevelInfo(t *testing.T) {
```
Comment (jbw976) [inline pkg/ceph/client/image_test.go]: nice work adding unit tests too!

File: pkg/ceph/client/image_test.go [hunk 3]
```diff
@@ -91,3 +91,103 @@ func TestCreateImage(t *testing.T) {
...
+	emptyListResult = true
+	images, err = ListImages(context, "foocluster", "pool1")
+	assert.Nil(t, err)
+	assert.NotNil(t, images)
+	assert.True(t, len(images) == 0)
+	assert.True(t, listCalled)
+	listCalled = false
+}
+
+func TestListImageLogLevelDebug(t *testing.T) {
```
Comment (jbw976) [inline pkg/ceph/client/image_test.go]: Looks like this unit test failed in the Jenkins build: https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-947/2/pipeline

```
--- FAIL: TestListImageLogLevelDebug (0.00s)
	assertions.go:237: 
                        
	Error Trace:	image_test.go:180
		
	Error:		Expected nil, but got: &errors.errorString{s:"unmarshal failed: invalid character '\\\\' after top-level value.  raw buffer response: []\\n[{\"image\":\"image1\",\"size\":1048576,\"format\":2},{\"image\":\"image2\",\"size\":2048576,\"format\":2},{\"image\":\"image3\",\"size\":3048576,\"format\":2}]"}
		
	assertions.go:237: 
                        
	Error Trace:	image_test.go:181
		
	Error:		Expected value not to be nil.
		
	assertions.go:237: 
                        
	Error Trace:	image_test.go:182
		
	Error:		Should be true
```
Are you seeing the same failure locally?

File: pkg/ceph/client/image.go [hunk 4]
```diff
@@ -41,6 +42,9 @@ func ListImages(context *clusterd.Context, clusterName, poolName string) ([]Ceph
 		return nil, fmt.Errorf("failed to list images for pool %s: %+v", poolName, err)
 	}
 
+	res := regexp.MustCompile(`\[(.*)\]$`).FindStringSubmatch(string(buf))
```
Comment (jbw976) [inline pkg/ceph/client/image.go]: consider adding a comment about why this regex is necessary.

**Comment by kokhang** [comment]
@mrahbar could you change the title and make it more explicit. In the body you can put "fixes #942". It looks more descriptive for someone browsing commit history.

File: pkg/ceph/client/image_test.go (hunk 3 above)
Comment (mrahbar) [reply pkg/ceph/client/image_test.go]: Sorry but on my windows laptop I'm currently not able to run the tests...but I will try bring this test case somehow to work

File: pkg/ceph/client/image.go (hunk 1 above)
Comment (mrahbar) [reply pkg/ceph/client/image.go]: I was testing this on a ceph cluster with and without images as well as on INFO and debug log. The results of rbd ls -l are in the playground code. 
I will add the length check anyways an threat it as an empty case since error checking was already done at that line.

File: pkg/ceph/client/image_test.go (hunk 3 above)
Comment (mrahbar) [reply pkg/ceph/client/image_test.go]: The tests seem to run, a carriage return messed up the result

**Comment by jbw976** [comment]
LGTM now, please squash/rebase all the changes into a single commit and then we can approve and merge.  Thanks!

**Comment by mrahbar** [comment]
The failing tests wasn't windows specific but on my laptop the vendor packages wasn't set up correctly so I got a lot of 'flag redefined: ' errors

**Comment by jbw976** [comment]
Thanks again for your efforts @mrahbar! :satisfied:
