### PR TITLE
Get flexvolume plugin dir for all k8s versions

### LINKED ISSUE #1162: rook-agent using default volume plugin path when a non-default has been set on the Kubelet
I update CoreOS from 1409.7.0 to 1520.8.0 and kubernters from 1.6.1 to 1.8.1 and now i have error when "rook-agent" conteiners running.
all (3) rook-agent conteiners have status RunContainerError.
And in conteiners logs i see this:
kubectl -n rook-system logs rook-agent-mklwd
failed to open log file "/var/log/pods/7a5eb042-be51-11e7-8ce2-0050569d04a3/rook-agent_1.log": open /var/log/pods/7a5eb042-be51-11e7-8ce2-0050569d04a3/rook-agent_1.log: no such file or directory
I can provide any data to solve this problem if necessary.

### PR DESCRIPTION
**Pull request by jbw976**
Fixes #1162

### CODE REVIEW

**Comment by jbw976** [comment]
@kokhang @travisn @dangula you can take a look at this PR now, I think this will be a decent way to catch regressions in discovering the flexvolume path as we integrate with new k8s versions.

File: pkg/operator/agent/agent.go [hunk 1]
```diff
@@ -217,40 +221,68 @@ func (a *Agent) discoverFlexvolumeDir() string {
...
-	flexvolumeDirPath = configKubelet.ComponentConfig.VolumePluginDir
-	if flexvolumeDirPath == "" {
-		// unmarshall to a NodeConfigControllerManager
-		configControllerManager := NodeConfigControllerManager{}
-		if err := json.Unmarshal(nodeConfig, &configControllerManager); err != nil {
-			logger.Warningf("unable to parse node config from controller manager: %+v", err)
-			return getDefaultFlexvolumeDir()
-		}
+
+	if flexvolumeDirPath != "" {
```
Comment (travisn) [inline pkg/operator/agent/agent.go]: why check for a value here? Why not simply log and return in the previous code block on line 229? Seems like the checks for empty string could be removed in that case. If the unmarshal fails, have you seen that it can actually successfully assign a value to the path?

File: pkg/operator/agent/agent.go [hunk 2]
```diff
@@ -217,40 +221,68 @@ func (a *Agent) discoverFlexvolumeDir() string {
...
 		flexvolumeDirPath = configControllerManager.ComponentConfig.VolumeConfiguration.FlexVolumePluginDir
-		if flexvolumeDirPath == "" {
-			flexvolumeDirPath = getDefaultFlexvolumeDir()
-		}
 	}
 
-	logger.Infof("using flexvolume dir path: %s", flexvolumeDirPath)
-	return flexvolumeDirPath
+	if flexvolumeDirPath != "" {
+		logFlexvolumeDirSource("NodeConfigControllerManager")
```
Comment (travisn) [inline pkg/operator/agent/agent.go]: minor suggestion... You could return two values from the function: `source` and `path`. Then the logging of the source could be done once by the caller instead of everywhere there is a return inside this method.

File: pkg/operator/agent/agent.go [hunk 3]
```diff
@@ -217,40 +221,68 @@ func (a *Agent) discoverFlexvolumeDir() string {
...
+		return flexvolumeDirPath
+	}
+
+	// unmarshal to a KubeletConfiguration
+	kubeletConfiguration := KubeletConfiguration{}
+	if err := json.Unmarshal(nodeConfig, &kubeletConfiguration); err != nil {
```
Comment (travisn) [inline pkg/operator/agent/agent.go]: this is the new code path that only works with 1.8? After the 1.8 client changes, would you expect this isn't necessary anymore?

File: pkg/operator/agent/agent.go (hunk 1 above)
Comment (jbw976) [reply pkg/operator/agent/agent.go]: there are 3 types we know of that can be returned from the node config API.  if the JSON response is of a different type than we attempt to unmarshal it as, the unmarshal operation succeeds but we get the zero values for the fields in the unmarshalled struct.  JSON decoding in golang is very permissive in that way.  See this example: https://play.golang.org/p/VbhEoylRED

Just because the unmarshal did not return an error, that does not in any way guarantee that we will have a non empty flexvolume directory path.  That's why i'm checking after each unmarshal to see if we actually have an answer, because we often don't, and we then need to move onto the next try.

i have not seen the unmarshal straight up fail before, that may only happen if the JSON is malformed, but i'm not certain.  I was trying to be as resilient as possible such that if unmarshalling returns an error we will try with the next type.

File: pkg/operator/agent/agent.go (hunk 2 above)
Comment (jbw976) [reply pkg/operator/agent/agent.go]: yes, i think i like this approach better to return both the path and the source.

File: pkg/operator/agent/agent.go (hunk 3 above)
Comment (jbw976) [reply pkg/operator/agent/agent.go]: yes this is the new type that only works with 1.8+.  I suspect that when we have the 1.8 client to build against, we can refer to the proper type directly.  Here's the new type in the 1.8 tree: https://github.com/kubernetes/kubernetes/blob/release-1.8/pkg/kubelet/apis/kubeletconfig/types.go#L187

**Comment by jbw976** [comment]
@travisn i've responded to your feedback and incorporated some too, PTAL.

File: pkg/operator/agent/agent.go (hunk 3 above)
Comment (travisn) [reply pkg/operator/agent/agent.go]: ok, i'll keep an eye on it with the 1.8 changes

File: pkg/operator/agent/agent.go (hunk 1 above)
Comment (travisn) [reply pkg/operator/agent/agent.go]: ok, i see that it might not even fail, but it could still be empty

**Comment by kokhang** [comment]
Hey @jbw976, thanks for looking at this. I would also suggest that we test a non-default volume-plugin. Perhaps on just our 1.8.x test, we can add the --volume-plugin-dir flag to point at somewhere else. You can do that with something similar to https://github.com/rook/rook/blob/master/tests/scripts/kubeadm.sh#L28. This will test both the new response type and that a non-default path works.

Sorry i cant be more descriptive. I am typing from my phone since i didnt bring my mac (might have been purposely) on my vacation.

**Comment by jbw976** [comment]
thanks @kokhang, i wanted to make the integration tests use a non default path, but wasn't quite sure the best way to do it.  i've tried to follow the example you pointed me at with a new commit, so we will see how the integration tests run with that update now.

**Comment by kokhang** [comment]
Integration tests passed but it doesnt say whether the non-default plugin dir is being used. It would be awesome if we could get the log printout from the agent and output it on the integration test logs. So that we can see whether the source is correct by looking at `discovered flexvolume dir path from source` log line.

**Comment by jbw976** [comment]
For some reason I thought it would get logged out, but I needed to make another update for that to happen.  This is what the test output looks like now, so I can confirm on 1.8 we are properly using a non-default path:
```
=== RUN   TestOperatorGetFlexvolumePath
2017-11-27 20:39:15.229527 I | integrationTest: flexvolume discovery log statement: discovered flexvolume dir path from source KubeletConfiguration. value: /var/lib/kubelet/volumeplugins
--- PASS: TestOperatorGetFlexvolumePath (0.01s)
```
