### PR TITLE
external: update logging when comparing ceph version

### LINKED ISSUE #13782: Confusing ceph cluster version message
* Bug Report

**Deviation from expected behavior:**
When attempting to using the `rook-ceph` module from MicroK8s with an external MicroCeph cluster, I started receiving the following error message:
`ceph-file-controller: failed to reconcile refusing to run new crd: local cluster ceph version is higher "17.2.6-0 quincy" than the external cluster "18.2.1-0 reef", this must never happen`
The error message is confusing, 17 is not higher than 18.

I am logging this here as I found the [code in question](https://github.com/rook/rook/blob/04a5fd6ab5fae673f821deea49a2e6ba3b0eef21/pkg/operator/ceph/version/version.go#L313) within this project.

I am not raising an issue about my problem using `CephFS`, it's just about the error message received when attempting to do so.

**Expected behavior:**
The error messages need to be understandable. The parameters passed to the `errors.Errorf` method do not appear match the order of the text.

It may also be that the preceeding `IsSuperior` check is invalid, all depending on if the order of the text or paramaters is correct (I am not expert enough to make that call).

**How to reproduce it (minimal and precise):**
There may be quicker way to do this, but this is how I enouctered the message:
* Install MicroCeph 18.2.0 or 17.2.6 (single node is OK): `snap install microceph`
  * Perform [basic configuration](https://canonical-microceph.readthedocs-hosted.com/en/latest/tutorial/single-node/)
* Install MicroK8s 1.29 (single node is OK): `snap install microk8s --revision=6364 --classic`
* Enable Rook-Ceph: `microk8s enable rook-ceph`
  * [Connect to MicroCeph](https://microk8s.io/docs/how-to-ceph#connect-microceph-to-microk8s-3)
* Attempt to configure CephFS my using a [modified Rook example](https://rook.io/docs/rook/latest-release/Storage-Configuration/Shared-Filesystem-CephFS/filesystem-storage/):
```
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: myfs
  #Updated for rook-ceph
  namespace: rook-ceph-external 
spec:
  metadataPool:
    replicated:
      # Reduced purely for testing
      size: 1 
  dataPools:
    - replicated:
        size: 1
  preservePoolsOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true
```
* `microk8s.kubectl apply -f the.yaml`
* In time the message will start to appear
 
**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 22.02
* Kernel (e.g. `uname -a`): .5.0-17-generic
* Cloud provider or hardware configuration: N/A
* Rook version (use `rook version` inside of a Rook Pod): v1.11.9
* Storage backend version (e.g. for ceph do `ceph -v`): 18.2.0 Reef and 17.2.6 Quincy
* Kubernetes version (use `kubectl version`): v1.29.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): MicroK8s
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_OK

### PR DESCRIPTION
**Pull request by shay1760**
external: update logging when comparing ceph version

when comparing local ceph version with external cluster
there is wrong log printing. Updating to print the right
log message.

 ci: remove extra space with 'network' commit title

removing extra space infront of 'network' commit tittle.

**Issue resolved by this Pull Request:**
Resolves #13782 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

File: pkg/operator/ceph/version/version.go [hunk 1]
```diff
@@ -310,7 +310,7 @@ func ValidateCephVersionsBetweenLocalAndExternalClusters(localVersion, externalV
 
 	// Local version must never be higher than the external one
 	if IsSuperior(localVersion, externalVersion) {
-		return errors.Errorf("local cluster ceph version is higher %q than the external cluster %q, this must never happen", externalVersion.String(), localVersion.String())
```
Comment (travisn) [inline pkg/operator/ceph/version/version.go:313]: The check is for `IsSuperior()`, which means we are only trying to validate if the local version is higher than the external ceph version, which isn't supported. Why isn't this message accurate? The suggested message isn't accurate since we do not require the versions to match.

Comment (parth-gr) [reply pkg/operator/ceph/version/version.go:313]: I think the message is correct

Comment (parth-gr) [inline pkg/operator/ceph/version/version.go:313]: It's just the printing issue,
```
return errors.Errorf("local cluster ceph version is higher %q than the external cluster %q, this must never happen", localVersion.String(), externalVersion.String()) 
Local version should come before.
```

**Review by parth-gr — CHANGES_REQUESTED** [review]

File: pkg/operator/ceph/version/version.go (hunk 1 above)
Comment (shay1760) [reply pkg/operator/ceph/version/version.go:313]: Right, updated the log

File: pkg/operator/ceph/version/version.go [hunk 2]
```diff
@@ -310,7 +310,7 @@ func ValidateCephVersionsBetweenLocalAndExternalClusters(localVersion, externalV
...
+		return errors.Errorf("local cluster ceph version is higher %q than the external cluster %q, this must never happen", localVersion.String(), externalVersion.String())
```
Comment (travisn) [inline pkg/operator/ceph/version/version.go:313]: a small suggestion
```suggestion
		return errors.Errorf("local cluster ceph version %q is higher than the external cluster version %q, this must never happen", localVersion.String(), externalVersion.String())
```

Comment (shay1760) [reply pkg/operator/ceph/version/version.go]: updated

**Review by travisn — APPROVED** [review]

**Review by parth-gr — APPROVED** [review]

**Review by subhamkrai — APPROVED** [review]
