### PR TITLE
Set min Ceph version to 13.2.4 and improved orchestration event handling

### LINKED ISSUE #2632: Ceph version management with Rook version
Since I've started my work on implementing msgr2 support in Rook (https://github.com/rook/rook/pull/2559), I add to implement a Ceph version check, to perform certain operations whether we run Nautilus and above or earlier versions.
Currently Rook support Luminous, Mimic and Nautilus (let's say partially)

The exceptions are going to grow over time, that's a given. The more they grow the more complex the Rook code will be to maintain and years from now we are going to regret it. At first we think, "yes that's not so much" and then we keep addind more and more exceptions. I realize this might break Rook's promise to have a single operator *to rule them all* but in the long run that's not worth it.

To mitigate that, I believe we should start pinning the support for N number of version of Ceph for a certain version of the Rook operator. One major version of the operator could support up to two Ceph version (so we can handle upgrades).

Rook 1.0 is around the corner and I believe it's a good opportunity to make it Ceph Nautilus only. So basically we would have something like:

* Rook 0.X supports Luminous and Mimic
* Rook 1.0 supports Nautilus (upgrade path included from Mimic) and Octopus
* Rook 1.1 supports  P (upgrade path included from Octopus) and Q

So to go from Mimic to Nautilus, you will have to upgrade the operator first, then trigger your Ceph upgrade to Nautilus.

@BlaineEXE @travisn @jbw976 @galexrt, @liewegas, @rootfs  please share your thoughts :).

### PR DESCRIPTION
**Pull request by travisn**
**Description of your changes:**
In v1.1 we need to increase the min version of ceph that is supported to a release of Mimic
- Luminous is no longer supported in v1.1
- No longer should we be creating bluestore OSDs with rook's legacy partitioning scheme. `ceph-volume` should always be called by rook to create OSDs. 

The operator was also in need of some simplification and basic refactor for handling update events for the cluster CRs. The code around the updates was getting unnecessarily complex. The changes include:
- If the `onUpdate` event is creating a new cluster (since the `onAdd` event failed), treat it as a new cluster and properly initialize the new cluster
- Range checks for mon count are not necessary in the operator code since these are checked statically in the CRD manifest
- Status updates to the CRs simplified by refactoring logging to a common place instead of being duplicated. @dyusupov EdgeFS code was touched in this area.

Resolves #2632 

**Checklist:**

- [X] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/v1.0/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [X] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](../CONTRIBUTING.md#comments)
- [ ] Add the flag for skipping the CI if this PR does not require a build. See [here](/INSTALL.md#skip-ci) for more details.

[all logs]

### CODE REVIEW

File: pkg/operator/ceph/cluster/controller.go [hunk 1]
```diff
@@ -256,81 +256,57 @@ func (c *ClusterController) onAdd(obj interface{}) {
...
+	failedMessage := ""
+	state := cephv1.ClusterStateError
 
-		if !cluster.Spec.CephVersion.AllowUnsupported {
-			if !cephVersion.Supported() {
-				err = fmt.Errorf("unsupported ceph version detected: %s. allowUnsupported must be set to true to run with this version", cephVersion)
-				logger.Errorf("%+v", err)
-				validOrchestration = false
-				// it may seem strange to log error and exit true but we don't want to retry if the version is not supported
+	err := wait.Poll(clusterCreateInterval, clusterCreateTimeout, func() (bool, error) {
```
Comment (BlaineEXE) [inline pkg/operator/ceph/cluster/controller.go]: I found myself confused for quite a while trying to figure out how a return-less function is returning `bool, err`. It's very easy to miss that this comes from this function definition as a parameter. Could we change this so that the `func() (bool, error)` is defined before the `wait.Poll` call? It also seems just as good/better to define a new function for this `func (c *clusterController) funcName() (bool, err)` and send the `failedMessage` with the error when returning.

File: pkg/operator/ceph/cluster/controller.go [hunk 2]
```diff
@@ -801,24 +753,22 @@ func (c *ClusterController) removeFinalizer(obj interface{}) {
...
-func (c *ClusterController) updateClusterStatus(namespace, name string, state cephv1.ClusterState, message string) error {
-	logger.Infof("CephCluster %s status: %s", namespace, state)
+func (c *ClusterController) updateClusterStatus(namespace, name string, state cephv1.ClusterState, message string) {
+	logger.Infof("CephCluster %s status: %s. %s", namespace, state, message)
 
 	// get the most recent cluster CRD object
 	cluster, err := c.context.RookClientset.CephV1().CephClusters(namespace).Get(name, metav1.GetOptions{})
 	if err != nil {
-		return fmt.Errorf("failed to get cluster from namespace %s prior to updating its status: %+v", namespace, err)
+		logger.Errorf("failed to get cluster from namespace %s prior to updating its status: %+v", namespace, err)
```
Comment (BlaineEXE) [inline pkg/operator/ceph/cluster/controller.go]: With these errors, we should include what the new status is so that if a users' cluster status can't be trusted, at least that information is available in the logs alongside the error.

File: pkg/operator/edgefs/cluster/controller.go [hunk 3]
```diff
@@ -384,20 +362,19 @@ func (c *ClusterController) handleDelete(clust *edgefsv1beta1.Cluster, retryInte
 	return nil
 }
 
-func (c *ClusterController) updateClusterStatus(namespace, name string, state edgefsv1beta1.ClusterState, message string) error {
+func (c *ClusterController) updateClusterStatus(namespace, name string, state edgefsv1beta1.ClusterState, message string) {
```
Comment (BlaineEXE) [inline pkg/operator/edgefs/cluster/controller.go]: Changing edgefs code here seems out of scope for a Ceph PR.

File: pkg/operator/ceph/cluster/cluster.go [hunk 4]
```diff
@@ -83,37 +84,63 @@ func newCluster(c *cephv1.CephCluster, context *clusterd.Context) *cluster {
...
+		return nil, true, fmt.Errorf("failed to extract ceph version. %+v", err)
 	}
-
 	logger.Infof("Detected ceph image version: %s", version)
-	return version, nil
+
+	return version, false, c.checkVersion(version)
+}
+
+func (c *cluster) checkVersion(version *cephver.CephVersion) error {
```
[the remark this answers is not in the document]
Comment (travisn) [reply pkg/operator/ceph/cluster/cluster.go]: If we're already in a ceph and the version type is CephVersion, I wouldn't think the method name would also need `Ceph`.

File: pkg/operator/ceph/cluster/cluster.go [hunk 5]
```diff
@@ -83,37 +84,63 @@ func newCluster(c *cephv1.CephCluster, context *clusterd.Context) *cluster {
 	}
 }
 
-func (c *cluster) detectCephVersion(rookImage, cephImage string, timeout time.Duration) (*cephver.CephVersion, error) {
+// detectCephVersion loads the ceph version from the image and checks that it meets the version requirements to
+// run in the cluster
+func (c *cluster) detectCephVersion(rookImage, cephImage string, timeout time.Duration) (*cephver.CephVersion, bool, error) {
+	logger.Infof("detecting the ceph image version for image %s...", cephImage)
```
[the remark this answers is not in the document]
Comment (travisn) [reply pkg/operator/ceph/cluster/cluster.go]: For docs I would want consistency, but why for logging? Logs tend to be lower case so i wouldn't worry about it.

File: pkg/operator/ceph/cluster/cluster.go [hunk 6]
```diff
@@ -83,37 +84,63 @@ func newCluster(c *cephv1.CephCluster, context *clusterd.Context) *cluster {
 	}
 }
 
-func (c *cluster) detectCephVersion(rookImage, cephImage string, timeout time.Duration) (*cephver.CephVersion, error) {
+// detectCephVersion loads the ceph version from the image and checks that it meets the version requirements to
+// run in the cluster
+func (c *cluster) detectCephVersion(rookImage, cephImage string, timeout time.Duration) (*cephver.CephVersion, bool, error) {
```
[the remark this answers is not in the document]
Comment (travisn) [reply pkg/operator/ceph/cluster/cluster.go]: That's fair, i'll separate to two methods.

File: pkg/operator/ceph/cluster/cluster.go [hunk 7]
```diff
@@ -83,37 +84,63 @@ func newCluster(c *cephv1.CephCluster, context *clusterd.Context) *cluster {
...
+		return fmt.Errorf("the version does not meet the minimum version: %s", cephver.Minimum.String())
+	}
+
+	if !version.Supported() {
+		logger.Warningf("unsupported ceph version detected: %s.", version)
+
+		if c.Spec.CephVersion.AllowUnsupported {
+			return nil
+		}
+
```
[the remark this answers is not in the document]
Comment (travisn) [reply pkg/operator/ceph/cluster/cluster.go]: As long as gofmt doesn't enforce the whitespace, we'll always be fighting for consistency with different styles. For example, I think a blank line after a closing brace is good in general, even if not required.

File: pkg/operator/ceph/cluster/cluster_test.go [hunk 8]
```diff
@@ -0,0 +1,57 @@
...
+	v = &cephver.CephVersion{Major: 15}
+	assert.Nil(t, c.checkVersion(v))
+}
+
+func TestSupportedVersion(t *testing.T) {
+	c := cluster{Spec: &cephv1.ClusterSpec{}}
+
+	// Unsupported versions are not valid
+	v := &cephver.CephVersion{Major: 15, Minor: 2, Extra: 0}
+	assert.NotNil(t, c.checkVersion(v))
```
[the remark this answers is not in the document]
Comment (travisn) [reply pkg/operator/ceph/cluster/cluster_test.go]: Is there a difference in behavior? To me it's a preference thing.

File: pkg/operator/ceph/cluster/controller.go (hunk 1 above)
Comment (travisn) [reply pkg/operator/ceph/cluster/controller.go]: While readability of inline methods is always going to have its challenges, I think defining it like this is also helpful because it's only used in this one place and you can easily see that context that it's for continued polling. In fact, everywhere rook calls `wait.Poll()`, it defines the method inline.

File: pkg/operator/ceph/cluster/controller.go (hunk 2 above)
Comment (travisn) [reply pkg/operator/ceph/cluster/controller.go]: The previous line in the log (see line 757) will show the current status. It seems redundant if we add it here.

File: pkg/operator/edgefs/cluster/controller.go (hunk 3 above)
Comment (travisn) [reply pkg/operator/edgefs/cluster/controller.go]: This status change method is the same for both ceph and edgefs. When there is a pattern used across multiple backends that needs updating I'd rather update it at the same time. There is at least a separate commit for this change. @dyusupov Does that work for you?

**Comment by travisn** [comment]
Updated integration tests, docs, and yamls now added as well. @BlaineEXE PTAL, thanks!

File: Documentation/ceph-pool-crd.md [hunk 9]
```diff
@@ -54,7 +54,7 @@ High performance applications typically will not use erasure coding due to the p
 
 When creating an erasure-coded pool, it is highly recommended to create the pool when you have **bluestore OSDs** in your cluster
 (see the [OSD configuration settings](ceph-cluster-crd.md#osd-configuration-settings). Filestore OSDs have
-[limitations](http://docs.ceph.com/docs/luminous/rados/operations/erasure-code/#erasure-coding-with-overwrites) that are unsafe and lower performance.
+[limitations](http://docs.ceph.com/docs/nautilus/rados/operations/erasure-code/#erasure-coding-with-overwrites) that are unsafe and lower performance.
```
Comment (leseb) [inline Documentation/ceph-pool-crd.md]: Shouldn't we always point to master instead of changing the release every now and then?

File: pkg/operator/ceph/cluster/cluster.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (BlaineEXE) [reply pkg/operator/ceph/cluster/cluster.go]: It ultimately is a nit, and I won't push. The Go documents do mention that log messages should not *start* with a capital unless it is a proper noun, which implies that they expect some people at least will capitalize proper nouns.

File: pkg/operator/ceph/cluster/cluster_test.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (BlaineEXE) [reply pkg/operator/ceph/cluster/cluster_test.go]: There is no difference in behavior, but there is a difference in readability and a difference in the cognitive effort required to interpret the line. I would say that choosing the more explicit of available options is a solid best-practice.

File: pkg/operator/ceph/cluster/controller.go (hunk 1 above)
Comment (BlaineEXE) [reply pkg/operator/ceph/cluster/controller.go]: I've encountered this a few times in the past week, and I get tripped up every time. Can we meet in the middle and move the `func() (bool, error) {` to the next line so that it stands out more? The examples I see of go code online with functions as parameters do this, and those functions are seldom more than 10 lines long.

File: pkg/operator/ceph/cluster/controller.go (hunk 2 above)
Comment (BlaineEXE) [reply pkg/operator/ceph/cluster/controller.go]: As a developer I agree that it's redundant, but I think for users all the information we give to them in the error message itself empowers them. I think about how many times I've seen someone ask on slack how to fix some problem, and the only information given is a single error line. Users can be myopic and often don't look further than the first error they find. This would be especially helpful if debug logging is turned on, as the previous message might be lost in a sea of messages the `ceph` tool spits out.

File: Documentation/ceph-pool-crd.md (hunk 9 above)
Comment (BlaineEXE) [reply Documentation/ceph-pool-crd.md]: I think I would lean toward using master as well. My reasoning being that the master docs will inform the user that the docs are for a dev version, and they will then be prompted to seek out docs for the Ceph version they're using. Otherwise we have assumed they are using nautilus when they may be using mimic, and they won't see any kind of warning there.

File: pkg/operator/edgefs/cluster/controller.go (hunk 3 above)
Comment (BlaineEXE) [reply pkg/operator/edgefs/cluster/controller.go]: With separate commit and @dyusupov 's ok, seems okay to me.

File: pkg/operator/ceph/cluster/controller.go [hunk 10]
```diff
@@ -496,36 +481,13 @@ func (c *ClusterController) onUpdate(oldObj, newObj interface{}) {
 
 	// if the image changed, we need to detect the new image version
 	if oldClust.Spec.CephVersion.Image != newClust.Spec.CephVersion.Image {
-		logger.Infof("the ceph version changed. detecting the new image version...")
-		version, err := cluster.detectCephVersion(c.rookImage, newClust.Spec.CephVersion.Image, detectCephVersionTimeout)
+		logger.Infof("the ceph version changed")
+		version, _, err := c.detectAndValidateCephVersion(cluster, newClust.Spec.CephVersion.Image)
```
Comment (BlaineEXE) [inline pkg/operator/ceph/cluster/controller.go]: This function is only used twice, once with the middle parameter omitted and once with it kept. In this situation, having this function doesn't add value over simply choosing to call `validateCephVersion` after the latter situation and not calling it here.

File: pkg/operator/ceph/cluster/cluster_test.go [hunk 11]
```diff
@@ -0,0 +1,57 @@
...
+	// All versions at least 13.2.4 are valid
+	v = &cephver.CephVersion{Major: 13, Minor: 2, Extra: 4}
+	assert.Nil(t, c.validateCephVersion(v))
+	v = &cephver.CephVersion{Major: 14}
+	assert.Nil(t, c.validateCephVersion(v))
+	v = &cephver.CephVersion{Major: 15}
+	assert.Nil(t, c.validateCephVersion(v))
+}
+
+func TestSupportedVersion(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (travisn) [reply pkg/operator/ceph/cluster/cluster_test.go]: Sure i'll add a test for that

File: pkg/operator/ceph/cluster/controller.go (hunk 10 above)
Comment (travisn) [reply pkg/operator/ceph/cluster/controller.go]: In both situations I need to call `validateCephVersion()`. The difference is whether or not the error means we should retry the operation. So I see it reducing the duplication by having the helper method.

File: pkg/operator/ceph/cluster/controller.go (hunk 2 above)
Comment (travisn) [reply pkg/operator/ceph/cluster/controller.go]: In principal I agree that more info in messages can help reduce confusion. Good error messages can make all the difference in a product. In this case I don't see the concern of getting lost in other debug messages from the previous line, but i'll add it anyway.

File: pkg/operator/edgefs/cluster/controller.go (hunk 3 above)
Comment (travisn) [reply pkg/operator/edgefs/cluster/controller.go]: For clarify i decided to split it out into #3509. I'll rebase this after that merges.

File: Documentation/ceph-cluster-crd.md [hunk 12]
```diff
@@ -44,12 +44,12 @@ Settings can be specified at the global level to apply to the cluster as a whole
 ### Cluster Settings
 
 - `cephVersion`: The version information for launching the ceph daemons.
-  - `image`: The image used for running the ceph daemons. For example, `ceph/ceph:v12.2.9-20181026` or `ceph/ceph:v13.2.2-20181023`.
+  - `image`: The image used for running the ceph daemons. For example, `ceph/ceph:v13.2.6-20190604` or `ceph/ceph:v14.2.1-20190430`.
```
Comment (leseb) [inline Documentation/ceph-cluster-crd.md]: Should we bump this to `v14.2.2-20190722`?

File: Documentation/ceph-pool-crd.md (hunk 9 above)
Comment (leseb) [reply Documentation/ceph-pool-crd.md]: I still think using master is easier for the reasons mentioned by @BlaineEXE. At some point, they should look at the doc corresponding with their Ceph version.

File: cluster/examples/kubernetes/ceph/common.yaml [hunk 13]
```diff
@@ -42,9 +42,6 @@ spec:
                   type: boolean
                 image:
                   type: string
-                name:
-                  pattern: ^(luminous|mimic|nautilus)$
```
[the remark this answers is not in the document]
Comment (BlaineEXE) [reply cluster/examples/kubernetes/ceph/common.yaml]: I thought I saw that `name` is still in the API struct, but I may have been mistaken.

File: Documentation/ceph-pool-crd.md (hunk 9 above)
Comment (BlaineEXE) [reply Documentation/ceph-pool-crd.md]: Did this just get missed? It's still on `nautilus`.

**Comment by travisn** [comment]
@BlaineEXE Nautilus links updated now, thanks for catching that.

**Comment by travisn** [comment]
The additional test log collection shows that at the end of the multicluster file test, the operator is waiting on the wrong mds daemon name. This then causes the operator to stall and break later tests. A new commit is added to fix this issue.
```
2019-08-12 17:37:43.138301 I | op-mon: checking if we can continue the deployment rook-ceph-mds-test-fs-2-a
2019-08-12 17:37:43.141247 I | exec: Running command: ceph status --connect-timeout=15 --cluster=mrc-n2 --conf=/var/lib/rook/mrc-n2/mrc-n2.config --keyring=/var/lib/rook/mrc-n2/client.admin.keyring --format json --out-file /tmp/702385445
2019-08-12 17:37:44.128662 I | util: retrying after 15s, last error: mds rook-ceph-mds-test-fs-2-a not found in fsmap, this likely means mdss are transitioning between active and standby states
```

File: pkg/daemon/ceph/client/filesystem.go [hunk 14]
```diff
@@ -195,7 +195,7 @@ func SetNumMDSRanks(context *clusterd.Context, cephVersion cephver.CephVersion,
 	// Now check the error to see if we can even determine whether we should reduce or not
 	if errAtStart != nil {
 		return fmt.Errorf(`failed to get filesystem %s info needed to ensure mds rank can be changed correctly,
-if Ceph version is Luminous (12.y.z) and num active mdses (max_mds) was lowered, USER should deactivate extra active mdses manually: %v`,
+if num active mdses (max_mds) was lowered, USER should deactivate extra active mdses manually: %v`,
```
Comment (leseb) [inline pkg/daemon/ceph/client/filesystem.go]:
```suggestion
if num active mdses (max_mds) was lowered, USER should deactivate extra active mdses manually: %+v`,
```

I know it's not part of your change, but while we are at it...

File: tests/longhaul/base_block_test.go [hunk 15]
```diff
@@ -145,7 +145,7 @@ func StartLoadTestCluster(t func() *testing.T, namespace string) (LoadTestCluste
 	kh, err := utils.CreateK8sHelper(t)
 	require.NoError(t(), err)
 
-	i := installer.NewCephInstaller(t, kh.Clientset, false, installer.VersionMaster, cephv1.CephVersionSpec{Image: "ceph/ceph:v12.2.7"})
+	i := installer.NewCephInstaller(t, kh.Clientset, false, installer.VersionMaster, cephv1.CephVersionSpec{Image: "ceph/ceph:v14.2.1"})
```
Comment (leseb) [inline tests/longhaul/base_block_test.go]:
```suggestion
	i := installer.NewCephInstaller(t, kh.Clientset, false, installer.VersionMaster, cephv1.CephVersionSpec{Image: "ceph/ceph:v14.2.2"})
```

?

Comment (travisn) [reply tests/longhaul/base_block_test.go]: now updated to a valid image name with the date
