### PR TITLE
ceph: Only restart ceph dashboard module if settings changed

### LINKED ISSUE #6527: Rook 1.4.5 - MGR restarted in a static environment more than 20 times
Hi,
I'm running the cluster for 12d and I noticed that it has rebooted for 19 times. didn't find a reason why
I attached the mgr and operator logs.

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

* Kernel (e.g. `uname -a`):
Linux node1 4.15.0-121-generic #123-Ubuntu SMP Mon Oct 5 16:16:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
1.4.5
* Storage backend version (e.g. for ceph do `ceph -v`):
15.2.4
* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:51Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:36:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
kubespray 2.12

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
HEALTH_OK
[mgr-crash.zip](https://github.com/rook/rook/files/5473578/mgr-crash.zip)

### PR DESCRIPTION
**Pull request by travisn**
**Description of your changes:**
If ssl was not enabled, the dashboard was being restarted with every reconcile. Instead, the dashboard should only be restarted when the settings have changed in order to reduce the frequency that the dashboard is restarted.

**Which issue is resolved by this Pull Request:**
Resolves #6527 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

File: pkg/operator/ceph/cluster/mgr/dashboard_test.go [hunk 1]
```diff
@@ -133,8 +133,8 @@ func TestStartSecureDashboard(t *testing.T) {
 	assert.NoError(t, err)
 	// the dashboard is enabled, then disabled and enabled again to restart
 	// it with the cert, and another restart when setting the dashboard port
```
Comment (BlaineEXE) [inline pkg/operator/ceph/cluster/mgr/dashboard_test.go:135]: This comment is no longer true, yes?

Comment (travisn) [reply pkg/operator/ceph/cluster/mgr/dashboard_test.go:135]: Good catch I'll update it

**Review by BlaineEXE — APPROVED** [review]
