### PR TITLE
ceph: fix cert manager errors

### LINKED ISSUE #7955: ci: intermittent failure on webhook cert
See:

```
2021-05-20 07:56:14.714780 D | exec: mutatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook created
2021-05-20 07:56:14.788262 D | exec: validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook created
2021-05-20 07:56:15.010505 D | exec: No resources found in cert-manager namespace.
2021-05-20 07:56:16.459057 D | exec: No resources found in cert-manager namespace.
2021-05-20 07:56:17.715942 D | exec: No resources found in cert-manager namespace.
2021-05-20 07:56:18.949203 D | exec: No resources found in cert-manager namespace.
2021-05-20 07:56:20.127921 D | exec: No resources found in cert-manager namespace.
2021-05-20 07:56:27.556431 D | exec: Deploying webhook config
2021-05-20 07:56:28.271270 D | exec: Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": x509: certificate signed by unknown authority
2021-05-20 07:56:28.271304 D | exec: Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": x509: certificate signed by unknown authority
2021-05-20 07:56:28.531375 D | exec: warning: deleting cluster-scoped resources, not scoped to the provided namespace
2021-05-20 07:56:28.541436 D | exec: Error from server (NotFound): validatingwebhookconfigurations.admissionregistration.k8s.io "rook-ceph-webhook" not found
2021-05-20 07:56:29.072739 D | exec: Error from server (NotFound): certificates.cert-manager.io "rook-admission-controller-cert" not found
```

Seen in https://github.com/rook/rook/pull/7953/checks?check_run_id=2627814259

### PR DESCRIPTION
**Pull request by subhamkrai**
**Description of your changes:**
see individual commits.

**Which issue is resolved by this Pull Request:**
Resolves #7955 #7876 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by subhamkrai** [comment]
@vbnrh ^^

File: tests/scripts/deploy_admission_controller.sh [hunk 1]
```diff
@@ -54,6 +54,7 @@ echo "Deploying cert-manager"
 kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/$CERT_VERSION/cert-manager.yaml
 timeout 150 sh -c 'until [ $(kubectl -n cert-manager get pods --field-selector=status.phase=Running|grep -c ^cert-) -eq 3 ]; do sleep 1; done'
 timeout 20 sh -c 'until [ $(kubectl -n cert-manager get pods -o custom-columns=READY:status.containerStatuses[*].ready | grep -c true) -eq 3 ]; do sleep 1; done'
+sleep 20
```
Comment (leseb) [inline tests/scripts/deploy_admission_controller.sh:57]: How can we check like above instead of sleeping?

**Review by leseb — CHANGES_REQUESTED** [review]

File: tests/scripts/deploy_admission_controller.sh (hunk 1 above)
Comment (subhamkrai) [reply tests/scripts/deploy_admission_controller.sh:57]: the reason for sleep is for cainjector to inject ca certs https://github.com/jetstack/cert-manager/issues/3338#issuecomment-707579834. I'm not aware if there is any command to check ca injector status.

Comment (subhamkrai) [reply tests/scripts/deploy_admission_controller.sh:57]: I'm looking if I can find something

**Comment by vbnrh** [comment]
Please run through CI few times and ensure none of the issues are occurring.

**Comment by subhamkrai** [comment]
I restarted integration tests which run the admission controller(total 8 for ceph including diff k8s versions) around 12 time which means a total of 96 actions to confirm it didn't fail with admission controller starting problem. So, I asume we are good now.

File: tests/scripts/deploy_admission_controller.sh [hunk 2]
```diff
@@ -33,12 +50,16 @@ export SERVICE_NAME="rook-ceph-admission-controller"
 
 echo "$BASE_DIR"
 
+echo "Deploying cert-manager"
 kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/$CERT_VERSION/cert-manager.yaml
 timeout 150 sh -c 'until [ $(kubectl -n cert-manager get pods --field-selector=status.phase=Running|grep -c ^cert-) -eq 3 ]; do sleep 1; done'
 timeout 20 sh -c 'until [ $(kubectl -n cert-manager get pods -o custom-columns=READY:status.containerStatuses[*].ready | grep -c true) -eq 3 ]; do sleep 1; done'
+timeout 25 sh -c 'until [ $(kubectl get validatingwebhookconfigurations cert-manager-webhook -o jsonpath='{.webhooks[*].clientConfig.caBundle}' | wc -c) -gt 1 ]; do sleep 1; done'
```
Comment (leseb) [inline tests/scripts/deploy_admission_controller.sh:57]: much better!

Comment (leseb) [inline tests/scripts/deploy_admission_controller.sh:57]:
```suggestion
timeout 25 sh -c 'until [ $(kubectl get validatingwebhookconfigurations cert-manager-webhook -o jsonpath='{.webhooks[*].clientConfig.caBundle}' | wc -c) -gt 1 ]; do sleep 1 && echo "wait for...."; done'
```

Let's print what we are waiting for

**Review by leseb — CHANGES_REQUESTED** [review]

File: tests/scripts/deploy_admission_controller.sh [hunk 3]
```diff
@@ -11,7 +11,24 @@ function cleanup() {
...
+function error_log() {
+  set +e -x
+  kubectl get validatingwebhookconfigurations cert-manager-webhook -o yaml | grep caBundle
+  kubectl get mutatingwebhookconfigurations cert-manager-webhook -o yaml | grep caBundle
+  kubectl -n rook-ceph get certificate
+  kubectl -n rook-ceph get secret | grep rook-ceph-admission-controller
+  kubectl -n rook-ceph get validatingwebhookconfigurations.admissionregistration.k8s.io 
+  kubectl describe validatingwebhookconfigurations.admissionregistration.k8s.io cert-manager-webhook 
+  kubectl describe validatingwebhookconfigurations.admissionregistration.k8s.io rook-ceph-webhook 
+  kubectl -n cert-manager logs deploy/cert-manager-webhook --tail=10
```
Comment (vbnrh) [inline tests/scripts/deploy_admission_controller.sh:24]: No need to output the webhook logs. May make the test logs verbose and we always get the specific errors messages which caused the failure . Can we instead check if all the major pieces for running the admission webhooks are in place and in healthy state.

**Review by vbnrh — CHANGES_REQUESTED** [review]

File: tests/scripts/deploy_admission_controller.sh [hunk 4]
```diff
@@ -24,7 +41,7 @@ fi
 
 # Set our known directories and parameters.
 BASE_DIR=$(cd "$(dirname "$0")"; pwd)
-CERT_VERSION="v1.2.0"
+CERT_VERSION="v1.3.1"
```
[the remark this answers is not in the document]
Comment (subhamkrai) [reply tests/scripts/deploy_admission_controller.sh:44]: it's not a part of the fix that's why I kept that in separate commit but I can make a separate PR. @leseb thoughts?

File: tests/scripts/deploy_admission_controller.sh (hunk 3 above)
Comment (subhamkrai) [reply tests/scripts/deploy_admission_controller.sh:24]: what other major pieces?

Comment (vbnrh) [reply tests/scripts/deploy_admission_controller.sh:24]: pods, services that rook creates, status of rook operator (provided it is up in tests when we execute this) ? think you may need to add the issuer here too.

Comment (vbnrh) [reply tests/scripts/deploy_admission_controller.sh:24]: Also we can remove caBundle output for the webhhoks as it will mean nothing when we look at it in the logs. If the caBundles are missing, then the validations which rook will perform will fail.
I think just checking the status may be enough otherwise you may want to add logs when you print the output

Comment (subhamkrai) [reply tests/scripts/deploy_admission_controller.sh:24]: > pods, services that rook creates, status of rook operator (provided it is up in tests when we execute this) ? think you may need to add the issuer here too.

yes for Issuer, for the pods and services that rook creates, it will be created after this script is done.

Comment (subhamkrai) [reply tests/scripts/deploy_admission_controller.sh:24]: > Also we can remove caBundle output for the webhhoks as it will mean nothing when we look at it in the logs. If the caBundles are missing, then the validations which rook will perform will fail.
> I think just checking the status may be enough otherwise you may want to add logs when you print the output

sounds good, will remove

File: tests/scripts/deploy_admission_controller.sh (hunk 1 above)
Comment (subhamkrai) [reply tests/scripts/deploy_admission_controller.sh]: found a way.

File: tests/scripts/deploy_admission_controller.sh (hunk 2 above)
Comment (subhamkrai) [reply tests/scripts/deploy_admission_controller.sh]: done

File: tests/scripts/deploy_admission_controller.sh [hunk 5]
```diff
@@ -33,12 +49,16 @@ export SERVICE_NAME="rook-ceph-admission-controller"
 
 echo "$BASE_DIR"
 
+echo "Deploying cert-manager"
 kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/$CERT_VERSION/cert-manager.yaml
-timeout 150 sh -c 'until [ $(kubectl -n cert-manager get pods --field-selector=status.phase=Running|grep -c ^cert-) -eq 3 ]; do sleep 1; done'
-timeout 20 sh -c 'until [ $(kubectl -n cert-manager get pods -o custom-columns=READY:status.containerStatuses[*].ready | grep -c true) -eq 3 ]; do sleep 1; done'
+timeout 150 sh -c 'until [ $(kubectl -n cert-manager get pods --field-selector=status.phase=Running|grep -c ^cert-) -eq 3 ]; do sleep 1 && echo "waiting for cert-manager pods to be in running state"; done'
+timeout 20 sh -c 'until [ $(kubectl -n cert-manager get pods -o custom-columns=READY:status.containerStatuses[*].ready | grep -c true) -eq 3 ]; do sleep 1 && echo "wait for the pods to be in ready state"; done'
```
Comment (leseb) [inline tests/scripts/deploy_admission_controller.sh:55]:
```suggestion
timeout 20 sh -c 'until [ $(kubectl -n cert-manager get pods -o custom-columns=READY:status.containerStatuses[*].ready | grep -c true) -eq 3 ]; do sleep 1 && echo "waiting for the pods to be in ready state"; done'
```

Let's remain consistent with other logs.

File: tests/scripts/deploy_admission_controller.sh (hunk 4 above)
[the remark this answers is not in the document]
Comment (leseb) [reply tests/scripts/deploy_admission_controller.sh:43]: Honestly, I don't mind, a new PR could be better but since we have "waits" in place not sure if it's worth it.

**Review by leseb — APPROVED** [review]
