### PR TITLE
Make sed usage compatible with GNU and BSD

### LINKED ISSUE #1664: Change code generation script to be portable and work on Linux
## **Bug Report**

**What happened:**
Running `make codegen` does not work on GNU/Linux. This is because of the `sed` usage in `build/codegen/codegen.sh`:
```
find ${scriptdir}/../../pkg/client -name "clientset_generated.go" -exec sed -i '' 's/fakePtr := testing.Fake{}/cs := \&Clientset{}/g' {} +
find ${scriptdir}/../../pkg/client -name "clientset_generated.go" -exec sed -i '' 's/fakePtr.AddReactor/cs.Fake.AddReactor/g' {} +
find ${scriptdir}/../../pkg/client -name "clientset_generated.go" -exec sed -i '' 's/fakePtr.AddWatchReactor/cs.Fake.AddWatchReactor/g' {} +
find ${scriptdir}/../../pkg/client -name "clientset_generated.go" -exec sed -i '' 's/return &Clientset{fakePtr, \&fakediscovery.FakeDiscovery{Fake: &fakePtr}}/cs.discovery = \&fakediscovery.FakeDiscovery{Fake:    \&cs.Fake}\
  return cs/g' {} +
```

Currently, this will only work on OSX/BSD ([here is more info on that](https://stackoverflow.com/questions/2320564/i-need-my-sed-i-command-for-in-place-editing-to-work-with-both-gnu-sed-and-bsd)). We need a portable way to do this string replacement in the files.. perhaps consider using `tr` or something else.

**What you expected to happen:**

Successfully generated code on Linux.

**How to reproduce it (minimal and precise):**
Just run `make codegen` on a linux machine.

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Antergos Linux"
VERSION="16.2-ISO-Rolling"
ID="antergos"
ID_LIKE="arch"
PRETTY_NAME="Antergos Linux"
CPE_NAME="cpe:/o:antergosproject:antergos:16.2"
ANSI_COLOR="1;34;40"
HOME_URL="https://antergos.com/"
SUPPORT_URL="https://forum.antergos.com/"
BUG_REPORT_URL="https://github.com/antergos"
* Kernel (e.g. `uname -a`):
Linux legion 4.16.3-1-ARCH #1 SMP PREEMPT Thu Apr 19 09:17:56 UTC 2018 x86_64 GNU/Linux

* Cloud provider or hardware configuration:
n/a

* Rook version (use `rook version` inside of a Rook Pod):
Commit 44f543ff921119bca43f7761e9152b63d34d9016

### PR DESCRIPTION
**Pull request by galexrt**
```
Update codegen header.txt to current year

Fixes #1664

Signed-off-by: Alexander Trost <galexrt@googlemail.com>
```
Description of your changes:
This fixes issues with GNU and allows for GNU and BSD sed versions to work.

Which issue is resolved by this Pull Request:
Resolves #1664

Checklist:
- [x] Documentation has been updated, if necessary.
- [x] Pending release notes updated with breaking and/or notable changes, if necessary.
- [x] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.

[skip ci]

### CODE REVIEW

File: build/codegen/codegen.sh [hunk 1]
```diff
@@ -24,9 +24,12 @@ cd ${scriptdir}/../../vendor/k8s.io/code-generator && ./generate-groups.sh \
 # this seems busted in the release-1.8 branch
 #  --go-header-file ${SCRIPT_ROOT}/build/codegen/header.txt
 
+# Based on https://stackoverflow.com/a/38595160 to fix GNU and BSD issues
```
Comment (tonya11en) [inline build/codegen/codegen.sh]: Rather than the link, could you just provide a short explanation? Just a few sentences.

**Comment by galexrt** [comment]
@tonya11en PTAL

**Comment by tonya11en** [comment]
@jbw976 I pulled it down and verified it works on Linux. Jury's still out on  darwin/BSD.

**Comment by travisn** [comment]
@galexrt running this on my mac, the script says it succeeds, but the output file has quotes on the end of the filename so something isn't quite right.
```
~/src/go/src/github.com/rook/rook$ ls pkg/client/clientset/versioned/fake/clientset_generated.go*
pkg/client/clientset/versioned/fake/clientset_generated.go	pkg/client/clientset/versioned/fake/clientset_generated.go""
```

**Comment by galexrt** [comment]
@travisn @tonya11en PTAL This should work correctly now on both Linux and Mac.

**Comment by jbw976** [comment]
I just tested this now and `make codegen` succeeded, but it generated a new file with ticks at the end of its name:
```
jared@Jareds-MacBook-Pro ~/dev/go/src/github.com/rook/rook ((HEAD detached at galexrt/1664))
> git status
HEAD detached at galexrt/1664
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	pkg/client/clientset/versioned/fake/clientset_generated.go''

nothing added to commit but untracked files present (use "git add" to track)
```

File: build/codegen/codegen.sh [hunk 2]
```diff
@@ -14,19 +14,31 @@
...
-cd ${scriptdir}/../../vendor/k8s.io/code-generator && ./generate-groups.sh \
+cd "${scriptdir}/../../vendor/k8s.io/code-generator" && ./generate-groups.sh \
   all \
   github.com/rook/rook/pkg/client \
   github.com/rook/rook/pkg/apis \
   "rook.io:v1alpha1,v1alpha2 ceph.rook.io:v1alpha1"
 # this seems busted in the release-1.8 branch
 #  --go-header-file ${SCRIPT_ROOT}/build/codegen/header.txt
 
+SED="sed -i.bak"
```
Comment (tonya11en) [inline build/codegen/codegen.sh]: Doesn't this just leave behind a bunch of .bak files? How do they all get cleaned up?

Comment (galexrt) [reply build/codegen/codegen.sh]: Look at line 44. :)
https://github.com/rook/rook/pull/1712/files#diff-d6b28ecdaf1e8f2759c1062ca98f7549R44

Comment (tonya11en) [reply build/codegen/codegen.sh]: Ah, I see. Well this works fine on Ubuntu.

**Comment by galexrt** [comment]
I don't think we need to wait for CI here.
CI is not using the codegen script AFAIK.

**Comment by jbw976** [comment]
that's correct @galexrt, `make codegen` is not used in the build process, it's only a manual step for developers as needed.  i'll add `[skip ci]` and try to get it green.

**Comment by galexrt** [comment]
@jbw976 As @travisn wrote we should wait with the merge until the CI is working again, otherwise the `master` will become more and more red ;)

**Comment by galexrt** [comment]
@tonya11en @jbw976 I readded a pending release note.
