### PR TITLE
crush: set host properly in the crush map

### LINKED ISSUE #1135: Rook OSD daemon changes all the nodes hostnames
In my cluster, it seems the OSD daemon is changing the node hostname, causing kubelet restarts to fail when trying to register the node.

hostnames are changed according to this code https://github.com/rook/rook/blob/307adad72982257bbb11bbd48342fc4d6760d3f7/pkg/ceph/osd/daemon.go#L98, don't know if it's actually there but it rings all the bells.

my nodes FQDN go from host.domain.com to host-domain-com after starting the rook pods.

### PR DESCRIPTION
**Pull request by travisn**
The host name in the crush map is set by the `crush location` setting in the config file, rather than a hack to set the `hostname` of the pod. Fixes #1135

### CODE REVIEW

File: pkg/ceph/mon/config.go [hunk 1]
```diff
@@ -299,23 +296,21 @@ func CreateDefaultCephConfig(context *clusterd.Context, cluster *ClusterInfo, ru
 			OsdPoolDefaultMinSize:  1,
 			OsdPoolDefaultPgNum:    100,
 			OsdPoolDefaultPgpNum:   100,
-			OsdObjectStore:         store,
```
Comment (travisn) [inline pkg/ceph/mon/config.go]: no reason to have filestore/bluestore be a default for all types of daemons

File: pkg/ceph/mon/config.go [hunk 2]
```diff
@@ -58,7 +58,7 @@ type cephConfig struct {
 }
 
 type GlobalConfig struct {
-	EnableExperimental       string `ini:"enable experimental unrecoverable data corrupting features"`
+	EnableExperimental       string `ini:"enable experimental unrecoverable data corrupting features,omitempty"`
```
Comment (galexrt) [inline pkg/ceph/mon/config.go]: Doesn't this "remove" the `EnableExperimental` option in the config when empty?

Comment (travisn) [reply pkg/ceph/mon/config.go]: that's correct, we shouldn't need the property in the config since bluestore isn't experimental anymore

File: pkg/ceph/osd/device.go [hunk 3]
```diff
@@ -611,15 +617,10 @@ func addOSDToCrushMap(context *clusterd.Context, config *osdConfig, clusterName,
...
-	if err != nil {
-		return err
-	}
-
 	logger.Infof("adding %s (%s), bytes: %d, weight: %.4f, to crush map at '%s'",
-		osdEntity, osdDataPath, totalBytes, weight, strings.Join(locArgs, " "))
+		osdEntity, osdDataPath, totalBytes, weight, location)
 	args := []string{"osd", "crush", "create-or-move", strconv.Itoa(osdID), fmt.Sprintf("%.4f", weight)}
-	args = append(args, locArgs...)
+	args = append(args, strings.Split(location, " ")...)
```
Comment (jbw976) [inline pkg/ceph/osd/device.go]: are spaces in any of the CRUSH location fields supported at the ceph level?  the way we are handling them it looks like Rook would not support any spaces.

Comment (travisn) [reply pkg/ceph/osd/device.go]: while i can't find anything in the documentation about spaces in the crush types, it seems prone to disaster. The `crush location` in the config file is space-delimited as well and I haven't seen any examples putting quotes around the names.
