### PR TITLE
toolbox: Fallback to rook-api dns name when service env vars are not set

### LINKED ISSUE #1267: rook-tools does not work out-of-the-box with hostNetworking=true
I set up a 3 node k8s 1.7.5 cluster, modified `cluster/examples/kubernetes/rook-cluster.yaml` to set "hostNetwork: true", then brought up rook and the wordpress example, along with rook-tools.  When I attempted to use rook-tools, the `$ROOK_API_SERVICE_HOST` and `$ROOK_API_SERVICE_PORT` environment variables were not set up, so rookctl didn't work.  When I manually set them, rookctl worked.

```
% kubectl -n rook get services
NAME       CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
rook-api   None         <none>        8124/TCP   1m
% kubectl -n rook get pods -o wide | grep rook-api
rook-api-388455989-b0g1k          1/1       Running   0          1m        172.17.8.103   172.17.8.103
% kubectl -n rook exec -it rook-tools /bin/bash
root@rook-tools:/# rookctl block list                                                                                                                  
$ROOK_API_SERVICE_HOST or $ROOK_API_SERVICE_PORT are not set. Check if the rook-api service is running.
failed to get block images: Get http:///image: http: no Host in request URL
root@rook-tools:/# export ROOK_API_SERVICE_PORT=8124
root@rook-tools:/# export ROOK_API_SERVICE_HOST=172.17.8.103
root@rook-tools:/# rookctl block list
NAME                                       POOL          SIZE        DEVICE    MOUNT
pvc-9d695ec1-d477-11e7-80c5-001c4200cea2   replicapool   20.00 GiB   rbd       
pvc-9eef32a1-d477-11e7-80c5-001c4200cea2   replicapool   20.00 GiB   rbd       
root@rook-tools:/# 
```

### PR DESCRIPTION
**Pull request by galexrt**
Fixes #1267

***

This adds the fallback for the toolbox to the DNS service name when the service env vars are not set which most likely means that the `hostNetwork: true` is used.

### CODE REVIEW

File: images/toolbox/toolbox.sh [hunk 1]
```diff
@@ -62,6 +62,9 @@ if [[ -z ${ROOK_API_SERVER_ENDPOINT} ]]; then
         # we have some rook env vars set, get client info from the rook API server and construct
         # a ceph config file from that
         ROOK_API_SERVER_ENDPOINT=${ROOK_API_SERVICE_HOST}:${ROOK_API_SERVICE_PORT}
+    else
+        # hostNetwork: true is most likely used, use DNS name for rook API server access
+        ROOK_API_SERVER_ENDPOINT=rook-api:8124
```
Comment (dab-q) [inline images/toolbox/toolbox.sh]: It also needs to set:
ROOK_API_SERVICE_HOST=rook-api
ROOK_API_SERVICE_PORT=8124
or rookctl will continue to complain about those variables not being set.
