### PR TITLE
Use existing TPR when exists

### LINKED ISSUE #473: rook-operator should use existing TPR?
If the rook-operator pod is recreated it gets stuck in a loop trying to create another TPR.

```
2017-03-13 13:32:12.392785 I | rook-operator: starting operator in namespace rook
2017-03-13 13:32:12.392999 I | operator: creating rook TPR
2017-03-13 13:32:12.449403 E | operator: failed to create tpr. failed to create TPR. thirdpartyresources.extensions "cluster.rook.io" already exists. retrying...
```

For now deleting the TPR resumes normal operation.
```
kubectl delete thirdpartyresource cluster.rook.io
```

### PR DESCRIPTION
**Pull request by travisn**
This was a regression from #467. Fixes #473

### CODE REVIEW

File: pkg/operator/tpr.go [hunk 1]
```diff
@@ -59,7 +59,7 @@ func (o *Operator) createTPR() error {
 		}
 	}
 
-	return err
```
Comment (kokhang) [inline pkg/operator/tpr.go]: we should revert this back. If we get an error that is not IsAlreadyExist, that will not be returned.
And for the happy path, err==nil so it will still work.

Comment (jbw976) [inline pkg/operator/tpr.go]: i'm reading this change a different way @kokhang.  it looks to me like the only error that will be returned is if it is not an "already exists" error...which is what we want right?

Comment (kokhang) [inline pkg/operator/tpr.go]: If the intention is to swallow all the other errors, then we should at least log them.

Comment (travisn) [inline pkg/operator/tpr.go]: correct @jbw976, errors other than already existing will be returned above

Comment (kokhang) [inline pkg/operator/tpr.go]: @travisn but if TPR fails to create for any reason, shouldnt we raise that? Without TPR, the cluster will not be created

Comment (travisn) [inline pkg/operator/tpr.go]: @kokhang to see where the error is returned you have to expand the code a few lines

Comment (kokhang) [inline pkg/operator/tpr.go]: @travisn line 58 right? I see it but i still think we should return an error because the TPR was not created and that will manifest later in the flow. But if we are going to swallow the errors that are not alreadyExist, we should at least log them in my opinion

Comment (kokhang) [inline pkg/operator/tpr.go]: ahh i understand the code better.. you are not actually swalling the exception. You are returning all the errors except when it is already created. When i looked at it, i thought you were doing the opposite.
