### PR TITLE
ceph: fix ignoring device specification with non-kname

### LINKED ISSUE #5504: devicePathFilter doesn't work with /dev/disk/by-partlabel
* Bug Report

**Deviation from expected behavior:**
Devices are ignored.
**Expected behavior:**
Devices are used in cluster.
**How to reproduce it (minimal and precise):**
Create a simple partition on a disk. Use gdisk to give the partition a label.
Use: "devicePathFilter: /dev/disk/by-partlabel/<the-label>"

**File(s) to submit**:

Fresh 1.2.7 deployment.

Log from the discovery (cut useless info):
```
2020-05-18 13:19:40.022717 I | exec: Running command: udevadm info --query=property /dev/sdb
2020-05-18 13:19:40.027761 I | exec: Running command: lsblk --noheadings --list -o NAME /dev/sdb
2020-05-18 13:19:40.033102 I | exec: Running command: udevadm info --query=property /dev/sdb1
2020-05-18 13:19:40.037794 I | inventory: skipping device "sdb" because it has child, considering the child instead.
2020-05-18 13:19:40.037829 I | exec: Running command: lsblk /dev/sdb1 --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
2020-05-18 13:19:40.041742 I | exec: Running command: udevadm info --query=property /dev/sdb1
```
udevadm info --query=property /dev/sdb1:
```
DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1:1.0/host6/target6:0:0/6:0:0:0/block/sdb/sdb1
DEVNAME=/dev/sdb1
DEVTYPE=partition
PARTN=1
PARTNAME=CEPH_DATA
MAJOR=8
MINOR=17
SUBSYSTEM=block
USEC_INITIALIZED=83937007236
ID_VENDOR=Crucial_
ID_VENDOR_ENC=Crucial_
ID_VENDOR_ID=152d
ID_MODEL=CT256MX100SSD1
ID_MODEL_ENC=CT256MX100SSD1\x20\x20
ID_MODEL_ID=1576
ID_REVISION=0204
ID_SERIAL=Crucial__CT256MX100SSD1_987654321029-0:0
ID_SERIAL_SHORT=987654321029
ID_TYPE=disk
ID_INSTANCE=0:0
ID_BUS=usb
ID_USB_INTERFACES=:080650:080662:
ID_USB_INTERFACE_NUM=00
ID_USB_DRIVER=uas
ID_PATH=pci-0000:00:1d.0-usb-0:1.1:1.0-scsi-0:0:0:0
ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_1_1_0-scsi-0_0_0_0
ID_PART_TABLE_UUID=0e5b541c-593f-364e-aad0-9e14a35330d2
ID_PART_TABLE_TYPE=gpt
ID_FS_UUID=909d7a94-518f-437c-96ad-0081cd2c0b92
ID_FS_UUID_ENC=909d7a94-518f-437c-96ad-0081cd2c0b92
ID_FS_VERSION=1.0
ID_FS_TYPE=ext4
ID_FS_USAGE=filesystem
ID_PART_ENTRY_SCHEME=gpt
ID_PART_ENTRY_NAME=CEPH_DATA
ID_PART_ENTRY_UUID=69b2a0e3-78c8-fc4d-968e-27cf536b05b1
ID_PART_ENTRY_TYPE=0fc63daf-8483-4772-8e79-3d69d8477de4
ID_PART_ENTRY_NUMBER=1
ID_PART_ENTRY_OFFSET=2048
ID_PART_ENTRY_SIZE=500116111
ID_PART_ENTRY_DISK=8:16
DEVLINKS=/dev/disk/by-uuid/909d7a94-518f-437c-96ad-0081cd2c0b92 /dev/disk/by-id/usb-Crucial__CT256MX100SSD1_987654321029-0:0-part1 /dev/disk/by-partlabel/CEPH_DATA /dev/disk/by-partuuid/69b2a0e3-78c8-fc4d-968e-27cf536b05b1 /dev/disk/by-path/pci-0000:00:1d.0-usb-0:1.1:1.0-scsi-0:0:0:0-part1
TAGS=:systemd:
```
So both PARTNAME and DEVLINKS show the correct label (CEPH_DATA), but i guess because the 'raw' devpath is still sdb, it's ignored.

This causes issues, because I want to generalize the config for all machines and use autodiscover. I just want to be able to use different devices in different machines with different paths with a generic configuration. All my machines have different disks attached, but all the Ceph partitions are labeled properly. In the future, I'm probably going to use CEPH_DATA[0-90-9] as a filter, so I can easily and dynamically add OSD's.

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`): Debian 10, fully updated
* Cloud provider or hardware configuration: Intel NUC's
* Rook version (use `rook version` inside of a Rook Pod): 1.2.7
* Storage backend version (e.g. for ceph do `ceph -v`): latest for 1.2.7
* Kubernetes version (use `kubectl version`):1.17.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): healthy

### PR DESCRIPTION
**Pull request by satoru-takeuchi**
**Description of your changes:**

Since partition's DevLinks are empty in osd-prepare-pod, the device specification with non-kname, for example devicePathFilter, doesn't work.

**Which issue is resolved by this Pull Request:**

Resolves #5504 

**Checklist:**

- [o] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [o] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [o] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [o] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [o] Documentation has been updated, if necessary.
- [o] Unit tests have been added, if necessary.
- [o] Integration tests have been added, if necessary.
- [o] Pending release notes updated with breaking and/or notable changes, if necessary.
- [o] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [o] Code generation (`make codegen`) has been run to update object specifications, if necessary.

[test ceph]

### CODE REVIEW

**Comment by satoru-takeuchi** [comment]
I confirmed the `devicePathFilter` case works correctly, but full-path case is not tested yet.

File: pkg/daemon/ceph/osd/daemon.go [hunk 1]
```diff
@@ -375,6 +375,13 @@ func getAvailableDevices(context *clusterd.Context, agent *OsdAgent) (*DeviceOsd
 						logger.Infof("device %q matches device filter %q", device.Name, desiredDevice.Name)
 					}
 				} else if desiredDevice.IsDevicePathFilter {
+					if device.Type == sys.PartType {
+						device, err = clusterd.PopulateDeviceUdevInfo(device.Name, context.Executor, device)
```
Comment (travisn) [inline pkg/daemon/ceph/osd/daemon.go:379]: Since we need to detect this for partitions, how about moving this up inside the code block on line 308 that already checks for partitions? Then it is just a single check instead of calling the same thing in two places.

**Comment by satoru-takeuchi** [comment]
Test failed in mgr test suite. Since it's not related to my change, rerun test.

**Comment by satoru-takeuchi** [comment]
Re-test again since failed in TestCephFlexSuite that is not relarted to my change too.

File: pkg/daemon/ceph/osd/daemon.go (hunk 1 above)
Comment (satoru-takeuchi) [reply pkg/daemon/ceph/osd/daemon.go]: Thanks, fixed.

File: pkg/daemon/ceph/osd/daemon.go [hunk 2]
```diff
@@ -310,6 +310,11 @@ func getAvailableDevices(context *clusterd.Context, agent *OsdAgent) (*DeviceOsd
 				logger.Infof("skipping device %q because it is a partition and ceph version is too old, you need at least ceph %q", device.Name, cephVolumeRawModeMinCephVersion.String())
 				continue
 			}
+			device, err := clusterd.PopulateDeviceUdevInfo(device.Name, context.Executor, device)
+			if err != nil {
+				logger.Errorf("failed to get udev info of partition %q", device.Name)
```
Comment (leseb) [inline pkg/daemon/ceph/osd/daemon.go:315]:
```suggestion
				logger.Errorf("failed to get udev info of partition %q. %v", device.Name, err)
```

Comment (satoru-takeuchi) [reply pkg/daemon/ceph/osd/daemon.go]: Fixed.
