### PR TITLE
Ceph: ObjectStore replica size will not change

### LINKED ISSUE #4341: [cephobjectstore]change replicated.size then apply -f，nothing happened
I use cephobjectstore,and at first,I only store 1 replicate.
Now I wish to replicated 3 times,but this doesn't work
But when I change CephBlockPool's replicated.size,then apply ,it works?

Is this a bug or cephobjectstore can't update replicated.size dynamic?

### PR DESCRIPTION
**Pull request by rajatsingh25aug**
The pool size for cephObjectStore `(object.yaml)` , are not getting updated in the cluster upon changing.

Signed-off-by: RAJAT SINGH <rajasing@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #4341 

**Checklist:**

- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from the previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](https://github.com/rook/rook/blob/master/CONTRIBUTING.md#comments)
- [ ] Add the flag for skipping the CI if this PR does not require a build. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for more details.

[test ceph]

### CODE REVIEW

**Comment by rajatsingh25aug** [comment]
cc @umangachapagain  @travisn 
@leseb so the `RGW` pods aren't coming up, the reason being that the `CephObjectStore` is still getting and due to which the user `my-user` is in the pending state.
I followed this [doc](https://rook.io/docs/rook/v0.8/object.html).

**Comment by leseb** [comment]
> cc @umangachapagain @travisn
> @leseb so the `RGW` pods aren't coming up, the reason being that the `CephObjectStore` is still getting and due to which the user `my-user` is in the pending state. Ideally, it should not happen and I think it's a bug.
> I followed this [doc](https://rook.io/docs/rook/v0.8/object.html).

I'm not sure to understand what's going on, can add more details here about the error? Thanks.

**Comment by rajatsingh25aug** [comment]
> > cc @umangachapagain @travisn
> > @leseb so the `RGW` pods aren't coming up, the reason being that the `CephObjectStore` is still getting and due to which the user `my-user` is in the pending state. Ideally, it should not happen and I think it's a bug.
> > I followed this [doc](https://rook.io/docs/rook/v0.8/object.html).
> 
> I'm not sure to understand what's going on, can add more details here about the error? Thanks.

1. Created a rook-ceph cluster
2. Followed the above doc to create the Object Store.
3. Now I waited for the RGW pods to come up, but it didn't come up.
4. Checked the logs of rook-ceph operator pod which says  and which I suspect is the reason why my RGW pods are not coming up is. The operator logs says 
`2019-12-18 11:27:45.137637 I | op-object: creating user my-user in namespace rook-ceph
2019-12-18 11:27:45.148628 I | op-object: CephObjectStore my-store is running
2019-12-18 11:27:45.148652 I | op-object: Creating user: my-user
2019-12-18 11:27:45.148676 I | exec: Running command: radosgw-admin user create --uid my-user --display-name my display name --rgw-realm=my-store --rgw-zonegroup=my-store --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring`

**Comment by leseb** [comment]
> > > cc @umangachapagain @travisn
> > > @leseb so the `RGW` pods aren't coming up, the reason being that the `CephObjectStore` is still getting and due to which the user `my-user` is in the pending state. Ideally, it should not happen and I think it's a bug.
> > > I followed this [doc](https://rook.io/docs/rook/v0.8/object.html).
> > 
> > 
> > I'm not sure to understand what's going on, can add more details here about the error? Thanks.
> 
> 1. Created a rook-ceph cluster
> 2. Followed the above doc to create the Object Store.
> 3. Now I waited for the RGW pods to come up, but it didn't come up.
> 4. Checked the logs of rook-ceph operator pod which says  and which I suspect is the reason why my RGW pods are not coming up is. The operator logs says
>    `2019-12-18 11:27:45.137637 I | op-object: creating user my-user in namespace rook-ceph 2019-12-18 11:27:45.148628 I | op-object: CephObjectStore my-store is running 2019-12-18 11:27:45.148652 I | op-object: Creating user: my-user 2019-12-18 11:27:45.148676 I | exec: Running command: radosgw-admin user create --uid my-user --display-name my display name --rgw-realm=my-store --rgw-zonegroup=my-store --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring`

That's because your PGs are not clean. If objects cannot be placed you won't be able to create the user.

**Comment by rajatsingh25aug** [comment]
Can you please brief a little more about clean PGs?.
What can I do to "clean" the PGs?.
I never created any data in it.

**Comment by umangachapagain** [comment]
> >    `2019-12-18 11:27:45.137637 I | op-object: creating user my-user in namespace rook-ceph 2019-12-18 11:27:45.148628 I | op-object: CephObjectStore my-store is running 2019-12-18 11:27:45.148652 I | op-object: Creating user: my-user 2019-12-18 11:27:45.148676 I | exec: Running command: radosgw-admin user create --uid my-user --display-name my display name --rgw-realm=my-store --rgw-zonegroup=my-store --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring`
> 
> That's because your PGs are not clean. If objects cannot be placed you won't be able to create the user.
>
I have seen this issue before while running Integration Tests on CI. Anything we can do to make things better?

File: pkg/operator/ceph/object/objectstore.go [hunk 1]
```diff
@@ -289,7 +290,11 @@ func createSimilarPools(context *Context, pools []string, poolSpec model.Pool) e
 			if err != nil {
 				return errors.Errorf("failed to create pool %s for object store %s", name, context.Name)
 			}
+		} else {
+			ceph.SetPoolProperty(context.Context, context.ClusterName, name, "size", strconv.Itoa(int(poolDetails.Size)))
 		}
+		//update the pools if it already exist
```
Comment (travisn) [inline pkg/operator/ceph/object/objectstore.go]: shouldn't this comment be inside the `else` statement?

Comment (rajatsingh25aug) [reply pkg/operator/ceph/object/objectstore.go]: yep it should be :) , I’ll make it at the start of else block

**Comment by rajatsingh25aug** [comment]
Yes I can try that but, can you please brief me about clean PGs?.
Also, Whenever I setup my test cluster,I always have 3 OSDs up and running.
What workarounds are you talking about?.

**Comment by travisn** [comment]
If your cluster already has 3 OSDs and they are `up` and `in` according to the `ceph status`, sounds like you already have a healthy cluster that I wanted to confirm. Usually the PGs are not clean if OSDs are down or if the replication is set to more than the number of OSDs

**Comment by rajatsingh25aug** [comment]
after setting up the cluster, my cluster health was 'HEALTH_OK'

**Comment by leseb** [comment]
> after setting up the cluster, my cluster health was 'HEALTH_OK'

This is not enough, you need to check the status after pools have been created.

File: pkg/operator/ceph/object/objectstore.go (hunk 1 above)
Comment (rajatsingh25aug) [reply pkg/operator/ceph/object/objectstore.go]: Done!, Closing this conversation.

File: pkg/operator/ceph/object/objectstore.go [hunk 2]
```diff
@@ -289,6 +290,9 @@ func createSimilarPools(context *Context, pools []string, poolSpec model.Pool) e
 			if err != nil {
 				return errors.Errorf("failed to create pool %s for object store %s", name, context.Name)
 			}
+		} else {
+			//update the pools if it already exist
```
Comment (leseb) [inline pkg/operator/ceph/object/objectstore.go]:
```suggestion
			// update the pool if it already exists
```

Comment (rajatsingh25aug) [reply pkg/operator/ceph/object/objectstore.go]: Thanks, Please check the commit message and let me know if it's correct and explains the commit clearly.

File: pkg/operator/ceph/object/objectstore.go [hunk 3]
```diff
@@ -289,6 +290,9 @@ func createSimilarPools(context *Context, pools []string, poolSpec model.Pool) e
 			if err != nil {
 				return errors.Errorf("failed to create pool %s for object store %s", name, context.Name)
 			}
+		} else {
+			//update the pool if it already exists
+			ceph.SetPoolProperty(context.Context, context.ClusterName, name, "size", strconv.Itoa(int(poolDetails.Size)))
```
Comment (travisn) [inline pkg/operator/ceph/object/objectstore.go]: Are you always setting this size for existing pools? If it's an erasure-coded pool we wouldn't want to set the size.

Comment (travisn) [reply pkg/operator/ceph/object/objectstore.go]: And why are we setting the pool size to the same thing as `poolDetails.Size`? Seems like no setting is changed. If the size of the pool in the CR changed, we need to get the new size from the CR.

Comment (rajatsingh25aug) [reply pkg/operator/ceph/object/objectstore.go]: > Are you always setting this size for existing pools? If it's an erasure-coded pool we wouldn't want to set the size.

Yes, we are always checking the size.
I forgot about if its an erasure-coded pool or not.
I will add a check accordingly.

Comment (rajatsingh25aug) [reply pkg/operator/ceph/object/objectstore.go]: > And why are we setting the pool size to the same thing as `poolDetails.Size`? Seems like no setting is changed. If the size of the pool in the CR changed, we need to get the new size from the CR.

`setPoolProperty` method is used to change the pool's property right?.  If I change the pool property here i.e the pool's size, that will be updated in CR  too I believe.

Comment (travisn) [reply pkg/operator/ceph/object/objectstore.go]: > setPoolProperty method is used to change the pool's property right?. If I change the pool property here i.e the pool's size, that will be updated in CR too I believe.

The CR is only updated by the admin when they want to change the desired state. The operator then responds to the action of updating the settings in the CR by running this orchestration. We want to make sure the settings are applied from the CR. In this case, I would expect nothing to happen if you're applying the setting to Ceph that you just retrieved from Ceph.

Comment (travisn) [reply pkg/operator/ceph/object/objectstore.go]: To be more specific, I'd recommend the following in this else block:
```
} else {
  logger.Infof("pool %s already exists", name)
  if !ecPool {
      replicationChanged := //detect if the replication is different from the pool details
      if replicationChanged {
        // call SetPoolReplicatedSizeProperty() similar to how it is called in the CreateReplicatedPoolForApp() method
      } 
  } 
}
```

File: pkg/operator/ceph/object/objectstore.go [hunk 4]
```diff
@@ -289,6 +290,21 @@ func createSimilarPools(context *Context, pools []string, poolSpec model.Pool) e
...
 			}
+		} else {
+			logger.Infof("pool %s already exists", name)
+			if !isECPool {
+				//detect if the replication is different from the pool details
+				replicationChanged := false
+				if poolDetails.Size != poolSpec.ReplicatedConfig.Size {
+					replicationChanged = true
+				}
+				if replicationChanged {
```
Comment (travisn) [inline pkg/operator/ceph/object/objectstore.go]: How about if you check directly for `if poolDetails.Size != poolSpec.ReplicatedConfig.Size`? No need for the `replicationChanged` variable.

Comment (rajatsingh25aug) [reply pkg/operator/ceph/object/objectstore.go]: I think that `replicationChanged` improves the redability?.

Comment (travisn) [reply pkg/operator/ceph/object/objectstore.go]: If the conditions were more complex I would agree, but the single condition is simple enough

Comment (rajatsingh25aug) [reply pkg/operator/ceph/object/objectstore.go]: Done , please review now.
Thanks

File: pkg/operator/ceph/object/objectstore.go [hunk 5]
```diff
@@ -289,6 +290,16 @@ func createSimilarPools(context *Context, pools []string, poolSpec model.Pool) e
 			if err != nil {
 				return errors.Errorf("failed to create pool %s for object store %s", name, context.Name)
 			}
+		} else {
+			logger.Infof("pool %s already exists", name)
```
Comment (leseb) [inline pkg/operator/ceph/object/objectstore.go]: What about not logging since it's a no-op?

File: pkg/operator/ceph/object/objectstore.go [hunk 6]
```diff
@@ -289,6 +290,16 @@ func createSimilarPools(context *Context, pools []string, poolSpec model.Pool) e
...
+			if !isECPool {
+				//detect if the replication is different from the pool details
```
Comment (leseb) [inline pkg/operator/ceph/object/objectstore.go]:
```suggestion
				// detect if the replication is different from the pool details
```

File: pkg/operator/ceph/object/objectstore.go [hunk 7]
```diff
@@ -289,6 +290,16 @@ func createSimilarPools(context *Context, pools []string, poolSpec model.Pool) e
...
+				if poolDetails.Size != poolSpec.ReplicatedConfig.Size {
+					if err := ceph.SetPoolReplicatedSizeProperty(context.Context, context.ClusterName, poolDetails.Name, strconv.FormatUint(uint64(poolDetails.Size), 10), poolDetails.RequireSafeReplicaSize); err != nil {
```
Comment (travisn) [inline pkg/operator/ceph/object/objectstore.go]: @leseb Here is an example of where logging would be suppressed from the ceph command. If the logging of ceph commands is info level, the action will be found in the log. If not, we need to ensure we add a `logger.Info()` call everywhere we make an important config change like this.

Comment (leseb) [reply pkg/operator/ceph/object/objectstore.go]: Well I think this will bring overall clarity on logs then if I know nothing about Ceph and CLI and I'm looking from a UI, I'd gladly have a meaningful INFO instead of the cli call...

Comment (travisn) [reply pkg/operator/ceph/object/objectstore.go]: @rajatsingh25aug Please add a log entry before line 298 to indicate that the pool size is changing from the old value to the new value

Comment (rajatsingh25aug) [reply pkg/operator/ceph/object/objectstore.go]: Done!

Comment (travisn) [reply pkg/operator/ceph/object/objectstore.go]: `poolSpec.ReplicatedConfig.Size` is the new size so I think you need to switch the two args to the message

Comment (rajatsingh25aug) [reply pkg/operator/ceph/object/objectstore.go]: Thanks, I also made changes to Line 300 as there also I was using the old variable old pool's size value.
