### PR TITLE
integration tests updates

### LINKED ISSUE #979: An error starting an e2e test cluster needs more debug info
When the test cluster fails to start, whether failed mon or osd pods, the tests will time out waiting for the rook-api pod to start. A couple thoughts to improve this:
- The test could print the status of all the rook pods to the log
- The logs were not collected for the daemon pods.

There is also bug in `GetPodHostID()` where the podNames[0] can be the empty string. 
https://github.com/rook/rook/blob/master/tests/framework/utils/k8s_helper.go#L514

Then it leads to a crash in the test as seen in this build.
https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-975/14/pipeline

In the log, notice there is no argument for `kubectl get` before the `-o`. That means the `rook-api` pod was not found from the previous command.
```
Running command: kubectl get pods -l app=rook-api -o wide --no-headers=true -o name -n rook
Running command: kubectl get  -o jsonpath='{.status.hostIP}' -n rook
```

### PR DESCRIPTION
**Pull request by dangula**
- remove standalone references
   - fail test and gather logs if test setUp fails - not paniking anymore.
 fix #979 and #994

### CODE REVIEW

File: tests/framework/clients/rest_client.go [hunk 1]
```diff
@@ -34,33 +33,27 @@ type RestAPIClient struct {
...
 		}
-		endpoint = fmt.Sprintf("http://%s:%s", apiIP, nodePort)
-	case platform == enums.StandAlone:
-		endpoint = "http://localhost:8124"
-	default:
-		panic(fmt.Errorf("platform type %s not yet supported", platform))
 	}
+	apiIP, err := k8sHelper.GetPodHostID("rook-api", namespace)
+	if err != nil {
+		panic(fmt.Errorf("Host Ip for Rook-api service not found. %+v", err))
```
Comment (travisn) [inline tests/framework/clients/rest_client.go]: can we get rid of all panics?

File: tests/framework/clients/test_client.go [hunk 2]
```diff
@@ -44,30 +40,18 @@ const (
...
-		poolClient = CreatePoolClient(rookRestClient)
-	case platform == enums.StandAlone:
-		blockClient = nil  //TODO- Not yet implemented
-		fsClient = nil     //TODO- Not yet implemented
-		objectClient = nil //TODO- Not yet implemented
-		poolClient = nil   //TODO- Not yet implemented
-	default:
-		return &TestClient{}, fmt.Errorf("Unsupported Rook Platform Type")
-	}
+	rookRestClient := CreateRestAPIClient(k8sHelper, namespace)
```
Comment (travisn) [inline tests/framework/clients/test_client.go]: why do we have all these different clients? Looks like they have similar properties with k8s and rest client objects.

File: tests/framework/installer/install_helper.go [hunk 3]
```diff
@@ -158,7 +159,7 @@ func (h *InstallHelper) CreateK8sRookCluster(clusterNamespace string) (err error
 }
 
 //InstallRookOnK8s installs rook on k8s
-func (h *InstallHelper) InstallRookOnK8s(clusterNamespace string) (err error) {
+func (h *InstallHelper) InstallRookOnK8s(clusterNamespace string) (result bool, err error) {
```
Comment (travisn) [inline tests/framework/installer/install_helper.go]: i wouldn't generally use named return values. In the header, just declare `(bool, error)`. Then you can be explicit everywhere about the values to return

File: tests/framework/installer/install_helper.go [hunk 4]
```diff
@@ -222,61 +217,62 @@ func (h *InstallHelper) UninstallRookFromK8s(clusterNamespace string, helmInstal
 	logger.Infof("Uninstalling Rook")
 	k8sHelp, err := utils.CreateK8sHelper(h.T)
 	if err != nil {
-		panic(err)
+		logger.Errorf("cannot uninstall rook err ->  %v", err)
```
Comment (travisn) [inline tests/framework/installer/install_helper.go]: in this method, should we use assert.Nil(t, err) instead of just logging the error. We will likely not notice the error since it doesn't block the test. Or maybe we don't want to fail the test?

File: tests/framework/installer/install_helper.go [hunk 5]
```diff
@@ -222,61 +217,62 @@ func (h *InstallHelper) UninstallRookFromK8s(clusterNamespace string, helmInstal
...
+			logger.Errorf("cannot delete CRDs err -> %+v", err)
 		}
 	} else {
 		_, err = k8sHelp.DeleteResource([]string{"thirdpartyresources", "cluster.rook.io", "pool.rook.io", "objectstore.rook.io", "filesystem.rook.io"})
 		if err != nil {
-			panic(err)
+			logger.Errorf("cannot delete TPRs err -> %+v", err)
 		}
 	}
+	_, err = k8sHelp.DeleteResource([]string{"secret", clusterNamespace + "-rook-user"})
```
Comment (travisn) [inline tests/framework/installer/install_helper.go]: do we need to delete the namespace-specific resources since the namespace will clean that up when it's deleted?

File: tests/integration/block_createBlock_api_test.go [hunk 6]
```diff
@@ -43,27 +43,37 @@ func TestBlockCreateAPI(t *testing.T) {
...
+		s.TearDownSuite()
+		s.T().FailNow()
+	}
 
-	s.testClient, err = clients.CreateTestClient(enums.Kubernetes, kh, "rook")
-	require.Nil(s.T(), err)
+	s.testClient, err = clients.CreateTestClient(s.kh, "rook")
+	if err != nil {
+		logger.Errorf("Cannot create rook test client, er -> %v", err)
+		s.TearDownSuite()
```
Comment (travisn) [inline tests/integration/block_createBlock_api_test.go]: the tear down isn't implicit?

File: tests/framework/enums/rook_platform_types.go [hunk 7]
```diff
@@ -1,63 +0,0 @@
...
-//RookPlatformType is enum if rook platforms
-type RookPlatformType int
-
-const (
-	//Kubernetes plafrom is default
-	Kubernetes RookPlatformType = iota + 1
-	//BareMetal plafrom
-	BareMetal
-	//StandAlone plafrom is default
-	StandAlone
```
Comment (travisn) [inline tests/framework/enums/rook_platform_types.go]: To fully remove standalone (in another PR), it would also be good to remove the unnecessary test interfaces. Navigating the code will be a lot easier that way.

File: tests/framework/installer/install_helper.go (hunk 4 above)
Comment (jbw976) [reply tests/framework/installer/install_helper.go]: i think this PR has this problem in general in other places.  In a lot of places, we've replaced a panic with just a log statement, when we probably want to return the failure to the caller or assert/require to fail the test.

If we simply log an error, we'll run into problems later on that may not be immediately obvious that they are the result of a previous failure.  That will make debugging more difficult.

File: tests/integration/block_createBlock_api_test.go (hunk 6 above)
Comment (dangula) [reply tests/integration/block_createBlock_api_test.go]: it's not when there is a failure in SetUp, the teardown is never called if set up fails.

File: tests/framework/installer/install_helper.go (hunk 4 above)
Comment (dangula) [reply tests/framework/installer/install_helper.go]: the install section is returning erros now(instead of panic) and the tests assert those errors. However i have added asserts to the uninstall func instead of returning errors.

File: tests/framework/installer/install_helper.go (hunk 5 above)
Comment (dangula) [reply tests/framework/installer/install_helper.go]: There clean up steps reflect documentaion, I can remove them if we think they are redundant.

Comment (travisn) [reply tests/framework/installer/install_helper.go]: if the user chooses not to delete the entire namespace, then the individual cleanup instructions would be necessary. But since the test is deleting the namespace, it could skip deleting the secret and other artifacts in the namespace. You can save this for another PR though

**Comment by travisn** [comment]
when you squash, please add a more descriptive merge commit and PR title.
