### PR TITLE
core: Add annotations and labels to detect version jobs

### LINKED ISSUE #14575: Add support for annotations on version detection pods
The Rook operator and most pods it creates are able to have custom annotations added to them. The version detection pods are an exception, and this request is to add support for custom annotations on those pods.

Some environments require pods to be annotated in order to run correctly. For example, AppArmor is used in some places to manage permissions and to prevent non-permitted pods from running. In such environments, the version detection jobs attempt to create pods without annotations and those pods are prevented from running, which causes the Ceph cluster deployment to fail.

Adding the ability to assign custom annotations to the version detection pods would allow Rook to be used to deploy and manage Ceph in environments that require all pods to have custom annotations.

### PR DESCRIPTION
**Pull request by travisn**
The jobs to detect the ceph and csi versions now can have custom annotations and labels added to them. They are very short-lived jobs, but they may need custom annotations in some environments to run.

**Issue resolved by this Pull Request:**
Resolves #14575 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

File: pkg/operator/ceph/csi/controller.go [hunk 1]
```diff
@@ -58,6 +58,8 @@ type ReconcileCSI struct {
 	opManagerContext   context.Context
 	opConfig           opcontroller.OperatorConfig
 	clustersWithHolder []ClusterDetail
+	// the first cluster CR which will determine some settings for the csi driver
+	firstCephCluster *cephv1.ClusterSpec
```
Comment (travisn) [inline pkg/operator/ceph/csi/controller.go:62]: This is only needed temporarily until the csi operator is fully supported, but seemed simple enough to add for now until that transition is done.

File: pkg/apis/ceph.rook.io/v1/labels_test.go [hunk 2]
```diff
@@ -58,8 +58,9 @@ func TestCephLabelsMerge(t *testing.T) {
 
 	// Merge with "all"
 	testLabels = LabelsSpec{
-		"all": {"allkey1": "allval1", "allkey2": "allval2"},
-		"mgr": {"mgrkey": "mgrval"},
+		"all":           {"allkey1": "allval1", "allkey2": "allval2"},
+		"mgr":           {"mgrkey": "mgrval"},
+		"detectversion": {"detect": "myversion"},
```
Comment (BlaineEXE) [inline pkg/apis/ceph.rook.io/v1/labels_test.go:63]: In a greater sense, the issue is that the command reporter "cmdreporter" doesn't have labels/placement. The cmd reporter is used mostly for version detection, but it is also used for network inspection, and I think one more thing. Could we expand this to be for all uses of the command reporter?

Comment (travisn) [reply pkg/apis/ceph.rook.io/v1/labels_test.go:63]: Yeah, I meant to look at that. The one other instance I see is for the networkreporter. I see it has a reference to the cephcluster, so it would be a simple change. Then what should we name it instead of `detectversion`? `cmdreporter` doesn't mean much to the user. What about `jobrunner`? Or maybe just go with `cmdreporter` to match the code where it's used.

Comment (travisn) [reply pkg/apis/ceph.rook.io/v1/labels_test.go]: `cmdreporter` is set now

**Review by BlaineEXE — APPROVED** [review]
