### PR TITLE
TPRs managed in the cluster namespace instead of the operator namespace

### LINKED ISSUE #492: rook-operator crashes every 50-60 minutes
On my 5-node Kubernetes cluster the rook-operator appears to crash and restart every 53-55 minutes.  It appears to be quite regular.

The log looks like:
```
kerns@castle2:~$ kubectl logs -p rook-operator-3615234556-zgs8l | more
2017-03-15 23:26:30.154673 I | rook-operator: starting operator in namespace default
2017-03-15 23:26:30.154879 I | operator: creating rook TPR
2017-03-15 23:26:30.192379 I | operator: finding existing clusters...
2017-03-15 23:26:30.194107 I | operator: found 1 clusters
2017-03-15 23:26:30.194125 I | operator: resuming cluster my-rook in namespace rook
2017-03-15 23:26:30.194139 I | operator: start watching rook tpr: 2452569
2017-03-15 23:26:30.196818 I | op-mon: start running mons
2017-03-15 23:26:30.198494 I | op-mon: found existing monitor secrets for cluster rookcluster with fsid 44aea880-1a7e-412f-b147-3d0b526dca94
2017-03-15 23:26:30.202472 I | op-mon: there are 5 nodes available for 3 monitors
2017-03-15 23:26:30.206355 I | op-mon: 3 running, 0 pending pods
2017-03-15 23:26:30.206374 I | op-mon: pods are already running
2017-03-15 23:26:30.206380 I | op-api: starting the Rook api
2017-03-15 23:26:30.212969 I | op-api: API service running at :8124
2017-03-15 23:26:30.217781 I | op-api: api deployment already exists
2017-03-15 23:26:30.217797 I | op-osd: start running osds
2017-03-15 23:26:30.221158 I | op-osd: osd daemon set already exists
2017-03-15 23:26:30.221376 I | cephmon: connecting to ceph cluster rookcluster with user admin
2017-03-15 23:26:30.260100 I | cephclient: creating pool rook succeeded, info: pool 'rook' already exists, buf:
2017-03-15 23:26:30.266917 I | operator: updated existing rook-rbd-user secret
2017-03-15 23:26:30.267831 I | operator: Done creating rook instance in namespace rook
failed to run operator. requested version is outdated in apiserver
kerns@castle2:~$
```

I've gone over 70 cycles of this so far.

Dan

### PR DESCRIPTION
**Pull request by travisn**
- The pool tpr name and namespace are now used from the metadata instead of the spec. 
- The cluster tpr name now is used from the metadata, which name will be the namespace that is created for the cluster.

Fixes #492, #522, and #526

### CODE REVIEW

**Comment by travisn** [comment]
still needs some testing, but wanted to open the PR to start the review process...

**Comment by luxas** [comment]
Do you watch on all namespaces for Rook TPRs now?

**Comment by kokhang** [comment]
@luxas No. The rook-operator does not watch all namespace. What this patch does is to ensure that a pool has to be created in the same namespace where the rook-cluster was created. This is a preparation for the future when rook supports multiple clusters.

**Comment by travisn** [comment]
@luxas, the PR has been updated now to watch all namespaces. There is no longer a dependency to create TPRs in the same namespace as the operator. The operator can run in any namespace since it watches all namespaces for clusters.

File: pkg/operator/cluster.go [hunk 1]
```diff
@@ -33,42 +33,58 @@ import (
...
+		clusters:            make(map[string]*cluster.Cluster),
+		tracker:             newTPRTracker(),
+		inclusterInitiators: inclusterInitiators,
 	}
 }
 
-func (t *clusterTPR) Name() string {
+// Gets the name of the TPR
+func (t *clusterManager) Name() string {
 	return "rookcluster"
```
Comment (jbw976) [inline pkg/operator/cluster.go]: is this the name of the object that manages all clusters?  where is this value used?  Is the hard coded value of "rookcluster" appropriate?

File: pkg/operator/cluster.go [hunk 2]
```diff
@@ -33,42 +33,58 @@ import (
...
-	err := t.findAllClusters()
-	if err != nil {
-		return fmt.Errorf("failed to find clusters. %+v", err)
+		<-time.After(time.Second * time.Duration(t.context.retryDelay))
 	}
-	return nil
 }
 
-func (t *clusterTPR) findAllClusters() error {
+func (t *clusterManager) Load() error {
```
Comment (jbw976) [inline pkg/operator/cluster.go]: using `t` as the function receiver name is a bit odd now that the type has changed

File: pkg/operator/cluster.go [hunk 3]
```diff
@@ -77,23 +93,50 @@ func (t *clusterTPR) findAllClusters() error {
...
+func (t *clusterManager) startCluster(c *cluster.Cluster) {
+	c.Init(t.context.factory, t.context.clientset)
+	if err := t.startTrack(c); err != nil {
+		logger.Errorf("failed to start cluster %s in namespace %s. %+v", c.Name, c.Namespace, err)
+		return
+	}
+
 	if t.devicesInUse && c.Spec.Storage.AnyUseAllDevices() {
-		logger.Warningf("devices in more than one namespace not supported. ignoring devices in namespace %s", c.Spec.Namespace)
+		logger.Warningf("devices in more than one namespace not supported. ignoring devices in namespace %s", c.Namespace)
```
Comment (jbw976) [inline pkg/operator/cluster.go]: i think this was my warning message and it doesn't quite make sense.  if you are making other updates for this PR, do you want to also change this to something like:
> using all devices in more than one namespace...

File: pkg/operator/cluster.go [hunk 4]
```diff
@@ -102,32 +145,55 @@ func (t *clusterTPR) startCluster(c *cluster.Cluster) {
...
+			k8sutil.Retry(time.Duration(t.context.retryDelay)*time.Second, t.context.maxRetries, func() (bool, error) {
+				tprMgr, err := tpr.Create(t, c.Name, c.Namespace)
+				if err != nil {
+					logger.Warningf("cannot create in-cluster tpr %s. %+v. retrying...", t.Name(), err)
+					return false, nil
+				}
+
+				go tprMgr.Manage()
+
+				// Start the tpr-manager asynchronously
```
Comment (jbw976) [inline pkg/operator/cluster.go]: does this comment actually apply to line 166?

File: pkg/operator/cluster.go [hunk 5]
```diff
@@ -157,18 +223,9 @@ func (t *clusterTPR) Watch() error {
...
-					continue
-				}
-
-				newCluster := cluster.New(c.Spec, t.context.factory, t.context.clientset)
-				t.tracker.add(ns, c.Metadata.ResourceVersion)
-				t.clusters[ns] = newCluster
 
-				logger.Infof("starting new cluster %s in namespace %s", c.Metadata.Name, ns)
-				t.startCluster(newCluster)
+				logger.Infof("starting new cluster in namespace %s", c.Name)
```
Comment (jbw976) [inline pkg/operator/cluster.go]: is `c.Name` actually the namespace here (like the comment says)? or is it the name of the cluster?  maybe log both if so

File: pkg/operator/cluster/cluster.go [hunk 6]
```diff
@@ -103,15 +100,15 @@ func (c *Cluster) CreateInstance() error {
...
+	logger.Infof("Done creating rook instance in namespace %s", c.Namespace)
 	return nil
 }
 
 func (c *Cluster) Monitor(stopCh <-chan struct{}) {
 	for {
 		select {
 		case <-stopCh:
-			logger.Infof("Stopping monitoring of cluster %s", c.Spec.Namespace)
+			logger.Infof("Stopping monitoring of cluster %s", c.Namespace)
```
Comment (jbw976) [inline pkg/operator/cluster/cluster.go]: should this be `c.Name` instead? (also, should both namespace and cluster name be logged?)

File: Documentation/kubernetes.md [hunk 7]
```diff
@@ -119,6 +119,8 @@ To clean up all the artifacts created by the demo, run the following:
 kubectl delete -f wordpress.yaml
 kubectl delete -f mysql.yaml
 kubectl delete deployment rook-operator
```
Comment (kokhang) [inline Documentation/kubernetes.md]: Does the order of deletion matter? Ie, should the rook-operator be deleted last (since it was the first one to be created) and the rookcluster second last?

File: Documentation/kubernetes.md [hunk 8]
```diff
@@ -119,6 +119,8 @@ To clean up all the artifacts created by the demo, run the following:
...
+kubectl delete -n rook rookcluster rook
+kubectl delete -n rook rookpool replicapool
 kubectl delete thirdpartyresources rookcluster.rook.io rookpool.rook.io
```
Comment (kokhang) [inline Documentation/kubernetes.md]: Wouldnt delete the rook-operator delete the TPR? Since it was the rook-operator that created?

File: pkg/operator/mon/pod.go [hunk 9]
```diff
@@ -23,9 +23,8 @@ import (
 	"k8s.io/client-go/pkg/labels"
 )
 
-func ClusterNameEnvVar() v1.EnvVar {
-	ref := &v1.ObjectFieldSelector{FieldPath: "metadata.namespace"}
-	return v1.EnvVar{Name: "ROOKD_CLUSTER_NAME", ValueFrom: &v1.EnvVarSource{FieldRef: ref}}
+func ClusterNameEnvVar(name string) v1.EnvVar {
+	return v1.EnvVar{Name: "ROOKD_CLUSTER_NAME", Value: name}
```
Comment (jbw976) [inline pkg/operator/mon/pod.go]: this got more simple, didn't it?

File: Documentation/pool-tpr.md [hunk 10]
```diff
@@ -21,14 +20,12 @@ spec:
 ## Pool Settings
 
 ### Metadata
-- `name`: The name of the kubernetes resource. Must be unique across all Rook clusters. The naming convention is `clusterName-poolName`.
-- `namespace`: The namespace where the Rook operator is running.
+- `name`: The name of the pool to create.
+- `namespace`: The namespace of the Rook cluster where the pool is created.
```
Comment (kokhang) [inline Documentation/pool-tpr.md]: The namespace of the Rook cluster where the pool is `to be` created?

File: cmd/rookd/api.go [hunk 11]
```diff
@@ -30,21 +30,24 @@ import (
...
+	repoPrefix string
+	namespace  string
+)
 
 func init() {
 	apiCmd.Flags().IntVar(&apiPort, "port", 0, "port on which the api is listening")
 	apiCmd.Flags().StringVar(&repoPrefix, "repo-prefix", "quay.io/rook", "the repo from which to pull images")
-	apiCmd.Flags().StringVar(&cfg.containerVersion, "container-version", "latest", "version of the rook container to launch")
-	apiCmd.Flags().StringVar(&cfg.namespace, "namespace", "", "the namespace in which the api service is running")
+	apiCmd.Flags().StringVar(&cfg.versionTag, "version-tag", "latest", "version of the rook container to launch")
```
Comment (kokhang) [inline cmd/rookd/api.go]: Ahh cool.. Thanks for renaming this variable. VersionTag sounds better and more applicable :)

File: pkg/operator/tpr.go [hunk 12]
```diff
@@ -101,18 +110,36 @@ func waitForTPRInit(context *context, tpr TPR) error {
...
+func watchTPR(context *context, name, resourceVersion string) (*http.Response, error) {
+	uri := fmt.Sprintf("%s/%s?watch=true&resourceVersion=%s", context.masterHost, tprURI(name), resourceVersion)
+	logger.Debugf("watching tpr: %s", uri)
+	return context.kubeHttpCli.Get(uri)
 }
 
-func getRawList(context *context, tpr TPR) ([]byte, error) {
-	restcli := context.clientset.CoreV1().RESTClient()
-	return restcli.Get().RequestURI(tprURI(context, tpr.Name())).DoRaw()
+func tprURINamespaced(name, namespace string) string {
```
Comment (jbw976) [inline pkg/operator/tpr.go]: i'm thinking some comments and/or a quick example of what a final URL would look like for these couple of methods here would be useful.

File: demo/kubernetes/rook-pool.yaml [hunk 13]
```diff
@@ -1,14 +1,14 @@
...
   replication:
-    count: 1
-  # For an erasure-coded pool, comment out the replication count above and uncomment the following settings.
-  # Make sure you have enough OSDs to support the replica count or erasure code chunks.
+    size: 1
+  # For an erasure-coded pool, comment out the replication size above and uncomment the following settings.
+  # Make sure you have enough OSDs to support the replica size or sum of the erasure coding and data chunks.
   #erasureCode:
   #  codingChunks: 2
   #  dataChunks: 2
```
Comment (kokhang) [inline demo/kubernetes/rook-pool.yaml]: New line at the end of the file

File: pkg/operator/api/api.go [hunk 14]
```diff
@@ -33,18 +33,20 @@ const (
 )
 
 type Cluster struct {
-	clientset kubernetes.Interface
-	Namespace string
-	Version   string
-	Replicas  int32
+	clientset   kubernetes.Interface
+	ClusterName string
```
Comment (kokhang) [inline pkg/operator/api/api.go]: Nit: i would just name this variable `Name`. This already implies it is referring to the cluster name since the name of the struct is `Cluster`

File: pkg/operator/cluster.go [hunk 15]
```diff
@@ -77,23 +93,50 @@ func (t *clusterTPR) findAllClusters() error {
...
-		logger.Infof("resuming cluster %s in namespace %s", c.Metadata.Name, ns)
-		t.startCluster(existingCluster)
+func (t *clusterManager) startTrack(c *cluster.Cluster) error {
+	t.Lock()
+	defer t.Unlock()
+
+	existing, ok := t.clusters[c.Namespace]
+	if ok {
+		if c.Name != existing.Name {
+			return fmt.Errorf("cluster %s already running in namespace %s. multiple clusters per namespace not supported", existing.Name, existing.Namespace)
```
Comment (kokhang) [inline pkg/operator/cluster.go]: cluster %s `is` already running. `M`ultiple clusters per namespace not supported`.`"

File: pkg/operator/cluster/cluster.go [hunk 16]
```diff
@@ -133,7 +130,8 @@ func (c *Cluster) createClientAccess(clusterInfo *cephmon.ClusterInfo) error {
 	defer conn.Shutdown()
 
 	// create a user for rbd clients
-	username := "client.rook-rbd-user"
+	name := fmt.Sprintf("%s-rbd-user", c.Namespace)
```
Comment (kokhang) [inline pkg/operator/cluster/cluster.go]: Should we change the user to namespace-rook-user instead? I see rbd as a detail in rook that we want to hide from the user

File: pkg/operator/tpr.go [hunk 17]
```diff
@@ -101,18 +110,36 @@ func waitForTPRInit(context *context, tpr TPR) error {
...
+	return fmt.Sprintf("/apis/%s/%s/namespaces/%s/%ss", tprGroup, tprVersion, namespace, name)
```
Comment (kokhang) [inline pkg/operator/tpr.go]: is this a typo? The extra `s` at the end?

File: pkg/operator/tpr.go [hunk 18]
```diff
@@ -101,18 +110,36 @@ func waitForTPRInit(context *context, tpr TPR) error {
...
+}
+
+func tprURI(name string) string {
+	return fmt.Sprintf("/apis/%s/%s/%ss", tprGroup, tprVersion, name)
```
Comment (kokhang) [inline pkg/operator/tpr.go]: same here?

File: Documentation/kubernetes.md (hunk 8 above)
Comment (travisn) [inline Documentation/kubernetes.md]: since the operator created the tpr dynamically, the tpr has to be deleted as a separate step from the operator since kubernetes has no declaration that they are related

File: Documentation/kubernetes.md (hunk 7 above)
Comment (travisn) [inline Documentation/kubernetes.md]: the order of deleting the rook operator doesn't actually matter. it can go away first and it won't impact anything else being deleted

File: Documentation/pool-tpr.md (hunk 10 above)
Comment (travisn) [inline Documentation/pool-tpr.md]: not sure I see what you're trying to clarify. what is the confusion?

File: cmd/rookd/operator.go [hunk 19]
```diff
@@ -35,19 +35,12 @@ https://github.com/rook/rook`,
 }
 
 func init() {
-	operatorCmd.Flags().StringVar(&cfg.containerVersion, "container-version", "latest", "version of the rook container to launch")
-	operatorCmd.Flags().StringVar(&cfg.namespace, "namespace", "", "the namespace in which the operator is running")
```
Comment (travisn) [inline cmd/rookd/operator.go]: is the rook-operator.yaml, they would need to specify the `namespace` attribute in the metadata section.

File: pkg/operator/cluster.go (hunk 1 above)
Comment (travisn) [inline pkg/operator/cluster.go]: see the comment above the func. It is constant.

File: pkg/operator/cluster.go (hunk 2 above)
Comment (travisn) [inline pkg/operator/cluster.go]: agreed, i'll change it

File: pkg/operator/cluster.go (hunk 3 above)
Comment (travisn) [inline pkg/operator/cluster.go]: will do

File: pkg/operator/cluster.go (hunk 4 above)
Comment (travisn) [inline pkg/operator/cluster.go]: right, will move it

File: pkg/operator/cluster.go (hunk 5 above)
Comment (travisn) [inline pkg/operator/cluster.go]: oops, missed updating that reference

File: pkg/operator/cluster/cluster.go (hunk 6 above)
Comment (travisn) [inline pkg/operator/cluster/cluster.go]: right, i'll log both

File: pkg/operator/cluster/cluster.go (hunk 16 above)
Comment (travisn) [inline pkg/operator/cluster/cluster.go]: this was specifically for use by the rbd plugin. Let's update it later with your work around the plugins

File: pkg/operator/tpr.go (hunk 12 above)
Comment (travisn) [inline pkg/operator/tpr.go]: sounds good will add an example

File: pkg/operator/tpr.go (hunk 17 above)
Comment (travisn) [inline pkg/operator/tpr.go]: not a typo. The TPRs are actually made plural for a RESTful api. I was very confused too. :)

File: pkg/operator/api/api.go (hunk 14 above)
Comment (travisn) [inline pkg/operator/api/api.go]: I'll look at the naming again. I remember considering `Name`, but don't recall why i didn't go with it
