### PR TITLE
cli and api: Fix issues wtih erroring on user create even when it is a success.

### LINKED ISSUE #383: Creating a Rook object user prints failure message
Creating a Rook object user succeeds, but a failure message is printed. I would expect it to print success instead of "failed to create user". The user was indeed created successfully as shown by `rook object user list` and related commands.
```
$ rook object user create foo bar
failed to create user: HTTP status code 201 for query objectstore/users: '{"userId":"foo","displayName":"bar","email":"","accessKey":"AXG4VRYMOG1FVEQQW081","secretKey":"sqWg3xpT1XyH1SkVA8UtDGCxvvcayexDKhSuVqqF"}'
```

### PR DESCRIPTION
**Pull request by thephred**
Fixes #383

### CODE REVIEW

File: pkg/rook/client/object.go [hunk 1]
```diff
@@ -41,19 +42,19 @@ func (c *RookNetworkRestClient) CreateObjectStore() (string, error) {
 	return string(resp), nil
 }
 
-func (c *RookNetworkRestClient) GetObjectStoreConnectionInfo() (model.ObjectStoreS3Info, error) {
+func (c *RookNetworkRestClient) GetObjectStoreConnectionInfo() (*model.ObjectStoreS3Info, error) {
 	body, err := c.DoGet(path.Join(objectStoreQueryName, connectionInfoQueryName))
 	if err != nil {
-		return model.ObjectStoreS3Info{}, err
+		return nil, err
```
Comment (travisn) [inline pkg/rook/client/object.go]: is this related to the failure, or just follow up from the original PR?

File: cmd/rook/object/user.go [hunk 2]
```diff
@@ -195,7 +195,7 @@ func deleteUser(c client.RookRestClient, id string) (string, error) {
 		return "", fmt.Errorf("Unable to find user %s", id)
 	}
 
-	if err != nil {
+	if !client.IsHttpStatusCode(err, http.StatusNoContent) {
```
Comment (travisn) [inline cmd/rook/object/user.go]: is this technically the only change necessary for the bug?

Comment (thephred) [inline cmd/rook/object/user.go]: no, I needed to add returning the body even on "error"
