### PR TITLE
osd: skip wait loop when initial PGs is 0

### LINKED ISSUE #1708: Node cannot be removed from the cluster when its usage is 0
When a Ceph node is being removed from the cluster, the OSD pod waits for the usage or PG count of the OSDs to start going down, indicating that rebalancing has started before it moves on to the next step.  If the usage is 0 though, this value will never go down and the wait will eventually time out with an error similar to `last error: current used space and pg count for osd.94 has not decreased still`.

This should be an easy fix to just skip to the next step if initial usage and PG count is 0.
This was first mentioned by @dimm0 in https://github.com/rook/rook/issues/1687#issuecomment-386766763.

### PR DESCRIPTION
**Pull request by galexrt**
Description of your changes:
This checks if the initial PG count is zero and if so skips the loop which would normally timeout due to the initial and current PG count not decreasing.

I haven't tested the fix but as far as I understand the logic this should work.
Maybe @dimm0 can try to reproduce as he first mentioned it.

Which issue is resolved by this Pull Request:
Resolves #1708.

Checklist:
- [x] Documentation has been updated, if necessary.
- [x] Pending release notes updated with breaking and/or notable changes, if necessary.
- [x] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.

### CODE REVIEW

File: pkg/daemon/ceph/osd/agent.go [hunk 1]
```diff
@@ -565,6 +565,11 @@ func waitForRebalance(context *clusterd.Context, clusterName string, osdID int,
 					osdID, initialUsage, currUsage)
 			}
 
+			// when the initial OSD PG count is zero there is nothing to do here
+			if init.Pgs == "0" {
```
Comment (jbw976) [inline pkg/daemon/ceph/osd/agent.go]: what do you think about checking for `init.UsedKB == 0` here also?

Comment (galexrt) [reply pkg/daemon/ceph/osd/agent.go]: Should they be checked together (`&&`) or just one of them is enough for the check to pass (`||`)?

Comment (jbw976) [reply pkg/daemon/ceph/osd/agent.go]: i think the check should be `||`, meaning just one of them being 0 is good enough to bail out right away and not wait for any of the values to decrease.

**Comment by galexrt** [comment]
@jbw976 I added the condition. PTAL

@dimm0 could you test this fix (should be applicable to `v0.7.1` code too) or tell me how I can correctly reproduce your scenario?

File: pkg/daemon/ceph/osd/agent.go [hunk 2]
```diff
@@ -571,6 +571,11 @@ func waitForRebalance(context *clusterd.Context, clusterName string, osdID int,
 					osdID, initialUsage, currUsage)
 			}
 
+			// when the initial OSD PG count is zero there is nothing to do here
```
Comment (jbw976) [inline pkg/daemon/ceph/osd/agent.go]: you could update the comment also to reflect both checks

File: pkg/daemon/ceph/osd/agent.go [hunk 3]
```diff
@@ -571,6 +571,11 @@ func waitForRebalance(context *clusterd.Context, clusterName string, osdID int,
...
+			if init.Pgs == "0" || init.UsedKB == "0" {
```
Comment (jbw976) [inline pkg/daemon/ceph/osd/agent.go]: we are comparing `json.Number` types to strings, is that supported and work as expected for `json.Number` comparisons?

Comment (galexrt) [reply pkg/daemon/ceph/osd/agent.go]: @jbw976 `json.Number` is type `string`, so yes that does a normal string to string comparison, otherwise go vet/fmt would tell use.

**Comment by dimm0** [comment]
@galexrt I'd prefer to not experiment on our production cluster, but you should see this condition if you set the weights of all node OSDs to 0 (or mark the OSDs out), and then try deleting the node from cluster CRD

**Comment by galexrt** [comment]
@dimm0 Sure, no problem. I thought you may have a test cluster ready for that ;)

I'll try to test it at latest on the weekend.

File: pkg/daemon/ceph/osd/agent.go [hunk 4]
```diff
@@ -571,6 +571,11 @@ func waitForRebalance(context *clusterd.Context, clusterName string, osdID int,
 					osdID, initialUsage, currUsage)
 			}
 
+			// when the initial OSD PG count or the used KB is zero there is nothing to do here
+			if init.Pgs == "0" || init.UsedKB == "0" {
```
Comment (jbw976) [inline pkg/daemon/ceph/osd/agent.go]: when i originally wrote this function, I don't think I realized that `json.Number` type is just a string.  The comparisons are not valid in this function, see this quick example: https://play.golang.org/p/PQ-dmFp2PdN

I think we should convert these to integers first with https://golang.org/pkg/encoding/json/#Number.Int64 and then make any comparisons.  Can we do that now please? :anguished:

**Comment by liewegas** [comment]
``ceph osd safe-to-destroy <osd-id>`` is probably the command this should depend on.

**Comment by galexrt** [comment]
@liewegas @jbw976 I'll create a new issue for switching to `ceph osd safe-to-destroy <osd-id>`, so this is "partially" fixed at least.

**Comment by jbw976** [comment]
For this PR, could we just convert them to integers so that all comparisons are numerical as opposed to string based? That would make me feel better :)

File: pkg/operator/ceph/cluster/osd/remove.go [hunk 5]
```diff
@@ -89,11 +89,34 @@ func waitForRebalance(context *clusterd.Context, namespace string, osdID int, in
 					osdID, initialUsage, currUsage)
 			}
 
-			if curr.UsedKB == "0" && curr.Pgs == "" {
+			initUsedKB, err := init.UsedKB.Int64()
```
Comment (galexrt) [inline pkg/operator/ceph/cluster/osd/remove.go]: @jbw976 Like that?

File: pkg/operator/ceph/cluster/osd/remove.go [hunk 6]
```diff
@@ -89,11 +89,34 @@ func waitForRebalance(context *clusterd.Context, namespace string, osdID int, in
...
+			if err != nil {
+				return fmt.Errorf("error converting current used KB to int64. %+v", err)
```
Comment (jbw976) [inline pkg/operator/ceph/cluster/osd/remove.go]: this error should say "init used KB", not current

File: pkg/operator/ceph/cluster/osd/remove.go [hunk 7]
```diff
@@ -89,11 +89,34 @@ func waitForRebalance(context *clusterd.Context, namespace string, osdID int, in
...
+			}
+			initPGs, err := init.Pgs.Int64()
+			if err != nil {
+				return fmt.Errorf("error converting current PGs to int64. %+v", err)
```
Comment (jbw976) [inline pkg/operator/ceph/cluster/osd/remove.go]: this error should say "init PGs", not current

**Comment by jbw976** [comment]
This unit test failure looks related to your change, hopefully it will be easy to get the unit tests passing with `make test` locally:
```
2018-07-09 17:29:05.501154 I | util: retrying after 5s, last error: error converting current PGs to int64. strconv.ParseInt: parsing "": invalid syntax
```

**Comment by galexrt** [comment]
@jbw976 I added a check for the variables that when they are empty, they "default" to `0`.

**Comment by jbw976** [comment]
@galexrt, I still see the unit tests failing after timing out.  Related error message appears to be:
```
2018-07-10 16:07:29.986590 I | util: retrying after 5s, last error: error converting init PGs to int64. strconv.ParseInt: parsing "": invalid syntax
```
do you see this failure locally when running `make test`?

**Comment by galexrt** [comment]
@jbw976 Ah well `curr.Pgs == ""` and then converting it to int is the wrong way, `curr.Pgs != ""` is right.
