### PR TITLE
ci: wait for cert while deploying vault

### LINKED ISSUE #10158: encryption-pvc-kms-vault-token-auth test is failing
[encryption-pvc-kms-vault-token-auth](https://github.com/rook/rook/runs/6160644379?check_suite_focus=true#logs) canary test is failing in `deploy vault` stage. 

error
```
+ kubectl exec -ti vault-0 -- vault operator init -format json -ca-cert /vault/userconfig/vault-server-tls/vault.crt
Unable to use a TTY - input is not a terminal or the right kind of file
error: unable to upgrade connection: container not found ("vault")
Error: Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by subhamkrai**
sometimes, it take few seconds to fill certificate
after certificate approval. So, let's wait for few seconds.

Closes: https://github.com/rook/rook/issues/10158
Signed-off-by: subhamkrai <srai@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #10158 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by subhamkrai** [comment]
when it fails, we see something like 
```
kubectl get csr vault-csr -o 'jsonpath={.status.certificate}'
+ serverCert=
+ echo ''
```
when it passes, we see

```ertificatesigningrequest.certificates.k8s.io/vault-csr approved
++ kubectl get csr vault-csr -o 'jsonpath={.status.certificate}'
+ serverCert=LS0tLS1CRUdJTi .... RS0tLS0tCg==
+ echo LS0tLS1CRUdJTiBDRVJUSUZJQ0F  ....  RVJUSUZJQ0FURS0tLS0tCg==
```

File: tests/scripts/generate-tls-config.sh [hunk 1]
```diff
@@ -74,6 +74,13 @@ kubectl create -f "${DIR}/"csr.yaml
 
 kubectl certificate approve "${CSR_NAME}"
 
+timeout 10 bash <<-'EOF'
+    until [ $(kubectl get csr "${CSR_NAME}" -o jsonpath='{.status.certificate}' | wc -c) -gt 1  ]; do
+      echo "waiting for certificate to filled"
```
Comment (leseb) [inline tests/scripts/generate-tls-config.sh:79]:
```suggestion
      echo "waiting for certificate "${CSR_NAME}" to be filled"
```

**Review by leseb — CHANGES_REQUESTED** [review]

File: tests/scripts/generate-tls-config.sh (hunk 1 above)
Comment (subhamkrai) [reply tests/scripts/generate-tls-config.sh]: done

**Review by leseb — APPROVED** [review]
