### PR TITLE
api: Fix the second part of the bucket ordering issue

### LINKED ISSUE #382: Intermittent object test failure for bucket
A recent build failed with this error
https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-379/3/pipeline/20
```
--- FAIL: TestListBuckets (0.23s)
251 		assertions.go:109: 
                        
	Location:	object_test.go:581
252 			
	Error:		Not equal: []string{"metadata", "get", "--cluster=default", "--conf=/tmp/rgw/tmp/default.config", "--keyring=/tmp/rgw/tmp/keyring", "bucket:foo"} != []string{"metadata", "get", "--cluster=default", "--conf=/tmp/rgw/tmp/default.config", "--keyring=/tmp/rgw/tmp/keyring", "bucket:bar"}
253 			
254 		assertions.go:109: 
                        
	Location:	object_test.go:584
255 			
	Error:		Not equal: []string{"metadata", "get", "--cluster=default", "--conf=/tmp/rgw/tmp/default.config", "--keyring=/tmp/rgw/tmp/keyring", "bucket:bar"} != []string{"metadata", "get", "--cluster=default", "--conf=/tmp/rgw/tmp/default.config", "--keyring=/tmp/rgw/tmp/keyring", "bucket:foo"}
256 			
257 		assertions.go:109: 
                        
	Location:	object_test.go:591
258 			
	Error:		Not equal: "[{\"name\":\"foo\",\"owner\":\"bob\",\"createdAt\":\"2016-08-05T16:23:34.343343Z\",\"size\":4,\"numberOfObjects\":2},{\"name\":\"bar\",\"owner\":\"bill\",\"createdAt\":\"2016-08-05T18:31:22.445343Z\",\"size\":5,\"numberOfObjects\":4}]" != "[{\"name\":\"bar\",\"owner\":\"bob\",\"createdAt\":\"2016-08-05T16:23:34.343343Z\",\"size\":5,\"numberOfObjects\":4},{\"name\":\"foo\",\"owner\":\"bill\",\"createdAt\":\"2016-08-05T18:31:22.445343Z\",\"size\":4,\"numberOfObjects\":2}]"
259 			
```

### PR DESCRIPTION
**Pull request by thephred**
Fixes #382

### CODE REVIEW

**Comment by jbw976** [comment]
I have had a few of these intermittent golang unit test failures before and to verify with more confidence that i have fixed them i will always use something like `go test -run <test_name> -count 100` which will run the test 100 times in a row.

File: pkg/api/object_test.go [hunk 1]
```diff
@@ -571,18 +571,22 @@ func TestListBuckets(t *testing.T) {
 	assert.Equal(t, `[{"name":"foo","owner":"bob","createdAt":"2016-08-05T16:23:34.343343Z","size":9,"numberOfObjects":6}]`, w.Body.String())
 
 	// Two buckets
-	timeThrough := 0
+	first = true
 	w = runTest(func(args ...string) (string, error) {
-		timeThrough++
-		if timeThrough == 1 {
+		if first {
+			first = false
```
Comment (jbw976) [inline pkg/api/object_test.go]: for maintainability, it may be useful to add a comment for each branch here about why you expect the 1st call to do x and why you expect the other calls to do y

**Comment by thephred** [comment]
With respect to the running of the test 100 times that is a great recommendation. I went ahead and did that and it passed.
