### PR TITLE
object: Log all reconcile errors during object store creation

### LINKED ISSUE #15713: Creating CephObjectStorage Stopped Working
For development purposes I have been running Rook Ceph on my laptop for roughly the last year to test Ceph's S3 APIs. To do this on a laptop I create 3 loopback devices. 

Until recently this setup worked great - Ceph is happy and I can create an ObjectStore RGW gateway and CephFileSystems.

Sometime in the last month this has stopped working but I'm not sure why. The cluster is created correctly, the cluster status is healthy (see below). The job `ceph-object-controller-detect-version-t6t9j` runs successfully. Then is runs again and again and again. A objectstore is never created.

I am running Fedora 41 using latest minikube (v1.35.0). The minikube drive is set to none, so Kubernetes is directly running on my laptop.

What I would like is a pointer on how to proceed debugging this. I don't see anything in the operator logs included below.

**How to reproduce it (minimal and precise):**

Create a new minikube cluster, install the rook-ceph chart, then install the rook-cluster chart using the values.yaml file below. Reproducible every time. Note I am careful to remove `/var/lib/rook` on my laptop between installations.

**File(s) to submit**:

This is the values.yaml for rook-ceph-cluster helm chart:

```yaml

# A single node ceph cluster. It includes 1 manager, 1 monitor and 3 OSDs. Some inspiration from https://github.com/rook/rook/blob/master/deploy/examples/cluster-test.yaml.
operatorNamespace: rook-ceph

toolbox:
  enabled:  true  # Used to run ceph admin command

# See https://docs.ceph.com/en/latest/rados/troubleshooting/troubleshooting-pg/?highlight=troubleshoot#one-node-cluster
configOverride: |
  [global]
  osd_crush_chooseleaf_type = 0 

cephClusterSpec:
  cephVersion:
    image: quay.io/ceph/ceph:v19.2.2
  dataDirHostPath: /var/lib/rook # Make sure to clean this if doing a reinstall (or use the cleanupPolicy below)

  mon:
    count: 1
    allowMultiplePerNode: true

  mgr:
    count: 1
    allowMultiplePerNode: true
    modules:
      - name: pg_autoscaler # This is already enabled by default, but needs to be here so that we don't override the default behavior.
        enabled: true
      - name: rook # This enables the rook module (and thus orchestrator. https://serverfault.com/questions/1057092/orchestrator-is-not-available-with-fresh-rook-instance)
        enabled: true

  storage:
    useAllNodes: true
    useAllDevices: false
    # Use loop devices created by the actions.sh file
    devices:
      - name: /dev/loop33
      - name: /dev/loop34
      - name: /dev/loop35

  # No need to run this on a test cluster
  crashCollector:
    disable: true
    
  dashboard:
    enabled: true
    urlPrefix: /
    # This setting most of the time does NOT work and has to be manually set after installation
    ssl: false

  # TODO - enable this for prometheus integration
  monitoring:
    enabled: false

  # From https://github.com/rook/rook/blob/master/deploy/examples/cluster-test.yaml
  disruptionManagement:
    managePodBudgets: true
  
  # If you need to delete the cluster comment out this code and deploy the
  # rook-ceph-cluster helm chart. Then delete the rook-ceph-cluster helm chart
  # to trigger the cleanup. To recreate this cluster, comment out this code 
  # and deploy rook-ceph-cluster helm chart again.
  #cleanupPolicy:
  #  confirmation: yes-really-destroy-data
  #  sanitizeDisks:
  #    method: quick
  #    dataSource: zero
  #    iteration: 1
  #  allowUninstallWithVolumes: false

  resources:
    mgr:
      limits:
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 500Mi
    mon:
      limits:
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 512Mi
    osd:
      limits:
        memory: 2048Gi
      requests:
        cpu: 100m
        memory: 512Mi # Anything lower causes the OSD to crash with an allocation error
    mgr-sidecar:
      limits:
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 40Mi
    cleanup:
      limits:
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
    exporter:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 50Mi

ingress:
  dashboard:
    annotations:
    #  nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    #  nginx.ingress.kubernetes.io/server-snippet: |
    #    proxy_ssl_verify off;
    #nginx.ingress.kubernetes.io/rewrite-target: /ceph-dashboard/$2
    # If the dashboard has ssl: true the following will make sure the NGINX Ingress controller can expose the dashboard correctly
    host:
      name: ceph.<redacted>.internal
      path: /
    ingressClassName: nginx

# No block storage - meaning no ceph storage class to create Kubernetes persistent volumes (PVs)
cephBlockPools: []

cephBlockPoolsVolumeSnapshotClass:
  enabled: false

# Enable Ceph file system
cephFileSystems:
  - name: ceph-filesystem
    spec:
      metadataPool:
        failureDomain: osd
        replicated:
          size: 3
      dataPools:
        - failureDomain: osd
          replicated:
            size: 3
          name: data0
      metadataServer:
        activeCount: 1
        activeStandby: true
        resources:
          limits:
            memory: "4Gi"
          requests:
            cpu: "500m"
            memory: "4Gi"
        priorityClassName: system-cluster-critical

    storageClass:
      enabled: true
      isDefault: false
      name: ceph-filesystem
      pool: data0
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      volumeBindingMode: "Immediate"
      annotations: {}
      labels: {}
      mountOptions: []
      parameters:
        csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
        csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
        csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
        csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
        csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
        csi.storage.k8s.io/fstype: ext4

# Create one objectstore for S3 implementation
cephObjectStores:
  - name: ceph-objectstore
    spec:
      metadataPool:
        failureDomain: osd # We only have one node
        replicated:
          size: 3

      dataPool:
        failureDomain: osd # # We only have one node
        erasureCoded:
          dataChunks: 2
          codingChunks: 1
      preservePoolsOnDelete: false

      gateway:
        caBundleRef: terrabox-ca
        sslCertificateRef: rook-ceph-certificate
        port: 80
        securePort: 443
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
        instances: 1
        priorityClassName: system-cluster-critical

    storageClass:
      enabled: true
      name: ceph-bucket
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      parameters:
        region: us-west-2

    # S3 api
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: https
        nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,X-Amz-Content-Sha256,X-Amz-Date,X-Amz-Security-Token"
        nginx.ingress.kubernetes.io/cors-allow-origin: "https://*.<redacted>.internal"
        nginx.ingress.kubernetes.io/enable-cors: "true"
      enabled: true
      host:
        name: s3.<redacted>.internal
        path: /
      ingressClassName: nginx
```

**Logs to submit**:

The rook-ceph operator log looks like this:

```
2025/04/15 01:40:39 maxprocs: Leaving GOMAXPROCS=14: CPU quota undefined
2025-04-15 01:40:39.891392 I | rookcmd: starting Rook v1.16.6 with arguments '/usr/local/bin/rook ceph operator'
2025-04-15 01:40:39.891405 I | rookcmd: flag values: --enable-machine-disruption-budget=false, --help=false, --kubeconfig=, --log-level=INFO
2025-04-15 01:40:39.891409 I | cephcmd: starting Rook-Ceph operator
2025-04-15 01:40:39.965217 I | cephcmd: base ceph version inside the rook operator image is "ceph version 18.2.4 (e7ad5345525c7aa95470c26863873b581076945d) reef (stable)"
2025-04-15 01:40:39.969235 I | op-k8sutil: operator setting "CSI_ENABLE_OMAP_GENERATOR" = "false"
2025-04-15 01:40:39.969262 I | op-k8sutil: operator setting "CSI_RBD_PROVISIONER_RESOURCE" = "- name : csi-provisioner\n  resource:\n    requests:\n      memory: 128Mi\n      cpu: 100m\n    limits:\n      memory: 256Mi\n- name : csi-resizer\n  resource:\n    requests:\n      memory: 128Mi\n      cpu: 100m\n    limits:\n      memory: 256Mi\n- name : csi-attacher\n  resource:\n    requests:\n      memory: 128Mi\n      cpu: 100m\n    limits:\n      memory: 256Mi\n- name : csi-snapshotter\n  resource:\n    requests:\n      memory: 128Mi\n      cpu: 100m\n    limits:\n      memory: 256Mi\n- name : csi-rbdplugin\n  resource:\n    requests:\n      memory: 512Mi\n    limits:\n      memory: 1Gi\n- name : csi-omap-generator\n  resource:\n    requests:\n      memory: 512Mi\n      cpu: 250m\n    limits:\n      memory: 1Gi\n- name : liveness-prometheus\n  resource:\n    requests:\n      memory: 128Mi\n      cpu: 50m\n    limits:\n      memory: 256Mi\n"
2025-04-15 01:40:39.969269 I | op-k8sutil: operator setting "ROOK_CSI_ATTACHER_IMAGE" = "registry.k8s.io/sig-storage/csi-attacher:v4.8.0"
2025-04-15 01:40:39.969272 I | op-k8sutil: operator setting "ROOK_OBC_WATCH_OPERATOR_NAMESPACE" = "true"
2025-04-15 01:40:39.969275 I | op-k8sutil: operator setting "CSI_ENABLE_CEPHFS_SNAPSHOTTER" = "false"
2025-04-15 01:40:39.969277 I | op-k8sutil: operator setting "CSI_ENABLE_CSIADDONS" = "false"
2025-04-15 01:40:39.969279 I | op-k8sutil: operator setting "CSI_ENABLE_TOPOLOGY" = "false"
2025-04-15 01:40:39.969281 I | op-k8sutil: operator setting "ROOK_ENABLE_DISCOVERY_DAEMON" = "true"
2025-04-15 01:40:39.969283 I | op-k8sutil: operator setting "CSI_CEPHFS_FSGROUPPOLICY" = "File"
2025-04-15 01:40:39.969285 I | op-k8sutil: operator setting "CSI_ENABLE_METADATA" = "false"
2025-04-15 01:40:39.969288 I | op-k8sutil: operator setting "CSI_PLUGIN_PRIORITY_CLASSNAME" = "system-node-critical"
2025-04-15 01:40:39.969290 I | op-k8sutil: operator setting "ROOK_CEPH_ALLOW_LOOP_DEVICES" = "true"
2025-04-15 01:40:39.969292 I | op-k8sutil: operator setting "ROOK_CSI_ENABLE_NFS" = "false"
2025-04-15 01:40:39.969294 I | op-k8sutil: operator setting "ROOK_CSI_PROVISIONER_IMAGE" = "registry.k8s.io/sig-storage/csi-provisioner:v5.1.0"
2025-04-15 01:40:39.969307 I | op-k8sutil: operator setting "CSI_CEPHFS_PROVISIONER_RESOURCE" = "- name : csi-provisioner\n  resource:\n    requests:\n      memory: 128Mi\n      cpu: 100m\n    limits:\n      memory: 256Mi\n- name : csi-resizer\n  resource:\n    requests:\n      memory: 128Mi\n      cpu: 100m\n    limits:\n      memory: 256Mi\n- name : csi-attacher\n  resource:\n    requests:\n      memory: 128Mi\n      cpu: 100m\n    limits:\n      memory: 256Mi\n- name : csi-snapshotter\n  resource:\n    requests:\n      memory: 128Mi\n      cpu: 100m\n    limits:\n      memory: 256Mi\n- name : csi-cephfsplugin\n  resource:\n    requests:\n      memory: 512Mi\n      cpu: 250m\n    limits:\n      memory: 1Gi\n- name : liveness-prometheus\n  resource:\n    requests:\n      memory: 128Mi\n      cpu: 50m\n    limits:\n      memory: 256Mi\n"
2025-04-15 01:40:39.969310 I | op-k8sutil: operator setting "CSI_RBD_FSGROUPPOLICY" = "File"
2025-04-15 01:40:39.969313 I | op-k8sutil: operator setting "ROOK_CSI_ENABLE_CEPHFS" = "true"
2025-04-15 01:40:39.969319 I | op-k8sutil: operator setting "ROOK_CSI_ENABLE_RBD" = "false"
2025-04-15 01:40:39.969322 I | op-k8sutil: operator setting "ROOK_CSI_REGISTRAR_IMAGE" = "registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.13.0"
2025-04-15 01:40:39.969325 I | op-k8sutil: operator setting "ROOK_CSI_SNAPSHOTTER_IMAGE" = "registry.k8s.io/sig-storage/csi-snapshotter:v8.2.0"
2025-04-15 01:40:39.969329 I | op-k8sutil: operator setting "CSI_ENABLE_RBD_SNAPSHOTTER" = "false"
2025-04-15 01:40:39.969342 I | op-k8sutil: operator setting "CSI_NFS_PLUGIN_RESOURCE" = "- name : driver-registrar\n  resource:\n    requests:\n      memory: 128Mi\n      cpu: 50m\n    limits:\n      memory: 256Mi\n- name : csi-nfsplugin\n  resource:\n    requests:\n      memory: 512Mi\n      cpu: 250m\n    limits:\n      memory: 1Gi\n"
2025-04-15 01:40:39.969348 I | op-k8sutil: operator setting "CSI_PLUGIN_ENABLE_SELINUX_HOST_MOUNT" = "false"
2025-04-15 01:40:39.969352 I | op-k8sutil: operator setting "CSI_PROVISIONER_PRIORITY_CLASSNAME" = "system-cluster-critical"
2025-04-15 01:40:39.969354 I | op-k8sutil: operator setting "CSI_PROVISIONER_REPLICAS" = "2"
2025-04-15 01:40:39.969356 I | op-k8sutil: operator setting "CSI_RBD_ATTACH_REQUIRED" = "true"
2025-04-15 01:40:39.969358 I | op-k8sutil: operator setting "CSI_GRPC_TIMEOUT_SECONDS" = "150"
2025-04-15 01:40:39.969360 I | op-k8sutil: operator setting "CSI_ENABLE_ENCRYPTION" = "false"
2025-04-15 01:40:39.969366 I | op-k8sutil: operator setting "ROOK_CSIADDONS_IMAGE" = "quay.io/csiaddons/k8s-sidecar:v0.11.0"
2025-04-15 01:40:39.969370 I | op-k8sutil: operator setting "ROOK_CSI_CEPH_IMAGE" = "quay.io/cephcsi/cephcsi:v3.13.1"
2025-04-15 01:40:39.969373 I | op-k8sutil: operator setting "ROOK_CSI_IMAGE_PULL_POLICY" = "IfNotPresent"
2025-04-15 01:40:39.969378 I | op-k8sutil: operator setting "CSI_CEPHFS_ATTACH_REQUIRED" = "true"
2025-04-15 01:40:39.969382 I | op-k8sutil: operator setting "CSI_ENABLE_NFS_SNAPSHOTTER" = "false"
2025-04-15 01:40:39.969384 I | op-k8sutil: operator setting "CSI_FORCE_CEPHFS_KERNEL_CLIENT" = "true"
2025-04-15 01:40:39.969386 I | op-k8sutil: operator setting "CSI_NFS_FSGROUPPOLICY" = "File"
2025-04-15 01:40:39.969389 I | op-k8sutil: operator setting "ROOK_CEPH_COMMANDS_TIMEOUT_SECONDS" = "15"
2025-04-15 01:40:39.969391 I | op-k8sutil: operator setting "ROOK_CSI_DISABLE_DRIVER" = "false"
2025-04-15 01:40:39.969393 I | op-k8sutil: operator setting "ROOK_LOG_LEVEL" = "INFO"
2025-04-15 01:40:39.969395 I | op-k8sutil: operator setting "CSI_ENABLE_HOST_NETWORK" = "false"
2025-04-15 01:40:39.969398 I | op-k8sutil: operator setting "CSI_ENABLE_VOLUME_GROUP_SNAPSHOT" = "true"
2025-04-15 01:40:39.969400 I | op-k8sutil: operator setting "CSI_NFS_ATTACH_REQUIRED" = "true"
2025-04-15 01:40:39.969415 I | op-k8sutil: operator setting "CSI_NFS_PROVISIONER_RESOURCE" = "- name : csi-provisioner\n  resource:\n    requests:\n      memory: 128Mi\n      cpu: 100m\n    limits:\n      memory: 256Mi\n- name : csi-nfsplugin\n  resource:\n    requests:\n      memory: 512Mi\n      cpu: 250m\n    limits:\n      memory: 1Gi\n- name : csi-attacher\n  resource:\n    requests:\n      memory: 512Mi\n      cpu: 250m\n    limits:\n      memory: 1Gi\n"
2025-04-15 01:40:39.969421 I | op-k8sutil: operator setting "CSI_RBD_PLUGIN_RESOURCE" = "- name : driver-registrar\n  resource:\n    requests:\n      memory: 128Mi\n      cpu: 50m\n    limits:\n      memory: 256Mi\n- name : csi-rbdplugin\n  resource:\n    requests:\n      memory: 512Mi\n      cpu: 250m\n    limits:\n      memory: 1Gi\n- name : liveness-prometheus\n  resource:\n    requests:\n      memory: 128Mi\n      cpu: 50m\n    limits:\n      memory: 256Mi\n"
2025-04-15 01:40:39.969424 I | op-k8sutil: operator setting "ROOK_CSI_RESIZER_IMAGE" = "registry.k8s.io/sig-storage/csi-resizer:v1.13.1"
2025-04-15 01:40:39.969432 I | op-k8sutil: operator setting "CSI_CEPHFS_PLUGIN_RESOURCE" = "- name : driver-registrar\n  resource:\n    requests:\n      memory: 128Mi\n      cpu: 50m\n    limits:\n      memory: 256Mi\n- name : csi-cephfsplugin\n  resource:\n    requests:\n      memory: 512Mi\n      cpu: 250m\n    limits:\n      memory: 1Gi\n- name : liveness-prometheus\n  resource:\n    requests:\n      memory: 128Mi\n      cpu: 50m\n    limits:\n      memory: 256Mi\n"
2025-04-15 01:40:39.969438 I | operator: watching all namespaces for Ceph CRs
2025-04-15 01:40:39.969461 I | operator: setting up schemes
2025-04-15 01:40:39.971119 I | operator: setting up the controller-runtime manager
2025-04-15 01:40:39.971444 I | ceph-cluster-controller: successfully started
2025-04-15 01:40:39.971747 I | ceph-cluster-controller: enabling hotplug orchestration
2025-04-15 01:40:39.971773 I | ceph-nodedaemon-controller: successfully started
2025-04-15 01:40:39.971783 I | ceph-block-pool-controller: successfully started
2025-04-15 01:40:39.971794 I | ceph-object-store-user-controller: successfully started
2025-04-15 01:40:39.971813 I | ceph-object-realm-controller: successfully started
2025-04-15 01:40:39.971820 I | ceph-object-zonegroup-controller: successfully started
2025-04-15 01:40:39.971826 I | ceph-object-zone-controller: successfully started
2025-04-15 01:40:39.971928 I | ceph-object-controller: successfully started
2025-04-15 01:40:39.971954 I | ceph-file-controller: successfully started
2025-04-15 01:40:39.971973 I | ceph-nfs-controller: successfully started
2025-04-15 01:40:39.971987 I | ceph-rbd-mirror-controller: successfully started
2025-04-15 01:40:39.972006 I | ceph-client-controller: successfully started
2025-04-15 01:40:39.972016 I | ceph-filesystem-mirror-controller: successfully started
2025-04-15 01:40:39.972029 I | operator: rook-ceph-operator-config-controller successfully started
2025-04-15 01:40:39.972036 I | ceph-csi: rook-ceph-operator-csi-controller successfully started
2025-04-15 01:40:39.972135 I | op-bucket-prov: rook-ceph-operator-bucket-controller successfully started
2025-04-15 01:40:39.972144 I | ceph-bucket-topic: successfully started
2025-04-15 01:40:39.972151 I | ceph-bucket-notification: successfully started
2025-04-15 01:40:39.972156 I | ceph-bucket-notification: successfully started
2025-04-15 01:40:39.972161 I | ceph-fs-subvolumegroup-controller: successfully started
2025-04-15 01:40:39.972191 I | blockpool-rados-namespace-controller: successfully started
2025-04-15 01:40:39.972216 I | ceph-cosi-controller: successfully started
2025-04-15 01:40:39.972238 I | operator: starting the controller-runtime manager
2025-04-15 01:40:40.185380 I | op-discover: tolerations: []
2025-04-15 01:40:40.203794 I | ceph-csi: successfully created csi config map "rook-ceph-csi-config"
2025-04-15 01:40:40.203878 I | op-discover: rook-discover daemonset started
2025-04-15 01:40:40.203891 I | operator: rook-ceph-operator-config-controller done reconciling
2025-04-15 01:40:40.205410 I | op-k8sutil: removing daemonset csi-rbdplugin if it exists
2025-04-15 01:40:40.212540 I | op-k8sutil: removing deployment csi-rbdplugin-provisioner if it exists
2025-04-15 01:40:40.224037 I | ceph-csi: successfully removed CSI Ceph RBD driver
2025-04-15 01:40:40.224055 I | op-k8sutil: removing daemonset csi-cephfsplugin if it exists
2025-04-15 01:40:40.234016 I | op-k8sutil: removing deployment csi-cephfsplugin-provisioner if it exists
2025-04-15 01:40:40.247155 I | ceph-csi: successfully removed CSI CephFS driver
2025-04-15 01:40:40.247175 I | op-k8sutil: removing daemonset csi-nfsplugin if it exists
2025-04-15 01:40:40.248481 I | op-k8sutil: removing deployment csi-nfsplugin-provisioner if it exists
2025-04-15 01:40:40.296225 I | ceph-csi: successfully removed CSI NFS driver
2025-04-15 01:40:42.366551 I | ceph-spec: adding finalizer "cephcluster.ceph.rook.io" on "rook-ceph"
2025-04-15 01:40:42.378660 I | clusterdisruption-controller: deleted all legacy node drain canary pods
2025-04-15 01:40:42.379091 I | ceph-spec: adding finalizer "cephobjectstore.ceph.rook.io" on "ceph-objectstore"
2025-04-15 01:40:42.379635 I | ceph-cluster-controller: reconciling ceph cluster in namespace "rook-ceph"
2025-04-15 01:40:42.390362 I | ceph-cluster-controller: clusterInfo not yet found, must be a new cluster.
2025-04-15 01:40:42.414924 I | ceph-spec: detecting the ceph image version for image quay.io/ceph/ceph:v18.2.4...
2025-04-15 01:40:42.431625 E | clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
2025-04-15 01:40:42.433682 I | ceph-csi: cluster info for cluster "rook-ceph" is not ready yet, will retry in 10s, proceeding with ready clusters
2025-04-15 01:40:42.484951 E | clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
2025-04-15 01:40:42.533253 E | clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
2025-04-15 01:40:42.582914 E | clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
2025-04-15 01:40:42.648115 E | clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
2025-04-15 01:40:42.694908 E | clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
2025-04-15 01:40:42.697073 I | ceph-csi: successfully started CSI CephFS driver
2025-04-15 01:40:42.709518 I | ceph-csi: CSIDriver object created for driver "rook-ceph.cephfs.csi.ceph.com"
2025-04-15 01:40:42.709538 I | op-k8sutil: removing daemonset csi-rbdplugin if it exists
2025-04-15 01:40:42.723757 I | op-k8sutil: removing deployment csi-rbdplugin-provisioner if it exists
2025-04-15 01:40:42.764946 E | clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
2025-04-15 01:40:42.843692 E | clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
2025-04-15 01:40:42.898729 E | clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
2025-04-15 01:40:42.960383 E | clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
2025-04-15 01:40:42.973281 I | ceph-csi: successfully removed CSI Ceph RBD driver
2025-04-15 01:40:42.973299 I | op-k8sutil: removing daemonset csi-nfsplugin if it exists
2025-04-15 01:40:42.974677 I | op-k8sutil: removing deployment csi-nfsplugin-provisioner if it exists
2025-04-15 01:40:43.036162 E | clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
2025-04-15 01:40:43.105197 E | clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
2025-04-15 01:40:43.171192 I | ceph-csi: successfully removed CSI NFS driver
2025-04-15 01:40:43.271017 E | clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
2025-04-15 01:40:43.327818 E | clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
2025-04-15 01:40:43.577714 I | ceph-spec: detected ceph image version: "18.2.4-0 reef"
2025-04-15 01:40:43.577731 I | ceph-cluster-controller: validating ceph version from provided image
2025-04-15 01:40:43.646784 E | clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
2025-04-15 01:40:43.702152 E | clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
2025-04-15 01:40:43.768609 I | ceph-cluster-controller: cluster "rook-ceph": version "18.2.4-0 reef" detected for image "quay.io/ceph/ceph:v18.2.4"
2025-04-15 01:40:43.796647 E | ceph-spec: failed to update cluster condition to {Type:Progressing Status:True Reason:ClusterProgressing Message:Configuring the Ceph cluster LastHeartbeatTime:2025-04-15 01:40:43.792129791 +0000 UTC m=+3.916158960 LastTransitionTime:2025-04-15 01:40:43.792129743 +0000 UTC m=+3.916158913}. failed to update object "rook-ceph/rook-ceph" status: Operation cannot be fulfilled on cephclusters.ceph.rook.io "rook-ceph": the object has been modified; please apply your changes to the latest version and try again
2025-04-15 01:40:43.981641 I | op-mon: start running mons
2025-04-15 01:40:44.206764 I | ceph-spec: creating mon secrets for a new cluster
2025-04-15 01:40:44.340703 E | clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
2025-04-15 01:40:44.409070 E | clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
2025-04-15 01:40:45.169303 I | op-mon: existing maxMonID not found or failed to load. configmaps "rook-ceph-mon-endpoints" not found
2025-04-15 01:40:45.372825 I | op-mon: saved mon endpoints to config map map[csi-cluster-config-json:[{"clusterID":"rook-ceph","monitors":[],"cephFS":{"netNamespaceFilePath":"","subvolumeGroup":"","radosNamespace":"","kernelMountOptions":"","fuseMountOptions":""},"rbd":{"netNamespaceFilePath":"","radosNamespace":"","mirrorDaemonCount":0},"nfs":{"netNamespaceFilePath":""},"readAffinity":{"enabled":false,"crushLocationLabels":null},"namespace":""}] data: mapping:{"node":{}} maxMonId:-1 outOfQuorum:]
2025-04-15 01:40:45.674847 E | clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
2025-04-15 01:40:45.738534 E | clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
2025-04-15 01:40:46.168853 I | cephclient: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2025-04-15 01:40:46.168971 I | cephclient: generated admin config in /var/lib/rook/rook-ceph
2025-04-15 01:40:47.770513 I | op-mon: targeting the mon count 1
2025-04-15 01:40:47.784402 I | op-mon: created canary deployment rook-ceph-mon-a-canary
2025-04-15 01:40:48.169822 I | op-mon: canary monitor deployment rook-ceph-mon-a-canary scheduled to orthoceras
2025-04-15 01:40:48.169839 I | op-mon: mon a assigned to node orthoceras
2025-04-15 01:40:48.179354 I | op-mon: cleaning up canary monitor deployment "rook-ceph-mon-a-canary"
2025-04-15 01:40:48.192468 I | op-mon: creating mon a
2025-04-15 01:40:48.310074 E | clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
2025-04-15 01:40:48.362651 E | clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
2025-04-15 01:40:48.381941 I | op-mon: mon "a" cluster IP is 10.109.157.68
2025-04-15 01:40:48.972887 I | op-mon: monitor endpoints changed, updating the bootstrap peer token
2025-04-15 01:40:48.972915 I | op-mon: saved mon endpoints to config map map[csi-cluster-config-json:[{"clusterID":"rook-ceph","monitors":["10.109.157.68:6789"],"cephFS":{"netNamespaceFilePath":"","subvolumeGroup":"","radosNamespace":"","kernelMountOptions":"","fuseMountOptions":""},"rbd":{"netNamespaceFilePath":"","radosNamespace":"","mirrorDaemonCount":0},"nfs":{"netNamespaceFilePath":""},"readAffinity":{"enabled":false,"crushLocationLabels":null},"namespace":""}] data:a=10.109.157.68:6789 mapping:{"node":{"a":{"Name":"orthoceras","Hostname":"orthoceras","Address":"192.168.30.84"}}} maxMonId:-1 outOfQuorum:]
2025-04-15 01:40:48.972976 I | op-mon: monitor endpoints changed, updating the bootstrap peer token
2025-04-15 01:40:49.568825 I | cephclient: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2025-04-15 01:40:49.568996 I | cephclient: generated admin config in /var/lib/rook/rook-ceph
2025-04-15 01:40:49.978010 I | op-mon: 0 of 1 expected mons are ready. creating or updating deployments without checking quorum in attempt to achieve a healthy mon cluster
2025-04-15 01:40:50.168547 I | op-mon: updating maxMonID from -1 to 0
2025-04-15 01:40:50.969236 I | op-mon: saved mon endpoints to config map map[csi-cluster-config-json:[{"clusterID":"rook-ceph","monitors":["10.109.157.68:6789"],"cephFS":{"netNamespaceFilePath":"","subvolumeGroup":"","radosNamespace":"","kernelMountOptions":"","fuseMountOptions":""},"rbd":{"netNamespaceFilePath":"","radosNamespace":"","mirrorDaemonCount":0},"nfs":{"netNamespaceFilePath":""},"readAffinity":{"enabled":false,"crushLocationLabels":null},"namespace":""}] data:a=10.109.157.68:6789 mapping:{"node":{"a":{"Name":"orthoceras","Hostname":"orthoceras","Address":"192.168.30.84"}}} maxMonId:0 outOfQuorum:]
2025-04-15 01:40:50.969254 I | op-mon: waiting for mon quorum with [a]
2025-04-15 01:40:51.169178 I | op-mon: mon a is not yet running
2025-04-15 01:40:51.169194 I | op-mon: mons running: []
2025-04-15 01:40:52.383002 I | ceph-spec: parsing mon endpoints: a=10.109.157.68:6789
2025-04-15 01:40:52.383059 I | op-bucket-prov: ceph bucket provisioner launched watching for provisioner "rook-ceph.ceph.rook.io/bucket"
2025-04-15 01:40:52.383335 I | op-bucket-prov: successfully reconciled bucket provisioner
I0415 01:40:52.383393       1 manager.go:135] "msg"="starting provisioner" "logger"="objectbucket.io/provisioner-manager" "name"="rook-ceph.ceph.rook.io/bucket"
2025-04-15 01:40:53.189962 I | ceph-spec: parsing mon endpoints: a=10.109.157.68:6789
2025-04-15 01:40:53.506699 I | ceph-csi: successfully started CSI CephFS driver
2025-04-15 01:40:53.510356 I | ceph-csi: CSIDriver object updated for driver "rook-ceph.cephfs.csi.ceph.com"
2025-04-15 01:40:53.510377 I | op-k8sutil: removing daemonset csi-rbdplugin if it exists
2025-04-15 01:40:53.518921 I | op-k8sutil: removing deployment csi-rbdplugin-provisioner if it exists
2025-04-15 01:40:53.569821 I | ceph-csi: successfully removed CSI Ceph RBD driver
2025-04-15 01:40:53.569837 I | op-k8sutil: removing daemonset csi-nfsplugin if it exists
2025-04-15 01:40:53.571051 I | op-k8sutil: removing deployment csi-nfsplugin-provisioner if it exists
2025-04-15 01:40:53.770797 I | ceph-csi: successfully removed CSI NFS driver
2025-04-15 01:41:07.502712 E | clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
2025-04-15 01:41:10.711442 I | clusterdisruption-controller: OSDs are up and PGs are clean. PG status: "cluster has no PGs"
2025-04-15 01:41:10.711461 I | clusterdisruption-controller: `maxUnavailable` for the main OSD PDB is set to 1
2025-04-15 01:41:10.711495 I | clusterdisruption-controller: all PGs are active+clean. Restoring default OSD pdb settings
2025-04-15 01:41:10.711498 I | clusterdisruption-controller: creating the default pdb "rook-ceph-osd" with maxUnavailable=1 for all osd
2025-04-15 01:41:10.818944 I | clusterdisruption-controller: reconciling osd pdb controller
2025-04-15 01:41:11.018211 I | clusterdisruption-controller: OSDs are up and PGs are clean. PG status: "cluster has no PGs"
2025-04-15 01:41:11.018229 I | clusterdisruption-controller: `maxUnavailable` for the main OSD PDB is set to 1
2025-04-15 01:41:11.126000 I | clusterdisruption-controller: reconciling osd pdb controller
2025-04-15 01:41:11.223089 I | op-mon: mons running: [a]
2025-04-15 01:41:11.324306 I | op-mon: Monitors in quorum: [a]
2025-04-15 01:41:11.324323 I | op-mon: mons created: 1
2025-04-15 01:41:11.421280 I | op-mon: waiting for mon quorum with [a]
2025-04-15 01:41:11.423634 I | op-mon: mons running: [a]
2025-04-15 01:41:11.537300 I | op-mon: Monitors in quorum: [a]
2025-04-15 01:41:11.537554 I | op-config: applying ceph settings:
[global]
mon cluster log file    =
mon allow pool size one = true
mon allow pool delete   = true
2025-04-15 01:41:11.649383 I | op-config: successfully applied settings to the mon configuration database
2025-04-15 01:41:11.649611 I | op-config: applying ceph settings:
[global]
log to file = true
2025-04-15 01:41:11.768587 I | op-config: successfully applied settings to the mon configuration database
2025-04-15 01:41:11.768650 I | op-config: deleting "global" "log file" option from the mon configuration database
2025-04-15 01:41:11.867116 I | op-config: successfully deleted "log file" option from the mon configuration database
2025-04-15 01:41:11.867136 I | ceph-spec: not applying network settings for cluster "rook-ceph" ceph networks
2025-04-15 01:41:11.867152 I | cephclient: getting or creating ceph auth key "client.csi-rbd-provisioner"
2025-04-15 01:41:11.987692 I | cephclient: getting or creating ceph auth key "client.csi-rbd-node"
2025-04-15 01:41:12.120555 I | cephclient: getting or creating ceph auth key "client.csi-cephfs-provisioner"
2025-04-15 01:41:12.240553 I | cephclient: getting or creating ceph auth key "client.csi-cephfs-node"
2025-04-15 01:41:12.406573 I | ceph-csi: created kubernetes csi secrets for cluster "rook-ceph"
2025-04-15 01:41:12.406596 I | cephclient: getting or creating ceph auth key "client.crash"
2025-04-15 01:41:12.559592 I | ceph-nodedaemon-controller: created kubernetes crash collector secret for cluster "rook-ceph"
2025-04-15 01:41:12.559608 I | cephclient: getting or creating ceph auth key "client.ceph-exporter"
2025-04-15 01:41:12.786573 I | ceph-nodedaemon-controller: created kubernetes exporter secret for cluster "rook-ceph"
2025-04-15 01:41:12.786604 I | op-config: deleting "global" "rbd_default_map_options" option from the mon configuration database
2025-04-15 01:41:12.905154 I | op-config: successfully deleted "rbd_default_map_options" option from the mon configuration database
2025-04-15 01:41:12.905173 I | op-config: deleting "global" "ms_cluster_mode" option from the mon configuration database
2025-04-15 01:41:13.008163 I | op-config: successfully deleted "ms_cluster_mode" option from the mon configuration database
2025-04-15 01:41:13.008182 I | op-config: deleting "global" "ms_service_mode" option from the mon configuration database
2025-04-15 01:41:13.112235 I | op-config: successfully deleted "ms_service_mode" option from the mon configuration database
2025-04-15 01:41:13.112255 I | op-config: deleting "global" "ms_client_mode" option from the mon configuration database
2025-04-15 01:41:13.212123 I | op-config: successfully deleted "ms_client_mode" option from the mon configuration database
2025-04-15 01:41:13.212141 I | op-config: deleting "global" "ms_osd_compress_mode" option from the mon configuration database
2025-04-15 01:41:13.313470 I | op-config: successfully deleted "ms_osd_compress_mode" option from the mon configuration database
2025-04-15 01:41:13.313495 I | cephclient: create rbd-mirror bootstrap peer token "client.rbd-mirror-peer"
2025-04-15 01:41:13.313498 I | cephclient: getting or creating ceph auth key "client.rbd-mirror-peer"
2025-04-15 01:41:13.434307 I | cephclient: successfully created rbd-mirror bootstrap peer token for cluster "rook-ceph"
2025-04-15 01:41:13.450712 I | op-mgr: start running mgr
2025-04-15 01:41:13.452988 I | cephclient: getting or creating ceph auth key "mgr.a"
2025-04-15 01:41:13.598572 I | op-config: setting option "auth_allow_insecure_global_id_reclaim" (user "mon") to the mon configuration database
2025-04-15 01:41:13.744285 I | op-config: successfully set option "auth_allow_insecure_global_id_reclaim" (user "mon") to the mon configuration database
2025-04-15 01:41:13.744306 I | op-config: insecure global ID is now disabled
2025-04-15 01:41:17.948437 I | clusterdisruption-controller: OSDs are up and PGs are clean. PG status: "cluster has no PGs"
2025-04-15 01:41:17.948455 I | clusterdisruption-controller: `maxUnavailable` for the main OSD PDB is set to 1
2025-04-15 01:41:18.058368 I | clusterdisruption-controller: reconciling osd pdb controller
2025-04-15 01:41:34.769440 I | op-k8sutil: finished waiting for updated deployment "rook-ceph-mgr-a"
2025-04-15 01:41:34.805331 I | op-mgr: successful modules: balancer
2025-04-15 01:41:34.819582 I | op-osd: start running osds in namespace "rook-ceph"
2025-04-15 01:41:34.819601 I | op-osd: wait timeout for healthy OSDs during upgrade or restart is "10m0s"
2025-04-15 01:41:34.873733 I | op-osd: start provisioning the OSDs on PVCs, if needed
2025-04-15 01:41:34.876778 I | op-osd: no storageClassDeviceSets defined to configure OSDs on PVCs
2025-04-15 01:41:34.876796 I | op-osd: start provisioning the OSDs on nodes, if needed
2025-04-15 01:41:34.880440 I | op-osd: 1 of the 1 storage nodes are valid
2025-04-15 01:41:34.899239 I | op-osd: started OSD provisioning job for node "orthoceras"
2025-04-15 01:41:34.902031 I | op-osd: OSD orchestration status for node orthoceras is "starting"
2025-04-15 01:41:35.137287 I | op-mgr: successful modules: prometheus
2025-04-15 01:41:36.185496 I | op-mgr: successful modules: mgr module(s) from the spec
2025-04-15 01:41:36.455905 I | op-osd: OSD orchestration status for node orthoceras is "orchestrating"
2025-04-15 01:41:40.136119 I | op-mgr: the dashboard secret was already generated
2025-04-15 01:41:40.136139 I | op-mgr: setting ceph dashboard "admin" login creds
2025-04-15 01:41:41.251253 I | clusterdisruption-controller: OSDs are up and PGs are clean. PG status: "cluster has no PGs"
2025-04-15 01:41:41.251270 I | clusterdisruption-controller: `maxUnavailable` for the main OSD PDB is set to 1
2025-04-15 01:41:41.453326 I | clusterdisruption-controller: reconciling osd pdb controller
2025-04-15 01:41:42.913431 I | op-mgr: successful modules: orchestrator modules
2025-04-15 01:41:43.460816 I | op-mgr: successfully set ceph dashboard creds
2025-04-15 01:41:43.647182 I | op-config: setting option "mgr/dashboard/url_prefix" (user "mgr") to the mon configuration database
2025-04-15 01:41:43.850836 I | op-config: successfully set option "mgr/dashboard/url_prefix" (user "mgr") to the mon configuration database
2025-04-15 01:41:44.057757 I | op-config: setting option "mgr/dashboard/ssl" (user "mgr") to the mon configuration database
2025-04-15 01:41:44.260237 I | op-config: successfully set option "mgr/dashboard/ssl" (user "mgr") to the mon configuration database
2025-04-15 01:41:44.640418 I | op-config: setting option "mgr/dashboard/PROMETHEUS_API_SSL_VERIFY" (user "mgr") to the mon configuration database
2025-04-15 01:41:44.847944 I | op-config: successfully set option "mgr/dashboard/PROMETHEUS_API_SSL_VERIFY" (user "mgr") to the mon configuration database
2025-04-15 01:41:45.034523 I | op-config: setting option "mgr/dashboard/server_port" (user "mgr") to the mon configuration database
2025-04-15 01:41:45.235777 I | op-config: successfully set option "mgr/dashboard/server_port" (user "mgr") to the mon configuration database
2025-04-15 01:41:45.235800 I | op-config: deleting "mgr.a" "mgr/dashboard/url_prefix" option from the mon configuration database
2025-04-15 01:41:45.436383 I | op-config: successfully deleted "mgr/dashboard/url_prefix" option from the mon configuration database
2025-04-15 01:41:45.436402 I | op-config: deleting "mgr.a" "mgr/dashboard/ssl" option from the mon configuration database
2025-04-15 01:41:45.627812 I | op-config: successfully deleted "mgr/dashboard/ssl" option from the mon configuration database
2025-04-15 01:41:45.627830 I | op-config: deleting "mgr.a" "mgr/dashboard/PROMETHEUS_API_HOST" option from the mon configuration database
2025-04-15 01:41:45.824522 I | op-config: successfully deleted "mgr/dashboard/PROMETHEUS_API_HOST" option from the mon configuration database
2025-04-15 01:41:45.824543 I | op-config: deleting "mgr.a" "mgr/dashboard/PROMETHEUS_API_SSL_VERIFY" option from the mon configuration database
2025-04-15 01:41:46.015866 I | op-config: successfully deleted "mgr/dashboard/PROMETHEUS_API_SSL_VERIFY" option from the mon configuration database
2025-04-15 01:41:46.015885 I | op-config: deleting "mgr.a" "mgr/dashboard/server_port" option from the mon configuration database
2025-04-15 01:41:46.223818 I | op-config: successfully deleted "mgr/dashboard/server_port" option from the mon configuration database
2025-04-15 01:41:46.223837 I | op-config: deleting "mgr.a" "mgr/dashboard/ssl_server_port" option from the mon configuration database
2025-04-15 01:41:46.415211 I | op-config: successfully deleted "mgr/dashboard/ssl_server_port" option from the mon configuration database
2025-04-15 01:41:46.415227 I | op-mgr: All per-daemon mgr configuration has been deleted successfully.
2025-04-15 01:41:46.415230 I | op-mgr: dashboard config has changed. restarting the dashboard module
2025-04-15 01:41:46.415233 I | op-mgr: restarting the mgr module: dashboard
2025-04-15 01:41:48.482688 I | clusterdisruption-controller: OSDs are up and PGs are clean. PG status: "cluster has no PGs"
2025-04-15 01:41:48.482707 I | clusterdisruption-controller: `maxUnavailable` for the main OSD PDB is set to 1
2025-04-15 01:41:48.660447 I | op-mgr: successful modules: dashboard
2025-04-15 01:41:48.677055 I | clusterdisruption-controller: reconciling osd pdb controller
2025-04-15 01:41:49.669529 I | op-osd: OSD orchestration status for node orthoceras is "completed"
2025-04-15 01:41:49.669551 I | op-osd: creating OSD 2 on node "orthoceras"
2025-04-15 01:41:49.699439 I | op-osd: creating OSD 1 on node "orthoceras"
2025-04-15 01:41:49.724859 I | op-osd: creating OSD 0 on node "orthoceras"
2025-04-15 01:41:49.994156 W | clusterdisruption-controller: failed to get the node name for the OSD 2
2025-04-15 01:41:49.994173 W | clusterdisruption-controller: failed to get the node name for the OSD 1
2025-04-15 01:41:50.294913 I | clusterdisruption-controller: OSD(s) [2 1] are down but PGs are clean. PG Status: "cluster has no PGs"
2025-04-15 01:41:50.294935 I | clusterdisruption-controller: `maxUnavailable` for the main OSD PDB is set to 3
2025-04-15 01:41:50.540371 I | clusterdisruption-controller: reconciling osd pdb controller
2025-04-15 01:41:50.767152 W | clusterdisruption-controller: failed to get the node name for the OSD 2
2025-04-15 01:41:50.767170 W | clusterdisruption-controller: failed to get the node name for the OSD 0
2025-04-15 01:41:50.767174 W | clusterdisruption-controller: failed to get the node name for the OSD 1
2025-04-15 01:41:51.013619 I | clusterdisruption-controller: OSD(s) [2 0 1] are down but PGs are clean. PG Status: "cluster has no PGs"
2025-04-15 01:41:51.013636 I | clusterdisruption-controller: `maxUnavailable` for the main OSD PDB is set to 4
2025-04-15 01:41:51.255256 I | clusterdisruption-controller: reconciling osd pdb controller
2025-04-15 01:41:56.532465 I | op-osd: finished running OSDs in namespace "rook-ceph"
2025-04-15 01:41:56.532478 I | ceph-cluster-controller: done reconciling ceph cluster in namespace "rook-ceph"
2025-04-15 01:41:56.535970 E | ceph-spec: failed to update cluster condition to {Type:Ready Status:True Reason:ClusterCreated Message:Cluster created successfully LastHeartbeatTime:2025-04-15 01:41:56.532505826 +0000 UTC m=+76.656534988 LastTransitionTime:2025-04-15 01:41:56.532505774 +0000 UTC m=+76.656534938}. failed to update object "rook-ceph/rook-ceph" status: Operation cannot be fulfilled on cephclusters.ceph.rook.io "rook-ceph": the object has been modified; please apply your changes to the latest version and try again
2025-04-15 01:41:56.536045 I | ceph-cluster-controller: reporting cluster telemetry
2025-04-15 01:41:56.537301 I | ceph-cluster-controller: enabling ceph mon monitoring goroutine for cluster "rook-ceph"
2025-04-15 01:41:56.537312 I | op-osd: ceph osd status in namespace "rook-ceph" check interval "1m0s"
2025-04-15 01:41:56.537316 I | ceph-cluster-controller: enabling ceph osd monitoring goroutine for cluster "rook-ceph"
2025-04-15 01:41:56.537322 I | ceph-cluster-controller: ceph status check interval is 1m0s
2025-04-15 01:41:56.537326 I | ceph-cluster-controller: enabling ceph status monitoring goroutine for cluster "rook-ceph"
2025-04-15 01:41:59.891833 I | ceph-cluster-controller: reporting node telemetry
2025-04-15 01:42:02.484300 I | ceph-spec: parsing mon endpoints: a=10.109.157.68:6789
2025-04-15 01:42:02.484344 I | ceph-spec: detecting the ceph image version for image quay.io/ceph/ceph:v18.2.4...
2025-04-15 01:42:03.613607 I | ceph-spec: detected ceph image version: "18.2.4-0 reef"
2025-04-15 01:42:04.248545 I | ceph-object-controller: reconciling object store deployments
2025-04-15 01:42:04.264748 I | ceph-object-controller: ceph object store gateway service running at 10.99.200.133
2025-04-15 01:42:04.264779 I | ceph-object-controller: reconciling object store pools
2025-04-15 01:42:07.648987 I | cephclient: reconciling replicated pool ceph-objectstore.rgw.control succeeded
2025-04-15 01:42:07.649010 I | cephclient: setting pool property "pg_num_min" to "8" on pool "ceph-objectstore.rgw.control"
2025-04-15 01:42:11.762717 I | cephclient: reconciling replicated pool ceph-objectstore.rgw.meta succeeded
2025-04-15 01:42:11.762737 I | cephclient: setting pool property "pg_num_min" to "8" on pool "ceph-objectstore.rgw.meta"
2025-04-15 01:42:11.860469 I | clusterdisruption-controller: `maxUnavailable` for the main OSD PDB is set to 1
2025-04-15 01:42:12.078870 I | clusterdisruption-controller: successfully reconciled OSD PDB controller
2025-04-15 01:42:15.873083 I | cephclient: reconciling replicated pool ceph-objectstore.rgw.log succeeded
2025-04-15 01:42:15.873106 I | cephclient: setting pool property "pg_num_min" to "8" on pool "ceph-objectstore.rgw.log"
2025-04-15 01:42:19.101263 I | clusterdisruption-controller: `maxUnavailable` for the main OSD PDB is set to 1
2025-04-15 01:42:19.310224 I | clusterdisruption-controller: successfully reconciled OSD PDB controller
2025-04-15 01:42:20.044798 I | cephclient: reconciling replicated pool ceph-objectstore.rgw.buckets.index succeeded
2025-04-15 01:42:20.044822 I | cephclient: setting pool property "pg_num_min" to "8" on pool "ceph-objectstore.rgw.buckets.index"
2025-04-15 01:42:24.212311 I | cephclient: reconciling replicated pool ceph-objectstore.rgw.buckets.non-ec succeeded
2025-04-15 01:42:24.212333 I | cephclient: setting pool property "pg_num_min" to "8" on pool "ceph-objectstore.rgw.buckets.non-ec"
2025-04-15 01:42:28.399178 I | cephclient: reconciling replicated pool ceph-objectstore.rgw.otp succeeded
2025-04-15 01:42:28.399202 I | cephclient: setting pool property "pg_num_min" to "8" on pool "ceph-objectstore.rgw.otp"
2025-04-15 01:42:32.545640 I | cephclient: reconciling replicated pool .rgw.root succeeded
2025-04-15 01:42:32.545662 I | cephclient: setting pool property "pg_num_min" to "8" on pool ".rgw.root"
2025-04-15 01:42:36.661793 I | cephclient: setting pool property "allow_ec_overwrites" to "true" on pool "ceph-objectstore.rgw.buckets.data"
2025-04-15 01:42:38.770701 I | cephclient: creating EC pool ceph-objectstore.rgw.buckets.data succeeded
2025-04-15 01:42:38.770722 I | ceph-object-controller: configuring object store "ceph-objectstore"
2025-04-15 01:42:39.511659 I | ceph-object-controller: Object store "ceph-objectstore": realm=ceph-objectstore, zonegroup=ceph-objectstore, zone=ceph-objectstore
2025-04-15 01:42:39.667511 I | ceph-object-controller: committing changes to RGW configuration period for CephObjectStore "rook-ceph/ceph-objectstore"
2025-04-15 01:42:40.683795 I | ceph-object-controller: configuration for object-store ceph-objectstore is complete
2025-04-15 01:42:40.683814 I | ceph-object-controller: creating object store "ceph-objectstore" in namespace "rook-ceph"
2025-04-15 01:42:40.686016 I | cephclient: getting or creating ceph auth key "client.rgw.ceph.objectstore.a"
2025-04-15 01:42:40.923933 I | ceph-object-controller: setting rgw config flags
2025-04-15 01:42:40.924247 I | op-config: applying ceph settings:
[client.rgw.ceph.objectstore.a]
rgw_log_object_name_utc    = true
rgw_enable_usage_log       = true
rgw_zone                   = ceph-objectstore
rgw_zonegroup              = ceph-objectstore
rgw_enable_ops_log         = false
rgw_run_sync_thread        = true
rgw_log_nonexistent_bucket = true
2025-04-15 01:42:41.143893 I | op-config: successfully applied settings to the mon configuration database
2025-04-15 01:42:41.148835 I | ceph-object-controller: skipping reconcile since operator is still initializing
2025-04-15 01:42:51.156722 I | ceph-spec: parsing mon endpoints: a=10.109.157.68:6789
2025-04-15 01:42:51.156760 I | ceph-spec: detecting the ceph image version for image quay.io/ceph/ceph:v18.2.4...
2025-04-15 01:42:52.703708 I | ceph-spec: detected ceph image version: "18.2.4-0 reef"
2025-04-15 01:42:53.314820 I | ceph-object-controller: reconciling object store deployments
2025-04-15 01:42:53.349160 I | ceph-object-controller: ceph object store gateway service running at 10.99.200.133
2025-04-15 01:42:53.349182 I | ceph-object-controller: reconciling object store pools
2025-04-15 01:42:53.939510 I | cephclient: application "rgw" is already set on pool "ceph-objectstore.rgw.control"
2025-04-15 01:42:53.939535 I | cephclient: reconciling replicated pool ceph-objectstore.rgw.control succeeded
2025-04-15 01:42:53.939543 I | cephclient: setting pool property "pg_num_min" to "8" on pool "ceph-objectstore.rgw.control"
2025-04-15 01:42:55.198655 I | cephclient: application "rgw" is already set on pool "ceph-objectstore.rgw.meta"
2025-04-15 01:42:55.198673 I | cephclient: reconciling replicated pool ceph-objectstore.rgw.meta succeeded
2025-04-15 01:42:55.198678 I | cephclient: setting pool property "pg_num_min" to "8" on pool "ceph-objectstore.rgw.meta"
2025-04-15 01:42:56.210184 I | cephclient: application "rgw" is already set on pool "ceph-objectstore.rgw.log"
2025-04-15 01:42:56.210204 I | cephclient: reconciling replicated pool ceph-objectstore.rgw.log succeeded
2025-04-15 01:42:56.210210 I | cephclient: setting pool property "pg_num_min" to "8" on pool "ceph-objectstore.rgw.log"
2025-04-15 01:42:57.266694 I | cephclient: application "rgw" is already set on pool "ceph-objectstore.rgw.buckets.index"
2025-04-15 01:42:57.266711 I | cephclient: reconciling replicated pool ceph-objectstore.rgw.buckets.index succeeded
2025-04-15 01:42:57.266717 I | cephclient: setting pool property "pg_num_min" to "8" on pool "ceph-objectstore.rgw.buckets.index"
2025-04-15 01:42:58.293849 I | cephclient: application "rgw" is already set on pool "ceph-objectstore.rgw.buckets.non-ec"
2025-04-15 01:42:58.293868 I | cephclient: reconciling replicated pool ceph-objectstore.rgw.buckets.non-ec succeeded
2025-04-15 01:42:58.293875 I | cephclient: setting pool property "pg_num_min" to "8" on pool "ceph-objectstore.rgw.buckets.non-ec"
2025-04-15 01:42:59.373361 I | cephclient: application "rgw" is already set on pool "ceph-objectstore.rgw.otp"
2025-04-15 01:42:59.373378 I | cephclient: reconciling replicated pool ceph-objectstore.rgw.otp succeeded
2025-04-15 01:42:59.373384 I | cephclient: setting pool property "pg_num_min" to "8" on pool "ceph-objectstore.rgw.otp"
2025-04-15 01:43:00.411580 I | cephclient: application "rgw" is already set on pool ".rgw.root"
2025-04-15 01:43:00.411596 I | cephclient: reconciling replicated pool .rgw.root succeeded
2025-04-15 01:43:00.411602 I | cephclient: setting pool property "pg_num_min" to "8" on pool ".rgw.root"
2025-04-15 01:43:01.935573 I | cephclient: setting pool property "allow_ec_overwrites" to "true" on pool "ceph-objectstore.rgw.buckets.data"
2025-04-15 01:43:03.031711 I | cephclient: application "rgw" is already set on pool "ceph-objectstore.rgw.buckets.data"
2025-04-15 01:43:03.031726 I | cephclient: creating EC pool ceph-objectstore.rgw.buckets.data succeeded
2025-04-15 01:43:03.031730 I | ceph-object-controller: configuring object store "ceph-objectstore"
2025-04-15 01:43:03.155123 I | ceph-object-controller: Object store "ceph-objectstore": realm=ceph-objectstore, zonegroup=ceph-objectstore, zone=ceph-objectstore
2025-04-15 01:43:03.278048 I | ceph-object-controller: there are no changes to commit for RGW configuration period for CephObjectStore "rook-ceph/ceph-objectstore"
2025-04-15 01:43:03.278063 I | ceph-object-controller: configuration for object-store ceph-objectstore is complete
2025-04-15 01:43:03.278067 I | ceph-object-controller: creating object store "ceph-objectstore" in namespace "rook-ceph"
2025-04-15 01:43:03.280516 I | cephclient: getting or creating ceph auth key "client.rgw.ceph.objectstore.a"
2025-04-15 01:43:03.511225 I | ceph-object-controller: setting rgw config flags
2025-04-15 01:43:03.511463 I | op-config: applying ceph settings:
```

The rook [client.rgw.ceph.objectstore.a] then just repeat over and over and over

**Cluster Status to submit**:

```bash
bash-5.1$ ceph status 
  cluster:
    id:     150d208b-79be-42bf-8ba6-a5a98d7e7278
    health: HEALTH_OK
 
  services:
    mon: 1 daemons, quorum a (age 21m)
    mgr: a(active, since 30m)
    osd: 3 osds: 3 up (since 30m), 3 in (since 31m)
 
  data:
    pools:   9 pools, 89 pgs
    objects: 29 objects, 454 KiB
    usage:   109 MiB used, 30 GiB / 30 GiB avail
    pgs:     89 active+clean
 ```

**Environment**:
* OS (e.g. from /etc/os-release): Fedora 41
* Kernel (e.g. `uname -a`): Linux orthoceras 6.13.9-200.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Mar 29 01:29:31 UTC 2025 x86_64 GNU/Linux
* Cloud provider or hardware configuration: NA
* Rook version (use `rook version` inside of a Rook Pod): 1.16.6
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 18.2.4  e7ad5345525c7aa95470c26863873b581076945d) reef (stable)
(same thing happens for Ceph 19.2.2)

* Kubernetes version (use `kubectl version`): 1.32.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Minikube
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

### PR DESCRIPTION
**Pull request by travisn**
The object store controller was swallowing errors of the type not found, assuming a certain category of errors when ceph may still be initializing. But some of these errors could be user error and they need to troubleshoot the details of the error, so we need to log the specific error instead of swallowing it.

**Issue resolved by this Pull Request:**
Resolves #15713

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

File: pkg/operator/ceph/object/controller.go [hunk 1]
```diff
@@ -441,7 +441,9 @@ func (r *ReconcileCephObjectStore) reconcile(request reconcile.Request) (reconci
 	// CREATE/UPDATE
 	_, err = r.reconcileCreateObjectStore(cephObjectStore, request.NamespacedName, cephCluster.Spec)
 	if err != nil && kerrors.IsNotFound(err) {
-		logger.Info(opcontroller.OperatorNotInitializedMessage)
+		// A not found error may mean ceph is still initializing, but there might be some other error
+		// so we log the error and requeue
+		logger.Warningf("object store reconcile failed, ceph may still be initializing. %v", err)
```
Comment (BlaineEXE) [inline pkg/operator/ceph/object/controller.go:446]:
```suggestion
		logger.Warningf("object store %q reconcile failed, ceph may still be initializing. %v", namespacedName, err)
```

**Review by BlaineEXE — CHANGES_REQUESTED** [review]

File: pkg/operator/ceph/object/controller.go [hunk 2]
```diff
@@ -441,7 +441,9 @@ func (r *ReconcileCephObjectStore) reconcile(request reconcile.Request) (reconci
 	// CREATE/UPDATE
 	_, err = r.reconcileCreateObjectStore(cephObjectStore, request.NamespacedName, cephCluster.Spec)
 	if err != nil && kerrors.IsNotFound(err) {
-		logger.Info(opcontroller.OperatorNotInitializedMessage)
+		// A not found error may mean ceph is still initializing, but there might be some other error
+		// so we log the error and requeue
+		logger.Warningf("object store %q reconcile failed, ceph may still be initializing. %v", cephObjectStore.Name, err)
```
Comment (BlaineEXE) [inline pkg/operator/ceph/object/controller.go:446]: Namespaced name will help distinguish between stores if there are multiple clusters with same-named stores.

```suggestion
		logger.Warningf("object store %q reconcile failed, ceph may still be initializing. %v", cephObjectStore.Namespace+"/"+cephObjectStore.Name, err)
```

**Review by BlaineEXE — CHANGES_REQUESTED** [review]

**Review by BlaineEXE — APPROVED** [review]
