### PR TITLE
ceph: Separate placement for osd prepare jobs from osd daemons

### LINKED ISSUE #5586: OSDs and OSD Prepare pods on PVCs need independent settings for placement and resource limits
For some reason, two OSDs end up in the same node.

I have read the discussion here https://github.com/rook/rook/issues/4582 but I am still missing something.

My guess is that there is some issue with availability of resources between osd and osd-prepare, as both use the same resources requests.

I am specifying this on OSD, on 4 core nodes: (once any of these pods is running we only have 1.9 available cpu)
```
      resources:
        limits:
          cpu: "2000m"
          memory: "4Gi"
        requests:
          cpu: "2000m"
          memory: "4Gi"
```

**Expected behavior:**
Each OSD should be deployed on a different node.

**How to reproduce it (minimal and precise):**
You need a 3.99 cpu server (or one with less resources available than double the resources that you are requesting for OSDs)

```
  storage:
    storageClassDeviceSets:
    - name: set1
      count: 3
      portable: false
      tuneSlowDeviceClass: true
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role
                operator: In
                values:
                - ceph-node
        tolerations:
        - key: ceph-node
          operator: Exists
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd-prepare
              topologyKey: kubernetes.io/hostname
        topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - rook-ceph-osd
              - rook-ceph-osd-prepare
      resources:
        limits:
          cpu: "2000m"
          memory: "4Gi"
        requests:
          cpu: "2000m"
          memory: "4Gi"
```

**What doesn't work**
Removing  rook-ceph-osd-prepare from affinity rules does not work.
Changing preferred to required on affinity rules does not work.

**Workaround**
As soon as you lower or remove the resources requests, the cluster is deployed as intended.

### PR DESCRIPTION
**Pull request by travisn**
**Description of your changes:**
The osd prepare jobs and osd daemons may have different placement requirements. In particular, the topology spread constraints or pod anti-affinity should only work on either the prepare job or osd daemon, but does not work effectively on both types at the same time. Therefore, we split out the osd prepare placement to be separate from the osd daemon placement. 

If the osd prepare placement is not set the operator will fall back to the osd daemon placement for backward compatibility.

This only applies to OSDs created by portable storageClassDeviceSets. Non-portable OSDs will be tied to the host on which the OSD prepare job runs.

**Which issue is resolved by this Pull Request:**
Resolves: #5932 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

File: pkg/operator/ceph/cluster/osd/deviceSet.go [hunk 1]
```diff
@@ -75,6 +75,7 @@ func (c *Cluster) prepareStorageClassDeviceSets(config *provisionConfig) []rookv
 				Name:                storageClassDeviceSet.Name,
 				Resources:           storageClassDeviceSet.Resources,
 				Placement:           storageClassDeviceSet.Placement,
+				PreparePlacement:    storageClassDeviceSet.PreparePlacement,
```
Comment (leseb) [inline pkg/operator/ceph/cluster/osd/deviceSet.go:78]: Can we replace `storageClassDeviceSet.PreparePlacement` by `storageClassDeviceSet.Prepare` here instead if `storageClassDeviceSet.PreparePlacement` is nil?

Comment (travisn) [reply pkg/operator/ceph/cluster/osd/deviceSet.go:78]: I considered that, but thought it was better to preserve the spec settings as much as possible, and leave the fallback logic in the helpers when the placement is evaluated.

**Review by leseb — APPROVED** [review]
