### PR TITLE
api: recreate mon endpoint watcher when the result channel is closed

### LINKED ISSUE #1195: rook-api pod is using a high amount of CPU
We've been hearing reports recently of the rook-api pod using a lot of CPU.  This sounds like a recent regression, but i don't know the cause.  Will update this ticket when we have more information, but it definitely sounds like an issue that people are running into.

### PR DESCRIPTION
**Pull request by jbw976**
Fixes #1195

### CODE REVIEW

File: pkg/api/daemon.go [hunk 1]
```diff
@@ -65,26 +65,44 @@ func Run(context *clusterd.Context, c *Config) error {
...
+		opts := metav1.ListOptions{
+			FieldSelector: fields.OneTermEqualSelector(api.ObjectNameField, monop.EndpointConfigMapName).String(),
+		}
+		w, err := context.Clientset.Core().ConfigMaps(c.namespace).Watch(opts)
+		if err != nil {
+			logger.Errorf("WatchMonConfig watch init error: %+v", err)
+			return
+		}
+
+		defer func() {
```
Comment (travisn) [inline pkg/api/daemon.go]: does it matter if you call `Stop()` twice? If not, seems simpler to have `defer w.Stop()`

File: pkg/api/daemon.go [hunk 2]
```diff
@@ -65,26 +65,44 @@ func Run(context *clusterd.Context, c *Config) error {
...
+				w.Stop()
+			}
+		}()
+
+		for {
+			e, ok := <-w.ResultChan()
+			if !ok {
+				logger.Warning("WatchMonConfig result channel closed, restarting watch.")
+				w.Stop()
+				w = nil
```
Comment (travisn) [inline pkg/api/daemon.go]: if the above comment applies, you wouldn't set `w = nil` here

File: pkg/api/daemon.go (hunk 1 above)
Comment (jbw976) [reply pkg/api/daemon.go]: if i have traced the code correctly, it appears that calling `Stop()` more than once is safe, because of the locking/checking they do underneath: https://github.com/kubernetes/apimachinery/blob/728b986edb9bd4bb8a022a8cc13573a97ecc2239/pkg/watch/streamwatcher.go#L70

File: pkg/api/daemon.go [hunk 3]
```diff
@@ -65,26 +65,44 @@ func Run(context *clusterd.Context, c *Config) error {
...
-		if e.Type == watch.Modified {
-			// "unmarshal" object into configmap and set new endpoints
-			monEndpoints := e.Object.(*v1.ConfigMap)
-			c.clusterInfo.Monitors = mon.ParseMonEndpoints(monEndpoints.Data[monop.EndpointDataKey])
-
-			// write the latest config to the config dir
-			if err := mon.GenerateAdminConnectionConfig(context, c.clusterInfo); err != nil {
-				logger.Errorf("failed to write connection config. %+v", err)
-				return
+		// watch for changes only to the monitor endpoints config map
```
Comment (kokhang) [inline pkg/api/daemon.go]: why not have a conditional to check whether the watch object is invalid and then recreate one? Something like this

```
e, ok := <-w.ResultChan()
if !ok {
    if w != nil {
        w.Stop()
    }
    // create the watch again
    ...
    continue // start loop again
}
```

Comment (jbw976) [reply pkg/api/daemon.go]: with that approach, we'd either need to refactor the creation of the watcher into a new function, so it can be called at the beginning of this function and when the result channel is closed, or just duplicate the watcher creation in the 2 places.  I don't see either as a strong improvement over the current implementation, do you?

Comment (kokhang) [reply pkg/api/daemon.go]: i thought it would make it a bit more readable. You wouldnt have nested for loops and no defer function. But you would have to extract the creation of the watch object into a separate function to not duplicate it like you said.

Im ok with this.

Comment (kokhang) [reply pkg/api/daemon.go]: but it wouldnt be too much since you would only need to call the creation of the watch object, which is:
```w, err := context.Clientset.Core().ConfigMaps(c.namespace).Watch(opts)```

Comment (jbw976) [reply pkg/api/daemon.go]: you have to handle the potential error from that watcher creation in 2 places.  you'd also still need the `defer` function in case you are returning from the entire function if `mon.GenerateAdminConnectionConfig` fails.  IMHO, i don't think this change is worth the perceived readability improvement.

Comment (kokhang) [reply pkg/api/daemon.go]: Yes. You still would need something like this at the beginning:
`defer w.Stop()` 
OK LGTM

**Comment by jbw976** [comment]
@travisn your suggestion to not nil out the watcher (because it's safe to call Stop more than once) has been incorporated and tested.  PTAL
