### PR TITLE
ceph: update erasure coded profile command

### LINKED ISSUE #2016: Error on recreating Erasure Coded Pool with different Settings
* Bug Report
When you create an erasure coded pool, delete it, adjust your settings and recreate it rook fails, because rook didn't delete the erasure code profile:

```
2018-08-10 13:13:01.708698 I | exec: Error EPERM: will not override erasure code profile erasurepool_ecprofile because the existing profile {crush-device-class=,crush-failure-domain=host,crush-root=default,jerasure-per-chunk-alignment=false,k=4,m=2,plugin=jerasure,technique=reed_sol_van,w=8} is different from the proposed profile {crush-device-class=,crush-failure-domain=host,crush-root=default,jerasure-per-chunk-alignment=false,k=8,m=2,plugin=jerasure,technique=reed_sol_van,w=8}
2018-08-10 13:13:01.708826 E | op-pool: failed to create pool erasurepool. failed to create pool erasurepool. failed to create erasure code profile for pool 'erasurepool': failed to set ec-profile. exit status 1
```

**Deviation from expected behavior:**

Rook should delete the erasure code profile or use unique names.

**How to reproduce it (minimal and precise):**

- Create erasure coded pool:

```
apiVersion: ceph.rook.io/v1beta1
kind: Pool
metadata:
  name: erasurepool 
  namespace: rook-ceph
spec:
  failureDomain: osd
  crushRoot: default
  erasureCoded:
    dataChunks: 4
    codingChunks: 2
``` 

- Delete erasure coded pool
- Adjust settings and recreate erasure coded pool:

```
apiVersion: ceph.rook.io/v1beta1
kind: Pool
metadata:
  name: erasurepool 
  namespace: rook-ceph
spec:
  failureDomain: osd
  crushRoot: default
  erasureCoded:
    dataChunks: 8
    codingChunks: 4
```

**Environment**:
* OS (e.g. from /etc/os-release): CentOS-7
* Kernel (e.g. `uname -a`): Linux deploy 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Rook version (use `rook version` inside of a Rook Pod):  v0.8.0-67.gd331a3e
* Kubernetes version (use `kubectl version`): 1.11.2

### PR DESCRIPTION
**Pull request by subhamkrai**
currently, recreating erasure codedpPool with
different Settings show error and creation
failed.

**Description of your changes:**

Adding `--force` to the erasure coded profile
command works file with above condition.

Signed-off-by: subhamkrai <srai@redhat.com>

**Which issue is resolved by this Pull Request:**
Resolves #2016 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by subhamkrai** [comment]
Do we want to backport this to 1.5.x?

File: pkg/daemon/ceph/client/erasure-code-profile.go [hunk 1]
```diff
@@ -89,7 +89,7 @@ func CreateErasureCodeProfile(context *clusterd.Context, clusterInfo *ClusterInf
 		profilePairs = append(profilePairs, fmt.Sprintf("crush-device-class=%s", pool.DeviceClass))
 	}
 
-	args := []string{"osd", "erasure-code-profile", "set", profileName}
+	args := []string{"osd", "erasure-code-profile", "set", profileName, "--force"}
```
Comment (travisn) [inline pkg/daemon/ceph/client/erasure-code-profile.go:92]: Instead of force creating the profile, can we delete the EC profile during removal of the pool? Then it would be more clean for the uninstall case.

**Review by travisn — CHANGES_REQUESTED** [review]

File: pkg/daemon/ceph/client/erasure-code-profile.go (hunk 1 above)
Comment (subhamkrai) [reply pkg/daemon/ceph/client/erasure-code-profile.go:92]: I don't see `--force` arg in the removal command. `--force` is passed while creating only [here](https://docs.ceph.com/en/latest/rados/operations/erasure-code-profile/#osd-erasure-code-profile-set).

Comment (travisn) [reply pkg/daemon/ceph/client/erasure-code-profile.go:92]: Instead of passing the `--force` flag during creation, I am asking about a different approach. The root issue is that the EC profile is not deleted when the pool is deleted. If we deleted the EC profile during pool deletion, then the uninstall would be properly cleaned up and there would be no need for the `--force` flag during pool creation.

Comment (subhamkrai) [reply pkg/daemon/ceph/client/erasure-code-profile.go:92]: I see the profile is deleted while pool creation here, https://github.com/rook/rook/blob/40e66332801d8b7165427ec0dd7caec1d4331628/pkg/operator/ceph/object/objectstore.go#L604-L612

Comment (travisn) [reply pkg/daemon/ceph/client/erasure-code-profile.go:92]: Ok great. So does the original issue #2016 repro anymore? Maybe it's already fixed. If force is needed during new pool creation, seems like something wasn't cleaned up during pool removal.

Comment (subhamkrai) [reply pkg/daemon/ceph/client/erasure-code-profile.go:92]: I did test my changes and it was working...I tried both with YAML and cli so I believe it's working.
My first thought was the same to see if we are removing the profile :)

Comment (travisn) [reply pkg/daemon/ceph/client/erasure-code-profile.go:92]: And without your changes it was failing? I'd like to understand what wasn't cleaned up during pool deletion.

Comment (subhamkrai) [reply pkg/daemon/ceph/client/erasure-code-profile.go:92]: Yes, it was failing with the same error mentioned in the issue...not sure what wasn't cleared because both pool and profile are getting deleted but we have to use `--force` when recreating with a different setting and in the Ceph docs also it was mentioned to use `--force`.

Comment (travisn) [reply pkg/daemon/ceph/client/erasure-code-profile.go:92]: Ok thanks for the confirmation that you see the pool and profile both cleaned up. Sounds good to go with `--force`. It also works for new pool creation, right? We just don't have an integration test for EC pools so wanted to double check.

Comment (subhamkrai) [reply pkg/daemon/ceph/client/erasure-code-profile.go:92]: okay...give me some time I'll paste log/output here.

Comment (subhamkrai) [reply pkg/daemon/ceph/client/erasure-code-profile.go:92]: created `pool-ec.yaml` 
``` erasureCoded:
    dataChunks: 2
    codingChunks: 1
```
```
2021-05-05 14:28:01.268197 I | cephclient: setting pool property "allow_ec_overwrites" to "true" on pool "ec-pool"
2021-05-05 14:28:02.294373 I | cephclient: setting pool property "compression_mode" to "none" on pool "ec-pool"
2021-05-05 14:28:04.287084 I | cephclient: creating EC pool ec-pool succeeded
2021-05-05 14:28:13.784876 I | op-mon: parsing mon endpoints: a=10.101.111.169:6789
```
deleting `pool-ec.yaml`
```
2021-05-05 14:28:13.784899 I | ceph-block-pool-controller: deleting pool "ec-pool"
2021-05-05 14:28:14.321419 I | cephclient: no images/snapshosts present in pool "ec-pool"
2021-05-05 14:28:14.321474 I | cephclient: purging pool "ec-pool" (id=2)
2021-05-05 14:28:16.312577 I | cephclient: purge completed for pool "ec-pool"
2021-05-05 14:28:16.872855 I | ceph-spec: removing finalizer "cephblockpool.ceph.rook.io" on "ec-pool"

creating `pool-ec.yaml` with
```
  erasureCoded:
    dataChunks: 4
    codingChunks: 2
```
```
2021-05-05 14:28:36.079002 I | ceph-spec: adding finalizer "cephblockpool.ceph.rook.io" on "ec-pool"
2021-05-05 14:28:36.086710 W | ceph-block-pool-controller: failed to set pool "ec-pool" status to "Progressing". failed to update object "ec-pool" status: Operation cannot be fulfilled on cephblockpools.ceph.rook.io "ec-pool": the object has been modified; please apply your changes to the latest version and try again
2021-05-05 14:28:36.092343 I | op-mon: parsing mon endpoints: a=10.101.111.169:6789
2021-05-05 14:28:36.383661 I | ceph-block-pool-controller: creating pool "ec-pool" in namespace "rook-ceph"
2021-05-05 14:28:39.364564 I | cephclient: setting pool property "allow_ec_overwrites" to "true" on pool "ec-pool"
2021-05-05 14:28:40.429747 I | cephclient: setting pool property "compression_mode" to "none" on pool "ec-pool"
2021-05-05 14:28:42.403420 I | cephclient: creating EC pool ec-pool succeeded
2021-05-05 14:28:43.238145 I | clusterdisruption-controller: all osds are up. last drained failure domain: "".  pg health: "cluster is not fully clean. PGs: [{StateName:unknown Count:32} {StateName:active+clean Count:1}]". waiting for PGs to be active+clean or PG health check to timeout
2021-05-05 14:28:52.037688 I | op-mon: parsing mon endpoints: a=10.101.111.169:6789
```
deleting `pool-ec.yaml`
```
2021-05-05 14:28:52.037774 I | ceph-block-pool-controller: deleting pool "ec-pool"
2021-05-05 14:28:52.368300 I | clusterdisruption-controller: all osds are up. last drained failure domain: "".  pg health: "cluster is not fully clean. PGs: [{StateName:active+undersized Count:32} {StateName:active+clean Count:1}]". waiting for PGs to be active+clean or PG health check to timeout
2021-05-05 14:28:52.621629 I | cephclient: no images/snapshosts present in pool "ec-pool"
2021-05-05 14:28:52.622781 I | cephclient: purging pool "ec-pool" (id=3)
2021-05-05 14:28:54.434969 I | cephclient: purge completed for pool "ec-pool"
2021-05-05 14:28:55.011856 I | ceph-spec: removing finalizer "cephblockpool.ceph.rook.io" on "ec-pool"
```

**Review by travisn — APPROVED** [review]
