### PR TITLE
operator: improve ProbeHandler error message

### LINKED ISSUE #9846: Startup probe failed: no valid command found; 10 closest matches
**Environment**:
* rook version

```
v1.8.6
```

* OS (e.g. from /etc/os-release):
```
root@node1:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
* Kernel (e.g. `uname -a`):
```
root@node1:~# uname -a
Linux node1 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
root@node1:~# 
```

* Kubernetes version (use `kubectl version`):
```
root@node1:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
root@node1:~# 

```

## what happend

one osd pod is down

```
root@node1:~# kubectl -n rook-ceph get pods
NAME                                              READY   STATUS      RESTARTS   AGE
csi-cephfsplugin-9s5tz                            3/3     Running     3          17h
csi-cephfsplugin-j88wj                            3/3     Running     3          17h
csi-cephfsplugin-jhqcz                            3/3     Running     4          17h
csi-cephfsplugin-provisioner-6f54f6c477-blcxw     6/6     Running     23         17h
csi-cephfsplugin-provisioner-6f54f6c477-g49tw     6/6     Running     20         17h
csi-rbdplugin-jjhmz                               3/3     Running     4          17h
csi-rbdplugin-nt6sn                               3/3     Running     3          17h
csi-rbdplugin-provisioner-6d765b47d5-hslsf        6/6     Running     18         17h
csi-rbdplugin-provisioner-6d765b47d5-vjwcp        6/6     Running     23         17h
csi-rbdplugin-zzm7m                               3/3     Running     3          17h
rook-ceph-crashcollector-node1-54b78567c5-fhj2p   1/1     Running     1          16h
rook-ceph-crashcollector-node2-69d4577554-dmwhw   1/1     Running     1          17h
rook-ceph-crashcollector-node3-f4758c5df-7wxgj    1/1     Running     1          17h
rook-ceph-mgr-a-b557c664-92bpn                    1/1     Running     17         17h
rook-ceph-mon-a-c4484c877-msrjn                   1/1     Running     6          17h
rook-ceph-mon-b-6468c84f59-b9rwx                  1/1     Running     27         17h
rook-ceph-mon-c-7966fdfc5b-6nqp2                  1/1     Running     3          17h
rook-ceph-operator-7b4f6fd594-fjhv7               1/1     Running     1          16h
rook-ceph-osd-0-7757bd7dd8-j64hm                  1/1     Running     3          16h
rook-ceph-osd-1-5f746cfbd4-c2psg                  1/1     Running     1          16h
rook-ceph-osd-2-554b745799-df64d                  0/1     Running     0          60s

```

the osd logs
```
QoS Class:                   BestEffort
Node-Selectors:              kubernetes.io/hostname=node1
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  7m13s                  default-scheduler  Successfully assigned rook-ceph/rook-ceph-osd-2-6548745b8c-2ztn2 to node1
  Normal   Pulled     7m7s                   kubelet            Container image "quay.io/ceph/ceph:v16.2.7" already present on machine
  Normal   Created    7m4s                   kubelet            Created container activate
  Normal   Started    7m3s                   kubelet            Started container activate
  Normal   Pulled     6m58s                  kubelet            Container image "quay.io/ceph/ceph:v16.2.7" already present on machine
  Normal   Created    6m56s                  kubelet            Created container chown-container-data-dir
  Normal   Started    6m55s                  kubelet            Started container chown-container-data-dir
  Normal   Killing    5m13s                  kubelet            Container osd failed startup probe, will be restarted
  Normal   Pulled     4m41s (x2 over 6m53s)  kubelet            Container image "quay.io/ceph/ceph:v16.2.7" already present on machine
  Normal   Created    4m40s (x2 over 6m52s)  kubelet            Created container osd
  Normal   Started    4m39s (x2 over 6m51s)  kubelet            Started container osd
  Warning  Unhealthy  4m22s (x2 over 5m52s)  kubelet            Startup probe failed:
  Warning  Unhealthy  2m3s (x16 over 6m33s)  kubelet            Startup probe failed: no valid command found; 10 closest matches:
0
1
2
abort
assert
bluefs debug_inject_read_zeros
bluefs files list
bluefs stats
bluestore bluefs device info [<alloc_size:int>]
config diff
admin_socket: invalid command
```
i delete this  `startupProbe` section and pod running success

```
root@node1:~# kubectl -n rook-ceph edit deployment.apps/rook-ceph-osd-2


        startupProbe:
          exec:
            command:
            - env
            - -i
            - sh
            - -c
            - ceph --admin-daemon /run/ceph/ceph-osd.2.asok status
          failureThreshold: 9
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1

```

### PR DESCRIPTION
**Pull request by motorailgun**
**Description of your changes:**

This commit implements more diagnostic error for unsccessful
Liveness- and Readiness-Probe of Pods.

Added codes are expected to catch failures of
`ceph status` and `ceph mon_status`, and report it.

**Which issue is resolved by this Pull Request:**
Resolves #9846,  #9852

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [x] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by travisn — COMMENTED** [review]
LGTM, @BlaineEXE could you also review?

File: pkg/operator/ceph/controller/spec.go [hunk 1]
```diff
@@ -570,12 +570,18 @@ func GenerateLivenessProbeExecDaemon(daemonType, daemonID string) *v1.Probe {
...
+				// We'd better ignore this message and give users more simple one.
+				// The workaround below is bit dirty; but it works.
+				// ref: https://github.com/rook/rook/issues/9846
 				Command: []string{
 					"env",
 					"-i",
 					"sh",
 					"-c",
-					fmt.Sprintf("ceph --admin-daemon %s %s", confDaemon.buildSocketPath(), confDaemon.buildAdminSocketCommand()),
+					fmt.Sprintf("ceph --admin-daemon %s %s 2>/dev/null; if [ \\$? -ne 0 ]; then echo %s; exit 1; fi",
```
Comment (BlaineEXE) [inline pkg/operator/ceph/controller/spec.go:583]: I am concerned that this will destroy any error message including potentially valid ones. This also destroys the original return code. 

```suggestion
					fmt.Sprintf("ceph --admin-daemon %s %s; rc=\\$?; if [ \\$rc -ne 0 ]; then echo %s; exit \\$rc; fi",
```

File: pkg/operator/ceph/controller/spec.go [hunk 2]
```diff
@@ -570,12 +570,18 @@ func GenerateLivenessProbeExecDaemon(daemonType, daemonID string) *v1.Probe {
...
+						confDaemon.buildSocketPath(), confDaemon.buildAdminSocketCommand(), "ceph daemon health check failed."),
```
Comment (BlaineEXE) [inline pkg/operator/ceph/controller/spec.go:584]: Also a small nit that Rook follows the convention that error messages don't end in periods.

```suggestion
						confDaemon.buildSocketPath(), confDaemon.buildAdminSocketCommand(), "ceph daemon health check failed"),
```

File: pkg/operator/ceph/controller/spec.go [hunk 3]
```diff
@@ -570,12 +570,18 @@ func GenerateLivenessProbeExecDaemon(daemonType, daemonID string) *v1.Probe {
 				//
 				// Example:
 				// env -i sh -c "ceph --admin-daemon /run/ceph/ceph-osd.0.asok status"
+				//
+				// Ceph gives pretty un-diagnostic error message when `ceph status` or `ceph mon_status` command fails.
+				// We'd better ignore this message and give users more simple one.
+				// The workaround below is bit dirty; but it works.
+				// ref: https://github.com/rook/rook/issues/9846
```
Comment (BlaineEXE) [inline pkg/operator/ceph/controller/spec.go:577]: If we are no longer ignoring the original message, we can modify the comment as well. 

```suggestion
				// Ceph gives un-diagnostic error message when `ceph status` or `ceph mon_status` command fails.
				// Add a clear message after Ceph's to help.
				// ref: https://github.com/rook/rook/issues/9846
```

**Review by BlaineEXE — CHANGES_REQUESTED** [review]
I have concerns about totally destroying the message (and to a lesser extent, return code) that Ceph reports. Doing so can also lead to cases where we can't accurately diagnose a failure. 

After briefly looking at Ceph's code, an example of a case where the returned text could be critical is a segfault followed by a stack trace that might help us direct a bug report to the Ceph project.

File: pkg/operator/ceph/controller/spec.go (hunk 1 above)
Comment (BlaineEXE) [reply pkg/operator/ceph/controller/spec.go:583]: We could get a little more fancy with this if it seems helpful to put "ceph daemon health check failed" before any returned text from Ceph. That would be something like this:

```sh
```suggestion
					fmt.Sprintf(`outp="\\$(ceph --admin-daemon %s %s 2>&1); rc=\\$?; if [ \\$? -ne 0 ]; then echo %s; echo "\\$oupt"; exit \\$rc; fi`,
```

Comment (motorailgun) [reply pkg/operator/ceph/controller/spec.go]: Fair point, thanks. Thought it's better to quote Ceph's output so changed it to do so (and also, fix of shell script's bugs).

**Review by satoru-takeuchi — APPROVED** [review]

**Comment by satoru-takeuchi** [comment]
I took this PR.

File: pkg/operator/ceph/controller/spec.go [hunk 4]
```diff
@@ -570,12 +570,24 @@ func GenerateLivenessProbeExecDaemon(daemonType, daemonID string) *v1.Probe {
...
-					fmt.Sprintf("ceph --admin-daemon %s %s", confDaemon.buildSocketPath(), confDaemon.buildAdminSocketCommand()),
+					fmt.Sprintf(`outp="$(ceph --admin-daemon %s %s 2>&1)";`+
+						`rc=$?;`+
+						`if [ $rc -ne 0 ]; `+
+						`then echo %s;`+
+						`echo "$outp" | sed -e 's/^/> /g';`+
+						`exit $rc;`+
+						`fi`,
+						confDaemon.buildSocketPath(), confDaemon.buildAdminSocketCommand(),
+						"ceph daemon health check failed with the following output."),
```
Comment (BlaineEXE) [inline pkg/operator/ceph/controller/spec.go:590]: If we are already breaking this up on multiple lines, should we use a multiline const for a script instead of a one-liner? I think that might help us avoid issues with the semicolons when changing this in the future.

```suggestion
fmt.Sprintf(`outp="$(ceph --admin-daemon %s %s 2>&1)"
rc=$?
if [ $rc -ne 0 ]; then 
  echo "ceph daemon health check failed with the following output:"
  echo "$outp" | sed -e 's/^/> /g'
  exit $rc
fi`,
confDaemon.buildSocketPath(), confDaemon.buildAdminSocketCommand()),
```

Comment (satoru-takeuchi) [reply pkg/operator/ceph/controller/spec.go]: Indeed, fixed.

**Review by BlaineEXE — APPROVED** [review]
