### PR TITLE
Increase OSD size when the template size increases

### LINKED ISSUE #5309: Operator should expand OSD PVC size when the template size is increased in the cluster CR
* Bug Report
A new feature was added in 1.3 to allow expansion of OSDs running on top of PVs
https://github.com/rook/rook/pull/4844

**Deviation from expected behavior:**
Modifying the
`.storageClassDeviceSets.volumeClaimTemplates.spec.resources.requests.storage`
by increasing the size has no effect
Refer to this discussion on Slack: https://rook-io.slack.com/archives/CK9CF5H2R/p1587544293418000

**Expected behavior:**
I would expect
- That the underlying EBS PVC was expanded
- That the corresponding OSD was expanded
neither happens

I can manually alter the OSD PVC to increase the size. Restarting a OSD pod does not change the OSD size, but I can confirm that the PVC was changed inside the pod. 
```
loop0                                                                                                   7:0    0  125G  0 loop
nvme1n1                                                                                               259:1    0  125G  0 disk
`-ceph--6658e799--4dc7--41fb--bf2c--b11784d9a729-osd--block--064e7e25--45c4--4432--818d--c4bcc3ac73a8 254:0    0  100G  0 lvm
```
* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
operator log
```
2020-04-22 08:22:53.992137 I | rookcmd: starting Rook v1.3.1 with arguments '/usr/local/bin/rook ceph operator'
2020-04-22 08:22:53.992217 I | rookcmd: flag values: --add_dir_header=false, --alsologtostderr=false, --csi-cephfs-plugin-template-path=/etc/ceph-csi/cephfs/csi-cephfsplugin.yaml, --csi-cephfs-provisioner-dep-template-path=/etc/ceph-cs
i/cephfs/csi-cephfsplugin-provisioner-dep.yaml, --csi-cephfs-provisioner-sts-template-path=/etc/ceph-csi/cephfs/csi-cephfsplugin-provisioner-sts.yaml, --csi-rbd-plugin-template-path=/etc/ceph-csi/rbd/csi-rbdplugin.yaml, --csi-rbd-provi
sioner-dep-template-path=/etc/ceph-csi/rbd/csi-rbdplugin-provisioner-dep.yaml, --csi-rbd-provisioner-sts-template-path=/etc/ceph-csi/rbd/csi-rbdplugin-provisioner-sts.yaml, --enable-discovery-daemon=false, --enable-flex-driver=false, -
-enable-machine-disruption-budget=false, --help=false, --kubeconfig=, --log-flush-frequency=5s, --log-level=INFO, --log_backtrace_at=:0, --log_dir=, --log_file=, --log_file_max_size=1800, --logtostderr=true, --master=, --mon-healthchec
k-interval=30s, --mon-out-timeout=10m0s, --operator-image=, --service-account=, --skip_headers=false, --skip_log_headers=false, --stderrthreshold=2, --v=0, --vmodule=
2020-04-22 08:22:53.992226 I | cephcmd: starting operator
2020-04-22 08:22:54.021599 I | operator: rook-provisioner ceph.rook.io/block started using ceph.rook.io flex vendor dir
2020-04-22 08:22:54.021860 I | operator: rook-provisioner rook.io/block started using rook.io flex vendor dir
2020-04-22 08:22:54.021879 I | operator: Watching all namespaces for cluster CRDs
2020-04-22 08:22:54.021888 I | op-cluster: start watching clusters in all namespaces
I0422 08:22:54.021901       6 leaderelection.go:242] attempting to acquire leader lease  rook-ceph/ceph.rook.io-block...
2020-04-22 08:22:54.021923 I | op-cluster: Enabling hotplug orchestration: ROOK_DISABLE_DEVICE_HOTPLUG=false
I0422 08:22:54.022122       6 leaderelection.go:242] attempting to acquire leader lease  rook-ceph/rook.io-block...
2020-04-22 08:22:54.022431 I | operator: setting up the controller-runtime manager
2020-04-22 08:22:54.024875 I | op-cluster: ConfigMap "rook-ceph-operator-config" changes detected. Updating configurations
2020-04-22 08:22:54.034514 I | op-cluster: starting cluster in namespace rook-ceph
2020-04-22 08:22:55.400278 I | ceph-csi: detecting the ceph csi image version for image "quay.io/cephcsi/cephcsi:v2.0.1"
2020-04-22 08:22:55.430649 I | operator: starting the controller-runtime manager
2020-04-22 08:22:55.750405 I | ceph-spec: "ceph-block-pool-controller": operator is not ready to run ceph command, cannot reconcile yet.
2020-04-22 08:22:55.838627 I | ceph-spec: "ceph-file-controller": operator is not ready to run ceph command, cannot reconcile yet.
2020-04-22 08:22:55.847485 I | ceph-spec: "ceph-block-pool-controller": operator is not ready to run ceph command, cannot reconcile yet.
2020-04-22 08:22:58.033981 I | ceph-csi: Detected ceph CSI image version: "v2.0.1"
2020-04-22 08:22:58.063054 I | ceph-csi: successfully created csi config map "rook-ceph-csi-config"
2020-04-22 08:23:01.414036 I | ceph-csi: CSIDriver CRD already had been registered for "rook-ceph.rbd.csi.ceph.com"
2020-04-22 08:23:01.423207 I | ceph-csi: CSIDriver CRD already had been registered for "rook-ceph.cephfs.csi.ceph.com"
2020-04-22 08:23:01.423225 I | operator: successfully started Ceph CSI driver(s)
2020-04-22 08:23:05.852786 I | ceph-spec: "ceph-block-pool-controller": operator is not ready to run ceph command, cannot reconcile yet.
2020-04-22 08:23:05.973163 I | ceph-spec: "ceph-block-pool-controller": operator is not ready to run ceph command, cannot reconcile yet.
2020-04-22 08:23:05.975947 I | ceph-spec: "ceph-file-controller": operator is not ready to run ceph command, cannot reconcile yet.
2020-04-22 08:23:07.474542 I | op-cluster: detecting the ceph image version for image ceph/ceph:v14.2.8...
2020-04-22 08:23:09.554972 I | op-cluster: Detected ceph image version: "14.2.8-0 nautilus"
2020-04-22 08:23:09.568634 I | op-mon: parsing mon endpoints: c=100.70.91.227:6789,a=100.68.141.27:6789,b=100.69.167.202:6789
2020-04-22 08:23:09.569071 I | cephconfig: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2020-04-22 08:23:09.569163 I | cephconfig: generated admin config in /var/lib/rook/rook-ceph
2020-04-22 08:23:09.972285 I | op-cluster: cluster "rook-ceph": version "14.2.8-0 nautilus" detected for image "ceph/ceph:v14.2.8"
2020-04-22 08:23:10.002996 I | op-config: CephCluster "rook-ceph" status: "Progressing". "Cluster is checking if updates are needed"
2020-04-22 08:23:10.026314 I | op-mon: start running mons
2020-04-22 08:23:10.037798 I | op-mon: parsing mon endpoints: c=100.70.91.227:6789,a=100.68.141.27:6789,b=100.69.167.202:6789
2020-04-22 08:23:10.052792 I | op-mon: saved mon endpoints to config map map[csi-cluster-config-json:[{"clusterID":"rook-ceph","monitors":["100.70.91.227:6789","100.68.141.27:6789","100.69.167.202:6789"]}] data:c=100.70.91.227:6789,a=1
00.68.141.27:6789,b=100.69.167.202:6789 mapping:{"node":{"a":null,"b":null,"c":null}} maxMonId:2]
2020-04-22 08:23:10.078595 I | cephconfig: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2020-04-22 08:23:10.078703 I | cephconfig: generated admin config in /var/lib/rook/rook-ceph
I0422 08:23:11.339283       6 leaderelection.go:252] successfully acquired lease rook-ceph/ceph.rook.io-block
I0422 08:23:11.339389       6 event.go:281] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"rook-ceph", Name:"ceph.rook.io-block", UID:"69e9b767-e96f-4f97-b1d1-03fcca49ff98", APIVersion:"v1", ResourceVersion:"20638367", FieldPath
:""}): type: 'Normal' reason: 'LeaderElection' rook-ceph-operator-f46b86b6b-rq42w_b8addf34-53b1-4bce-b9cd-2eb739aeca4d became leader
I0422 08:23:11.339436       6 controller.go:780] Starting provisioner controller ceph.rook.io/block_rook-ceph-operator-f46b86b6b-rq42w_b8addf34-53b1-4bce-b9cd-2eb739aeca4d!
I0422 08:23:11.537262       6 leaderelection.go:252] successfully acquired lease rook-ceph/rook.io-block
I0422 08:23:11.537304       6 event.go:281] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"rook-ceph", Name:"rook.io-block", UID:"e2fc3e17-e48c-4895-89e1-0c2064be5bf2", APIVersion:"v1", ResourceVersion:"20638368", FieldPath:""})
: type: 'Normal' reason: 'LeaderElection' rook-ceph-operator-f46b86b6b-rq42w_a5e4e0e1-bb81-4c9e-a56f-bc94564cb9fc became leader
I0422 08:23:11.537340       6 controller.go:780] Starting provisioner controller rook.io/block_rook-ceph-operator-f46b86b6b-rq42w_a5e4e0e1-bb81-4c9e-a56f-bc94564cb9fc!
2020-04-22 08:23:11.734506 I | op-mon: targeting the mon count 3
I0422 08:23:12.539678       6 controller.go:829] Started provisioner controller ceph.rook.io/block_rook-ceph-operator-f46b86b6b-rq42w_b8addf34-53b1-4bce-b9cd-2eb739aeca4d!
I0422 08:23:13.337583       6 controller.go:829] Started provisioner controller rook.io/block_rook-ceph-operator-f46b86b6b-rq42w_a5e4e0e1-bb81-4c9e-a56f-bc94564cb9fc!
2020-04-22 08:23:13.668986 I | op-mon: checking for basic quorum with existing mons
2020-04-22 08:23:14.337933 I | op-mon: mon "c" endpoint are [v2:100.70.91.227:3300,v1:100.70.91.227:6789]
2020-04-22 08:23:14.938292 I | op-mon: mon "a" endpoint are [v2:100.68.141.27:3300,v1:100.68.141.27:6789]
2020-04-22 08:23:15.537990 I | op-mon: mon "b" endpoint are [v2:100.69.167.202:3300,v1:100.69.167.202:6789]
2020-04-22 08:23:16.534364 I | op-mon: saved mon endpoints to config map map[csi-cluster-config-json:[{"clusterID":"rook-ceph","monitors":["100.70.91.227:6789","100.68.141.27:6789","100.69.167.202:6789"]}] data:c=100.70.91.227:6789,a=1
00.68.141.27:6789,b=100.69.167.202:6789 mapping:{"node":{"a":null,"b":null,"c":null}} maxMonId:2]
2020-04-22 08:23:16.887281 I | ceph-block-pool-controller: creating pool "ec-pool" in namespace "rook-ceph"
2020-04-22 08:23:17.360391 I | cephconfig: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2020-04-22 08:23:17.360544 I | cephconfig: generated admin config in /var/lib/rook/rook-ceph
2020-04-22 08:23:17.533788 I | op-mon: parsing mon endpoints: c=100.70.91.227:6789,a=100.68.141.27:6789,b=100.69.167.202:6789
2020-04-22 08:23:17.934555 I | cephconfig: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2020-04-22 08:23:17.934669 I | cephconfig: generated admin config in /var/lib/rook/rook-ceph
2020-04-22 08:23:17.950813 I | op-mon: deployment for mon rook-ceph-mon-c already exists. updating if needed
2020-04-22 08:23:17.963373 I | op-mon: checking if we can stop the deployment rook-ceph-mon-c
2020-04-22 08:23:19.279998 I | op-k8sutil: updating deployment "rook-ceph-mon-c"
2020-04-22 08:23:19.819317 I | ceph-file-controller: filesystem r2-fs already exists
2020-04-22 08:23:20.697107 I | cephclient: creating EC pool ec-pool succeeded
2020-04-22 08:23:21.306498 I | op-k8sutil: finished waiting for updated deployment "rook-ceph-mon-c"
2020-04-22 08:23:21.306523 I | op-mon: checking if we can continue the deployment rook-ceph-mon-c
2020-04-22 08:23:21.306539 I | op-mon: waiting for mon quorum with [c a b]
2020-04-22 08:23:21.333064 I | op-mon: mons running: [c a b]
2020-04-22 08:23:21.811320 I | ceph-block-pool-controller: creating pool "r2-pool" in namespace "rook-ceph"
2020-04-22 08:23:21.814994 I | op-mon: Monitors in quorum: [a b c]
2020-04-22 08:23:21.823410 I | op-mon: deployment for mon rook-ceph-mon-a already exists. updating if needed
2020-04-22 08:23:21.838270 I | op-mon: checking if we can stop the deployment rook-ceph-mon-a
2020-04-22 08:23:23.279591 I | op-k8sutil: updating deployment "rook-ceph-mon-a"
2020-04-22 08:23:25.283619 I | ceph-file-controller: start running mdses for filesystem "r2-fs"
2020-04-22 08:23:25.283659 I | cephclient: getting or creating ceph auth key "mds.r2-fs-a"
2020-04-22 08:23:25.307912 I | op-k8sutil: finished waiting for updated deployment "rook-ceph-mon-a"
2020-04-22 08:23:25.307931 I | op-mon: checking if we can continue the deployment rook-ceph-mon-a
2020-04-22 08:23:25.307943 I | op-mon: waiting for mon quorum with [c a b]
2020-04-22 08:23:25.334313 I | op-mon: mons running: [c a b]
2020-04-22 08:23:25.868377 I | op-mds: deployment for mds rook-ceph-mds-r2-fs-a already exists. updating if needed
2020-04-22 08:23:25.870598 I | cephclient: creating replicated pool r2-pool succeeded
2020-04-22 08:23:25.882959 I | op-mon: Monitors in quorum: [a b c]
2020-04-22 08:23:25.884427 I | op-k8sutil: deployment "rook-ceph-mds-r2-fs-a" did not change, nothing to update
2020-04-22 08:23:25.884446 I | cephclient: getting or creating ceph auth key "mds.r2-fs-b"
2020-04-22 08:23:25.891539 I | op-mon: deployment for mon rook-ceph-mon-b already exists. updating if needed
2020-04-22 08:23:25.913268 I | op-mon: checking if we can stop the deployment rook-ceph-mon-b
2020-04-22 08:23:26.470445 I | op-mds: deployment for mds rook-ceph-mds-r2-fs-b already exists. updating if needed
2020-04-22 08:23:26.486111 I | op-k8sutil: deployment "rook-ceph-mds-r2-fs-b" did not change, nothing to update
2020-04-22 08:23:26.486141 I | cephclient: getting or creating ceph auth key "mds.r2-fs-c"
2020-04-22 08:23:26.886681 I | op-k8sutil: updating deployment "rook-ceph-mon-b"
2020-04-22 08:23:26.994236 I | op-mds: deployment for mds rook-ceph-mds-r2-fs-c already exists. updating if needed
2020-04-22 08:23:27.054720 I | op-k8sutil: deployment "rook-ceph-mds-r2-fs-c" did not change, nothing to update
2020-04-22 08:23:27.054749 I | cephclient: getting or creating ceph auth key "mds.r2-fs-d"
2020-04-22 08:23:27.540994 I | op-mds: deployment for mds rook-ceph-mds-r2-fs-d already exists. updating if needed
2020-04-22 08:23:27.854552 I | op-k8sutil: deployment "rook-ceph-mds-r2-fs-d" did not change, nothing to update
2020-04-22 08:23:27.854580 I | cephclient: getting or creating ceph auth key "mds.r2-fs-e"
2020-04-22 08:23:28.425506 I | op-mds: deployment for mds rook-ceph-mds-r2-fs-e already exists. updating if needed
2020-04-22 08:23:28.654716 I | op-k8sutil: deployment "rook-ceph-mds-r2-fs-e" did not change, nothing to update
2020-04-22 08:23:28.654747 I | cephclient: getting or creating ceph auth key "mds.r2-fs-f"
2020-04-22 08:23:28.917531 I | op-k8sutil: finished waiting for updated deployment "rook-ceph-mon-b"
2020-04-22 08:23:28.917561 I | op-mon: checking if we can continue the deployment rook-ceph-mon-b
2020-04-22 08:23:28.917579 I | op-mon: waiting for mon quorum with [c a b]
2020-04-22 08:23:29.118312 I | op-mon: mons running: [c a b]
2020-04-22 08:23:29.582845 I | op-mon: Monitors in quorum: [a b c]
2020-04-22 08:23:29.582870 I | op-mon: mons created: 3
2020-04-22 08:23:29.732555 I | op-mds: deployment for mds rook-ceph-mds-r2-fs-f already exists. updating if needed
2020-04-22 08:23:29.746725 I | op-k8sutil: deployment "rook-ceph-mds-r2-fs-f" did not change, nothing to update
2020-04-22 08:23:29.984899 I | op-mon: waiting for mon quorum with [c a b]
2020-04-22 08:23:30.318416 I | op-mon: mons running: [c a b]
2020-04-22 08:23:30.774788 I | op-mon: Monitors in quorum: [a b c]
2020-04-22 08:23:30.774821 I | cephclient: getting or creating ceph auth key "client.csi-rbd-provisioner"
2020-04-22 08:23:31.419507 I | cephclient: getting or creating ceph auth key "client.csi-rbd-node"
2020-04-22 08:23:31.856236 I | cephclient: getting or creating ceph auth key "client.csi-cephfs-provisioner"
2020-04-22 08:23:32.300434 I | cephclient: getting or creating ceph auth key "client.csi-cephfs-node"
2020-04-22 08:23:33.114324 I | ceph-csi: created kubernetes csi secrets for cluster "rook-ceph"
2020-04-22 08:23:33.114352 I | cephclient: getting or creating ceph auth key "client.crash"
2020-04-22 08:23:33.915104 I | ceph-crashcollector-controller: created kubernetes crash collector secret for cluster "rook-ceph"
2020-04-22 08:23:34.334486 I | cephclient: successfully enabled msgr2 protocol
2020-04-22 08:23:34.334517 I | op-mgr: start running mgr
2020-04-22 08:23:34.334533 I | cephclient: getting or creating ceph auth key "mgr.a"
2020-04-22 08:23:34.941282 I | op-mgr: deployment for mgr rook-ceph-mgr-a already exists. updating if needed
2020-04-22 08:23:34.951971 I | op-k8sutil: deployment "rook-ceph-mgr-a" did not change, nothing to update
2020-04-22 08:23:35.539292 I | op-mgr: dashboard service already exists
2020-04-22 08:23:38.088957 I | op-mgr: successful modules: prometheus
2020-04-22 08:23:38.119861 I | op-mgr: successful modules: crash
2020-04-22 08:23:39.836755 I | op-mgr: successful modules: orchestrator modules
2020-04-22 08:23:41.425591 I | op-mgr: successful modules: http bind settings
2020-04-22 08:23:42.084356 I | op-mgr: the dashboard secret was already generated
2020-04-22 08:23:42.084390 I | op-mgr: setting ceph dashboard "admin" login creds
2020-04-22 08:23:42.117617 I | op-mgr: successful modules: mgr module(s) from the spec
2020-04-22 08:23:42.854132 I | op-mgr: successfully set ceph dashboard creds
2020-04-22 08:23:45.744862 I | op-mgr: dashboard config has changed. restarting the dashboard module.
2020-04-22 08:23:45.744886 I | op-mgr: restarting the mgr module
2020-04-22 08:23:48.263302 I | op-mgr: successful modules: dashboard
2020-04-22 08:23:48.296275 I | op-mgr: mgr metrics service already exists
2020-04-22 08:23:48.296305 I | op-mgr: starting monitoring deployment
W0422 08:23:48.297188       6 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2020-04-22 08:23:48.310654 I | op-mgr: servicemonitor enabled
W0422 08:23:48.313702       6 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2020-04-22 08:23:48.395579 I | op-mgr: prometheusRule deployed
2020-04-22 08:23:48.395606 I | op-osd: start running osds in namespace rook-ceph
2020-04-22 08:23:48.395612 I | op-osd: start provisioning the osds on pvcs, if needed
2020-04-22 08:23:48.401655 I | op-osd: successfully provisioned pvc "zone-a-0-data-lzh28" for VolumeClaimTemplates "data" for storageClassDeviceSet "zone-a" of set 0
2020-04-22 08:23:48.407227 I | op-osd: successfully provisioned pvc "zone-b-0-data-k5c6h" for VolumeClaimTemplates "data" for storageClassDeviceSet "zone-b" of set 0
2020-04-22 08:23:48.412931 I | op-osd: successfully provisioned pvc "zone-c-0-data-9gtht" for VolumeClaimTemplates "data" for storageClassDeviceSet "zone-c" of set 0
2020-04-22 08:23:48.436287 I | op-osd: skip OSD prepare pod creation as OSD daemon already exists for "zone-a-0-data-lzh28"
2020-04-22 08:23:48.607416 I | op-osd: skip OSD prepare pod creation as OSD daemon already exists for "zone-b-0-data-k5c6h"
2020-04-22 08:23:49.808337 I | op-osd: skip OSD prepare pod creation as OSD daemon already exists for "zone-c-0-data-9gtht"
2020-04-22 08:23:50.199519 I | op-osd: start osds after provisioning is completed, if needed
2020-04-22 08:23:50.400784 I | op-osd: osd orchestration status for node zone-a-0-data-lzh28 is completed
2020-04-22 08:23:50.400848 I | op-osd: starting 1 osd daemons on pvc zone-a-0-data-lzh28
2020-04-22 08:23:50.400867 I | cephclient: getting or creating ceph auth key "osd.0"
2020-04-22 08:23:51.220670 I | op-osd: deployment for osd 0 already exists. updating if needed
2020-04-22 08:23:51.625318 I | op-k8sutil: deployment "rook-ceph-osd-0" did not change, nothing to update
2020-04-22 08:23:51.625350 I | op-osd: started deployment for osd 0 on pvc
2020-04-22 08:23:52.006657 I | op-osd: osd orchestration status for node zone-b-0-data-k5c6h is completed
2020-04-22 08:23:52.006684 I | op-osd: starting 1 osd daemons on pvc zone-b-0-data-k5c6h
2020-04-22 08:23:52.006718 I | cephclient: getting or creating ceph auth key "osd.2"
2020-04-22 08:23:52.628732 I | op-osd: deployment for osd 2 already exists. updating if needed
2020-04-22 08:23:53.018304 I | op-k8sutil: deployment "rook-ceph-osd-2" did not change, nothing to update
2020-04-22 08:23:53.018330 I | op-osd: started deployment for osd 2 on pvc
2020-04-22 08:23:53.405402 I | op-osd: osd orchestration status for node zone-c-0-data-9gtht is completed
2020-04-22 08:23:53.405425 I | op-osd: starting 1 osd daemons on pvc zone-c-0-data-9gtht
2020-04-22 08:23:53.405436 I | cephclient: getting or creating ceph auth key "osd.1"
2020-04-22 08:23:54.020213 I | op-osd: deployment for osd 1 already exists. updating if needed
2020-04-22 08:23:54.419998 I | op-k8sutil: deployment "rook-ceph-osd-1" did not change, nothing to update
2020-04-22 08:23:54.420026 I | op-osd: started deployment for osd 1 on pvc
2020-04-22 08:23:54.806609 I | op-osd: start provisioning the osds on nodes, if needed
2020-04-22 08:23:54.806636 W | op-osd: skipping osd provisioning where no dataDirHostPath is set
2020-04-22 08:23:55.206143 I | op-osd: completed running osds in namespace rook-ceph
2020-04-22 08:23:55.206171 I | rbd-mirror: configure rbd-mirroring with 0 workers
2020-04-22 08:23:55.214372 I | rbd-mirror: no extra daemons to remove
2020-04-22 08:23:55.214390 I | op-cluster: Done creating rook instance in namespace rook-ceph
2020-04-22 08:23:55.221464 I | op-config: CephCluster "rook-ceph" status: "Ready". "Cluster created successfully"
2020-04-22 08:23:55.252694 I | op-client: start watching client resources in namespace "rook-ceph"
2020-04-22 08:23:55.252720 I | op-bucket-prov: Ceph Bucket Provisioner launched
2020-04-22 08:23:55.254289 I | op-cluster: ceph status check interval is 30s
I0422 08:23:55.254324       6 manager.go:118] objectbucket.io/provisioner-manager "msg"="starting provisioner"  "name"="ceph.rook.io/bucket"
2020-04-22 08:23:55.264022 I | op-cluster: finalizer already set on cluster rook-ceph
2020-04-22 09:29:34.785904 I | op-cluster: The Cluster CR has changed. diff=  v1.ClusterSpec{
        CephVersion: v1.CephVersionSpec{Image: "ceph/ceph:v14.2.8"},
        Storage: v1.StorageScopeSpec{
                ... // 4 identical fields
                Selection:     v1.Selection{},
                VolumeSources: nil,
                StorageClassDeviceSets: []v1.StorageClassDeviceSet{
                        {
                                ... // 3 identical fields
                                Placement: v1.Placement{NodeAffinity: &v1.NodeAffinity{RequiredDuringSchedulingIgnoredDuringExecution: &v1.NodeSelector{NodeSelectorTerms: []v1.NodeSelectorTerm{{MatchExpressions: []v1.NodeSelectorRequir
ement{{Key: "k8s.gdo.aws/zone", Operator: "In", Values: []string{"a"}}, {Key: "k8s.gdo.aws/role", Operator: "In", Values: []string{"storage"}}}}}}}, Tolerations: []v1.Toleration{{Key: "k8s.gdo.aws/role", Operator: "Equal", Value: "stor
age", Effect: "NoSchedule"}}},
                                Config:    nil,
                                VolumeClaimTemplates: []v1.PersistentVolumeClaim{
                                        {
                                                TypeMeta:   v1.TypeMeta{},
                                                ObjectMeta: v1.ObjectMeta{Name: "data"},
                                                Spec: v1.PersistentVolumeClaimSpec{
                                                        AccessModes: []v1.PersistentVolumeAccessMode{"ReadWriteOnce"},
                                                        Selector:    nil,
                                                        Resources: v1.ResourceRequirements{
                                                                Limits:   nil,
-                                                               Requests: v1.ResourceList{s"storage": {i: resource.int64Amount{value: 128849018880}, Format: "BinarySI"}},
+                                                               Requests: v1.ResourceList{
+                                                                       s"storage": {i: resource.int64Amount{value: 134217728000}, s: "125Gi", Format: "BinarySI"},
+                                                               },
                                                        },
                                                        VolumeName:       "",
                                                        StorageClassName: &"ebs-gp2",
                                                        ... // 2 identical fields
                                                },
                                                Status: v1.PersistentVolumeClaimStatus{},
                                        },
                                },
                                Portable:            true,
                                TuneSlowDeviceClass: false,
                        },
                        {
                                ... // 3 identical fields
                                Placement: v1.Placement{NodeAffinity: &v1.NodeAffinity{RequiredDuringSchedulingIgnoredDuringExecution: &v1.NodeSelector{NodeSelectorTerms: []v1.NodeSelectorTerm{{MatchExpressions: []v1.NodeSelectorRequir
ement{{Key: "k8s.gdo.aws/zone", Operator: "In", Values: []string{"b"}}, {Key: "k8s.gdo.aws/role", Operator: "In", Values: []string{"storage"}}}}}}}, Tolerations: []v1.Toleration{{Key: "k8s.gdo.aws/role", Operator: "Equal", Value: "stor
age", Effect: "NoSchedule"}}},
                                Config:    nil,
                                VolumeClaimTemplates: []v1.PersistentVolumeClaim{
                                        {
                                                TypeMeta:   v1.TypeMeta{},
                                                ObjectMeta: v1.ObjectMeta{Name: "data"},
                                                Spec: v1.PersistentVolumeClaimSpec{
                                                        AccessModes: []v1.PersistentVolumeAccessMode{"ReadWriteOnce"},
                                                        Selector:    nil,
                                                        Resources: v1.ResourceRequirements{
                                                                Limits:   nil,
-                                                               Requests: v1.ResourceList{s"storage": {i: resource.int64Amount{value: 128849018880}, Format: "BinarySI"}},
+                                                               Requests: v1.ResourceList{
+                                                                       s"storage": {i: resource.int64Amount{value: 134217728000}, s: "125Gi", Format: "BinarySI"},
+                                                               },
                                                        },
                                                        VolumeName:       "",
                                                        StorageClassName: &"ebs-gp2",
                                                        ... // 2 identical fields
                                                },
                                                Status: v1.PersistentVolumeClaimStatus{},
                                        },
                                },
                                Portable:            true,
                                TuneSlowDeviceClass: false,
                        },
                        {
                                ... // 3 identical fields
                                Placement: v1.Placement{NodeAffinity: &v1.NodeAffinity{RequiredDuringSchedulingIgnoredDuringExecution: &v1.NodeSelector{NodeSelectorTerms: []v1.NodeSelectorTerm{{MatchExpressions: []v1.NodeSelectorRequir
ement{{Key: "k8s.gdo.aws/zone", Operator: "In", Values: []string{"c"}}, {Key: "k8s.gdo.aws/role", Operator: "In", Values: []string{"storage"}}}}}}}, Tolerations: []v1.Toleration{{Key: "k8s.gdo.aws/role", Operator: "Equal", Value: "stor
age", Effect: "NoSchedule"}}},
                                Config:    nil,
                                VolumeClaimTemplates: []v1.PersistentVolumeClaim{
                                        {
                                                TypeMeta:   v1.TypeMeta{},
                                                ObjectMeta: v1.ObjectMeta{Name: "data"},
                                                Spec: v1.PersistentVolumeClaimSpec{
                                                        AccessModes: []v1.PersistentVolumeAccessMode{"ReadWriteOnce"},
                                                        Selector:    nil,
                                                        Resources: v1.ResourceRequirements{
                                                                Limits:   nil,
-                                                               Requests: v1.ResourceList{s"storage": {i: resource.int64Amount{value: 128849018880}, Format: "BinarySI"}},
+                                                               Requests: v1.ResourceList{
+                                                                       s"storage": {i: resource.int64Amount{value: 134217728000}, s: "125Gi", Format: "BinarySI"},
+                                                               },
                                                        },
                                                        VolumeName:       "",
                                                        StorageClassName: &"ebs-gp2",
                                                        ... // 2 identical fields
                                                },
                                                Status: v1.PersistentVolumeClaimStatus{},
                                        },
                                },
                                Portable:            true,
                                TuneSlowDeviceClass: false,
                        },
                },
        },
        Annotations: nil,
        Placement:   v1.PlacementSpec{"mon": {PodAntiAffinity: &v1.PodAntiAffinity{PreferredDuringSchedulingIgnoredDuringExecution: []v1.WeightedPodAffinityTerm{{Weight: 100, PodAffinityTerm: v1.PodAffinityTerm{LabelSelector: &v1.Label
Selector{MatchExpressions: []v1.LabelSelectorRequirement{{Key: "app", Operator: "In", Values: []string{"rook-ceph-mon"}}}}, TopologyKey: "failure-domain.beta.kubernetes.io/zone"}}}}}},
        ... // 16 identical fields
  }
2020-04-22 09:29:34.785942 I | op-cluster: update event for cluster "rook-ceph" is supported, orchestrating update now
2020-04-22 09:29:34.792646 I | op-config: CephCluster "rook-ceph" status: "Updating". "Cluster is updating"
2020-04-22 09:29:35.204361 I | op-cluster: ceph daemons running versions are: {Mon:map[ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable):3] Mgr:map[ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022
d35cb) nautilus (stable):1] Osd:map[ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable):3] Rgw:map[] Mds:map[ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable):6] RbdMirror:map
[] Overall:map[ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable):13]}
2020-04-22 09:29:35.211639 I | op-config: CephCluster "rook-ceph" status: "Updating". "Cluster is updating"
2020-04-22 09:29:35.234548 I | op-mon: start running mons
2020-04-22 09:29:35.244727 I | op-mon: parsing mon endpoints: c=100.70.91.227:6789,a=100.68.141.27:6789,b=100.69.167.202:6789
2020-04-22 09:29:35.260128 I | op-mon: saved mon endpoints to config map map[csi-cluster-config-json:[{"clusterID":"rook-ceph","monitors":["100.70.91.227:6789","100.68.141.27:6789","100.69.167.202:6789"]}] data:c=100.70.91.227:6789,a=1
00.68.141.27:6789,b=100.69.167.202:6789 mapping:{"node":{"a":null,"b":null,"c":null}} maxMonId:2]
2020-04-22 09:29:35.284410 I | cephconfig: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2020-04-22 09:29:35.284523 I | cephconfig: generated admin config in /var/lib/rook/rook-ceph
2020-04-22 09:29:36.627373 I | op-mon: targeting the mon count 3
2020-04-22 09:29:38.604886 I | op-mon: checking for basic quorum with existing mons
2020-04-22 09:29:38.652526 I | op-mon: mon "c" endpoint are [v2:100.70.91.227:3300,v1:100.70.91.227:6789]
2020-04-22 09:29:38.715031 I | op-mon: mon "a" endpoint are [v2:100.68.141.27:3300,v1:100.68.141.27:6789]
2020-04-22 09:29:39.230997 I | op-mon: mon "b" endpoint are [v2:100.69.167.202:3300,v1:100.69.167.202:6789]
2020-04-22 09:29:39.829290 I | op-mon: saved mon endpoints to config map map[csi-cluster-config-json:[{"clusterID":"rook-ceph","monitors":["100.70.91.227:6789","100.68.141.27:6789","100.69.167.202:6789"]}] data:c=100.70.91.227:6789,a=1
00.68.141.27:6789,b=100.69.167.202:6789 mapping:{"node":{"a":null,"b":null,"c":null}} maxMonId:2]
2020-04-22 09:29:40.428372 I | cephconfig: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2020-04-22 09:29:40.428476 I | cephconfig: generated admin config in /var/lib/rook/rook-ceph
2020-04-22 09:29:41.228575 I | cephconfig: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2020-04-22 09:29:41.228698 I | cephconfig: generated admin config in /var/lib/rook/rook-ceph
2020-04-22 09:29:41.245773 I | op-mon: deployment for mon rook-ceph-mon-c already exists. updating if needed
2020-04-22 09:29:41.258568 I | op-mon: checking if we can stop the deployment rook-ceph-mon-c
2020-04-22 09:29:42.051562 I | op-k8sutil: updating deployment "rook-ceph-mon-c"
2020-04-22 09:29:44.079694 I | op-k8sutil: finished waiting for updated deployment "rook-ceph-mon-c"
2020-04-22 09:29:44.079727 I | op-mon: checking if we can continue the deployment rook-ceph-mon-c
2020-04-22 09:29:44.079747 I | op-mon: waiting for mon quorum with [c a b]
2020-04-22 09:29:44.135803 I | op-mon: mons running: [c a b]
2020-04-22 09:29:44.651223 I | op-mon: Monitors in quorum: [a b c]
2020-04-22 09:29:44.659028 I | op-mon: deployment for mon rook-ceph-mon-a already exists. updating if needed
2020-04-22 09:29:44.669598 I | op-mon: checking if we can stop the deployment rook-ceph-mon-a
2020-04-22 09:29:45.454412 I | op-k8sutil: updating deployment "rook-ceph-mon-a"
2020-04-22 09:29:47.481387 I | op-k8sutil: finished waiting for updated deployment "rook-ceph-mon-a"
2020-04-22 09:29:47.481413 I | op-mon: checking if we can continue the deployment rook-ceph-mon-a
2020-04-22 09:29:47.481427 I | op-mon: waiting for mon quorum with [c a b]
2020-04-22 09:29:47.510057 I | op-mon: mons running: [c a b]
2020-04-22 09:29:48.006448 I | op-mon: Monitors in quorum: [a b c]
2020-04-22 09:29:48.016764 I | op-mon: deployment for mon rook-ceph-mon-b already exists. updating if needed
2020-04-22 09:29:48.033307 I | op-mon: checking if we can stop the deployment rook-ceph-mon-b
2020-04-22 09:29:48.935908 I | op-k8sutil: updating deployment "rook-ceph-mon-b"
2020-04-22 09:29:50.961305 I | op-k8sutil: finished waiting for updated deployment "rook-ceph-mon-b"
2020-04-22 09:29:50.961337 I | op-mon: checking if we can continue the deployment rook-ceph-mon-b
2020-04-22 09:29:50.961351 I | op-mon: waiting for mon quorum with [c a b]
2020-04-22 09:29:50.990235 I | op-mon: mons running: [c a b]
2020-04-22 09:29:51.538133 I | op-mon: Monitors in quorum: [a b c]
2020-04-22 09:29:51.538158 I | op-mon: mons created: 3
2020-04-22 09:29:51.932047 I | op-mon: waiting for mon quorum with [c a b]
2020-04-22 09:29:51.960593 I | op-mon: mons running: [c a b]
2020-04-22 09:29:52.439216 I | op-mon: Monitors in quorum: [a b c]
2020-04-22 09:29:52.439254 I | cephclient: getting or creating ceph auth key "client.csi-rbd-provisioner"
2020-04-22 09:29:52.879049 I | cephclient: getting or creating ceph auth key "client.csi-rbd-node"
2020-04-22 09:29:53.317914 I | cephclient: getting or creating ceph auth key "client.csi-cephfs-provisioner"
2020-04-22 09:29:53.769172 I | cephclient: getting or creating ceph auth key "client.csi-cephfs-node"
2020-04-22 09:29:54.267539 I | ceph-csi: created kubernetes csi secrets for cluster "rook-ceph"
2020-04-22 09:29:54.267561 I | cephclient: getting or creating ceph auth key "client.crash"
2020-04-22 09:29:54.721768 I | ceph-crashcollector-controller: created kubernetes crash collector secret for cluster "rook-ceph"
2020-04-22 09:29:55.117520 I | cephclient: successfully enabled msgr2 protocol
2020-04-22 09:29:55.117547 I | op-mgr: start running mgr
2020-04-22 09:29:55.117560 I | cephclient: getting or creating ceph auth key "mgr.a"
2020-04-22 09:29:55.606831 I | op-mgr: deployment for mgr rook-ceph-mgr-a already exists. updating if needed
2020-04-22 09:29:55.617688 I | op-k8sutil: deployment "rook-ceph-mgr-a" did not change, nothing to update
2020-04-22 09:29:56.141295 I | op-mgr: dashboard service already exists
2020-04-22 09:29:57.515002 I | op-mgr: successful modules: crash
2020-04-22 09:29:58.550937 I | op-mgr: successful modules: prometheus
2020-04-22 09:30:00.398843 I | op-mgr: successful modules: orchestrator modules
2020-04-22 09:30:02.147391 I | op-mgr: successful modules: http bind settings
2020-04-22 09:30:02.539221 I | op-mgr: successful modules: mgr module(s) from the spec
2020-04-22 09:30:03.597140 I | op-mgr: the dashboard secret was already generated
2020-04-22 09:30:03.597187 I | op-mgr: setting ceph dashboard "admin" login creds
2020-04-22 09:30:04.342646 I | op-mgr: successfully set ceph dashboard creds
2020-04-22 09:30:07.319339 I | op-mgr: dashboard config has changed. restarting the dashboard module.
2020-04-22 09:30:07.319364 I | op-mgr: restarting the mgr module
2020-04-22 09:30:09.698337 I | op-mgr: successful modules: dashboard
2020-04-22 09:30:09.740663 I | op-mgr: mgr metrics service already exists
2020-04-22 09:30:09.740693 I | op-mgr: starting monitoring deployment
W0422 09:30:09.741444       6 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2020-04-22 09:30:09.754420 I | op-mgr: servicemonitor enabled
W0422 09:30:09.757315       6 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2020-04-22 09:30:09.832011 I | op-mgr: prometheusRule deployed
2020-04-22 09:30:09.832047 I | op-osd: start running osds in namespace rook-ceph
2020-04-22 09:30:09.832057 I | op-osd: start provisioning the osds on pvcs, if needed
2020-04-22 09:30:09.838329 I | op-osd: successfully provisioned pvc "zone-a-0-data-lzh28" for VolumeClaimTemplates "data" for storageClassDeviceSet "zone-a" of set 0
2020-04-22 09:30:09.844104 I | op-osd: successfully provisioned pvc "zone-b-0-data-k5c6h" for VolumeClaimTemplates "data" for storageClassDeviceSet "zone-b" of set 0
2020-04-22 09:30:09.850087 I | op-osd: successfully provisioned pvc "zone-c-0-data-9gtht" for VolumeClaimTemplates "data" for storageClassDeviceSet "zone-c" of set 0
2020-04-22 09:30:09.872741 I | op-osd: skip OSD prepare pod creation as OSD daemon already exists for "zone-a-0-data-lzh28"
2020-04-22 09:30:09.917939 I | op-osd: skip OSD prepare pod creation as OSD daemon already exists for "zone-b-0-data-k5c6h"
2020-04-22 09:30:10.517752 I | op-osd: skip OSD prepare pod creation as OSD daemon already exists for "zone-c-0-data-9gtht"
2020-04-22 09:30:10.906920 I | op-osd: start osds after provisioning is completed, if needed
2020-04-22 09:30:11.307266 I | op-osd: osd orchestration status for node zone-a-0-data-lzh28 is completed
2020-04-22 09:30:11.307291 I | op-osd: starting 1 osd daemons on pvc zone-a-0-data-lzh28
2020-04-22 09:30:11.307302 I | cephclient: getting or creating ceph auth key "osd.0"
2020-04-22 09:30:12.325859 I | op-osd: deployment for osd 0 already exists. updating if needed
2020-04-22 09:30:12.722887 I | op-k8sutil: deployment "rook-ceph-osd-0" did not change, nothing to update
2020-04-22 09:30:12.722912 I | op-osd: started deployment for osd 0 on pvc
2020-04-22 09:30:12.912051 I | op-osd: osd orchestration status for node zone-b-0-data-k5c6h is completed
2020-04-22 09:30:12.912133 I | op-osd: starting 1 osd daemons on pvc zone-b-0-data-k5c6h
2020-04-22 09:30:12.912166 I | cephclient: getting or creating ceph auth key "osd.2"
2020-04-22 09:30:13.420041 I | op-osd: deployment for osd 2 already exists. updating if needed
2020-04-22 09:30:13.722683 I | op-k8sutil: deployment "rook-ceph-osd-2" did not change, nothing to update
2020-04-22 09:30:13.722713 I | op-osd: started deployment for osd 2 on pvc
2020-04-22 09:30:14.114560 I | op-osd: osd orchestration status for node zone-c-0-data-9gtht is completed
2020-04-22 09:30:14.114584 I | op-osd: starting 1 osd daemons on pvc zone-c-0-data-9gtht
2020-04-22 09:30:14.114599 I | cephclient: getting or creating ceph auth key "osd.1"
2020-04-22 09:30:15.125136 I | op-osd: deployment for osd 1 already exists. updating if needed
2020-04-22 09:30:15.522042 I | op-k8sutil: deployment "rook-ceph-osd-1" did not change, nothing to update
2020-04-22 09:30:15.522069 I | op-osd: started deployment for osd 1 on pvc
2020-04-22 09:30:15.711894 I | op-osd: start provisioning the osds on nodes, if needed
2020-04-22 09:30:15.711917 W | op-osd: skipping osd provisioning where no dataDirHostPath is set
2020-04-22 09:30:16.210310 I | op-osd: completed running osds in namespace rook-ceph
2020-04-22 09:30:16.210339 I | rbd-mirror: configure rbd-mirroring with 0 workers
2020-04-22 09:30:16.219366 I | rbd-mirror: no extra daemons to remove
2020-04-22 09:30:16.219385 I | op-cluster: Done creating rook instance in namespace rook-ceph
2020-04-22 09:30:16.226578 I | op-config: CephCluster "rook-ceph" status: "Ready". "Cluster updated successfully"
2020-04-22 09:30:16.260602 I | op-cluster: succeeded updating cluster in namespace "rook-ceph"
```

**Environment**:
* Cloud provider or hardware configuration: AWS
* Rook version (use `rook version` inside of a Rook Pod): 1.3.1
* Storage backend version (e.g. for ceph do `ceph -v`): Ceph v14.2.8
* Kubernetes version (use `kubectl version`): 1.16.7
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kops
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

### PR DESCRIPTION
**Pull request by travisn**
**Description of your changes:**
When the PVC template increases in size for the storageClassDeviceSet in the cluster CR, we need to increase the size of the PVC and restart the OSD. The OSD is restarted by changing a variable on the pod spec that indicates the desired size of the OSD.

@paalkr will plan on getting this in v1.3.6...

**Which issue is resolved by this Pull Request:**
Resolves #5309 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

[test ceph]

### CODE REVIEW

**Comment by paalkr** [comment]
Thx @travisn . Absolutely brilliant!

File: pkg/operator/ceph/cluster/osd/deviceSet.go [hunk 1]
```diff
@@ -107,14 +110,35 @@ func (c *Cluster) createStorageClassDeviceSetPVC(storageClassDeviceSetName strin
...
 
-func makeStorageClassDeviceSetPVC(storageClassDeviceSetName, pvcStorageClassDeviceSetPVCId string, setIndex int, pvcTemplate v1.PersistentVolumeClaim) (pvcs *v1.PersistentVolumeClaim) {
+func (c *Cluster) updatePVCIfChanged(desiredPVC *v1.PersistentVolumeClaim, currentPVC *v1.PersistentVolumeClaim) {
+	desiredSize, desiredOK := desiredPVC.Spec.Resources.Requests[v1.ResourceStorage]
+	currentSize, currentOK := currentPVC.Spec.Resources.Requests[v1.ResourceStorage]
+	if !desiredOK || !currentOK {
+		logger.Debugf("desired or current size are not specified for pvc %q", currentPVC.Name)
+		return
+	}
+	if desiredSize.Value() > currentSize.Value() {
```
Comment (leseb) [inline pkg/operator/ceph/cluster/osd/deviceSet.go:129]: Should we check if `desiredSize.Value() < currentSize.Value()` and print a message explaining it's unsupported?

File: pkg/operator/ceph/cluster/osd/deviceSet.go [hunk 2]
```diff
@@ -107,14 +110,35 @@ func (c *Cluster) createStorageClassDeviceSetPVC(storageClassDeviceSetName strin
...
+		currentPVC.Spec.Resources.Requests[v1.ResourceStorage] = desiredSize
+		logger.Infof("updating pvc %q size from %s to %s", currentPVC.Name, currentSize.String(), desiredSize.String())
+		if _, err := c.context.Clientset.CoreV1().PersistentVolumeClaims(c.Namespace).Update(currentPVC); err != nil {
+			// log the error, but don't fail the reconcile
+			logger.Errorf("failed to update pvc size. %+v", err)
```
Comment (leseb) [inline pkg/operator/ceph/cluster/osd/deviceSet.go:134]:
```suggestion
			logger.Errorf("failed to update pvc size. %v", err)
```

**Comment by satoru-takeuchi** [comment]
FYI: The KEP for the similar feature of StatefulSet.

Add StatefulSet Volume Expansion Kep #660
https://github.com/kubernetes/enhancements/pull/660

**Comment by satoru-takeuchi** [comment]
I hesitate to add this feature because it may cause serious problems if there are a lot of OSDs.

- Many OSD pods are restarted at once
- Many volume expansions would incur heavy load to the storage system. 
- A wrong operation causes the above-mentioned disaster easily, and the rollback will be very hard.

I consider that it's better to update the size of PVCs one by one.

**Comment by travisn** [comment]
@satoru-takeuchi Good questions, but I believe we are ok for reasons below...

> I hesitate to add this feature because it may cause serious problems if there are a lot of OSDs.
> 
> * Many OSD pods are restarted at once

The PVCs will all be increased in size immediately, but the OSDs will only be started one by one. The restarts will happen with the same procedure that we are already using for upgrades to start OSDs one by one.

> * Many volume expansions would incur heavy load to the storage system.

You are referring to the load from data rebalancing? This is an impact that will be good to document.

> * A wrong operation causes the above-mentioned disaster easily, and the rollback will be very hard.

What disaster will happen? The increased load to the system? 

> I consider that it's better to update the size of PVCs one by one.

Does the OSD restarting one at a time answer this concern?

File: pkg/operator/ceph/cluster/osd/deviceSet.go (hunk 1 above)
Comment (travisn) [reply pkg/operator/ceph/cluster/osd/deviceSet.go:129]: Agreed, will add a log message in that case.

**Comment by satoru-takeuchi** [comment]
> @satoru-takeuchi Good questions, but I believe we are ok for reasons below...
> 
> > I hesitate to add this feature because it may cause serious problems if there are a lot of OSDs.
> > 
> > * Many OSD pods are restarted at once
> 
> The PVCs will all be increased in size immediately, but the OSDs will only be started one by one. The restarts will happen with the same procedure that we are already using for upgrades to start OSDs one by one.

Got it.

> 
> > * Many volume expansions would incur heavy load to the storage system.
> 
> You are referring to the load from data rebalancing? This is an impact that will be good to document.

One of the loads is data rebalancing. The other is running many volume expansion simultaneously. IIRC, the volume expansion is asynchronous to restarting pods. Then, my concern is the possibility of heavy load in the storage systems. For example, moving the existing data to the new place before expansion behind the scene. However, I should admit I can't provide the real example.

I guess it would be able to avoid this problem by serializing the volume expansions too. In other words, expand PVC0 -> restart the Pod corresponding to PVC0 -> expand PVC1 -> restart the Pod corresponding to PVC1....

> 
> > * A wrong operation causes the above-mentioned disaster easily, and the rollback will be very hard.
> 
> What disaster will happen? The increased load to the system?

Yes.

> 
> > I consider that it's better to update the size of PVCs one by one.
> 
> Does the OSD restarting one at a time answer this concern?

As I said above, I'm also afraid of the many volume expansions at once.

**Comment by satoru-takeuchi** [comment]
> This is an impact that will be good to document.

If we wrote the document of this feature, we can't avoid the many rebalancing. If this feature waits until all PGs becomes active+clean for each Pod restarting, it's nice.

**Comment by travisn** [comment]
> I guess it would be able to avoid this problem by serializing the volume expansions too. In other words, expand PVC0 -> restart the Pod corresponding to PVC0 -> expand PVC1 -> restart the Pod corresponding to PVC1....

While it would be ideal to follow that pattern of increasing the PVC size and then the same OSD before increasing the next PVC size, it would really require a lot more change to the code. The impact to the Ceph cluster should really only come when the OSDs are restarted, which is already spaced out. 

> > This is an impact that will be good to document.
> 
> Even thoug we wrote the document of this feature, we can't avoid the many rebalancing. If this feature waits until all PGs becomes active+clean for each Pod restarting, it's nice.

Each OSD upgrade will wait 10-20 minutes for the PGs to become active+clean before continuing to upgrade the next OSD, so we should be covered.

**Comment by satoru-takeuchi** [comment]
Than kyou for your explanation, I understood and I'll review code. Please wait for one more day .
