### PR TITLE
ceph: periodically prune crash entries older than user-provided days

### LINKED ISSUE #6332: ceph crash periodic kubernetes cron job to prune crash
After some time, we might want to prune the log from the collector.
For this, we could expand the `crash` section of the CephCluster CR and add an option to remove crashes older than X days.

We could then schedule a Kubernetes cron to perform the `ceph crash prune <keep>`, command.

### PR DESCRIPTION
**Pull request by renan-campos**
Signed-off-by: Renan Campos <rcampos@redhat.com>

**Description of your changes:**
Rook's crashcollector pod posts entries to the ceph cluster when a crash occurs. 
Over time the number cluster may hold crash entries needlessly. 
To clean up old crash entries, this PR adds a field to the ceph cluster CR for the user to specify the number of days a crash entry should be kept for. 
Providing a value for the field keepXDays creates a cronjob that runs every day at midnight, calling "ceph crash prune <keepXDays>". 

**Which issue is resolved by this Pull Request:**
Resolves #6332 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

[test full]

### CODE REVIEW

**Review by travisn — CHANGES_REQUESTED** [review]
Thanks for the contribution!

File: pkg/operator/ceph/cluster/crash/crash.go [hunk 1]
```diff
@@ -126,6 +128,59 @@ func (r *ReconcileNode) createOrUpdateCephCrash(node corev1.Node, tolerations []
...
+	cronJob := &v1beta1.CronJob{
+		ObjectMeta: metav1.ObjectMeta{
+			Name:            fmt.Sprintf("%s-%s", AppName, "pruner"),
+			Namespace:       cephCluster.GetNamespace(),
+			OwnerReferences: []metav1.OwnerReference{clusterOwnerRef(cephCluster.GetName(), string(cephCluster.GetUID()))},
+		},
+	}
+
+	// Adding volumes to pods containing data needed to connect to the ceph cluster.
+	//volumes := controller.DaemonVolumesBase(config.NewDatalessDaemonDataPathMap(cephCluster.GetNamespace(), cephCluster.Spec.DataDirHostPath), "")
```
Comment (leseb) [inline pkg/operator/ceph/cluster/crash/crash.go:142]: ?

File: pkg/operator/ceph/cluster/crash/crash.go [hunk 2]
```diff
@@ -182,6 +237,36 @@ func getCrashDaemonContainer(cephCluster cephv1.CephCluster, cephVersion version
...
+	// Because there is no capability restricting to only "crash prune", this pod
+	// will have admin priviledges.
+	volumeMounts := controller.CephVolumeMounts(dataPathMap, false)
+
+	container := corev1.Container{
+		Name: "ceph-crash-pruner",
+		Command: []string{
+			"ceph",
+			"-c",
+			"/var/lib/rook/rook-ceph/rook-ceph.config",
```
Comment (leseb) [inline pkg/operator/ceph/cluster/crash/crash.go:253]: Where do you generate the config file?
If you just use `generateCrashEnvVar()` in `envVars` it will just work without the `-c ...`.

File: pkg/apis/ceph.rook.io/v1/types.go [hunk 3]
```diff
@@ -281,7 +281,8 @@ type ExternalSpec struct {
 
 // CrashCollectorSpec represents options to configure the crash controller
 type CrashCollectorSpec struct {
-	Disable bool `json:"disable"`
+	Disable   bool `json:"disable"`
+	KeepXDays int  `json:"keepXDays,omitempty"`
```
[the remark this answers is not in the document]
Comment (leseb) [reply pkg/apis/ceph.rook.io/v1/types.go:285]: Use `uint` as well.

File: pkg/operator/ceph/cluster/crash/crash.go [hunk 4]
```diff
@@ -126,6 +128,59 @@ func (r *ReconcileNode) createOrUpdateCephCrash(node corev1.Node, tolerations []
...
+					getCrashPruneContainer(cephCluster, *cephVersion),
+				},
+				RestartPolicy: corev1.RestartPolicyNever,
+				HostNetwork:   cephCluster.Spec.Network.IsHost(),
+				Volumes:       volumes,
+			},
+		}
+
+		// Run every day at midnight.
+		cronJob.Spec.Schedule = "0 0 * * *"
```
Comment (leseb) [inline pkg/operator/ceph/cluster/crash/crash.go:171]: Use a constant for the value.

**Review by leseb — CHANGES_REQUESTED** [review]

File: cluster/examples/kubernetes/ceph/common.yaml [hunk 5]
```diff
@@ -998,6 +1009,17 @@ rules:
   - delete
   - get
   - update
+- apiGroups:
```
[the remark this answers is not in the document]
Comment (renan-campos) [reply cluster/examples/kubernetes/ceph/common.yaml:1012]: I initially thought the `cronjobs` RBAC settings should be defined in the `rook-ceph-system` `Role`, however I found that trying to access `cronjobs` without the permissions being provided on the `ClusterRole` lead to access errors. Could this also be the case for `jobs` as well, which is why the permissions are specified in `ClusterRole`?

File: pkg/operator/ceph/cluster/crash/reconcile.go [hunk 6]
```diff
@@ -171,6 +174,44 @@ func (r *ReconcileNode) reconcile(request reconcile.Request) (reconcile.Result,
...
+				return reconcile.Result{}, err
+			}
+		} else {
+			logger.Debugf("keepXdays set to: %d", cephCluster.Spec.CrashCollector.KeepXDays)
+			// Create or update Cronjob
+			op, err := r.createOrUpdateCephCron(cephCluster, cephVersion)
+			if err != nil {
+				return reconcile.Result{}, errors.Wrapf(err, "node reconcile failed on op %q", op)
+			}
+			if op != controllerutil.OperationResultNone {
```
[the remark this answers is not in the document]
Comment (renan-campos) [reply pkg/operator/ceph/cluster/crash/reconcile.go:208]: The idea there was that if no change occurred to `cronjob`, then the reconcile wasn't called to update `cronjob` so it shouldn't return, but instead continue on to call `r.createOrUpdateCrash`.

File: cluster/examples/kubernetes/ceph/common.yaml (hunk 5 above)
[the remark this answers is not in the document]
Comment (travisn) [reply cluster/examples/kubernetes/ceph/common.yaml:1012]: Ok, I'm not seeing why it should be on the clusterrole instead of the role. Both of them have a binding to the rook-ceph-system service account. Since it's working, and to be consistent with the jobs, we can keep it on the ClusterRole. Then you shouldn't need to add it to the role, right?

File: pkg/operator/ceph/cluster/crash/crash.go (hunk 2 above)
Comment (renan-campos) [reply pkg/operator/ceph/cluster/crash/crash.go:253]: client.crash doesn't have the capability to run `ceph prune`, so I used this config in the rook_data mount because it had the admin keyring. But on second thought I could just change the client.crash capabilities instead. The change will be in the next push.

File: pkg/operator/ceph/cluster/crash/keyring.go [hunk 7]
```diff
@@ -33,7 +33,7 @@ const (
 [client.crash]
 	key = %s
 	caps mon = "allow profile crash"
```
Comment (renan-campos) [inline pkg/operator/ceph/cluster/crash/keyring.go:35]: Why is it necessary to specify the capabilities in the keyring file?

File: pkg/operator/ceph/cluster/crash/add.go [hunk 8]
```diff
@@ -39,7 +39,8 @@ import (
 const (
 	controllerName = "ceph-crashcollector-controller"
 	// AppName is the value to the "app" label for the ceph-crash pods
-	AppName = "rook-ceph-crashcollector"
+	AppName    = "rook-ceph-crashcollector"
+	PrunerName = "rook-ceph-crashcollector-pruner"
```
Comment (leseb) [inline pkg/operator/ceph/cluster/crash/add.go:43]: Why is `PrunerName` exported?

File: pkg/operator/ceph/cluster/crash/crash.go [hunk 9]
```diff
@@ -40,6 +41,8 @@ import (
 const (
 	crashCollectorKeyringUsername = "client.crash"
 	crashCollectorKeyName         = "rook-ceph-crash-collector-keyring"
+	// Pruner is schedualed to run every day at midnight.
```
Comment (leseb) [inline pkg/operator/ceph/cluster/crash/crash.go:44]:
```suggestion
	// pruneSchedule is scheduled to run every day at midnight.
```

File: pkg/operator/ceph/cluster/crash/crash.go [hunk 10]
```diff
@@ -182,6 +236,34 @@ func getCrashDaemonContainer(cephCluster cephv1.CephCluster, cephVersion version
...
+	envVars := append(controller.DaemonEnvVars(cephImage), generateCrashEnvVar())
+	dataPathMap := config.NewDatalessDaemonDataPathMap(cephCluster.GetNamespace(), cephCluster.Spec.DataDirHostPath)
+	volumeMounts := controller.DaemonVolumeMounts(dataPathMap, "")
+	volumeMounts = append(volumeMounts, keyring.VolumeMount().CrashCollector())
+
+	container := corev1.Container{
+		Name: "ceph-crash-pruner",
+		Command: []string{
+			"ceph",
+			"-n client.crash",
```
Comment (leseb) [inline pkg/operator/ceph/cluster/crash/crash.go:250]:
```suggestion
			"-n",
			"client.crash",
```

Make `client.crash` a constant coming from `pkg/operator/ceph/cluster/crash/keyring.go`.

File: pkg/operator/ceph/cluster/crash/reconcile.go [hunk 11]
```diff
@@ -171,6 +173,35 @@ func (r *ReconcileNode) reconcile(request reconcile.Request) (reconcile.Result,
 			return reconcile.Result{}, nil
 		}
 
+		// ceph crash prune configuration
+		if cephCluster.Spec.CrashCollector.DaysToRetain < 1 {
+			logger.Debugf("Deleting cronjob if it exists...")
```
Comment (leseb) [inline pkg/operator/ceph/cluster/crash/reconcile.go:178]: You have this message twice.

File: pkg/operator/ceph/cluster/crash/reconcile.go [hunk 12]
```diff
@@ -171,6 +173,35 @@ func (r *ReconcileNode) reconcile(request reconcile.Request) (reconcile.Result,
...
+			cronJob := &v1beta1.CronJob{
+				ObjectMeta: metav1.ObjectMeta{
+					Name:      PrunerName,
+					Namespace: namespace,
+				},
+			}
+			logger.Debugf("Deleting cronjob if it exists...")
+			err := r.client.Delete(context.TODO(), cronJob)
+			if err == nil {
```
Comment (leseb) [inline pkg/operator/ceph/cluster/crash/reconcile.go:187]: Why do we ignore the error?

**Review by leseb — CHANGES_REQUESTED** [review]

File: pkg/operator/ceph/cluster/crash/add.go (hunk 8 above)
Comment (renan-campos) [reply pkg/operator/ceph/cluster/crash/add.go:43]: No reason, just a habit of capitalizing global vars will change.

File: pkg/operator/ceph/cluster/crash/reconcile.go (hunk 12 above)
Comment (renan-campos) [reply pkg/operator/ceph/cluster/crash/reconcile.go:187]: Following @travisn 's suggestion above to just delete the cronjob and ignore errors if the cronjob isn't present. I don't see a way from the documentation to distinguish between errors returned by Delete, so I was assuming that if Delete fails then the cronjob doesn't exist. But thinking about it a little more, it does make more sense to check for the cron job first before deleting so that the reconciler doesn't have to keep calling Delete all the time.

Comment (travisn) [reply pkg/operator/ceph/cluster/crash/reconcile.go:187]: Instead of calling `Get()`, then `Delete()` if it exists, it's faster just to call `Delete()` and then ignore the failure if it's `errors.IsNotFound(err)`. If you search for that, you should see a number of examples.

Comment (renan-campos) [reply pkg/operator/ceph/cluster/crash/reconcile.go]: Ah just found an example of that right after I sent my comment so I deleted it an made the change you just suggested.

File: pkg/operator/ceph/cluster/crash/reconcile.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (sp98) [reply pkg/operator/ceph/cluster/crash/reconcile.go:205]: Still a bit confused about this check.  If the `op` is `created`, then line 205 will be true and return. So `r.createOrUpdateCrash` won't be called.

**Review by sp98 — COMMENTED** [review]
Some nits and one query.

**Comment by renan-campos** [comment]
Why does the unit test keep failing?

**Comment by subhamkrai** [comment]
> Why does the unit test keep failing?

you might want to update unit test. see the logs test `TestCephCrashCollectorKeyringCaps` is failing.

File: pkg/operator/ceph/cluster/crash/reconcile.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (renan-campos) [reply pkg/operator/ceph/cluster/crash/reconcile.go:205]: Sorry I misunderstood the flow and now see that it shouldn't return when an update/creation occurs. 

But now I'm confused: Where `r.createOrUpdateCrash` resides is looping through namespaces that contain ceph pods, why does any operation within this loop return? Shouldn't it continue to check the next namespace?

**Comment by renan-campos** [comment]
Thanks @subhamkrai. So you grep for FAIL in the test log to find the errors... actually seems pretty obvious now that I'm typing it out.

File: tests/framework/installer/ceph_manifests.go [hunk 13]
```diff
@@ -1051,6 +1051,7 @@ rules:
   - batch
   resources:
   - jobs
+	- cronjobs
```
Comment (sp98) [inline tests/framework/installer/ceph_manifests.go:1054]: indent looks off.

Comment (subhamkrai) [reply tests/framework/installer/ceph_manifests.go:1054]: I see CI is failing due to indent, in `manifests.go` we use `space` instead of `tab` IIRC and earlier I had  similar kind of issue. Not sure but this might be the reason.

File: tests/framework/installer/ceph_manifests.go [hunk 14]
```diff
@@ -1051,6 +1051,7 @@ rules:
   - batch
   resources:
   - jobs
+  - cronjobs
   verbs:
```
Comment (travisn) [inline tests/framework/installer/ceph_manifests.go:1055]: In the integration tests, let's add a check that the crash collector pruner job is able to be created successfully. For example:
- In the `GetRookCluster()` method in this test file, configure the new pruner setting
- In the `InstallRook()` method of ceph_installer.go, validate that the cronjob is created. In that method there are other examples of testing for the existence of the pods that may be helpful.

**Review by travisn — CHANGES_REQUESTED** [review]

File: pkg/operator/ceph/cluster/crash/reconcile.go [hunk 15]
```diff
@@ -192,6 +193,35 @@ func (r *ReconcileNode) reconcile(request reconcile.Request) (reconcile.Result,
 			}
 			logger.Debugf("deployment successfully reconciled for node %q. operation: %q", request.Name, op)
 		}
+
+		// ceph crash prune configuration
+		if cephCluster.Spec.CrashCollector.DaysToRetain < 1 {
```
Comment (leseb) [inline pkg/operator/ceph/cluster/crash/reconcile.go:198]: What about `== 0` instead since `DaysToRetain` is `uint`?

**Review by leseb — CHANGES_REQUESTED** [review]

File: pkg/operator/ceph/cluster/crash/crash.go [hunk 16]
```diff
@@ -40,6 +41,8 @@ import (
 const (
 	crashCollectorKeyringUsername = "client.crash"
 	crashCollectorKeyName         = "rook-ceph-crash-collector-keyring"
+	// pruneSchedule is scheduled to run every day at midnight.
+	pruneSchedule = "0 0 * * *"
```
[the remark this answers is not in the document]
Comment (renan-campos) [reply pkg/operator/ceph/cluster/crash/crash.go:45]: Well suppose the user only wants to keep crash entries for 7 days and a crash occurs on a Monday. If we ran the job every Friday, then the crash will be 12 days old when it gets pruned. Running it daily ensures the user expectation that there are never any crash entries present that are older than `daysToRetain` is satisfied.

File: tests/framework/installer/ceph_manifests.go (hunk 14 above)
Comment (renan-campos) [reply tests/framework/installer/ceph_manifests.go:2327]: I updated the integration test to include the suggested checks, but this caused the Jenkins job to fail. From the output of `tests/scripts/makeTestImages.sh`, it looks like the fail is caused by using the official ceph image instead of one built with the local changes, so it doesn't know how to process the `daysToRetain` field.

File: pkg/operator/ceph/cluster/crash/reconcile.go [hunk 17]
```diff
@@ -192,6 +193,35 @@ func (r *ReconcileNode) reconcile(request reconcile.Request) (reconcile.Result,
 			}
 			logger.Debugf("deployment successfully reconciled for node %q. operation: %q", request.Name, op)
 		}
+
+		// ceph crash prune configuration
+		if cephCluster.Spec.CrashCollector.DaysToRetain == 0 {
```
Comment (travisn) [inline pkg/operator/ceph/cluster/crash/reconcile.go:198]: This method is getting long, how about factoring the retention policy out to another method?

File: tests/framework/installer/ceph_manifests.go (hunk 14 above)
Comment (travisn) [reply tests/framework/installer/ceph_manifests.go:2327]: You'll need to skip this check for the upgrade suite. Those tests will start by installing v1.3, then upgrade to 1.4, etc. The cron job won't be created until the latest is installed. You should be able to skip it with a check like this:
```
  if rookVersion == VersionMaster {
    // wait for the cron job
  } 
```
You'll need to pass the rookVersion from the parent caller method.

Comment (travisn) [reply tests/framework/installer/ceph_manifests.go:2327]: I believe the other CI failures were intermittent. How about fixing this issue and let's see if there are any more failures.

**Review by travisn — CHANGES_REQUESTED** [review]

File: cluster/examples/kubernetes/ceph/cluster.yaml [hunk 18]
```diff
@@ -88,6 +88,7 @@ spec:
   # enable the crash collector for ceph daemon crash collection
   crashCollector:
     disable: false
+    daysToRetain: 30
```
Comment (travisn) [inline cluster/examples/kubernetes/ceph/cluster.yaml:91]: The doc says the default is to retain them indefinitely, but this shows 30. How about commenting this setting out by default so we get the default behavior in the example?

File: tests/scripts/webhook-create-signed-cert.sh [hunk 19]
```diff
@@ -26,6 +26,16 @@ EOF
     exit 1
 }
 
+checkKubectlVersion() {
```
Comment (travisn) [inline tests/scripts/webhook-create-signed-cert.sh:29]: Were you seeing integration tests fail locally, or what was the need for this?

Comment (renan-campos) [reply tests/scripts/webhook-create-signed-cert.sh:29]: Yes I the tests were failing locally and I didn't really understand why from the logs; the cause was found to be from a version mismatch, so I added this check.

**Review by leseb — CHANGES_REQUESTED** [review]
Sorry if this comment comes late, but I just realized something. Why can't we just run this command from the operator code directly instead of the k8s job? The k8s job seems a bit over-engineered and the `ceph crash prune` could simply run inside the operator. It's not a "local" command as far as I know.

**Comment by renan-campos** [comment]
To be honest, I went with this way because it was the easiest to implement, debug, and test. I think it will also be the simplest way to maintain. We don't have to test any time logic since that's handled by CronJob, and if something goes wrong, there's artifacts besides logs that can be used to debug it. I don't see what could be gained by having the operator do it.

File: tests/scripts/webhook-create-signed-cert.sh (hunk 19 above)
Comment (leseb) [reply tests/scripts/webhook-create-signed-cert.sh:29]: Please make this a specific commit since it's unrelated to the main implemenation.

**Review by leseb — CHANGES_REQUESTED** [review]
One small thing, also please rebase, we will merge this week. Thanks for your patience.

**Review by leseb — APPROVED** [review]

**Comment by leseb** [comment]
CI intermittent failure on Jenkins, but passed on the Github Action job.
