### PR TITLE
Ensure the cluster channel is closed once

### LINKED ISSUE #618: operator crashes periodically with "panic: close of closed channel"
I noticed the rook-operator running master-latest (v0.3.1-99-gea2b435) had crashed a few times in the past couple hours:
```
> kubectl get pod
NAME                             READY     STATUS    RESTARTS   AGE
rook-operator-1641293690-h77mx   1/1       Running   3          2h
```

The logs show the reason for the crash:
```
> kubectl logs --previous=true rook-operator-1641293690-h77mx
<ommitted>
2017-04-28 02:17:56.987758 W | operator: cancelling cluster tpr watch. failed to poll cluster event. EOF
2017-04-28 02:17:56.988055 E | operator: failed to watch clusters. received invalid event from API server: failed to poll cluster event. EOF
2017-04-28 02:17:56.988136 I | op-cluster: Stopping monitoring of cluster rook in namespace rook
panic: close of closed channel

goroutine 86 [running]:
github.com/rook/rook/pkg/operator.(*clusterManager).stopTrack(0xc4200cfe60, 0xc42040c3c0)
	/home/rook/go/src/github.com/rook/rook/pkg/operator/cluster.go:128 +0x1a1
github.com/rook/rook/pkg/operator.(*clusterManager).startCluster.func1(0xc4200cfe60, 0xc42040c3c0)
	/home/rook/go/src/github.com/rook/rook/pkg/operator/cluster.go:186 +0x2e7
created by github.com/rook/rook/pkg/operator.(*clusterManager).startCluster
	/home/rook/go/src/github.com/rook/rook/pkg/operator/cluster.go:186 +0x20c
```

Note that a very similar event happens for the pool TPR (EOF), but we recover from that one OK:
```
2017-04-28 02:01:12.361612 E | operator: failed to watch rook pool tpr. received invalid event from API server: failed to poll pool event. EOF. retrying...
2017-04-28 02:01:18.362424 I | operator: finding existing pools...
2017-04-28 02:01:18.366234 I | operator: found 1 pools. ensuring they exist.
2017-04-28 02:01:18.366317 I | operator: checking pool replicapool in namespace rook
2017-04-28 02:01:18.376719 I | op-cluster: pool replicapool already exists in namespace rook 
2017-04-28 02:01:18.376790 I | operator: start watching pool tpr in namespace rook: 11451
```

### PR DESCRIPTION
**Pull request by travisn**
Fixes #618

### CODE REVIEW

File: pkg/operator/tracker.go [hunk 1]
```diff
@@ -43,15 +43,19 @@ func (t *tprTracker) add(name, version string) {
 func (t *tprTracker) remove(name string) {
 	delete(t.clusterRVs, name)
 
+	t.Lock()
```
Comment (kokhang) [inline pkg/operator/tracker.go]: Would it cause problem if `delete(t.clusterRVs, name)` is not part of the lock?

File: pkg/operator/tracker.go [hunk 2]
```diff
@@ -43,15 +43,19 @@ func (t *tprTracker) add(name, version string) {
...
 }
 
 func (t *tprTracker) stop() {
+	t.Lock()
+	defer t.Unlock()
 	for _, stop := range t.stopChMap {
 		close(stop)
 	}
-	t.waitCluster.Wait()
+	t.stopChMap = map[string]chan struct{}{}
```
Comment (kokhang) [inline pkg/operator/tracker.go]: just curious about the need to initialize this map.

File: pkg/operator/tracker.go (hunk 1 above)
Comment (travisn) [inline pkg/operator/tracker.go]: no, the only conflict here would be with the `stop` function where the channel is closed and removed from that map

File: pkg/operator/tracker.go (hunk 2 above)
Comment (travisn) [inline pkg/operator/tracker.go]: we need to remove the channels from the map after they are closed so that a caller to `remove` or `stop` won't try to close them again. the easiest way is to create a new map

**Comment by travisn** [comment]
@jbw976 yes, there is an outer loop in `Manage()` of cluster.go that will retry after the failure

**Comment by jbw976** [comment]
Help me understand more then why the pool TPR didn't crash, but the cluster TPR did when they both got an EOF?

**Comment by travisn** [comment]
the cluster and pool TPRs have different handlers. The cluster pool is treated at an outer level, while the pool TPRs belong to a cluster. So the cluster implementation had the issue while the pool tpr was ok.
