### PR TITLE
fix testify.m flag

### LINKED ISSUE #1262: unable to run a specific integration test: "flag provided but not defined: -testify.m"
The `testify` flags no longer seem to be initialized, so I am not able to run a specific integration test on my laptop:
```
> go test -v -timeout 1800s -run SmokeSuite github.com/rook/rook/tests/integration -testify.m TestOperatorGetFlexvolumePath
flag provided but not defined: -testify.m
```

### PR DESCRIPTION
**Pull request by dangula**
found the issue after looking back at the commits and finding the commit the broke testify.m flag.  The current refator fixed the issue and running single test from a suite should be enabled again.
fix #1262 [smoke only]

### CODE REVIEW

**Comment by dangula** [comment]
the test flags are initialized in the installer package using init function. And calling the installer package multiple times from test is somehow faling to initilaize flags from vendors - the testify.m flag. I know init gets only called once, so all flags are initialized just once, but somehow calling the packing multiple times from test is not initializing flags from vendor/dependencies. It is really strange, and i can't find docs to support what i am seeing. But Tried other things, like moving the init to another package and making ever func under installer pakcage a member function, but still failed.

**Comment by jbw976** [comment]
Hmm, I am never comfortable with not understanding why a change makes something work :)

I'm wondering if our call to `flag.Parse()` in https://github.com/rook/rook/blob/master/tests/framework/objects/environment_manifest.go#L44, which is currently called from the installer package's `init()` func, is causing issues.  According to https://golang.org/pkg/flag/#Parse:
> Must be called after all flags are defined

It seems like testify already calls `flag.Parse()` in it's main entry point: https://github.com/stretchr/testify/blob/master/_codegen/main.go#L39

Maybe we should remove our call to `flag.Parse()` and see if just that one change by itself fixes this issue?

**Comment by dangula** [comment]
thanks @jbw976 , simply removing the flag.Parse() fixed the issue. I was looking at the wrong place,and assumed that testify was not calling flag.parse().

File: tests/framework/objects/environment_manifest.go [hunk 1]
```diff
@@ -41,7 +41,7 @@ func NewManifest() EnvironmentManifest {
 	flag.IntVar(&e.LoadConcurrentRuns, "load_parallel_runs", 20, "number of routines for load test")
 	flag.IntVar(&e.LoadVolumeNumber, "load_volumes", 1, "number of volumes(file,object or block) to be created for load test")
 	flag.IntVar(&e.LoadTime, "load_time", 1800, "number of seconds each thread perform operations for")
-	flag.Parse()
+	//flag.Parse()
```
Comment (jbw976) [inline tests/framework/objects/environment_manifest.go]: Nice, i'm glad the fix turned out to be this simple!! is there a reason to leave this as commented out?  Can we just delete it completely?
