### PR TITLE
mgr: failed to update the port of dashboard

### LINKED ISSUE #11931: mgr: update the port of mgr dashboard failed
https://github.com/rook/rook/blob/5832d564763b5b011df3c69101a2096a2422f76d/pkg/operator/ceph/cluster/mgr/dashboard.go#L91

Produce:

1. enable dashboard, set the port with 443 or 6443 that it was occupied by other server;
2. the dashboard willl start failed with:
  **Module 'dashboard' has failed: OSError("No socket could be created -- (('::', 443, 0, 0): [Errno 13] Permission denied)",**
3. status of ceph is 
```
    cluster:
    id:     f329ada2-776f-4ee9-8552-af85c27215d1
    health: HEALTH_ERR
            Module 'dashboard' has failed: OSError("No socket could be created -- (('::', 443, 0, 0): [Errno 13] Permission denied)",)
 
  services:
    mon: 3 daemons, quorum a,b,c (age 109s)
    mgr: b(active, since 7s), standbys: a
    osd: 6 osds: 6 up (since 11s), 6 in (since 7d)
    rgw: 3 daemons active (3 hosts, 1 zones)
 
  data:
    pools:   10 pools, 169 pgs
    objects: 493 objects, 257 MiB
    usage:   1.1 GiB used, 599 GiB / 600 GiB avail
    pgs:     169 active+clean
```
4. update the port of  the dashboard that the port not be occupied, the status of the ceph is always error.

because of after update the port , the "ceph dashboard ac-user-create admin xx" run failed, so after update the port, we need to restart the dashboard firstly and then exec "c.initializeSecureDashboard()", the response of the "c.initializeSecureDashboard()" is always false.

### PR DESCRIPTION
**Pull request by zhucan**
**Description of your changes:**
Firstly we use the port 443 or 6443 to mgr dashboard, but it was used by other daemon; The dashboard will start failed and the status of the ceph will be HEALTH_ERR; then we update the port to a unused port，the operator can not deal with it. after this change,  dashboard can start normally and the status of ceph will be HEALTH_OK.

**Which issue is resolved by this Pull Request:**
Resolves #11931 

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by zhucan** [comment]
releated qa: https://github.com/rook/rook/discussions/11916#discussioncomment-5363800

**Review by subhamkrai — COMMENTED** [review]
@zhucan can you explain more about the changes in pr description? Thanks!

**Comment by zhucan** [comment]
> @zhucan can you explain more about the changes in pr description? Thanks!

Please take a look at the https://github.com/rook/rook/issues/11931，because firstly we use the port 443 or 6443, but it was used by other daemon，the dashboard will start failed and the status of the ceph will be err，then we update the port to a unused port，the operator can not deal with it.

**Comment by travisn** [comment]
@zhucan Please also fill in the PR description section: `Description of your changes:`

**Comment by zhucan** [comment]
@travisn  done

File: pkg/operator/ceph/cluster/mgr/dashboard.go [hunk 1]
```diff
@@ -104,7 +100,13 @@ func (c *Cluster) configureDashboardModules() error {
 	}
 	if hasChanged {
 		logger.Info("dashboard config has changed. restarting the dashboard module")
-		return c.restartDashboard()
+		if err := c.restartDashboard(); err != nil {
+			return errors.Wrap(err, "failed to restart dashboard")
+		}
+	}
+	_, err := c.initializeSecureDashboard()
```
Comment (travisn) [inline pkg/operator/ceph/cluster/mgr/dashboard.go:107]: It looks like `initializeSecureDashboard()` always returns false. In that case, please update that method to just return the err instead of ignoring the return value.  
```suggestion
	err := c.initializeSecureDashboard()
```

File: pkg/operator/ceph/cluster/mgr/dashboard.go [hunk 2]
```diff
@@ -104,7 +100,13 @@ func (c *Cluster) configureDashboardModules() error {
 	}
 	if hasChanged {
 		logger.Info("dashboard config has changed. restarting the dashboard module")
-		return c.restartDashboard()
+		if err := c.restartDashboard(); err != nil {
```
Comment (travisn) [inline pkg/operator/ceph/cluster/mgr/dashboard.go:103]: Don't we need to restart the dashboard after the ssl cert is generated? Now we won't restart the dashboard if the ssl setting changes, won't that be a problem? Perhaps we need another dashboard restart inside `initializeSecureDashboard()` in that case.

**Review by travisn — CHANGES_REQUESTED** [review]

File: pkg/operator/ceph/cluster/mgr/dashboard.go (hunk 2 above)
Comment (zhucan) [reply pkg/operator/ceph/cluster/mgr/dashboard.go:103]: https://github.com/rook/rook/blob/473d8f89cfebda07316e3f178e7f2930ff05942d/pkg/operator/ceph/cluster/mgr/dashboard.go#L91 The response is always false,  if the configure of the dashboard  not change, it will not restart under previous reality. we had tested with this case?

Comment (zhucan) [reply pkg/operator/ceph/cluster/mgr/dashboard.go:103]: other question is:  after the ssl cert is generated, need to restart dashboard? we had tested with this case? may need to test the case.

Comment (zhucan) [reply pkg/operator/ceph/cluster/mgr/dashboard.go:103]: @travisn please take a look at it

File: pkg/operator/ceph/cluster/mgr/dashboard.go [hunk 3]
```diff
@@ -148,30 +150,30 @@ func (c *Cluster) configureDashboardModuleSettings(daemonID string) (bool, error
...
 	if c.spec.Dashboard.SSL {
 		alreadyCreated, err := c.createSelfSignedCert()
 		if err != nil {
-			return false, errors.Wrap(err, "failed to create a self signed cert for the ceph dashboard")
+			return errors.Wrap(err, "failed to create a self signed cert for the ceph dashboard")
 		}
 		if alreadyCreated {
-			return false, nil
+			return nil
 		}
```
Comment (travisn) [inline pkg/operator/ceph/cluster/mgr/dashboard.go:169]: How about restarting the dashboard after generating the cert the first time, just to be safe?
```suggestion
		} else {
			if err := c.restartDashboard(); err != nil {
				logger.Warningf("failed to restart dashboard after generating ssl cert. %v", err)
			}
		}
```

File: pkg/operator/ceph/cluster/mgr/dashboard.go [hunk 4]
```diff
@@ -106,6 +102,11 @@ func (c *Cluster) configureDashboardModules() error {
 		logger.Info("dashboard config has changed. restarting the dashboard module")
 		return c.restartMgrModule(dashboardModuleName)
 	}
+	err := c.initializeSecureDashboard()
+	if err != nil {
+		return errors.Wrap(err, "failed to initialize dashboard")
+
```
Comment (travisn) [inline pkg/operator/ceph/cluster/mgr/dashboard.go:108]: nit: remove blank line before end bracket

File: pkg/operator/ceph/cluster/mgr/dashboard.go [hunk 5]
```diff
@@ -148,30 +149,34 @@ func (c *Cluster) configureDashboardModuleSettings(daemonID string) (bool, error
...
 	if c.spec.Dashboard.SSL {
 		alreadyCreated, err := c.createSelfSignedCert()
 		if err != nil {
-			return false, errors.Wrap(err, "failed to create a self signed cert for the ceph dashboard")
+			return errors.Wrap(err, "failed to create a self signed cert for the ceph dashboard")
 		}
 		if alreadyCreated {
-			return false, nil
+			return nil
+		} else {
```
Comment (travisn) [inline pkg/operator/ceph/cluster/mgr/dashboard.go:168]: nit: no need for the `else` block since there was a `return` statement from the previous condition.
```suggestion
		} 
```

**Review by travisn — CHANGES_REQUESTED** [review]

**Review by travisn — APPROVED** [review]

**Review by travisn — CHANGES_REQUESTED** [review]
Actually, a fix is needed for the unit test `TestStartSecureDashboard`

**Comment by zhucan** [comment]
@travisn please take a look
