### PR TITLE
ceph: do not merge nodeAffinity

### LINKED ISSUE #7176: Placement of device set OSDs are merged with the .spec.resources.osd
Seems like https://github.com/rook/rook/pull/6918 introduced a regression when using both PVC OSDs and raw device OSDs in the same ceph cluster, which was added in https://github.com/rook/rook/pull/6822

If the raw device OSDs and the PVC OSDs have different resource requests and placement config, the .spec.resources.osd merges with what's defined at the deviceset placement spec.

cluster spec to illustrate the problem
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false 
  continueUpgradeAfterChecksEvenIfNotHealthy: true
  # removeOSDsIfOutAndSafeToRemove: true
  mon:
    count: 3
    allowMultiplePerNode: false
    volumeClaimTemplate:
      spec:
        storageClassName: ebs-gp2
        resources:
          requests:
            storage: 10Gi
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true 
    - name: balancer
      enabled: true                  
  placement:
    mon:
      podAntiAffinity:   
        preferredDuringSchedulingIgnoredDuringExecution:        
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - rook-ceph-mon
            topologyKey: failure-domain.beta.kubernetes.io/zone
    osd:
      tolerations:
      - key: k8s.gdo.aws/role
        operator: Equal
        value: storage-ephemeral
        effect: NoSchedule
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kops.k8s.io/instancegroup
              operator: In
              values:
              - storage-a-ephemeral 
              - storage-b-ephemeral
              - storage-c-ephemeral
    prepareosd:
      tolerations:
      - key: k8s.gdo.aws/role
        operator: Equal
        value: storage-ephemeral
        effect: NoSchedule
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kops.k8s.io/instancegroup
              operator: In
              values:
              - storage-a-ephemeral 
              - storage-b-ephemeral
              - storage-c-ephemeral
  resources:
    osd:
      limits:
        cpu: "3500m"
        memory: "25Gi"
      requests:
        cpu: "2500m"
        memory: "12Gi"
    prepareosd:
      limits:
        cpu: "500m"
        memory: "2Gi"
      requests:
        cpu: "200m"
        memory: "1Gi"
  cephVersion:
    image: ceph/ceph:v15.2.4
    allowUnsupported: false
  dashboard:
    enabled: true
    urlPrefix: /ceph-dashboard
    port: 8443
    ssl: false
  monitoring:
    # requires Prometheus to be pre-installed
    enabled: true
    # namespace to deploy prometheusRule in. If empty, namespace of the cluster will be used.
    # Recommended:
    # If you have a single rook-ceph cluster, set the rulesNamespace to the same namespace as the cluster or keep it empty.
    # If you have multiple rook-ceph clusters in the same k8s cluster, choose the same namespace (ideally, namespace with prometheus
    # deployed) to set rulesNamespace for all the clusters. Otherwise, you will get duplicate alerts with multiple alert definitions.
    rulesNamespace: rook-ceph    
  network:
    hostNetwork: false
  crashCollector:
    disable: false
  # healthChecks
  # Valid values for daemons are 'mon', 'osd', 'status'
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    # Change pod liveness probe, it works for all mon,mgr,osd daemons
    livenessProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false  
  storage:
    topologyAware: true
    useAllNodes: true
    useAllDevices: true
    config:
      # osdsPerDevice: "1"
      deviceClass: nvme
    storageClassDeviceSets:
    - name: zone-a
      count: 1
      portable: true
      tuneDeviceClass: true
      resources:
        limits:
          cpu: "3500m"
          memory: "7Gi"
        requests:
          cpu: "3000m"
          memory: "6.5Gi"
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: k8s.gdo.aws/zone
                operator: In
                values:
                - a 
              - key: k8s.gdo.aws/role
                operator: In
                values:
                - storage   
        tolerations:
        - key: k8s.gdo.aws/role
          operator: Equal
          value: storage
          effect: NoSchedule                
      volumeClaimTemplates:
      - metadata:
          name: data
          annotations:
            crushDeviceClass: ssd
        spec:
          resources:
            requests:
              storage: 305Gi
          storageClassName: ebs-gp2
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
    - name: zone-b
      count: 1
      portable: true
      tuneDeviceClass: true
      resources:
        limits:
          cpu: "3500m"
          memory: "7Gi"
        requests:
          cpu: "3000m"
          memory: "6.5Gi"
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: k8s.gdo.aws/zone
                operator: In
                values:
                - b
              - key: k8s.gdo.aws/role
                operator: In
                values:
                - storage  
        tolerations:
        - key: k8s.gdo.aws/role
          operator: Equal
          value: storage
          effect: NoSchedule                
      volumeClaimTemplates:
      - metadata:
          name: data
          annotations:
            crushDeviceClass: ssd
        spec:
          resources:
            requests:
              storage: 305Gi
          storageClassName: ebs-gp2
          volumeMode: Block
          accessModes:
            - ReadWriteOnce 
    - name: zone-c
      count: 1
      portable: true
      tuneDeviceClass: true
      resources:
        limits:
          cpu: "3500m"
          memory: "7Gi"
        requests:
          cpu: "3000m"
          memory: "6.5Gi"
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: k8s.gdo.aws/zone
                operator: In
                values:
                - c
              - key: k8s.gdo.aws/role
                operator: In
                values:
                - storage 
        tolerations:
        - key: k8s.gdo.aws/role
          operator: Equal
          value: storage
          effect: NoSchedule
      volumeClaimTemplates:
      - metadata:
          name: data
          annotations:
            crushDeviceClass: ssd
        spec:
          resources:
            requests:
              storage: 305Gi
          storageClassName: ebs-gp2
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
```

The rendered pvc OSD deployment for deviceset `zone-a` ends up with this affinity rules, which will not satisfy any of the nodes in the cluster. 

deployment for DeviceSet `zone-a`
```
  spec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: k8s.gdo.aws/zone
              operator: In
              values:
              - a
            - key: k8s.gdo.aws/role
              operator: In
              values:
              - storage
            - key: kops.k8s.io/instancegroup
              operator: In
              values:
              - storage-a-ephemeral
              - storage-b-ephemeral
              - storage-c-ephemeral
```

deployment for DeviceSet `zone-b`
```
  spec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: k8s.gdo.aws/zone
              operator: In
              values:
              - b
            - key: k8s.gdo.aws/role
              operator: In
              values:
              - storage
            - key: kops.k8s.io/instancegroup
              operator: In
              values:
              - storage-a-ephemeral
              - storage-b-ephemeral
              - storage-c-ephemeral
```

deployment for DeviceSet `zone-c`
```
  spec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: k8s.gdo.aws/zone
              operator: In
              values:
              - c
            - key: k8s.gdo.aws/role
              operator: In
              values:
              - storage
            - key: kops.k8s.io/instancegroup
              operator: In
              values:
              - storage-a-ephemeral
              - storage-b-ephemeral
              - storage-c-ephemeral
```

### PR DESCRIPTION
**Pull request by subhamkrai**
we don't want to merge the node affinity if specified in both
storageClassDeviceSet and placement. 

**Description of your changes:**
Now, we are passing new
a boolean argument in `ApplyToPodSpec` which will be false in 
case of osd and prepare pods only because we don't want to overlap 
placement of osd on PVC's and non-PVC's.

Signed-off-by: subhamkrai <srai@redhat.com>

**Which issue is resolved by this Pull Request:**
Resolves #7176 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

File: pkg/operator/ceph/cluster/osd/provision_spec.go [hunk 1]
```diff
@@ -157,6 +157,8 @@ func (c *Cluster) provisionPodTemplateSpec(osdProps osdProperties, restart v1.Re
 	p := cephv1.GetOSDPlacement(c.spec.Placement)
 	if !osdProps.onPVC() {
 		p.ApplyToPodSpec(&podSpec)
+	} else if osdProps.getPreparePlacement().NodeAffinity != nil {
+		osdProps.getPreparePlacement().ApplyToPodSpec(&podSpec)
 	} else {
 		osdProps.getPreparePlacement().ApplyToPodSpec(&podSpec)
 		p.ApplyToPodSpec(&podSpec)
```
Comment (BlaineEXE) [inline pkg/operator/ceph/cluster/osd/provision_spec.go:164]: If I understand the if-elseif-else block correctly...
- if this is not an OSD on PVC, only apply the OSD placement
- if prepare pod placement node affinity is set, only use prepare pod placement
- if it is an osd on pvc and prepare pod placement isn't set, we still merge prepare and osd spec

This doesn't seem to be quite what is intended.

Also, why do we only care about the `NodeAffinity` property of the prepare placement? We don't care about pod affinity/anti-affinity?

File: pkg/operator/ceph/cluster/osd/spec.go [hunk 2]
```diff
@@ -634,9 +634,12 @@ func (c *Cluster) makeDeployment(osdProps osdProperties, osd OSDInfo, provisionC
 	controller.AddCephVersionLabelToDeployment(c.clusterInfo.CephVersion, deployment)
 	controller.AddCephVersionLabelToDeployment(c.clusterInfo.CephVersion, deployment)
 	k8sutil.SetOwnerRef(&deployment.ObjectMeta, &c.clusterInfo.OwnerRef)
+
 	p := cephv1.GetOSDPlacement(c.spec.Placement)
 	if !osdProps.onPVC() {
 		p.ApplyToPodSpec(&deployment.Spec.Template.Spec)
+	} else if osdProps.placement.NodeAffinity != nil {
+		osdProps.placement.ApplyToPodSpec(&deployment.Spec.Template.Spec)
```
[the remark this answers is not in the document]
Comment (BlaineEXE) [reply pkg/operator/ceph/cluster/osd/spec.go:642]: Actually I see these are different. One for prepare and one for the osd itself. Disregard.

**Comment by BlaineEXE** [comment]
It might be good to write a method on the placement API spec where we can query `<placement>.IsSet()`. Since we only want to apply one placement or another, we can do something like 
```
if osd.IsOnPVC() && osd.placement.IsSet() {
  // use storageClassDeviceSet placement
} else if osdPlacement.IsSet() {
  // use osd placement
} else if preparePlacement.IsSet() {
  // use prepare Placement
}
```

File: pkg/operator/ceph/cluster/osd/provision_spec.go [hunk 3]
```diff
@@ -157,6 +157,8 @@ func (c *Cluster) provisionPodTemplateSpec(osdProps osdProperties, restart v1.Re
 	p := cephv1.GetOSDPlacement(c.spec.Placement)
 	if !osdProps.onPVC() {
 		p.ApplyToPodSpec(&podSpec)
+	} else if osdProps.getPreparePlacement().NodeAffinity != nil {
+		osdProps.getPreparePlacement().ApplyToPodSpec(&podSpec)
```
Comment (travisn) [inline pkg/operator/ceph/cluster/osd/provision_spec.go:161]: The merging of node affinity was really only done for mons since the mons have some affinity generated by the operator, to be merged with the placement in the CR. We basically don't want/need to have the merging for OSD pod specs. How about this approach?
- Add a new bool param to `ApplyToPodSpec()` that indicates if it should merge the properties. If false, it would skip the logic that merges the node affinity.
- The OSDs would pass `false`. 
- Other daemons would pass `true`.

File: pkg/operator/ceph/cluster/osd/spec.go [hunk 4]
```diff
@@ -634,9 +634,12 @@ func (c *Cluster) makeDeployment(osdProps osdProperties, osd OSDInfo, provisionC
 	controller.AddCephVersionLabelToDeployment(c.clusterInfo.CephVersion, deployment)
 	controller.AddCephVersionLabelToDeployment(c.clusterInfo.CephVersion, deployment)
 	k8sutil.SetOwnerRef(&deployment.ObjectMeta, &c.clusterInfo.OwnerRef)
+
 	p := cephv1.GetOSDPlacement(c.spec.Placement)
```
Comment (travisn) [inline pkg/operator/ceph/cluster/osd/spec.go:638]: Unrelated to this PR, seems like we could simplify the pattern to be:
```go
p := cephv1.GetOSDPlacement(c.spec.Placement)
if osdProps.onPVC() {
  osdProps.getPreparePlacement().ApplyToPodSpec(&podSpec)
}
p.ApplyToPodSpec(&podSpec) 
```
no need to duplicate the last line in both the if and else if

**Review by travisn — CHANGES_REQUESTED** [review]

File: pkg/operator/ceph/cluster/osd/provision_spec.go (hunk 1 above)
Comment (subhamkrai) [reply pkg/operator/ceph/cluster/osd/provision_spec.go]: going with this (https://github.com/rook/rook/pull/7192#discussion_r573964162) approach

File: pkg/operator/ceph/cluster/osd/provision_spec.go [hunk 5]
```diff
@@ -155,12 +155,11 @@ func (c *Cluster) provisionPodTemplateSpec(osdProps osdProperties, restart v1.Re
...
 	p := cephv1.GetOSDPlacement(c.spec.Placement)
-	if !osdProps.onPVC() {
-		p.ApplyToPodSpec(&podSpec)
-	} else {
-		osdProps.getPreparePlacement().ApplyToPodSpec(&podSpec)
-		p.ApplyToPodSpec(&podSpec)
+	if osdProps.onPVC() {
+		osdProps.getPreparePlacement().ApplyToPodSpec(&podSpec, false)
 	}
+	p.ApplyToPodSpec(&podSpec, false)
```
Comment (travisn) [inline pkg/operator/ceph/cluster/osd/provision_spec.go:161]: How about adding a comment about why we don't want to merge the osd placement, since we don't want the placement for osds on pvcs and non-pvcs to overlap.

Comment (subhamkrai) [reply pkg/operator/ceph/cluster/osd/provision_spec.go:161]: Added.

**Review by travisn — APPROVED** [review]

**Comment by subhamkrai** [comment]
#7236
