### PR TITLE
tests: stabilize check for deleted pool

### LINKED ISSUE #1095: e2e random test failure checking for a deleted pool
The block store test failed when checking that a pool was deleted. 
```
--- FAIL: TestBlockStoreOnRookInstalledViaHelm (23.93s)
	assertions.go:237: 
                        
	Error Trace:	base_block_test.go:160
		
			base_block_test.go:146
		
			base_block_test.go:140
		
			helm_test.go:79
		
	Error:		Expected nil, but got: client.RookRestError{Query:"pool", Status:500, Body:[]uint8{}}
```

The api log shows that the rookpool status was not found. Likely it was in the middle of being deleted when the api service was querying for details since it returned error `2`.
```
2017-10-17 20:21:17.766744 I | api: 1196f990-3b1b-4169-93a2-abb524ec0e17	GET	/pool	GetPools	(start)
2017-10-17 20:21:17.766913 I | exec: Running command: ceph osd lspools --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/rook/rook/client.admin.keyring --format json --out-file /tmp/867946458
2017-10-17 20:21:18.063897 I | exec: Running command: ceph osd pool get rookpool all --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/rook/rook/client.admin.keyring --format json --out-file /tmp/802215281
2017-10-17 20:21:18.426942 I | exec: Error ENOENT: unrecognized pool 'rookpool'
2017-10-17 20:21:18.427282 E | api: failed to get pools: failed to get details for pool rookpool. failed to get pool rookpool details: exit status 2
2017-10-17 20:21:18.427319 I | api: 1196f990-3b1b-4169-93a2-abb524ec0e17	GET	/pool	GetPools	500 Internal Server Error	660.578637ms
```

### PR DESCRIPTION
**Pull request by travisn**
Fixes #1095

### CODE REVIEW

File: pkg/ceph/osd/agent_test.go [hunk 1]
```diff
@@ -355,9 +355,12 @@ func TestGetPartitionPerfScheme(t *testing.T) {
...
 	assert.Equal(t, 4, len(scheme.Metadata.Partitions))
 
-	// verify the first entry in the performance partition scheme.
+	// verify the first entry in the performance partition scheme.  note that the block device will either be sda or
+	// sdb because ordering of map traversal in golang isn't guaranteed.  Ensure that the first is either sda or sdb
+	// and that the second is the other one.
 	entry := scheme.Entries[0]
 	assert.Equal(t, 11, entry.ID)
+
 	// verify the first entry in the performance partition scheme.
```
Comment (jbw976) [inline pkg/ceph/osd/agent_test.go]: this comment is a dupe of the first sentence of the previous comment.  it can be removed i believe.

File: tests/integration/base_block_test.go [hunk 2]
```diff
@@ -143,7 +144,13 @@ func runBlockE2ETestLite(helper *clients.TestClient, k8sh *utils.K8sHelper, s su
 func checkPoolDeleted(helper *clients.TestClient, s suite.Suite, name string) {
 	i := 0
 	for i < utils.RetryLoop {
-		if !foundPool(helper, s, name) {
+		found, err := foundPool(helper, s, name)
+		if err != nil {
+			// try again on failure since the pool may have been in an unexpected state while deleting
+			logger.Warningf("error getting pools. %+v", err)
+			continue
```
Comment (jbw976) [inline tests/integration/base_block_test.go]: is a small sleep in between retries needed?

File: tests/integration/base_block_test.go [hunk 3]
```diff
@@ -154,16 +161,18 @@ func checkPoolDeleted(helper *clients.TestClient, s suite.Suite, name string) {
...
 	p := helper.GetPoolClient()
 	pools, err := p.PoolList()
-	assert.Nil(s.T(), err)
+	if err != nil {
+		return false, err
+	}
 	for _, pool := range pools {
 		if name == pool.Name {
-			return true
+			return false, nil
```
Comment (jbw976) [inline tests/integration/base_block_test.go]: why isn't this `return true, nil` meaning you found the pool?

File: pkg/ceph/osd/agent_test.go (hunk 1 above)
Comment (travisn) [reply pkg/ceph/osd/agent_test.go]: ah i see the dup now

File: tests/integration/base_block_test.go (hunk 2 above)
Comment (travisn) [reply tests/integration/base_block_test.go]: yes, definitely, good catch

File: tests/integration/base_block_test.go (hunk 3 above)
Comment (travisn) [reply tests/integration/base_block_test.go]: oops, not sure how that changed
