### PR TITLE
ceph: set rbd_default_map_options for encryption

### LINKED ISSUE #11522: rbd pvc map is failing with the encryption and compression enabled
```
sh-4.4# rbd --id csi-rbd-node -m 172.20.140.187:3300,172.20.104.208:3300,172.20.188.93:3300 --key=AQCqJ71jrg54HRAAde8KRRYjEwwr8xxxdzQ== map ocs-storagecluster-cephblockpool/csi-vol-973c00b8-90c4-11ed-94bc-0a580a83000f --device-type krbd --options noudev               
rbd: failed to get mon address (possible ms_mode mismatch)
In some cases useful info is found in syslog - try "dmesg | tail".
rbd: map failed: (2) No such file or directory
```

when the `rbd map` is run with `ms_mode=secure` the map succeed

```
sh-4.4# rbd --id csi-rbd-node -m 172.20.140.187:3300,172.20.104.208:3300,172.20.188.93:3300 --key=AQCqJ71jrg54HRAAde8KRRYjEwccccxddzQ/dzQ== map ocs-storagecluster-cephblockpool/csi-vol-973c00b8-90c4-11ed-94bc-0a580a83000f --device-type krbd --options noudev,ms_mode=secure
/dev/rbd0
```

I got to know from @idryomov that we need to set `ms_mode` option on the client side or else this is expected because v1 ports are assumed by default in the kernel client.

We have 2 options like below

* set `ms_mode` in storageclass parameters
* set `ms_mode` in ceph.conf >  this will not work as cephcsi is supposed with work with multiple ceph clusters, 1 cluster might have v1 ports and another cluster might have v2 ports enabled.

Thanks to @idryomov for helping to understand this one.

### PR DESCRIPTION
**Pull request by Madhu-1**
**Description of your changes:**

Set rbd_default_map_options to secure when encryption is enabled.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

**Which issue is resolved by this Pull Request:**
Resolves #11522 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

File: pkg/operator/ceph/cluster/cluster.go [hunk 1]
```diff
@@ -604,14 +604,18 @@ func (c *cluster) configureMsgr2() error {
 	monStore := config.GetMonStore(c.context, c.ClusterInfo)
 	if c.Spec.Network.Connections.Encryption != nil {
 		encryptionSetting := "crc secure"
+		// crc mode, if denied agree to secure mode
+		defaultRBDMapOptions := "prefer-crc"
```
Comment (idryomov) [inline pkg/operator/ceph/cluster/cluster.go:608]: This should be `ms_mode=prefer-crc`.

File: pkg/operator/ceph/cluster/cluster.go [hunk 2]
```diff
@@ -604,14 +604,18 @@ func (c *cluster) configureMsgr2() error {
...
 		if c.Spec.Network.Connections.Encryption.Enabled {
 			encryptionSetting = "secure"
+			defaultRBDMapOptions = "secure"
```
Comment (idryomov) [inline pkg/operator/ceph/cluster/cluster.go:611]: Ditto, `ms_mode=secure`.

**Comment by Madhu-1** [comment]
```
sh-4.4$ ceph config dump
WHO     MASK  LEVEL     OPTION                                 VALUE           RO
global        basic     log_to_file                            false             
global        advanced  mon_allow_pool_delete                  true              
global        advanced  mon_allow_pool_size_one                true              
global        advanced  mon_cluster_log_file                                     
global        basic     ms_client_mode                         secure          * 
global        basic     ms_cluster_mode                        secure          * 
global        basic     ms_service_mode                        secure          * 
global        advanced  rbd_default_map_options                ms_mode=secure  * 
mon           advanced  auth_allow_insecure_global_id_reclaim  false             
```

**Review by idryomov — APPROVED** [review]
LGTM but please test this

**Comment by Madhu-1** [comment]
```
sh-4.4$ ceph config dump
WHO                                      MASK  LEVEL     OPTION                                 VALUE                              RO
global                                         basic     log_to_file                            true                                 
global                                         advanced  mon_allow_pool_delete                  true                                 
global                                         advanced  mon_allow_pool_size_one                true                                 
global                                         advanced  mon_cluster_log_file                                                        
global                                         advanced  mon_pg_warn_min_per_osd                0                                    
global                                         basic     ms_client_mode                         secure                             * 
global                                         basic     ms_cluster_mode                        secure                             * 
global                                         advanced  ms_osd_compress_mode                   force                                
global                                         basic     ms_service_mode                        secure                             * 
global                                         advanced  rbd_default_map_options                ms_mode=secure                     * 
mon                                            advanced  auth_allow_insecure_global_id_reclaim  false                                
mgr                                            advanced  mgr/balancer/mode                      upmap                                
```

tested rbd map with above ceph config it worked

File: pkg/operator/ceph/cluster/cluster.go [hunk 3]
```diff
@@ -604,14 +604,18 @@ func (c *cluster) configureMsgr2() error {
 	monStore := config.GetMonStore(c.context, c.ClusterInfo)
 	if c.Spec.Network.Connections.Encryption != nil {
 		encryptionSetting := "crc secure"
+		// crc mode, if denied agree to secure mode
+		defaultRBDMapOptions := "ms_mode=prefer-crc"
```
Comment (travisn) [inline pkg/operator/ceph/cluster/cluster.go:608]: Should we just default to `crc`? Or why would crc be denied to fall back to secure? 
```suggestion
defaultRBDMapOptions := "ms_mode=crc"
```

Comment (Madhu-1) [reply pkg/operator/ceph/cluster/cluster.go:608]: @travisn i chose this one because of the encryption setting `encryptionSetting := "crc secure"`. Please let me know if you want me to modify this to crc?

Comment (travisn) [reply pkg/operator/ceph/cluster/cluster.go:608]: I see, it does match that behavior of the other encryption setting. Sounds good to keep it, I would expect it will always use crc in that case anyway, and wouldn't fall back to secure.

**Review by travisn — COMMENTED** [review]
Some of the tests actually enable encryption, but then enable fuse to avoid the kernel driver. Can you try disabling fuse [here](https://github.com/rook/rook/blob/f908bcdba2667ce62118a7eeb9124b7e87272f34/tests/framework/installer/ceph_manifests.go#L344-L348) in the tests to see if this fixes it?

**Comment by Madhu-1** [comment]
@travisn did the required tests passed or failed?

**Comment by Madhu-1** [comment]
```
  Warning  FailedMount  7m15s (x13 over 41m)  kubelet  Unable to attach or mount volumes: unmounted volumes=[csivol], unattached volumes=[csivol kube-api-access-xxshr]: time
d out waiting for the condition
  Warning  FailedMount  98s (x14 over 32m)    kubelet  (combined from similar events): MountVolume.MountDevice failed for volume "pvc-5103e7d5-2ce3-458b-9e4b-3eefb9840876" :
 rpc error: code = Internal desc = an error (exit status 32) occurred while running mount args: [-t ceph 10.98.7.250:3300:/volumes/csi/csi-vol-22aed57a-91c5-11ed-8ca0-0242ac
11000b/5e024b2c-c844-4645-a02d-c9a833030972 /var/lib/kubelet/plugins/kubernetes.io/csi/helm-ns.cephfs.csi.ceph.com/d8a4e9cf399adb7f85839069306831b645ec5821c978b1055d07120b6e
928858/globalmount -o name=csi-cephfs-node,secretfile=/tmp/csi/keys/keyfile-2614709560,mds_namespace=testfs,_netdev] stderr: 2023-01-11T16:13:19.697+0000 7f9f14844f40 -1 fai
led for service _ceph-mon._tcp
unable to get monitor info from DNS SRV with service name: ceph-mon
mount error: no mds server is up or the cluster is lagg
```
tests are failing reverting back the changes as we might not had required kernel bits

**Comment by idryomov** [comment]
> tests are failing reverting back the changes as we might not had required kernel bits

Just pointing out that this is a CephFS test and thus not really relevant.  CephFS obviously doesn't abide by `rbd_default_map_options` so you would most likely need to pass `-o ms_mode=secure` directly (or stay on `ceph-fuse` for CephFS).

Does Rook have a similar RBD test?

**Comment by travisn** [comment]
Oops, I should have suggested disabling the rbd-nbd in the tests [here](https://github.com/rook/rook/blob/f908bcdba2667ce62118a7eeb9124b7e87272f34/tests/framework/installer/ceph_manifests.go#L320).

**Comment by Madhu-1** [comment]
Updated PR, let's see how it goes.

**Comment by travisn** [comment]
> Updated PR, let's see how it goes.

The CI looks good now with that change! But something happened with the last push, can you rebase again?

**Review by travisn — APPROVED** [review]
