### PR TITLE
ceph: run bucket provisioner in multithreaded mode

### LINKED ISSUE #4907: Do not block OBC request handling on OBC deletion
* Bug Report

**Deviation from expected behavior:**
Deletion of an OBC whose OB has many entries blocks handling of subsequent OBC requests.

**Expected behavior:**
OBCs are deleted asynchronously.

**How to reproduce it (minimal and precise):**
1. Create an OBC.
2. Populate the OB owned by the OBC with several million entries.
3. Delete the OBC.
4. In another session, create another OBC.
Note the OB for the second OBC is not created until the first OBC is deleted.

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): 1.2.2
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.6
* Kubernetes version (use `kubectl version`): 1.11+
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OpenShift 3.11
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTHY

### PR DESCRIPTION
**Pull request by thotz**
**Description of your changes:**
The latest lib-bucket provisioner library supports multithreading via
env "LIB_BUCKET_PROVISIONER_THREADS". And that support is added is in this PR

**Which issue is resolved by this Pull Request:**
Resolves #4907

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by thotz** [comment]
@copejon @jeffvance  submitted PR in rook to consume the multithreading in the library

**Comment by thotz** [comment]
> I wonder if this is something we might want to expose as an Operator setting too. Thoughts?

Make more sense than hard corded value

File: pkg/operator/ceph/object/bucket/util.go [hunk 1]
```diff
@@ -47,12 +48,13 @@ const (
...
 	objectStoreNamespace = "objectStoreNamespace"
 	objectStoreEndpoint  = "endpoint"
+	threadcount          = "5"
 )
 
 func NewBucketController(cfg *rest.Config, p *Provisioner) (*provisioner.Provisioner, error) {
 	const allNamespaces = ""
 	provName := cephObject.GetObjectBucketProvisioner(p.context, p.namespace)
-
+	os.Setenv("LIB_BUCKET_PROVISIONER_THREADS", threadcount)
```
Comment (copejon) [inline pkg/operator/ceph/object/bucket/util.go:57]: I would think this would be set in the env (via the manifest) rather than hard coded.

Comment (travisn) [reply pkg/operator/ceph/object/bucket/util.go:57]: these are actually goroutines rather than threads, right? I assume we're just tied to the name of the env var from the bucket provisioner.

File: pkg/operator/ceph/object/bucket/util.go [hunk 2]
```diff
@@ -47,12 +48,13 @@ const (
 	objectStoreName      = "objectStoreName"
 	objectStoreNamespace = "objectStoreNamespace"
 	objectStoreEndpoint  = "endpoint"
+	threadcount          = "5"
```
Comment (jeffvance) [inline pkg/operator/ceph/object/bucket/util.go:51]: `bucketProvisionerNumThreads` is a more specific name and allows other operators to use a different thread count

File: pkg/operator/ceph/object/bucket/util.go (hunk 1 above)
Comment (jeffvance) [reply pkg/operator/ceph/object/bucket/util.go:57]: yes to goroutines but they are almost threads. I guess some are calling them _green_ threads: http://tleyden.github.io/blog/2014/10/30/goroutines-vs-threads/
The env var could have been named `LIB_BUCKET_CONCURRENCY_COUNT` to be more accurate.

Comment (jeffvance) [reply pkg/operator/ceph/object/bucket/util.go:57]: I agree with @copejon  that this env var should be set in the rook operator manifest, not in the code here.

**Comment by thotz** [comment]
@travisn @leseb the PR failed spuriously for jenkins job, can anyone please retrigger the job again?

File: pkg/operator/ceph/object/objectstore.go [hunk 3]
```diff
@@ -358,3 +359,12 @@ func GetObjectBucketProvisioner(c *clusterd.Context, namespace string) string {
 	}
 	return provName
 }
+
+func SetBucketProvisionerThreads(c *clusterd.Context) {
```
Comment (leseb) [inline pkg/operator/ceph/object/objectstore.go:363]: Shouldn't this be part of the bucket code instead?

File: pkg/operator/ceph/object/objectstore.go [hunk 4]
```diff
@@ -358,3 +359,12 @@ func GetObjectBucketProvisioner(c *clusterd.Context, namespace string) string {
...
+	bucketProvisionerNumThreads, err := k8sutil.GetOperatorSetting(c.Clientset, opcontroller.OperatorSettingConfigMapName, "ROOK_LIB_BUCKET_PROVISIONER_THREADS", "1")
```
Comment (leseb) [inline pkg/operator/ceph/object/objectstore.go:364]: Please make a constant for the default number of threads.

File: pkg/operator/ceph/object/objectstore.go [hunk 5]
```diff
@@ -358,3 +359,12 @@ func GetObjectBucketProvisioner(c *clusterd.Context, namespace string) string {
...
+	if err != nil {
+		logger.Warning("failed to fetch thread count for bucket provisioner")
+	} else {
+		os.Setenv("LIB_BUCKET_PROVISIONER_THREADS", bucketProvisionerNumThreads)
```
Comment (leseb) [inline pkg/operator/ceph/object/objectstore.go:368]: Use a constant for `LIB_BUCKET_PROVISIONER_THREADS`

File: pkg/operator/ceph/object/objectstore.go (hunk 3 above)
Comment (thotz) [reply pkg/operator/ceph/object/objectstore.go:363]: Done

**Comment by thotz** [comment]
@jeffvance addressed your comments from last patch

File: pkg/operator/ceph/object/bucket/util.go [hunk 6]
```diff
@@ -136,3 +142,12 @@ func randomString(n int) string {
 	}
 	return string(b)
 }
+
+func SetBucketProvisionerThreads(c *clusterd.Context) {
+	bucketProvisionerNumThreads, err := k8sutil.GetOperatorSetting(c.Clientset, opcontroller.OperatorSettingConfigMapName, "ROOK_LIB_BUCKET_PROVISIONER_THREADS", bucketProvisionerDefaultThreads)
+	if err != nil {
+		logger.Warning("failed to fetch thread count for bucket provisioner")
+	} else {
+		os.Setenv(libBucketProvisionerThreads, bucketProvisionerNumThreads)
```
Comment (travisn) [inline pkg/operator/ceph/object/bucket/util.go:151]: Why do we need any code changes for this? If the env var to set is `LIB_BUCKET_PROVISIONER_THREADS`, then the admin could just set that env var directly on the operator deployment spec (in operator.yaml).

File: cluster/examples/kubernetes/ceph/operator.yaml [hunk 7]
```diff
@@ -250,6 +250,8 @@ data:
 
   # Whether the OBC provisioner should watch on the operator namespace or not, if not the namespace of the cluster will be used
   ROOK_OBC_WATCH_OPERATOR_NAMESPACE: "true"
+  # The concurrency count of lib bucket provisioner
+  # ROOK_LIB_BUCKET_PROVISIONER_THREADS: "5"
```
Comment (jeffvance) [inline cluster/examples/kubernetes/ceph/operator.yaml:254]: why is this commented out (here and openshift yaml)?

File: cluster/examples/kubernetes/ceph/operator-openshift.yaml [hunk 8]
```diff
@@ -326,6 +326,8 @@ data:
 
   # Whether the OBC provisioner should watch on the operator namespace or not, if not the namespace of the cluster will be used
   ROOK_OBC_WATCH_OPERATOR_NAMESPACE: "true"
+  # The concurrency count of lib bucket provisioner
+  # ROOK_LIB_BUCKET_PROVISIONER_THREADS: "5"
```
Comment (jeffvance) [inline cluster/examples/kubernetes/ceph/operator-openshift.yaml:330]: I would move this value up to the `env` section for the rook-ceph operator container, rename it to be the same env var name handled by the lib, so "LIB_BUCKET_PROVISIONER_THREADS", and remove the rest of the code related to this. What is the reason for implementing it the way done in this PR?

File: pkg/operator/ceph/object/bucket/util.go (hunk 6 above)
Comment (thotz) [reply pkg/operator/ceph/object/bucket/util.go]: Make sense and modified

File: cluster/examples/kubernetes/ceph/operator-openshift.yaml (hunk 8 above)
Comment (thotz) [reply cluster/examples/kubernetes/ceph/operator-openshift.yaml]: My initial patch was setting env variable from rook code, never thought of using env variables in the pod until @travisn mentioned

Comment (jeffvance) [reply cluster/examples/kubernetes/ceph/operator-openshift.yaml]: I agree with @travisn (and @copejon wrote a similar comment earlier) that the env var should be set in the operator manifest. With that done I believe the rest of the changes in this

**Comment by thotz** [comment]
> Please add a release note

Done

**Comment by travisn** [comment]
@thotz Could you rebase on the latest to pick up a CI fix just merged?

**Comment by thotz** [comment]
> @thotz Could you rebase on the latest to pick up a CI fix just merged?

@travisn Done
