### PR TITLE
Ensure block images created by the operator's provisioner do not exce…

### LINKED ISSUE #599: volume provisioner fails on kernels older than 4.7
When running the rook operator's volume provisioner to create RBD storage in our CI environment, which is on an Ubuntu 16.04 LTS VM with kernel 4.4, the provisioner creates the block image but the RBD plugin fails to map and mount it.

These messages from `dmesg` show what looks like root cause:
```
[ 2992.389399] ceph_oid_set_name 'rbd_id.kubernetes-dynamic-pvc-0fd5988f-2516-11e7-aa55-02420ac00002-0fd85d37-2516-11e7-b212-0a580ac00203' len 103 vs 100, truncating
<ommitted>
[ 2992.392072] rbd: image replicapool/kubernetes-dynamic-pvc-0fd5988f-2516-11e7-aa55-02420ac00002-0fd85d37-2516-11e7-b212-0a580ac00203 does not exist
```

According to https://www.spinics.net/lists/ceph-devel/msg27755.html, `rbd map` will fail for image names longer than 100 chars.

This appears to be fixed in 4.7+ kernels here: https://github.com/torvalds/linux/commit/d30291b985d1854565d7f2c82a4457869d5265e8#diff-040a9fdaed0040bc9753eb3bf9c45b7e

Since the image name that operator's volume provisioner creates are of constant length, we can ensure that they are always less than 100 chars and be compatible with older kernels.

### PR DESCRIPTION
**Pull request by jbw976**
…ed 100 chars

Fixes #599

### CODE REVIEW

File: pkg/operator/provisioner.go [hunk 1]
```diff
@@ -201,3 +207,19 @@ func processMonAddresses(monAddresses []string) []string {
...
+	// image name should be under 100 chars to support kernels older than 4.7
+	// when the RBD kernel module converts the image name to an OID, it will use "rbd_id.<imageName>",
+	// so we have to leave room for that "rbd_id." prefix too.
+	pvNameMaxLen := imageNameMaxLen - len(rbdIDPrefix) - len(imageNamePrefix) - len(u) - 2 // 2 hyphens
+	if len(pvName) > pvNameMaxLen {
+		// the PV name is too long, truncate it before including it in the final image name
+		pvName = pvName[:pvNameMaxLen]
+	}
+
+	return fmt.Sprintf("%s-%s-%s", imageNamePrefix, pvName, u)
```
Comment (travisn) [inline pkg/operator/provisioner.go]: some naming questions:
1) why do we need a prefix? 
2) should we include `rook` in the name?
3) can we include the cluster name in the pv name?
4) if we include those, can we get rid of the trailing uuid?

Comment (jbw976) [inline pkg/operator/provisioner.go]: I'm not sure I have great answers to some of those questions since this was @kokhang's implementation first, although I think he was following some patterns used by the RBD in tree plug in.  However, I would guess that
1. we don't *need* a prefix, it's just a nice identifier to see at first glance which images were created by a dynamic provisioner.
1. Rook could indeed be put in the name, perhaps instead of k8s.
1. The cluster name isn't really necessary since images are only per cluster so including the cluster name would be somewhat redundant.
1. We don't have any control of the PV name coming in.  Depending on k8s environment, it could be different and I don't know what the rules are or if there's anything guaranteeing uniqueness.  Therefore, I'd be hesitant to not add a UUID of our own in, because I don't have any confidence that the PV name is unique itself.
