### PR TITLE
osd: fix CRUSH device class not applied during OSD re-discovery

### LINKED ISSUE #17227: OSD CRUSH device class not set during raw mode OSD reprovisioning
When a raw mode OSD is purged and reprovisioned (delete deployment, operator recreates), the CRUSH device class is not applied even though `deviceClass: nvme` is set in the CephCluster CR.

**Environment:** Rook v1.19.2, Ceph v19.2.3, raw mode OSDs on NVMe drives.

## Reproduction

1. Set `deviceClass: nvme` on NVMe devices in CephCluster CR
2. OSDs provision correctly with `nvme` device class
3. Purge an OSD: `ceph osd purge <id>`, delete its deployment
4. Operator reprovisions — new OSD comes up with no device class (shows blank in `ceph osd tree`)
5. `ceph osd metadata <id>` reports `default_device_class: ssd` (auto-detected) instead of `nvme`

## Root cause

The OSD deployment has `ROOK_OSD_DEVICE_CLASS=nvme` but the auto-detection in `GetDiskDeviceClass()` (`pkg/util/sys/device.go`) checks a different env var: `ROOK_OSD_CRUSH_DEVICE_CLASS`. During the prepare phase, `appendDeviceClassArg()` (`pkg/daemon/ceph/osd/volume.go:850`) passes `--crush-device-class nvme` to `ceph-volume raw prepare`, which should set it. But when `GetCephVolumeRawOSDs()` is called afterwards to build the `OSDInfo`, the device class at line 1313 is auto-detected via `GetDiskDeviceClass()` which doesn't find `ROOK_OSD_CRUSH_DEVICE_CLASS` in the environment, so it falls back to `GetDiskDeviceType()` which returns `ssd` (NVMe is non-rotational but the `RealPath` check for "nvme" may not match depending on the path used).

## Workaround

Manually set the class after reprovisioning:
```
ceph osd crush rm-device-class osd.<id>
ceph osd crush set-device-class nvme osd.<id>
```

### PR DESCRIPTION
**Pull request by ormandj**
Fixes #17227

When an OSD is purged and reprovisioned, it comes back without the correct CRUSH device class. NVMe devices configured with `deviceClass: nvme` in the CR end up as `ssd` (or no class at all in the CRUSH map).

The issue is in `GetCephVolumeRawOSDs()` it calls `GetDiskDeviceClass()` which checks `ROOK_OSD_CRUSH_DEVICE_CLASS`. That env var is only set during the prepare phase (passed to `ceph-volume raw prepare --crush-device-class`). During re-discovery (which happens when the operator recreates an OSD deployment), the env var is absent so it falls back to auto-detection. Auto-detection uses `GetDiskDeviceType()` which checks `disk.RealPath` for "nvme" — this works most of the time but can miss depending on the device path format.

Meanwhile, `ROOK_OSD_DEVICE_CLASS=nvme` (from the CR) is sitting right there in the OSD deployment env but never consulted.

Fix: when `ROOK_OSD_CRUSH_DEVICE_CLASS` isn't set and auto-detection is used, check `ROOK_OSD_DEVICE_CLASS` as a fallback. This is the value from the CR's `deviceClass` field, so it's always correct.

This is safe for existing clusters. If `ROOK_OSD_CRUSH_DEVICE_CLASS` is set (normal prepare path), the behavior is unchanged. The fallback only kicks in when auto-detection was going to be used anyway.

### CODE REVIEW

File: pkg/daemon/ceph/osd/volume.go [hunk 1]
```diff
@@ -1301,6 +1301,15 @@ func GetCephVolumeRawOSDs(context *clusterd.Context, clusterInfo *client.Cluster
...
 			crushDeviceClass := sys.GetDiskDeviceClass(oposd.CrushDeviceClassVarName, deviceType)
+			// ROOK_OSD_CRUSH_DEVICE_CLASS is only set during prepare; on re-discovery
+			// it's absent so GetDiskDeviceClass falls back to auto-detection which may
+			// return "ssd" for NVMe. Check ROOK_OSD_DEVICE_CLASS (set from the CR's
+			// deviceClass field) as a fallback.
+			if crushDeviceClass == deviceType {
+				if envClass := os.Getenv("ROOK_OSD_DEVICE_CLASS"); envClass != "" {
+					crushDeviceClass = envClass
+				}
+			}
```
Comment (travisn) [inline pkg/daemon/ceph/osd/volume.go]: Just a small suggestion to re-use the helper method to lookup the env var
```suggestion
			if crushDeviceClass == deviceType {
				crushDeviceClass = sys.GetDiskDeviceClass("ROOK_OSD_DEVICE_CLASS", deviceType)
			}
```

File: pkg/daemon/ceph/osd/volume.go [hunk 2]
```diff
@@ -1301,6 +1301,15 @@ func GetCephVolumeRawOSDs(context *clusterd.Context, clusterInfo *client.Cluster
 			logger.Infof("setting device type %q for device %q", osd.DeviceType, diskInfo.Name)
 
 			crushDeviceClass := sys.GetDiskDeviceClass(oposd.CrushDeviceClassVarName, deviceType)
+			// ROOK_OSD_CRUSH_DEVICE_CLASS is only set during prepare; on re-discovery
```
Comment (travisn) [inline pkg/daemon/ceph/osd/volume.go]: I'm having a hard time finding why this is needed only when an OSD is replaced, but does not repro when the OSD was first created. It doesn't surprise me though because the OSD creation code is overly complex. 

Were you able to build and test this fix? This seems like a simple and low-risk change to fix, we just ned to confirm in a test cluster to have confidence in the change.

**Review by travisn — CHANGES_REQUESTED** [review]

File: pkg/daemon/ceph/osd/volume.go (hunk 1 above)
Comment (ormandj) [reply pkg/daemon/ceph/osd/volume.go]: Good catch, refactored to reuse `GetDiskDeviceClass`. Updated the comment to be clearer about the code path difference too.

File: pkg/daemon/ceph/osd/volume.go (hunk 2 above)
Comment (ormandj) [reply pkg/daemon/ceph/osd/volume.go]: The reason it only manifests on re-discovery (not initial creation): during initial creation, `configureCVDevices` (volume.go line ~301) reads `ROOK_OSD_CRUSH_DEVICE_CLASS`, which the operator sets on the prepare job from the CR's `crushDeviceClass` or the device-specific `deviceClass`. So the class is correct on first run.

During re-discovery (`GetCephVolumeRawOSDs`), the OSD pod doesn't have `ROOK_OSD_CRUSH_DEVICE_CLASS` set (it was only on the prepare pod). So `GetDiskDeviceClass` falls back to auto-detected `deviceType`, which uses the rotational flag and returns "ssd" for NVMe regardless of what the user configured. The `ROOK_OSD_DEVICE_CLASS` env var IS set on the OSD pod (from the CR's `deviceClass` field), so falling back to it preserves the user's intent.

**Update**: Reworked to fix the root cause (see latest commits) and tested on a cluster with 12 OSDs (4x NVMe Micron 7450, 8x SATA WDC HDD) on Rook v1.19.2. After operator upgrade, all 12 OSD deployments received `ROOK_OSD_CRUSH_DEVICE_CLASS` correctly (nvme for NVMe, hdd for SATA). Purged and reprovisioned both an NVMe OSD and a SATA OSD -- both came up with correct device classes and HEALTH_OK.

**Comment by sp98** [comment]
> The issue is in GetCephVolumeRawOSDs() it calls GetDiskDeviceClass() which checks ROOK_OSD_CRUSH_DEVICE_CLASS. That env var is only set during the prepare phase (passed to ceph-volume raw prepare --crush-device-class). During re-discovery (which happens when the operator recreates an OSD deployment), the env var is absent so it falls back to auto-detection.

I have the same confusion, if the OSD is being purged and reprovisioned, then it means all entire flow for OSD creation is re triggered. A new OSD prepare pod is started. So why is not working the same way when the OSD was first provisioned? @ormandj

File: pkg/daemon/ceph/osd/volume.go [hunk 3]
```diff
@@ -1301,6 +1301,14 @@ func GetCephVolumeRawOSDs(context *clusterd.Context, clusterInfo *client.Cluster
 			logger.Infof("setting device type %q for device %q", osd.DeviceType, diskInfo.Name)
 
 			crushDeviceClass := sys.GetDiskDeviceClass(oposd.CrushDeviceClassVarName, deviceType)
+			// ROOK_OSD_CRUSH_DEVICE_CLASS is only set during the prepare job; on
+			// re-discovery it's absent, so GetDiskDeviceClass falls back to
+			// auto-detected deviceType (which may return "ssd" for NVMe). Fall
+			// back to ROOK_OSD_DEVICE_CLASS (set from the CephCluster CR's
+			// deviceClass field) to preserve the user's intended class.
+			if crushDeviceClass == deviceType {
+				crushDeviceClass = sys.GetDiskDeviceClass("ROOK_OSD_DEVICE_CLASS", deviceType)
```
Comment (sp98) [inline pkg/daemon/ceph/osd/volume.go]: I would be safer to export the [original const](https://github.com/rook/rook/blob/c6031410c758262f416ecebecf242aaf9eb567d0/pkg/operator/ceph/cluster/osd/envs.go#L33) instead of hardcoded string `ROOK_OSD_DEVICE_CLASS`

File: pkg/daemon/ceph/osd/volume.go [hunk 4]
```diff
@@ -1301,6 +1301,14 @@ func GetCephVolumeRawOSDs(context *clusterd.Context, clusterInfo *client.Cluster
 			logger.Infof("setting device type %q for device %q", osd.DeviceType, diskInfo.Name)
 
 			crushDeviceClass := sys.GetDiskDeviceClass(oposd.CrushDeviceClassVarName, deviceType)
+			// ROOK_OSD_CRUSH_DEVICE_CLASS is only set during the prepare job; on
+			// re-discovery it's absent, so GetDiskDeviceClass falls back to
+			// auto-detected deviceType (which may return "ssd" for NVMe). Fall
+			// back to ROOK_OSD_DEVICE_CLASS (set from the CephCluster CR's
+			// deviceClass field) to preserve the user's intended class.
+			if crushDeviceClass == deviceType {
```
Comment (sp98) [inline pkg/daemon/ceph/osd/volume.go]: This looks more like a workaround than the actual fix. So this change will be very confusing to a new person in the future. I think we should try to fix to root cause that `ROOK_OSD_CRUSH_DEVICE_CLASS` is absent during re-discovery.

**Review by sp98 — CHANGES_REQUESTED** [review]

File: pkg/daemon/ceph/osd/volume.go (hunk 3 above)
Comment (ormandj) [reply pkg/daemon/ceph/osd/volume.go]: Done. Renamed `osdDeviceClassEnvVarName` to `OSDDeviceClassVarName` (exported) in envs.go, updated the 2 internal references in envs.go and osd.go.

File: pkg/daemon/ceph/osd/volume.go (hunk 4 above)
Comment (ormandj) [reply pkg/daemon/ceph/osd/volume.go]: You're right -- I've reworked this to fix the root cause. The initial approach used a `ROOK_OSD_DEVICE_CLASS` fallback in the daemon because it was the smallest possible change (daemon-only, no operator code touched). But as you pointed out, it creates a confusing pattern where two different env vars serve the same purpose depending on which pod you're in.

The root cause: the operator sets `ROOK_OSD_CRUSH_DEVICE_CLASS` on prepare jobs (`provision_spec.go:239`) but not on OSD deployments (`spec.go`). During re-discovery the daemon reads this env var, finds it absent, and falls back to auto-detected `deviceType`.

**Fix**: Added `crushDeviceClassEnvVar(osd.DeviceClass)` to the OSD deployment spec in `spec.go:425`, alongside the existing `dataDeviceClassEnvVar`. The daemon code now just uses the single `GetDiskDeviceClass(oposd.CrushDeviceClassVarName, deviceType)` call -- no fallback logic needed. Net result: -8 lines of code.

Also exported `OSDDeviceClassVarName` (was unexported `osdDeviceClassEnvVarName`) for cross-package use.

**Tested on a real cluster** (12 OSDs: 4x NVMe Micron 7450 7.6TB + 8x SATA WDC 22TB, Rook v1.19.2, single-node Talos Linux):

- After operator upgrade, all 12 OSD deployments received `ROOK_OSD_CRUSH_DEVICE_CLASS` correctly:
  - NVMe OSDs: `ROOK_OSD_CRUSH_DEVICE_CLASS=nvme`
  - SATA OSDs: `ROOK_OSD_CRUSH_DEVICE_CLASS=hdd`
- Purged and reprovisioned both an NVMe OSD (osd.10) and a SATA OSD (osd.0)
- Both came up with correct CRUSH device classes and persistent by-id paths
- Cluster remained HEALTH_OK throughout, all 12 OSDs up after testing
- Existing deployments pick up the new env var on operator reconciliation without manual migration

**Comment by ormandj** [comment]
> I have the same confusion, if the OSD is being purged and reprovisioned, then it means all entire flow for OSD creation is re triggered. A new OSD prepare pod is started. So why is not working the same way when the OSD was first provisioned?

The confusion is understandable -- there are actually two different code paths inside the same prepare job, and the bug only affects one of them.

When the prepare job runs `configureCVDevices`, it checks `len(devices.Entries)`:

1. **`> 0` (new devices to prepare)**: Calls `initializeDevicesRawMode` which runs `ceph-volume raw prepare --crush-device-class <class>`. The per-device class is read from the `ROOK_DATA_DEVICES` JSON and passed correctly via `appendDeviceClassArg`. This path works fine.

2. **`== 0` (no new devices, idempotency check)**: Calls `GetCephVolumeRawOSDs` to list existing OSDs. This is the re-discovery path -- it reads `ROOK_OSD_CRUSH_DEVICE_CLASS` to determine the device class. On a prepare job this env var IS set, so it works. But this same `GetCephVolumeRawOSDs` function is also called from the **OSD pod itself** on startup, where `ROOK_OSD_CRUSH_DEVICE_CLASS` was not set (only prepare jobs had it).

The bug manifests when the OSD pod restarts (not during initial provisioning). The OSD pod calls `GetCephVolumeRawOSDs` to rediscover its own OSD info, reads `ROOK_OSD_CRUSH_DEVICE_CLASS` (absent), and falls back to auto-detection which returns "ssd" for NVMe.

The fix adds `ROOK_OSD_CRUSH_DEVICE_CLASS` to OSD deployment specs (not just prepare jobs), so the re-discovery path works correctly on OSD pods too.

File: pkg/daemon/ceph/osd/volume.go [hunk 5]
```diff
@@ -1300,8 +1300,7 @@ func GetCephVolumeRawOSDs(context *clusterd.Context, clusterInfo *client.Cluster
 			osd.DeviceType = deviceType
 			logger.Infof("setting device type %q for device %q", osd.DeviceType, diskInfo.Name)
 
-			crushDeviceClass := sys.GetDiskDeviceClass(oposd.CrushDeviceClassVarName, deviceType)
-			osd.DeviceClass = crushDeviceClass
+			osd.DeviceClass = sys.GetDiskDeviceClass(oposd.CrushDeviceClassVarName, deviceType)
```
Comment (travisn) [inline pkg/daemon/ceph/osd/volume.go]: There is no behavior change here, how about reverting this file for simplicity of the PR?

File: pkg/operator/ceph/cluster/osd/envs.go [hunk 6]
```diff
@@ -30,7 +30,7 @@ const (
 	osdDatabaseSizeEnvVarName = "ROOK_OSD_DATABASE_SIZE"
 	osdWalSizeEnvVarName      = "ROOK_OSD_WAL_SIZE"
 	osdsPerDeviceEnvVarName   = "ROOK_OSDS_PER_DEVICE"
-	osdDeviceClassEnvVarName  = "ROOK_OSD_DEVICE_CLASS"
+	OSDDeviceClassVarName     = "ROOK_OSD_DEVICE_CLASS"
```
Comment (travisn) [inline pkg/operator/ceph/cluster/osd/envs.go]: Let's revert this var rename. It doesn't change any behavior, nor does it improve anything.

**Review by travisn — CHANGES_REQUESTED** [review]
In your own words, please confirm how you have tested this fix for new and upgraded clusters. The AI description is quite complex.

**Comment by ormandj** [comment]
> In your own words, please confirm how you have tested this fix for new and upgraded clusters. The AI description is quite complex.

I have a local server (single-node Talos Linux, node "quasar") with 4x NVMe (Micron 7450 7.6TB) and 8x SATA HDD (WDC 22TB) -- 12 OSDs total. I installed rook-ceph v1.19.2 via Helm, then upgraded the operator to a custom image built from v1.19.2 with both this PR and #17226 applied.

After the operator upgrade, all 12 existing OSD deployments received ROOK_OSD_CRUSH_DEVICE_CLASS on reconciliation without any manual intervention -- nvme for NVMe, hdd for SATA. I then purged and re-provisioned both an NVMe OSD (osd.10) and a SATA OSD (osd.0). Both came back with the correct CRUSH device class and the cluster stayed HEALTH_OK throughout.

The initial creation path was already working -- configureCVDevices reads ROOK_OSD_CRUSH_DEVICE_CLASS from the prepare job where it's always been set. The devices had the correct class on initial installation. The bug only affects re-discovery on OSD pods, which is what the upgrade + reprovision test covers. They were coming up as 'ssd' instead of NVME prior to the fix:

`10    ssd    6.98630          osd.10       up   1.00000  1.00000`

There's a number of these types of issues that have been problematic for me for years running Ceph at large scale (non-Rook, >300PB under management), and I wanted to start addressing them. I've shifted to using Rook for more deployments vs. cephadm-managed clusters, so decided to contribute here. I apologize for the lack of context or clarity, and I hope this helps!

I'll go through the rest of the comments added, shortly, but I would greatly appreciate other folks testing this. I've got an image pushed up to my Github account, publicly, if people want to try it: https://github.com/users/ormandj/packages/container/package/rook-ceph - it includes this and the #17226 PR, as well.

File: pkg/daemon/ceph/osd/volume.go (hunk 5 above)
Comment (ormandj) [reply pkg/daemon/ceph/osd/volume.go]: Good call, that's just an incidental cleanup that snuck in during the rework. I'll revert it to keep the diff focused.

File: pkg/operator/ceph/cluster/osd/envs.go (hunk 6 above)
Comment (ormandj) [reply pkg/operator/ceph/cluster/osd/envs.go]: Makes sense. The export was from an earlier iteration when sp98 suggested using the const cross-package, but the reworked approach uses `CrushDeviceClassVarName` instead, so this rename is no longer needed. I'll revert it.

**Review by travisn — APPROVED** [review]
Thanks for the thorough validation and explanation with the fix. The fix does seem good and I cannot find a case where there would be undesirable side effects. @sp98 Anything else I might have missed?

**Comment by ormandj** [comment]
> Thanks for the thorough validation and explanation with the fix. The fix does seem good and I cannot find a case where there would be undesirable side effects. @sp98 Anything else I might have missed?

You're very welcome, and I want to also thank you (and others) for the rigorous reviews. I don't think maintainers of projects like this get enough credit for the enormous amount of work and effort you put into ensuring these projects (especially something state-related like rook-ceph) remain high quality, and you have my personal gratitude for your attention to detail and helpful feedback.

**Review by travisn — CHANGES_REQUESTED** [review]
One more request, if you could squash your commits, thanks!

**Review by travisn — APPROVED** [review]

**Review by sp98 — APPROVED** [review]
