### PR TITLE
Mons bind to the pod IP and advertise the service IP

### LINKED ISSUE #586: Cluster fails to come up after a reboot
The mons are dependent on a constant network identity. If that identity changes, nobody will be able to connect to the mon. The mon will be rejected.

Ceph enforces that the mon endpoint is what the mon binds to. Putting a k8s service in front of a mon to have a consistent endpoint does not work. 

Currently the mons use the PodIP, which will change at every restart. We must either find a way to soften the ceph endpoint requirements to allow the service translation, or find a way to get a consistent endpoint for everyone to talk to the mons, even after reboot.

### PR DESCRIPTION
**Pull request by travisn**
Monitors require a stable identity. In Kubernetes a stable IP is specified with a service. The mon startup sequence is now:
- Create a K8s service for each mon
- Set the expected mon endpoints in a configmap
- Start the monitor pods
- The mons will generate the monmap with all expected monitors

Fixes #586 to survive reboots. Also included is to fix the PID 1 issue and launch with tini, which means processes now will respond to properly shutdown the pod. 

A side effect of the monmap generation is that initial startup is on the order of a few seconds to form mon quorum instead of 30-60 seconds.

Still need to add functional tests.

### CODE REVIEW

File: pkg/ceph/mon/daemon.go [hunk 1]
```diff
@@ -116,17 +116,24 @@ func startMon(context *clusterd.Context, config *Config, confFilePath, monDataDi
...
 		fmt.Sprintf("mkfs-%s", config.Name),
 		"ceph-mon",
 		"--mkfs",
 		monNameArg,
 		fmt.Sprintf("--cluster=%s", config.Cluster.Name),
 		fmt.Sprintf("--mon-data=%s", monDataDir),
 		fmt.Sprintf("--conf=%s", confFilePath),
-		fmt.Sprintf("--keyring=%s", keyringPath))
+		fmt.Sprintf("--keyring=%s", keyringPath),
+		fmt.Sprintf("--monmap=%s", monmapPath))
```
Comment (bassam) [inline pkg/ceph/mon/daemon.go]: is this needed? I thought the monmap is only needed when calling mkfs.

File: pkg/ceph/mon/config.go [hunk 2]
```diff
@@ -84,7 +85,7 @@ func getMonKeyringPath(configDir, monName string) string {
 
 // get the path of a given monitor's data dir
 func getMonDataDirPath(configDir, monName string) string {
-	return filepath.Join(getMonRunDirPath(configDir, monName), fmt.Sprintf("mon.%s", monName))
+	return filepath.Join(getMonRunDirPath(configDir, monName), "data")
```
Comment (bassam) [inline pkg/ceph/mon/config.go]: why is this subdirectory needed at all?

File: pkg/ceph/mon/agent.go [hunk 3]
```diff
@@ -207,3 +214,18 @@ func writeBackendFile(monDataDir, backend string) error {
 	}
 	return nil
 }
+
+func generateMonMap(context *clusterd.Context, cluster *ClusterInfo, folder string) (string, error) {
+	path := path.Join(folder, "monmap")
+	args := []string{path, "--create", "--clobber", "--fsid", cluster.FSID}
```
Comment (bassam) [inline pkg/ceph/mon/agent.go]: why clobber?

File: pkg/operator/api/api.go [hunk 4]
```diff
@@ -171,13 +171,15 @@ func (c *Cluster) makeDeployment() *extensions.Deployment {
...
 
-	command := fmt.Sprintf("/usr/local/bin/rook api --config-dir=%s --port=%d ", k8sutil.DataDir, model.Port)
 	return v1.Container{
-		// TODO: fix "sleep 5".
-		// Without waiting some time, there is highly probable flakes in network setup.
-		Command: []string{"/bin/sh", "-c", fmt.Sprintf("sleep 5; %s", command)},
-		Name:    DeploymentName,
-		Image:   k8sutil.MakeRookImage(c.Version),
+		Command: []string{
+			"/tini", "--", "/usr/local/bin/rook",
```
Comment (bassam) [inline pkg/operator/api/api.go]: this is already the entrypoint in the Dockerfile. why do you need to repeat it here. Can you not just pass args "api ..."

File: pkg/ceph/osd/daemon.go [hunk 5]
```diff
@@ -38,6 +38,11 @@ const (
 )
 
 func Run(context *clusterd.Context, agent *OsdAgent) error {
+	if err := setHostName(context); err != nil {
```
Comment (bassam) [inline pkg/ceph/osd/daemon.go]: why is this needed?

File: pkg/ceph/mon/agent.go (hunk 3 above)
Comment (travisn) [inline pkg/ceph/mon/agent.go]: If for some reason mkfs needs to run again (because of failure the first time), we need to make sure the monmap is the latest from our authoritative source. During development I hit it initially when debugging, but since that issue is fixed I'm not anticipating we would expect to need it in the wild.

File: pkg/ceph/mon/config.go (hunk 2 above)
Comment (travisn) [inline pkg/ceph/mon/config.go]: good question, it probably isn't necessary, just following a pattern from the ceph docs.

File: pkg/ceph/mon/daemon.go (hunk 1 above)
Comment (travisn) [inline pkg/ceph/mon/daemon.go]: actually this is the call with --mkfs

File: pkg/ceph/osd/daemon.go (hunk 5 above)
Comment (travisn) [inline pkg/ceph/osd/daemon.go]: This is a re-implementation of #598 to support the tini change. We need a consistent hostname for the osd pod to put in the crush map

File: pkg/operator/api/api.go (hunk 4 above)
Comment (travisn) [inline pkg/operator/api/api.go]: good point, will remove this everywhere

File: pkg/operator/mon/health.go [hunk 6]
```diff
@@ -102,9 +119,20 @@ func (c *Cluster) removeMon(name string) error {
 		return fmt.Errorf("failed to remove mon %s from quorum. %+v", name, err)
 	}
 	delete(c.clusterInfo.Monitors, name)
+
+	// Remove the service endpoin
```
Comment (kokhang) [inline pkg/operator/mon/health.go]: nit: sp

File: pkg/ceph/mon/config.go (hunk 2 above)
Comment (bassam) [inline pkg/ceph/mon/config.go]: I thought mkfs created a `store` subdir. can you verify? I want to avoid `mon0/data/store/`

File: pkg/ceph/mon/agent.go (hunk 3 above)
Comment (bassam) [inline pkg/ceph/mon/agent.go]: ok. seems like we should alway start from a clean slate vs. clobber.

File: pkg/ceph/osd/daemon.go (hunk 5 above)
Comment (bassam) [inline pkg/ceph/osd/daemon.go]: should we be getting this from downstream API in kubelet? I'm not sure the environment is the best place to get a node identity.

Comment (kokhang) [inline pkg/ceph/osd/daemon.go]: Agree. NodeName is available as a downward API as of 1.4. https://github.com/kubernetes/kubernetes/pull/27880

Comment (travisn) [inline pkg/ceph/osd/daemon.go]: it actually is using the downward api. The way to access the downward api is by setting an env var. It is set here: https://github.com/travisn/rook/blob/bind-addr/pkg/operator/osd/osd.go#L259

File: pkg/ceph/mon/agent.go (hunk 3 above)
Comment (travisn) [inline pkg/ceph/mon/agent.go]: yes, i would always expect to start from a clean state. The clobber would only impact in a corner error case

File: pkg/ceph/mon/config.go (hunk 2 above)
Comment (travisn) [inline pkg/ceph/mon/config.go]: mon0/data shows the data files directly there. There is not another subdir beyond `data`

File: pkg/ceph/osd/daemon.go (hunk 5 above)
Comment (bassam) [inline pkg/ceph/osd/daemon.go]: ahh. then `NODENAME` is a more appropriate name for the env vs. `HOSTNAME` which is a standard linux env.

File: pkg/operator/mon/health.go (hunk 6 above)
Comment (travisn) [inline pkg/operator/mon/health.go]: good catch

File: pkg/ceph/osd/daemon.go (hunk 5 above)
Comment (travisn) [inline pkg/ceph/osd/daemon.go]: sure, will update

**Comment by travisn** [comment]
the final issue before merging this PR is that the e2e tests are failing to attach the block device due to a network issue specific to the docker-in-docker environment. Stay tuned...
