### PR TITLE
Metadatadevice should not be added to osd data device list

### LINKED ISSUE #5300: CephCluster CR is correct but the metadata device is applied incorrectly
**Environment**:
* OS: RHEL 7.7
* Cloud provider or hardware configuration: Openshift
* Rook version: v1.3.1
* Storage backend version: ceph v15.2.0
* Kubernetes version : v1.11+
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):Openshift

When i am trying to use metadatadevice (which was working in rook 1.2.7 with ceph v14.2.8) it is the osd prepare pod is failing and giving the following error.
`2020-04-20 10:44:10.880645 D | exec: Running command: stdbuf -oL ceph-volume lvm batch --prepare --bluestore --yes --dmcrypt --osds-per-device 1 /dev/vdb /dev/vdc --db-devices /dev/vdc --report
2020-04-20 10:44:32.018194 D | exec: Traceback (most recent call last):
2020-04-20 10:44:32.018275 D | exec:   File "/usr/sbin/ceph-volume", line 9, in <module>
2020-04-20 10:44:32.018320 D | exec:     load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
2020-04-20 10:44:32.018340 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 39, in __init__
2020-04-20 10:44:32.018355 D | exec:     self.main(self.argv)
2020-04-20 10:44:32.018375 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 59, in newfunc
2020-04-20 10:44:32.018385 D | exec:     return f(*a, **kw)
2020-04-20 10:44:32.018400 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 150, in main
2020-04-20 10:44:32.018406 D | exec:     terminal.dispatch(self.mapper, subcommand_args)
2020-04-20 10:44:32.018411 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2020-04-20 10:44:32.018417 D | exec:     instance.main()
2020-04-20 10:44:32.018422 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/main.py", line 42, in main
2020-04-20 10:44:32.018428 D | exec:     terminal.dispatch(self.mapper, self.argv)
2020-04-20 10:44:32.018434 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2020-04-20 10:44:32.018458 D | exec:     instance.main()
2020-04-20 10:44:32.018490 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 16, in is_root
2020-04-20 10:44:32.018499 D | exec:     return func(*a, **kw)
2020-04-20 10:44:32.018510 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 318, in main
2020-04-20 10:44:32.018532 D | exec:     self._get_explicit_strategy()
2020-04-20 10:44:32.018577 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 329, in _get_explicit_strategy
2020-04-20 10:44:32.018599 D | exec:     self._ensure_disjoint_device_lists()
2020-04-20 10:44:32.018625 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 380, in _ensure_disjoint_device_lists
2020-04-20 10:44:32.018636 D | exec:     raise Exception('Device lists are not disjoint')
2020-04-20 10:44:32.018661 D | exec: Exception: Device lists are not disjoint
failed to configure devices: failed to initialize devices: failed ceph-volume report: exit status 1`

### PR DESCRIPTION
**Pull request by travisn**
**Description of your changes:**
When the metadataDevice is specified, it was a regression that it was being interpreted also as a data device. ceph-volume was failing when the metadataDevice was added as both a data and metadata device. So we ensure it is not added to the list of data devices.

**Which issue is resolved by this Pull Request:**
Resolves #5300 

**Checklist:**

- [ ] **CommitLint Bot**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

[test ceph]

### CODE REVIEW

File: pkg/daemon/ceph/osd/volume.go [hunk 1]
```diff
@@ -396,6 +396,11 @@ func (a *OsdAgent) initializeDevices(context *clusterd.Context, devices *DeviceO
 	metadataDevices := make(map[string]map[string]string)
 	for name, device := range devices.Entries {
 		if device.Data == -1 {
+			if device.Metadata != nil {
+				logger.Infof("skipping metadata device %s config since it will be configured with a data device", name)
```
Comment (BlaineEXE) [inline pkg/daemon/ceph/osd/volume.go:400]: Is this the right behavior? I would think we should do nothing with the device, as this is clearly a configuration that isn't properly specified. Maybe we should even stop OSD provisioning entirely. ?

Comment (travisn) [reply pkg/daemon/ceph/osd/volume.go:400]: The `for` loop is expected to iterate over all the data devices. But metadata devices were also added to the `devices` map, which was causing the metadataDevice to also be treated as a data device. It's really a bug in the code rather than a configuration problem. All this code that translates the settings into c-v parameters is very confusing. I'd like to do a more thorough review of it later, but for now this was fixing the c-v failure blocking any metadataDevice OSDs from being created.

Comment (BlaineEXE) [reply pkg/daemon/ceph/osd/volume.go:400]: Makes sense... but the logic seems backwards IIUC. Should the device be skipped instead? The metadata devices are specified specifically right, but the devices are added automatically, so if a device is in both, the metadata device should be chosen but not the data one to my logic.

Comment (travisn) [reply pkg/daemon/ceph/osd/volume.go:400]: This loop is only intended to loop over data devices. If there is a metadataDevice specified, it will be looked up and handled below starting on line 418. Really, the metadataDevice should not have been added to the `devices` map in the first place, but I'd like to review that change with a more in-depth look at this code to see if it can be simplified.

Comment (BlaineEXE) [reply pkg/daemon/ceph/osd/volume.go:400]: Okay! My bad! I was misinterpreting! LGTM, and thanks!

**Comment by venkataramaredy** [comment]
Hi Have 3 worker nodes . in cluster.yaml file ,it should take only block devices for each node 
How to write in playbook  please help me

**Comment by travisn** [comment]
> Hi Have 3 worker nodes . in cluster.yaml file ,it should take only block devices for each node How to write in playbook please help me

Not sure about playbooks, but you can see the Quickstart guide](https://rook.github.io/docs/rook/v1.10/Getting-Started/quickstart/) to help you get started. For more questions, please join the Rook [Slack](http://slack.rook.io/).
