### PR TITLE
namespace: add retryOnConflict when updating status

### LINKED ISSUE #16641: CephBlockPoolRadosNamespace status stuck in Progressing due to stale object version during status update
The `CephBlockPoolRadosNamespace` resource remains stuck in the `Progressing` state indefinitely.
Logs from the `rook-ceph-operator` suggest a race condition during the status update, where the operator attempts to update a stale version of the resource, resulting in an update conflict such as:
```
2025-10-23 06:42:59.103881 E | blockpool-rados-namespace-controller: failed to set ceph blockpool rados namespace "rook-ceph/namespace-b" status to "Ready". failed to update object "rook-ceph/namespace-b" status: Operation cannot be fulfilled on cephblockpoolradosnamespaces.ceph.rook.io "namespace-b": the object has been modified; please apply your changes to the latest version and try again
```
**Steps to reproduce:**
1.Deploy a `CephBlockPoolRadosNamespace` resource (say namespace-a).
2. Wait for it to reach `Ready` state.
3. Deploy a second `CephBlockPoolRadosNamespace` resource (say namespace-b).
4. Observe that `namespace-b` remains in the `Progressing` state indefinitely.

**Possible Root Cause:**
A race condition might occur when the operator attempts to update a stale cached version of the object instead of fetching the latest version from the API server.

**Current Workaround:**
Restarting the operator pod which instantly updates the status to `Ready`. 

>Note: This behaviour was observed in the CI environment of the kubectl-rook-ceph repository.

### PR DESCRIPTION
**Pull request by subhamkrai**
currently, in RNS crd while updating status we don't have retryOnConflicts, similar to other CRD due to this RNS status was not updated succesfully and to fix this we have restart the rook operator pod.

subvolumegroup: add retry when updating status
currently, in SVG crd while updating status we don't have retryOnConflicts
similar to other CRD, this commit add the retryOnConflicts.

- [x] Testing Done

**Issue resolved by this Pull Request:**
Resolves #16641

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by travisn** [comment]
@subhamkrai Is this ready for final review? Or what is pending for DNM?

**Comment by subhamkrai** [comment]
> @subhamkrai Is this ready for final review? Or what is pending for DNM?

Testing with kubectl-rook-ceph repo was pending to other ci errors in that repo. I have started testing the now, will update here.

**Comment by subhamkrai** [comment]
@travisn Ready for review now. Thanks

File: pkg/operator/ceph/pool/radosnamespace/controller.go [hunk 1]
```diff
@@ -466,23 +467,28 @@ func (r *ReconcileCephBlockPoolRadosNamespace) deleteRadosNamespace(radosNamespa
 
 // updateStatus updates an object with a given status
 func (r *ReconcileCephBlockPoolRadosNamespace) updateStatus(client client.Client, name types.NamespacedName, status cephv1.ConditionType) {
-	cephBlockPoolRadosNamespace := &cephv1.CephBlockPoolRadosNamespace{}
-	if err := client.Get(r.opManagerContext, name, cephBlockPoolRadosNamespace); err != nil {
-		if kerrors.IsNotFound(err) {
-			logger.Debugf("CephBlockPoolRadosNamespace resource %q not found. Ignoring since object must be deleted.", name)
-			return
+	err := retry.RetryOnConflict(retry.DefaultRetry, func() error {
```
Comment (parth-gr) [inline pkg/operator/ceph/pool/radosnamespace/controller.go:470]: I think we might need similar behaviour for the subvolume group

Comment (subhamkrai) [reply pkg/operator/ceph/pool/radosnamespace/controller.go:470]: Added

**Comment by subhamkrai** [comment]
Tested this changes on this PR https://github.com/rook/kubectl-rook-ceph/pull/408 and it is working as expected,  CI is not failing while waiting for rns status to be updated.

File: pkg/operator/ceph/file/subvolumegroup/controller.go [hunk 2]
```diff
@@ -421,30 +422,35 @@ func (r *ReconcileCephFilesystemSubVolumeGroup) deleteSubVolumeGroup(cephFilesys
...
+		if observedGeneration != k8sutil.ObservedGenerationNotAvailable {
+			cephFilesystemSubVolumeGroup.Status.ObservedGeneration = observedGeneration
+		}
+		if err := reporting.UpdateStatus(r.client, cephFilesystemSubVolumeGroup); err != nil {
+			return errors.Wrapf(err, "failed to set ceph filesystem subvolume group %q status to %q", name, status)
+		}
+		return nil
+	})
+	if err != nil {
+		logger.Errorf("failed to update ceph blockpool rados namespace %q status to %q after retries. %v", name, status, err)
```
Comment (travisn) [inline pkg/operator/ceph/file/subvolumegroup/controller.go]:
```suggestion
		logger.Errorf("failed to update ceph filesystem subvolume group %q status to %q after retries. %v", name, status, err)
```

Comment (subhamkrai) [reply pkg/operator/ceph/file/subvolumegroup/controller.go]: done
