### PR TITLE
rgw: update ca bundle mount perms to read-all

### LINKED ISSUE #16957: CephObjectStore: spec.gateway.caBundleRef bad permission mounting when operator and cluster lives in different namespace
* Bug Report

in rook v1.19.0 and ceph tentacle v20.2.0, using caBundleRef property in the CR will generate a deployment spec as follows:

```yaml
- name: rook-ceph-custom-ca-bundle
  secret:
    defaultMode: 420             # 420 decimal = 0644
    items:
      - key: cabundle            # Key in the secret
        mode: 256                # 256 decimal = 0400 (read by owner only)
        path: custom-ca-bundle.crt
    secretName: trust-idp
```

The ceph radosgw process runs a "ceph" user as shown below

```sh
[root@rook-ceph-rgw-ceph-objectstore-a-6c7fcd8b5-j9jq2 ceph]# ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
ceph           1  0.6  0.7 5295980 121472 ?      Ssl  23:57   0:00 radosgw --fsid=89422e8f-8e56-472f-8348-ac4abc285a6b 
```

And the file mounted as per stated in the generated deployment spec by the rook operator:

```sh
[root@rook-ceph-rgw-ceph-objectstore-a-6c7fcd8b5-j9jq2 ceph]# ls -l /etc/ceph/rgw-ca-bundle/
total 0
lrwxrwxrwx 1 root root 27 Jan 24 23:57 custom-ca-bundle.crt -> ..data/custom-ca-bundle.crt
```

This renders the ca file non readable, especially in an enforced env where perms matter generating the log below in rgw pod:

```sh
curl error: Problem with the SSL CA cert (path? access rights?)
error setting certificate file: /etc/ceph/rgw-ca-bundle/custom-ca-bundle.crt
```

**Deviation from expected behavior:**

I mannually changed the perm set on the deployment secret and letting only the default mode.
This solve the issue.

I Believe that the CephObjectStore should generate deployment with only the default mode 420 when mounting secret.

### PR DESCRIPTION
**Pull request by BlaineEXE**
Update the CA bundle volume mount permissions to read-all (o444). RGW runs as 'ceph', but the volume mount defaults to 'root'. o444 ensures the RGW can read the bundle.

resolves #16957 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
  - Overwriting Ceph's configurations should be marked as breaking changes.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

File: pkg/operator/ceph/object/spec.go [hunk 1]
```diff
@@ -981,9 +981,8 @@ func (c *clusterConfig) generateVolumeSourceWithTLSSecret() (*v1.SecretVolumeSou
 }
 
 func (c *clusterConfig) generateVolumeSourceWithCaBundleSecret() (*v1.SecretVolumeSource, error) {
-	// Keep the ca-bundle as secure as possible in the container. Give only user read perms.
-	// Same as above for generateVolumeSourceWithTLSSecret function.
-	userReadOnly := int32(0o400)
+	// RGW runs as 'ceph' user and needs access to the CA bundle.
+	readOnly := int32(0o444)
```
Comment (BlaineEXE) [inline pkg/operator/ceph/object/spec.go:985]: I think there is an alternate strategy we could take: create another init container to `chown` this file.

I'd prefer not to do this unless we think the o400 perms are a realistic improvement to security. I don't see a strong reason why a CA bundle used to authenticate an outside service should be limited to read-by-owner only.

FWIW, we already use o444 permissions for RGW's serving TLS certificate (below). If we think this file is important to have o400 perms, we should probably consider a follow-up action to change the serving cert perms as well.

https://github.com/rook/rook/blob/5e3f7f8bc0e489c7351905fb95903bdf5953d962/pkg/operator/ceph/object/spec.go#L942-L956

@jhoblitt any thoughts?

**Comment by BlaineEXE** [comment]
Aside, it seems github actions (Azure) is having a really bad day. I see ~8 failures setting up the runner environment

File: pkg/operator/ceph/object/spec.go (hunk 1 above)
Comment (jhoblitt) [reply pkg/operator/ceph/object/spec.go:985]: Another option is to use `.spec.securityContext.fsGroup` https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#discussion to change the group ownership of the mounted secret. The `defaultMode` could then be `0440`.  That would avoid the need for a `chown` via init container while avoid making the file world readable. 

That said, I don't think making the bundle world readable is particularly terrible from a security point of view. A CA bundle typically isn't considered a "secret" and the most likely way the pod would be compromised would be via the rgw process, which would allow the bundle to be read.

Comment (BlaineEXE) [reply pkg/operator/ceph/object/spec.go:985]: I think `fsGroup` would be the most preferred option, but we have had issues with OpenShift's security policies around `fsGroups` and how it randomizes UIDs in running containers. If I remember the context right.

In general, I strive to make sure Rook doesn't revolve around OpenShift. In this particular case, I think we are okay to treat OpenShift as a known lowest-common-denominator, with the idea that other K8s distros could have similar security behavior. For now, I think we can merge this and get it backported.

-----

Thinking more broadly, it is possible that OpenShift (and/or other K8s distros) have had improvements over time to support `fsGroups` without the old issues. If we are to try to move this to `fsGroups` as a follow-up, I think it would be best done as a larger work item. We could potentially remove all of Rook's `chown` init containers if we don't believe `fsGroups` have issues on any modern K8s distros. Given the effort that would take and my perception of this as having low practical security impact, I'm not jumping to make a follow-up issue, but please do chime in if there's reason otherwise

**Comment by BlaineEXE** [comment]
Still having some Azure-related environment failures. Since we have pairs of tests and at least one of each pair is passing, I think we can proceed
