### PR TITLE
rook: remove block mount and unmount on mac

### LINKED ISSUE #185: Can run rook block mount on mac but it is not supported
I am able to run a command like `./rook block mount --name test --path /tmp/rook-volume` on my mac (with the endpoint pointed at a working rookd instance) even though this fails and is unsupported

```2016/11/14 10:12:02 Running command: modinfo -F parm rbd | grep "^single_major" | awk '{print $0}'
2016/11/14 10:12:02 Running command: sudo modprobe rbd
2016/11/14 10:12:02 sudo: modprobe: command not found
failed to load kernel module rbd: Failed to complete modprobe rbd: exit status 1
```

Expected Result:

It should either
* error immediately saying that rook block mount is unsupported on this platform.
* not have the command even available or in the help/usage.

It was suggested that either of these could be accomplished using build tags (_linux.go or build constraint).

### PR DESCRIPTION
**Pull request by thephred**
Block mount and unmount is not supported and will error so I've removed it from the rook client (only on mac) for now.

fixes #185

### CODE REVIEW

File: cmd/rook/block-list_test.go [hunk 1]
```diff
@@ -58,8 +59,14 @@ func TestListBlockImages(t *testing.T) {
 	out, err := listBlocks(mockRBDSysBusPath, c, e)
 	assert.Nil(t, err)
 
-	expectedOut := "NAME       POOL      SIZE       DEVICE    MOUNT\n" +
-		"myimage1   mypool1   1.00 KiB   rbd5      /tmp/mymount1\n"
+	var expectedOut string
+	if runtime.GOOS == "linux" {
+		expectedOut = "NAME       POOL      SIZE       DEVICE    MOUNT\n" +
```
Comment (travisn) [inline cmd/rook/block-list_test.go]: to reduce duplication, you could use the same base string, then simply append the mount path to the expectedOut
