### PR TITLE
core: add missing error type check to exec

### LINKED ISSUE #8280: do proper error type assertion in exec package
See this thread https://github.com/rook/rook/pull/8272#discussion_r665524183.
The goal is to get ride of:

```go
		// // This is ugly but I don't know why the type assertion does not work...
		// // Whatever I've tried I can see the type "exec.CodeExitError" but none of the "case" nor other attempts with "errors.As()" worked :(
		// // So I'm parsing the Error string until we have a solution
		if strings.Contains(err.Error(), "command terminated with exit code") {
			a := strings.SplitAfter(err.Error(), "command terminated with exit code")
			return strconv.Atoi(strings.TrimSpace(a[1]))
		}
```

And get the assertion on `kexec.CodeExitError` working properly.

### PR DESCRIPTION
**Pull request by BlaineEXE**
In ExtractExitCode, there is one error type that can be valid as a
pointer or not-as-a-pointer. Add a case to the type check for the
non-pointer condition.

Resolves #8280

Signed-off-by: Blaine Gardner <blaine.gardner@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by BlaineEXE** [comment]
@leseb I'm not sure how you were testing this before, but I'm pretty sure this will fix the issue. I'm going to add unit tests to be more sure of it, but it would be good to be able to run the real life test manually to be sure.

**Comment by BlaineEXE** [comment]
TODO:
- [ ] create unit test for this

**Comment by leseb** [comment]
> @leseb I'm not sure how you were testing this before, but I'm pretty sure this will fix the issue. I'm going to add unit tests to be more sure of it, but it would be good to be able to run the real life test manually to be sure.

I swear I had tested that too and each time I was not able to enter the right `case` and displaying the error type was not showing a pointer. Anyway, I think this does not hurt.

File: pkg/util/exec/exec_test.go [hunk 1]
```diff
@@ -43,3 +50,91 @@ func Test_assertErrorType(t *testing.T) {
...
+	tests := []struct {
+		name     string
+		inputErr error
+		want     int
+		wantErr  bool
+	}{
+		{"*exec.ExitError",
+			make_execExitError(3),
+			3, noError},
+		/* {"exec.ExitError", // non-pointer case is impossible */
```
Comment (leseb) [inline pkg/util/exec/exec_test.go:80]: Impossible because the exec package always returns a pointer?

**Review by leseb — COMMENTED** [review]
I'm not sure if this will fix the issue but better coverage is nice. Thanks!

**Comment by leseb** [comment]
@Mergifyio rebase

File: pkg/util/exec/exec_test.go [hunk 2]
```diff
@@ -43,3 +50,91 @@ func Test_assertErrorType(t *testing.T) {
 		})
 	}
 }
+
+func TestExtractExitCode(t *testing.T) {
+	make_execExitError := func(retcode int) *exec.ExitError {
```
Comment (leseb) [inline pkg/util/exec/exec_test.go:55]:
```suggestion
	makeExecExitError := func(retcode int) *exec.ExitError {
```

Missing Python? 😛

File: pkg/util/exec/exec.go [hunk 3]
```diff
@@ -336,18 +336,21 @@ func ExtractExitCode(err error) (int, error) {
...
-		// This is ugly but I don't know why the type assertion does not work...
-		// Whatever I've tried I can see the type "exec.CodeExitError" but none of the "case" nor other attempts with "errors.As()" worked :(
-		// So I'm parsing the Error string until we have a solution
+		// This is ugly, but it's a decent backup just in case the error isn't a type above.
 		if strings.Contains(err.Error(), "command terminated with exit code") {
 			a := strings.SplitAfter(err.Error(), "command terminated with exit code")
 			return strconv.Atoi(strings.TrimSpace(a[1]))
 		}
-		return 0, errors.Errorf("error %#v is not an ExitError nor CodeExitError but is %v", err, reflect.TypeOf(err))
+		return 0, errors.Errorf("error %#v is an unknown error type: %v", err, reflect.TypeOf(err))
```
Comment (leseb) [inline pkg/util/exec/exec.go:354]: Afterthoughts, should we return something else than `0` if we return an unknown error?

**Review by leseb — CHANGES_REQUESTED** [review]
nit and 1 question

File: pkg/util/exec/exec.go (hunk 3 above)
Comment (BlaineEXE) [reply pkg/util/exec/exec.go:354]: I had a similar thought. Let me do that.

File: pkg/util/exec/exec_test.go (hunk 2 above)
Comment (BlaineEXE) [reply pkg/util/exec/exec_test.go:55]: TBH, I think it might be better as-is. Go suggests against underscores, but I see them used in tests more often. I think this translates more clearly as `make exec.ExitError` if it's `make_execExitError` than `makeExecExitError`.

**Review by leseb — APPROVED** [review]

**Comment by leseb** [comment]
@BlaineEXE is the DNM label still relevant?
