### PR TITLE
rgw: fix dashboard admin creation for multiple object stores

### LINKED ISSUE #9099: Ceph dashboard configuration with multiple objectstore
* Bug Report

**Deviation from expected behavior:**
Hello,

When configure multiple objectstore, the dashboard configuration is not fully functional.

When you add a second objectstore , the dashboard-admin user is not created on the second realm 
```2021-11-04 09:43:23.440987 I | op-config: setting "client.rgw.my.test.store.a"="rgw_log_nonexistent_bucket"="true" option to the mon configuration database
2021-11-04 09:43:23.778565 I | op-config: successfully set "client.rgw.my.test.store.a"="rgw_log_nonexistent_bucket"="true" option to the mon configuration database
2021-11-04 09:43:23.778586 I | op-config: setting "client.rgw.my.test.store.a"="rgw_log_object_name_utc"="true" option to the mon configuration database
2021-11-04 09:43:24.112405 I | op-config: successfully set "client.rgw.my.test.store.a"="rgw_log_object_name_utc"="true" option to the mon configuration database
2021-11-04 09:43:24.112424 I | op-config: setting "client.rgw.my.test.store.a"="rgw_enable_usage_log"="true" option to the mon configuration database
2021-11-04 09:43:24.446680 I | op-config: successfully set "client.rgw.my.test.store.a"="rgw_enable_usage_log"="true" option to the mon configuration database
2021-11-04 09:43:24.446700 I | op-config: setting "client.rgw.my.test.store.a"="rgw_zone"="my-test-store" option to the mon configuration database
2021-11-04 09:43:24.782533 I | op-config: successfully set "client.rgw.my.test.store.a"="rgw_zone"="my-test-store" option to the mon configuration database
2021-11-04 09:43:24.782555 I | op-config: setting "client.rgw.my.test.store.a"="rgw_zonegroup"="my-test-store" option to the mon configuration database
2021-11-04 09:43:25.168630 I | op-config: successfully set "client.rgw.my.test.store.a"="rgw_zonegroup"="my-test-store" option to the mon configuration database
2021-11-04 09:43:25.168739 I | ceph-object-controller: object store "my-test-store" deployment "rook-ceph-rgw-my-test-store-a" created
2021-11-04 09:43:25.191817 I | ceph-object-controller: enabling rgw dashboard
2021-11-04 09:43:25.533310 I | ceph-object-controller: created object store "my-test-store" in namespace "rook-ceph"
2021-11-04 09:43:25.680743 I | ceph-object-controller: ceph rgw status check interval for object store "my-test-store" is "1m0s"
2021-11-04 09:43:25.680760 I | ceph-object-controller: starting rgw health checker for CephObjectStore "rook-ceph/my-test-store"
```

And the dashboard give an  error when trying to access le new object gateway , see screenshot
Screenshot 2021-11-04 at 10 47 56

the dashboard-admin user has not been created : 
```[root@rook-ceph-tools-694d4f8cfd-v2p2j /]# radosgw-admin user list --rgw-realm=my-test-store
[
    "rook-ceph-internal-s3-user-checker-5449aa24-4a23-46ee-b611-550ff1a9b8ec",
    "rgw-admin-ops-user"
]
```

To make it working you have to create the user manually in the my-test-store realm .

2nd issue if you remove one object store it disable dashboard access for every other objectstore 

```2021-11-04 08:41:44.975367 I | ceph-object-controller: deleting object store "my-test-store" from namespace "rook-ceph"
2021-11-04 08:41:44.975379 I | ceph-object-controller: deleting rgw CephX key and configuration in centralized mon database for "rook-ceph-rgw-my-test-store-a"
2021-11-04 08:41:45.307710 I | op-config: deleting "rgw_log_nonexistent_bucket" option from the mon configuration database
2021-11-04 08:41:45.675334 I | op-config: successfully deleted "rgw_log_nonexistent_bucket" option from the mon configuration database
2021-11-04 08:41:45.675352 I | op-config: deleting "rgw_log_object_name_utc" option from the mon configuration database
2021-11-04 08:41:46.009260 I | op-config: successfully deleted "rgw_log_object_name_utc" option from the mon configuration database
2021-11-04 08:41:46.009277 I | op-config: deleting "rgw_zone" option from the mon configuration database
2021-11-04 08:41:46.343106 I | op-config: successfully deleted "rgw_zone" option from the mon configuration database
2021-11-04 08:41:46.343122 I | op-config: deleting "rgw_enable_usage_log" option from the mon configuration database
2021-11-04 08:41:46.675900 I | op-config: successfully deleted "rgw_enable_usage_log" option from the mon configuration database
2021-11-04 08:41:46.675917 I | op-config: deleting "rgw_zonegroup" option from the mon configuration database
2021-11-04 08:41:47.019964 I | op-config: successfully deleted "rgw_zonegroup" option from the mon configuration database
2021-11-04 08:41:47.019982 I | ceph-object-controller: successfully deleted rgw config for "client.rgw.my.test.store.a" in mon configuration database
2021-11-04 08:41:47.019988 I | cephclient: deleting ceph auth "client.rgw.my.test.store.a"
2021-11-04 08:41:47.480973 I | ceph-object-controller: completed deleting rgw CephX key and configuration in centralized mon database for "rook-ceph-rgw-my-test-store-a"
2021-11-04 08:41:47.481070 I | ceph-object-controller: disabling the dashboard api user and secret key
```

to fix the access I have to update manually the acces_key and secret_key for the dashboard
```ceph dashboard set-rgw-api-access-key
ceph dashboard set-rgw-api-secret-key
```

**Environment**:
* OS (e.g. from /etc/os-release): debian 10 
* Kernel (e.g. `uname -a`): Linux hostname 5.10.0-0.bpo.8-amd64 #1 SMP Debian 5.10.46-4~bpo10+1 (2021-08-07) x86_64 GNU/Linux
* Cloud provider or hardware configuration: bare metal 
* Rook version (use `rook version` inside of a Rook Pod): v1.7.6
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.6 (ee28fb57e47e9f88813e24bbf4c14496ca299d31) pacific (stable)
* Kubernetes version (use `kubectl version`): v1.21.5

### PR DESCRIPTION
**Pull request by galexrt**
**Description of your changes:**

Check the radosgw-admin realm user list per object store instead of relying
on the ceph dashboard get-rgw-api- command.

**Which issue is resolved by this Pull Request:**

Resolves #9099

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [x] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [x] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [x] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

File: pkg/operator/ceph/object/controller_test.go [hunk 1]
```diff
@@ -334,7 +335,7 @@ func TestCephObjectStoreController(t *testing.T) {
 		clientset := test.New(t, 3)
 		c := &clusterd.Context{
 			Executor:      executor,
-			RookClientset: rookclient.NewSimpleClientset(),
+			RookClientset: rookfake.NewSimpleClientset(),
```
Comment (travisn) [inline pkg/operator/ceph/object/controller_test.go:338]: Looks like  rookclient and rookfake are the same import so we could remove one of them.

Comment (galexrt) [reply pkg/operator/ceph/object/controller_test.go:338]: Yeah, though I'll think it is better to change this and other "linter errors" in a separate PR.

**Comment by galexrt** [comment]
In my test with the latest PR branch, I have two object stores in the cluster and shown in the dashboard. The first object store which was accessible and the second was failing with "invalid access/secret key" when selected in the drop down.
The state before the fixed operator was deployed, is that there was no `dashboard-admin` user in the second object store.
After the fixed operator had ran the object store reconciliation, both object stores are now accessible in the dashboard without any "invalid keys" errors (see video):

https://user-images.githubusercontent.com/3718398/164982003-262e0cc8-3a41-4fbf-86a2-a1aac2237268.mp4

**Note**: I have removed my previously added unit test because I think the existing tests (e.g., `TestDashboard`) should suffice.
@travisn do you think adding a verification to the existing multi object store integration test(s) for this makes sense?
My idea for the verification in the integration tests would basically check that the `dashboard-admin` user exists and uses the same dashboard credentials in both object stores.

A security concern for the Ceph MGR dashboard is that every object store must use the same access and secret key for the dashboard to work.. Where can I open an issue regarding this concern?

**Comment by travisn** [comment]
> **Note**: I have removed my previously added unit test because I think the existing tests (e.g., `TestDashboard`) should suffice. @travisn do you think adding a verification to the existing multi object store integration test(s) for this makes sense? My idea for the verification in the integration tests would basically check that the `dashboard-admin` user exists and uses the same dashboard credentials in both object stores.

This sounds good to me, thanks

> A security concern for the Ceph MGR dashboard is that every object store must use the same access and secret key for the dashboard to work.. Where can I open an issue regarding this concern?

If the dashboard user can see all the object stores, what would we gain from using separate keys to give the dashboard access? Perhaps @cbodley or @thotz could answer that better though.

**Comment by cbodley** [comment]
> > A security concern for the Ceph MGR dashboard is that every object store must use the same access and secret key for the dashboard to work.. Where can I open an issue regarding this concern?
> 
> If the dashboard user can see all the object stores, what would we gain from using separate keys to give the dashboard access? Perhaps @cbodley or @thotz could answer that better though.

there isn't a single 'dashboard user', it's creating a separate rgw user inside of each object store. if the dashboard is using the same credentials for each of those users, that's probably for the sake of expediency

> Where can I open an issue regarding this concern?

https://tracker.ceph.com/projects/dashboard/issues/new

**Comment by galexrt** [comment]
@travisn I have added the verification to the integration tests https://github.com/rook/rook/pull/10137/files#diff-1c7383142f068e71620e2fdd7212b78ac3a2dd084280f506b0ee675626a5bca2R144-R154, PTAL

File: .commitlintrc.json [hunk 2]
```diff
@@ -30,7 +30,7 @@
         "rgw",
         "security",
         "subvolumegroup",
-	"namespace",
+	      "namespace",
```
Comment (BlaineEXE) [inline .commitlintrc.json:33]: Intentional change?

File: pkg/operator/ceph/object/admin.go [hunk 3]
```diff
@@ -108,7 +108,7 @@ var (
 
 // NewContext creates a new object store context.
 func NewContext(context *clusterd.Context, clusterInfo *cephclient.ClusterInfo, name string) *Context {
-	return &Context{Context: context, Name: name, clusterInfo: clusterInfo}
+	return &Context{Context: context, Name: name, Realm: name, clusterInfo: clusterInfo}
```
Comment (BlaineEXE) [inline pkg/operator/ceph/object/admin.go:111]: I don't see this added `Realm` parameter used anywhere. Did I miss something?

```suggestion
	return &Context{Context: context, Name: name, Realm: name, clusterInfo: clusterInfo}
```

File: pkg/operator/ceph/object/objectstore.go [hunk 4]
```diff
@@ -856,6 +892,8 @@ func enableRGWDashboard(context *Context) error {
 		return errors.Wrapf(err, "failed to create user %q", DashboardUser)
 	}
 
+	// TODO we should probably ensure that the access and secret keys for the dashboard-admin user
+	// are the same in every object store
```
Comment (BlaineEXE) [inline pkg/operator/ceph/object/objectstore.go:896]: We would need to make sure this doesn't apply to external stores, however.

File: pkg/operator/ceph/object/admin.go (hunk 3 above)
Comment (galexrt) [reply pkg/operator/ceph/object/admin.go:111]: It is used when here https://github.com/rook/rook/blob/2b189ea2dece5aa2121beb614129e6812408f0b7/pkg/operator/ceph/object/admin.go#L249 when the `radosgw-admin` to get the user info (`GetUser()`) is run.
Otherwise only the "default" realm's user info is returned.

File: pkg/operator/ceph/object/objectstore.go (hunk 4 above)
Comment (galexrt) [reply pkg/operator/ceph/object/objectstore.go:896]: So the current dashboard credentials should only be retrieved when the cluster is not external?

File: .commitlintrc.json (hunk 2 above)
Comment (galexrt) [reply .commitlintrc.json:33]: Not directly, the spacing is off and my editor fixed it. I'll create a separate PR in the future to fix this small nit.

File: pkg/operator/ceph/object/admin.go (hunk 3 above)
Comment (BlaineEXE) [reply pkg/operator/ceph/object/admin.go:111]: I see. I think this approach may be missing something though. When an object store is set up for multisite with `CephObjectRealm`, `CephObjectZoneGroup`, and `CephObjectZone` resources, the realm is not equal to the name. Why not use `NewMultisiteContext()` here and use the realm provided from that? I think that would be the approach that allows this corner case to work as well.

File: pkg/operator/ceph/object/objectstore.go (hunk 4 above)
Comment (BlaineEXE) [reply pkg/operator/ceph/object/objectstore.go:896]: I'm not sure if Rook can enable the dashboard for external clusters. @leseb do you know?

**Review by travisn — CHANGES_REQUESTED** [review]

File: pkg/operator/ceph/object/objectstore.go (hunk 4 above)
Comment (thotz) [reply pkg/operator/ceph/object/objectstore.go:898]: at least from the code, there is no specific external cluster check for the dashboard service. IMO the current code does not consider the external cluster scenarios, high chance it won't work properly

**Review by thotz — APPROVED** [review]
Overall change looks good to me, IMO for the time being we can skip the dash board changes for external cluster

File: pkg/operator/ceph/object/objectstore.go [hunk 5]
```diff
@@ -856,6 +892,8 @@ func enableRGWDashboard(context *Context) error {
 		return errors.Wrapf(err, "failed to create user %q", DashboardUser)
 	}
 
+	// TODO we should probably ensure that the access and secret keys for the dashboard-admin user
```
[the remark this answers is not in the document]
Comment (galexrt) [reply pkg/operator/ceph/object/objectstore.go]: I have rewritten the dashboard-admin user creation logic to check the access and secret keys in the latest commit now.

File: pkg/operator/ceph/object/user.go [hunk 6]
```diff
@@ -162,6 +170,26 @@ func CreateUser(c *Context, user ObjectUser, force bool) (*ObjectUser, int, erro
 	return decodeUser(result)
 }
 
+// CreateOrRecreateUserIfExists deletes an existing user if it already exists and re-creates it
+func CreateOrRecreateUserIfExists(c *Context, user ObjectUser, force bool) (*ObjectUser, int, error) {
```
Comment (travisn) [inline pkg/operator/ceph/object/user.go:174]: Why do we have do delete and recreate a user? Why not just create it if it doesn't exist?

Comment (galexrt) [reply pkg/operator/ceph/object/user.go:174]: It was easier to accomplish with the existing code, otherwise we need to manage the access key(s) of the dashboard-admin user. I haven't found code to manage the radosgw users access/secret key(s) in Rook (yet?).

Comment (travisn) [reply pkg/operator/ceph/object/user.go:174]: From the caller of this method, it looks like we only get to this method if the dashboard hasn't already been configured. If the dashboard was already configured, this method is not called again. So why would the dashboard user need to be re-created? It doesn't seem like we would hit this code in that case. But I must still be missing the scenario. Could you add comments to the code to explain?

Comment (galexrt) [reply pkg/operator/ceph/object/user.go:174]: `CreateOrRecreateUserIfExists()` will be called under the following conditions:
* `dashboard-admin` user does not exist.
* `dashboard-admin` user exists but the credentials that the dashboard has set and the user has assigned are different.
	* For this case can either manage the credentials or as I wrote delete and re-create the user with the correct credentials.

The idea here is that we ensure the dashboard-admin user is always correctly configured, even when the credentials are changed for whatever reason. I chose to re-create the user instead of managing the access/secret keys for it, was out of simplicity as we more or less have the code for creating/deleting users already and deleting.

Comment (travisn) [reply pkg/operator/ceph/object/user.go:174]: Where is the check for the changed creds? I just saw the check for the existence of the user. thanks

Comment (galexrt) [reply pkg/operator/ceph/object/user.go:174]: @travisn Here https://github.com/rook/rook/pull/10137/files#diff-3d31541d76db0087520217d3ccb2b5d704b3a7e05a31167c80bcf69b2cfcaec8R821-R840
The dashboard's credentials are pulled in from here: https://github.com/rook/rook/pull/10137/files#diff-3d31541d76db0087520217d3ccb2b5d704b3a7e05a31167c80bcf69b2cfcaec8R843-R869

Comment (travisn) [reply pkg/operator/ceph/object/user.go:174]: Thanks for the references, I see now. Perhaps this func name would just help.
```suggestion
func CreateOrRecreateUserIfCredsChanged(c *Context, user ObjectUser, force bool) (*ObjectUser, int, error) {
```

Comment (travisn) [reply pkg/operator/ceph/object/user.go:174]: Good point. How about adding that detail to the comments where this is called? I don't see comments in the calling method about only doing it if creds changed for an existing user.

Comment (galexrt) [reply pkg/operator/ceph/object/user.go:175]: @travisn I have added it to the comment of the `CreateOrRecreateUserIfExists()` function

**Review by travisn — APPROVED** [review]

**Comment by galexrt** [comment]
So it seems that in case multiple object stores are created at the same time, the `dashboard-admin` might not get the correct credentials set during the creation (/ "first reconcile" loop), but a second reconcile will fix that.

I'll merge after the CI is green now.
