### PR TITLE
Don't set runAsNonRoot explicitly when it is false.

### LINKED ISSUE #1209: OSD pods do not start on k8s 1.6.4 and lower
In master (and v0.6.0), OSD pods fail to start with the following message when running on Kuberenets 1.6.4 or lower:
```
$ kubectl -n rook get pod
NAME                              READY     STATUS                                         RESTARTS   AGE
rook-api-3536545610-54f3w         1/1       Running                                        0          23s
rook-ceph-mgr0-1387429650-b9xj6   1/1       Running                                        0          24s
rook-ceph-mgr1-2636939030-rmwws   1/1       Running                                        0          23s
rook-ceph-mon0-rwx00              1/1       Running                                        0          55s
rook-ceph-mon1-pfg7r              1/1       Running                                        0          44s
rook-ceph-mon2-h4d1w              1/1       Running                                        0          36s
rook-ceph-osd-32bkx               0/1       container's runAsUser breaks non-root policy   0          23s
```

This is a regression associated with #1188

This appears to be the upstream Kuberentes issue: https://github.com/kubernetes/kubernetes/issues/46996

### PR DESCRIPTION
**Pull request by phsiao**
In kubernetes < 1.6.4, it is being mis-treated as true when the flag runAsNonRoot is present regardless of its value, ref. https://github.com/kubernetes/kubernetes/pull/47009

Instead of removing the line, I decided to leave it and comment it out with a little explanation, so we don't trip that again.

Should fix #1209.

Pull request #1197  should also be updated to reflect this.

### CODE REVIEW

File: pkg/operator/osd/osd.go [hunk 1]
```diff
@@ -299,9 +301,11 @@ func (c *Cluster) osdContainer(devices []Device, directories []Directory, select
 		VolumeMounts: volumeMounts,
 		Env:          envVars,
 		SecurityContext: &v1.SecurityContext{
-			Privileged:             &privileged,
-			RunAsUser:              &runAsUser,
-			RunAsNonRoot:           &runAsNonRoot,
+			Privileged: &privileged,
+			RunAsUser:  &runAsUser,
```
Comment (bassam) [inline pkg/operator/osd/osd.go]: do we need to set RunAsUser at all? whats the default?

Comment (phsiao) [reply pkg/operator/osd/osd.go]: The default is what is set in the container image metadata.  https://kubernetes.io/docs/api-reference/v1.8/#securitycontext-v1-core

I propose to set it explicitly so kubernetes can ensure that pod is running as what we expect the image would be running as.   And by setting it explicitly now it is easier for us to review every pod type and restrict that down to the minimal needed.

Happy to remove that as well if it is redundant, but another lesson we learned is by setting the securityContext explicitly you also get more meaningful error messages at the control plane level because it mismatched.

Comment (bassam) [reply pkg/operator/osd/osd.go]: thats sounds reasonable. are you able to test this change on 1.6.4 and prior 1.7 onwards?

Comment (phsiao) [reply pkg/operator/osd/osd.go]: I don't have access to a 1.6.4 cluster or 1.7.x cluster, but I can test this one a 1.8.1 cluster.

File: pkg/operator/osd/osd.go [hunk 2]
```diff
@@ -289,7 +289,9 @@ func (c *Cluster) osdContainer(devices []Device, directories []Directory, select
 		privileged = true
 	}
 	runAsUser := int64(0)
-	runAsNonRoot := false
+	// don't set runAsNonRoot explicitly when it is false, Kubernetes version < 1.6.4 has
+	// an issue with this fixed in https://github.com/kubernetes/kubernetes/pull/47009
+	// runAsNonRoot := false
```
Comment (kokhang) [inline pkg/operator/osd/osd.go]: what is the repercussion of not setting the `runAsNonRoot` in newer version K8S, like 1.8? Will it set the SecurityContext to run as Root?

Comment (phsiao) [reply pkg/operator/osd/osd.go]: Not setting it just means there will be no validation on whether it is running as root or not.

From https://kubernetes.io/docs/api-reference/v1.8/#securitycontext-v1-core

Indicates that the container must run as a non-root user. If true, the Kubelet will validate the image at runtime to ensure that it does not run as UID 0 (root) and fail to start the container if it does. **If unset or false, no such validation will be performed.**

The problem is with for environment with more restricted PodSecurityPolicy, where a user or service account may have permissions to use multiple PSP, and without explicit securityContext the system may only USE a policy that is not sufficient.   For example, a user may have access to two PSPs, one that can only runAsNonRoot: false so you can't runAsUser:0 , and another PSP that can runAsNonRoot: true.  When runAsNonRoot is missing in the pod template, my observation is that both PSP qualify to run the pod, but if it picks the wrong one the pod would fail to run.  I don't know how it actually picks that, but we have seen confusions from our users running into this issue.

We can argue that it is probably a misconfiguration that a user/service account can have access to multiple PSPs that "conflicts", but I am not sure what the right thing to do here is, and we have learned to be very explicit about securityContext to avoid these issues.

Comment (kokhang) [reply pkg/operator/osd/osd.go]: Cool. Thanks @phsiao

**Comment by bassam** [comment]
if we do pickup a v0.6.1 we should consider back porting this change.
