### PR TITLE
osd: ensure default dir is always used when no dirs or devices are sp…

### LINKED ISSUE #1477: Default OSD dir is removed after pod restart
Hello!

**Bug Report**

I followed quick start introductions, which worked so far.
However, one OSD is failing with the following error:

```
2018-02-08 15:09:04.701118 I | exec: Running command: ceph osd out 1 --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/rook/rook/client.admin.keyring --format json --out-file /tmp/826323393
2018-02-08 15:09:05.029654 I | exec: osd.1 is already out. 
2018-02-08 15:09:05.029893 I | exec: Running command: ceph osd df --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/rook/rook/client.admin.keyring --format json --out-file /tmp/121898540
2018-02-08 15:09:05.346308 I | util: retrying after 5s, last error: current used space and pg count for osd.1 has not decreased still
2018-02-08 15:09:06.022545 I | osd1: 2018-02-08 15:09:06.022370 7fe764956700  0 -- 172.19.0.17:6801/27 >> 172.19.32.7:6801/190 conn(0x55fa25903800 :6801 s=STATE_ACCEPTING_WAIT_CONNECT_MSG_AUTH pgs=0 cs=0 l=0).handle_connect_msg accept connect_seq 0 vs existing csq=0 existing_state=STATE_CONNECTING_WAIT_CONNECT_REPLY
2018-02-08 15:09:10.346824 I | exec: Running command: ceph osd df --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/rook/rook/client.admin.keyring --format json --out-file /tmp/544734619
2018-02-08 15:09:10.657729 I | util: retrying after 5s, last error: current used space and pg count for osd.1 has not decreased still
2018-02-08 15:09:15.658177 I | exec: Running command: ceph osd df --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/rook/rook/client.admin.keyring --format json --out-file /tmp/348868670
2018-02-08 15:09:47.781531 I | util: retrying after 5s, last error: current used space and pg count for osd.1 has not decreased still
2018-02-08 15:09:52.782084 I | exec: Running command: ceph osd df --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/rook/rook/client.admin.keyring --format json --out-file /tmp/408667811
2018-02-08 15:09:53.115538 I | util: retrying after 5s, last error: current used space and pg count for osd.1 has not decreased still
2018-02-08 15:09:58.116725 I | exec: Running command: ceph osd df --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/rook/rook/client.admin.keyring --format json --out-file /tmp/090203046
2018-02-08 15:10:46.179610 I | util: retrying after 5s, last error: current used space and pg count for osd.1 has not decreased still
2018-02-08 15:10:51.180076 I | exec: Running command: ceph osd df --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/rook/rook/client.admin.keyring --format json --out-file /tmp/446903920
2018-02-08 15:10:51.484621 E | cephosd: failed to remove osd.1. failed to wait for cluster rebalancing after removing osd.1: max retries exceeded, last err: current used space and pg count for osd.1 has not decreased still
failed to remove dirs. failed to remove osd.1. failed to wait for cluster rebalancing after removing osd.1: max retries exceeded, last err: current used space and pg count for osd.1 has not decreased still
```

Beside that error I was able to create a block storage and use it from within a pod, so in principle it works. However, I assume that I have no redundancy currently.

I have absolutely no idea how to resolve this issue. Do you have any hints? Thank you!

Manuel

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1632.2.1
VERSION_ID=1632.2.1
BUILD_ID=2018-02-01-2053
PRETTY_NAME="Container Linux by CoreOS 1632.2.1 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

* Kernel (e.g. `uname -a`):
```
Linux k8s-node-2 4.14.16-coreos #1 SMP Thu Feb 1 20:38:35 UTC 2018 x86_64 Intel Core Processor (Broadwell, no TSX) GenuineIntel GNU/Linux
```

* Cloud provider or hardware configuration:
`Exoscale`

* Rook version (use `rook version` inside of a Rook Pod):
`rook: v0.6.0-207.g516e96f`

* Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0+coreos.0", GitCommit:"1b69a2a6c01194421b0aa17747a8c1a81738a8dd", GitTreeState:"clean", BuildDate:"2017-12-19T02:52:15Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):
```
  cluster:
    id:     8c8fe182-de79-457d-8abc-3bdfcebc4ebb
    health: HEALTH_WARN
            Degraded data redundancy: 194/291 objects degraded (66.667%), 100 pgs unclean, 100 pgs degraded, 100 pgs undersized
 
  services:
    mon: 3 daemons, quorum rook-ceph-mon0,rook-ceph-mon2,rook-ceph-mon1
    mgr: rook-ceph-mgr0(active)
    osd: 3 osds: 3 up, 2 in
 
  data:
    pools:   1 pools, 100 pgs
    objects: 97 objects, 290 MB
    usage:   4679 MB used, 380 GB / 384 GB avail
    pgs:     194/291 objects degraded (66.667%)
             100 active+undersized+degraded
```

### PR DESCRIPTION
**Pull request by jbw976**
…ecified

Description of your changes: When the user has specified no devices and no directories, the default dir should always be used.  This prevents the default dir from accidentally being removed after an OSD pod restart.

Which issue is resolved by this Pull Request:
Resolves #1477 

Checklist:
- [x] Documentation has been updated, if necessary.
- [x] Pending release notes updated with breaking and/or notable changes, if necessary.

### CODE REVIEW

File: pkg/daemon/ceph/osd/daemon.go [hunk 1]
```diff
@@ -256,15 +261,10 @@ func getDataDirs(context *clusterd.Context, kv *k8sutil.ConfigMapKVStore, desire
 	}
 
 	// the osd dirs map doesn't exist yet
```
Comment (galexrt) [inline pkg/daemon/ceph/osd/daemon.go]: Should this comment also be moved? The next line below it is empty.

File: pkg/daemon/ceph/osd/daemon.go [hunk 2]
```diff
@@ -256,15 +261,10 @@ func getDataDirs(context *clusterd.Context, kv *k8sutil.ConfigMapKVStore, desire
...
-	if len(dirList) == 0 {
-		// no dirs have been specified
-		if devicesSpecified {
-			// user is using devices instead of dirs
-			return map[string]int{}, removedDirs, nil
-		}
 
-		// no devices or dirs specified, return the default data dir
-		return map[string]int{context.ConfigDir: unassignedOSDID}, removedDirs, nil
```
Comment (travisn) [inline pkg/daemon/ceph/osd/daemon.go]: Help me understand what changed here. It seems we were already returning the default dir if there were zero directories and devices specified.

Comment (jbw976) [reply pkg/daemon/ceph/osd/daemon.go]: that's correct, we were returning the default dir if there were no devices and no dirs specified...in the case where there were no existing created OSDs, and that was the problem.  If there were existing OSD dirs, we'd go into the `getActiveAndRemovedDirs` function.  In the case of the "default dir" being used, we'd have:
* the default dir OSD in the saved dir map
* 0 user specified dirs
In that case, we would accidentally think the default dir OSD should be removed, because the user didn't say to use any dirs!

The right thing to do here is to always have a dir list of at least the default directory when no devices or dirs are specified.  If there's an existing default dir OSD then good, it won't be removed.  If there are no existing OSDs then good, one will get created in the default dir.

I think this is the right approach for all scenarios.  Let me know if that doesn't explain it all.

File: pkg/daemon/ceph/osd/daemon.go (hunk 1 above)
Comment (jbw976) [reply pkg/daemon/ceph/osd/daemon.go]: this comment is still applicable, but i thought it looked a little awkward when placed directly above the next code line, because it is a general comment of where we are in the flow and its not directly related to the next code line.  Let me know if you feel strongly on this, but either way the comment is applicable and should stay.
