### PR TITLE
test: fix integration test flags initilization

### LINKED ISSUE #1316: Test flags are not being initialized.
Test flags are not being initialized. Test flags are showing up but they are always asociated with the default values. this happed after fixing https://github.com/rook/rook/issues/1262.  where we removed flags.Parse() test EnvironmentManifest. Testify depenency is calling flag.Parse() defore the test flags are called. But calling flags.Parse() in EnvironmentManifest is causing Testify flags to not show up.  We need a fix where both test flags and testify flags are avaliable and initialized.

### PR DESCRIPTION
**Pull request by dangula**
test

Test flags in integration framework were being declared but not initialized. Moved flags.Parse() out of init function so both test flags and global flags(testify.m) are declated and initialized correctly. 

[smoke only]  fix #1316

### CODE REVIEW

File: tests/framework/installer/install_helper.go [hunk 1]
```diff
@@ -341,6 +337,8 @@ func NewK8sRookhelper(clientset *kubernetes.Clientset, t func() *testing.T) *Ins
 	if err != nil {
 		panic("failed to get kubectl client :" + err.Error())
 	}
+	env := objects.E
```
Comment (travisn) [inline tests/framework/installer/install_helper.go]: why not just use `objects.E` where it's needed instead of declaring the local var `env`?

File: tests/framework/objects/environment_manifest.go [hunk 2]
```diff
@@ -31,15 +31,15 @@ type EnvironmentManifest struct {
...
-	e := EnvironmentManifest{}
-	flag.StringVar(&e.HostType, "host_type", "localhost", "Host were tests are run eg - localhost,GCE or AWS")
-	flag.StringVar(&e.RookImageName, "rook_image", "rook/rook", "Docker image name for the rook container to install, must be in docker hub or local environment")
-	flag.StringVar(&e.ToolboxImageName, "toolbox_image", "rook/toolbox", "Docker image name of the toolbox container to install, must be in docker hub or local environment")
-	flag.StringVar(&e.SkipInstallRook, "skip_install_rook", "false", "Indicate if Rook need to installed - false if tests are being running at Rook that is pre-installed")
-	flag.IntVar(&e.LoadConcurrentRuns, "load_parallel_runs", 20, "number of routines for load test")
-	flag.IntVar(&e.LoadVolumeNumber, "load_volumes", 1, "number of volumes(file,object or block) to be created for load test")
-	flag.IntVar(&e.LoadTime, "load_time", 1800, "number of seconds each thread perform operations for")
-	return e
+var E EnvironmentManifest
```
Comment (travisn) [inline tests/framework/objects/environment_manifest.go]: Could you call it `Env`? Even better if we could add this to the test context instead of creating a global var

File: tests/framework/installer/install_helper.go [hunk 3]
```diff
@@ -341,6 +337,8 @@ func NewK8sRookhelper(clientset *kubernetes.Clientset, t func() *testing.T) *Ins
...
+	flag.Parse()
```
Comment (jbw976) [inline tests/framework/installer/install_helper.go]: this `flag.Parse()` call will happen multiple times here, right?  that goes against what this comment says: https://github.com/rook/rook/issues/1316#issuecomment-351879286.  But, the golang docs don't say that it cannot be called more than once: https://golang.org/pkg/flag/#Parse, so maybe that's OK

Comment (jbw976) [reply tests/framework/installer/install_helper.go]: That sounds reasonable, thanks for the explanation.
